### ISSUE TITLE
SenMangaRAW

### ISSUE THREAD

**Issue by ramenchef** [riderkick/FMD#100]
This website doesn't work at all for a while now. They changed something server side. The chapter list is always empty. I believe they use reCAPTCHA on every attempt to view the chapter list.

**Comment by rajlaksh** [comment]
Yes, reCAPTCHA is on every Attempt. You have to fill again and again :laughing:

**Comment by riderkick** [comment]
yes, I can't fix it yet. what make it worst, they're stalking this project and always block every attempt we take.
