### ISSUE TITLE
MangaTown 0.9.145.0 not available

### ISSUE THREAD

**Issue by LakotaGray** [riderkick/FMD#1002]
Commits looks like MangaTown was to be added back into available options, but after update Mangatown is not present in Options -> Websites to make available in drop down menu

**Comment by kmvi** [comment]
Is MangaTown.lua presented in modules list (Options -> Websites -> Modules)? Did you restart FMD after modules update?

**Comment by riderkick** [comment]
Mangatown should be available if you check modules update. Options > Websites > Modules > Check update.
