### ISSUE TITLE
not all image conversion option was saved

### ISSUE THREAD

**Issue by H4nZ83** [riderkick/FMD#1003]
![compression](https://user-images.githubusercontent.com/11715366/36339270-3885ed44-13f4-11e8-9218-bd0d04c96802.JPG)

i wonder if the option above was working or not ?
the option on above was not saved or loaded when restarting FMD
thanks..

**Comment by riderkick** [comment]
It is not saved yes. And PNG always saved as JPEG regardless of that option.
