### ISSUE TITLE
Please give more time for the updater so the instance can close first

### ISSUE THREAD

**Issue by wuhugm** [riderkick/FMD#1005]
By the time the updater cmd retries 10 times, my FMD instance hasn't closed so it always fail like this : 
https://i.imgur.com/39OGia6.png
Please make it retries at least 50 times since the instance closes way too slow
Or make it so we can run updater independently without opening FMD

**Comment by Tmp341** [comment]
Fmd closes immediately after update for me.

**Comment by wuhugm** [comment]
^Well, mine is not
And someone else mentioned this issue before too

**Comment by Tmp341** [comment]
Have you tried running FMD somewhere else other than C:\? Or running with admin rights? Because Windows likes creating problems when you run programs on C:\ drive.

**Comment by leoteesh** [comment]
getting the same message
![image](https://user-images.githubusercontent.com/21075197/36340224-7c4771c0-13d0-11e8-8977-0e7ce77ce61d.png)

**Comment by Tmp341** [comment]
I've tried it at 3 different locations:

1. documents folder
2. C:\Program\
3. desktop

All of them finished successfully.

**Comment by wuhugm** [comment]
^Moved to D:\

Still doesn't work
The FMD not fully closed when the retries reached 10/10

**Comment by Tmp341** [comment]
So, it is not a "rights" problem.

**Comment by riderkick** [comment]
Then you have another problem with your installation. Try to enable the log and see whats happen when you close fmd.
If I'm not mistaken the updater doesn't delete the updatepackage.7z. So you can extract them manually. Basically updater just extract and overwrite.

**Comment by wuhugm** [comment]
^The log is filled with loading/loaded modules, like this : 
https://i.imgur.com/i7Ni7Dq.png
How do you display image again?

Is my database just too large?
My FMD folder is 650 Mb
When I click X button on top right, it takes like 15 seconds or more till it closes

**Comment by riderkick** [comment]
When you close there will be a log about closing active threads with the time they started etc. So we can see where the problem is. 

Better create a new issue with title "FMD doesn't close immediately" or something like that.
