### ISSUE TITLE
I can't download manga databases

### ISSUE THREAD

**Issue by Habwuson** [riderkick/FMD#1009]
I get this error with every database I try to download.

"Failed to finish:

Unable to create file
C:\Users\User\Desktop\FMD\Batoto.7z"

Using the latest version of FMD.

**Comment by Tmp341** [comment]
I think it happens when SF is down.

**Comment by giercko** [comment]
I have the same problem, but SF is up, in fact download the db from the link and download it well, is there nothing manually added?

**Comment by Tmp341** [comment]
[https://sourceforge.net/projects/newfmd/files/data/](https://sourceforge.net/projects/newfmd/files/data/)
