### ISSUE TITLE
Connection problem.

### ISSUE THREAD

**Issue by Noblessez** [riderkick/FMD#101]
Hello, I have this problem when trying to download from Pururin.

http://prntscr.com/898lya

It only happens with that site, since I tried with others like Mangahere/Fox and it worked. Any suggestions on what should I do? Thanks for reading.

**Comment by Striker243** [comment]
I get the same problem on NHentai.net. Maybe these sites changed their directories and the downloader can't get the list?
I tried it with 0.9.7.1, too but with the same problem.

**Comment by Noblessez** [comment]
So it might be that, huh? Guess I should wait for an update that "fixes" it or something :(

**Comment by Striker243** [comment]
Yeah I hope the problem will be found and solved.

**Comment by riderkick** [comment]
related #113
