### ISSUE TITLE
Great team and great job .. but!

### ISSUE THREAD

**Issue by rafatreyad** [riderkick/FMD#1010]
Thank you and your team very much.
It's great job and hope to be the best.
But the problem is the downloading speed and updating the database ( i can't downloading manga list from server) so I have to use ( update manga list ). 
It's very slowly when I need to downloading or updating.
I hope you find a solution to increase speed downloading and solve the database problem .

With my regards .

**Comment by riderkick** [comment]
Download speed is depend on your side and the server side, there is nothing I can do about it.
We can't solve database problem right now. SF is not fully restored yet.

**Comment by rafatreyad** [comment]
I see .. Thank you ..
I'm waiting .
Can I send you databases for some sites (i.e. MangaInn) it's not complete yet but I'm downloading database now.
