### ISSUE TITLE
Couple of minor issues

### ISSUE THREAD

**Issue by molitar** [riderkick/FMD#1013]
Noticed a couple of minor problems with the new interface.

1. When I scroll down to a new site and let off the drop down box it does not refresh I have to click somewheres else. Can you put a mouse click release action there please.

2. MyMangaMe never downloads anything. Is that an active site?

**Comment by riderkick** [comment]
I don't understand your words. Please elaborate.

**Comment by molitar** [comment]
Ok I use the drop down box to change to a different site  (aka dropdown).  when I let off the button it does not change to the other site until I click on some other section of the application than it will change to the new site.  Current I am clicking the bar that has the mode text.

**Comment by riderkick** [comment]
Still doesn't make sense.
You mean website selection combobox in manga info tab?
It does change the selected website and load the database when you select an item.

**Comment by molitar** [comment]
Yes that is the combobox I mean.. and it is not loading the next selection until I click somewhere else in the application. It does not seem to be triggering on change or mouse button release. I have to click anywheres else for it to refresh and show the new site manga.

**Comment by riderkick** [comment]
It does change when you select an item.
Using keyboard, input some text and navigate up down then select by enter. Using mouse click an item. It does load a website.

**Comment by riderkick** [comment]
You mean you want the selected website loaded when you use mouse scroll to change the index?
That even is the same as using navigate up and down with keyboard. Or when hovering the item when the list appear.
Load the website every time index is changed is not good. It will become a bothersome. Because when loading a database it will block the UI, we can't advance the selection. That's bad design. Why not just click the drop down button and select the item or press enter.
Declined.

**Comment by molitar** [comment]
I was thinking on mouse up to trigger it.  That way when letting go of the the one that it will trigger.. so I scroll quickly to say kissmanga and than let off the mouse button it would trigger.. So could trigger it on mouse up on combobox or exiting combobox trigger.. yeah that would be too much for each scroll.

**Comment by riderkick** [comment]
How could you let off the mouse button when you said you navigate with mouse scroll? That doesn't make sense. Do your mouse scroll is actually a button that you press up/down like the keyboard?

**Comment by riderkick** [comment]
I can add middle mouse button click. How about that? Navigate using mouse scroll and confirm the selection with middle click.
