### ISSUE TITLE
Limit Mangadex's "update manga list"

### ISSUE THREAD

**Issue by Tomoko23** [riderkick/FMD#1022]
I got banned after updating mangadex's manga list. it was a long update though.
the update manga feature found 20.000 new manga. left it updating and woke up already banned

**Comment by Tmp341** [comment]
It was cloudflare protection i believe.

**Comment by Tomoko23** [comment]
yeah mangadex's admins were really cool about it. they said I will be unbanned once admin checks my PM, 
I just want to let you know that the update manga list feature triggers cloudflare's banhammer

**Comment by Tomoko23** [comment]
https://gyazo.com/589a6e7153259d02fc112c7480351a9b
uh it seems all the entries that were updated are duplicates?

**Comment by Tmp341** [comment]
You doubled them?
@riderkick I think you were doing something like "limiting speed". It was a dead end? limiting our download with "kb/s" would be good i think.

**Comment by riderkick** [comment]
@Tmp341It's not about the download speed. It's about number of hit per time basis. To able to finish the databases you have to use inverted list updates. It's in advanced options. If you set the limit to certain number it will load from that number to zero/found existed title if it's sorted. So you can do like 10 page first, then do again after a delay with 20, 30 and so on. That's what I do with EHentai in the past. Able to complete it in 1 month.

**Comment by Tomoko23** [comment]
@riderkick like this? 
https://gyazo.com/1920e31fe4ca24b15500bad70e511c20

**Comment by Tmp341** [comment]
@Tomoko23 The other one, "number of threads".

**Comment by throw395583** [comment]
@riderkick I don't see any such "Inverted list updates" in website -> advanced options. Where is it? (v. 0.9.148.0)

**Comment by riderkick** [comment]
Inverted list enabled when directory page number set > 0.

**Comment by Tmp341** [comment]
@riderkick Wouldn't creating a wiki page for common fixes be good?

**Comment by Tomoko23** [comment]
@Tmp341 ahh ok. thank you

**Comment by rs3mk** [comment]
not work in TMO

![sin titulo 19](https://user-images.githubusercontent.com/19628943/36709918-9d0766ca-1b48-11e8-8ed2-ddb4f9b3fafe.png)
![sin titulo 20](https://user-images.githubusercontent.com/19628943/36709921-9fc95fe4-1b48-11e8-9baa-300a3225846b.png)

**Comment by riderkick** [comment]
Mangadex limited to 1 task and 2 connections by default. But you can override that in website options.
