### ISSUE TITLE
FMD can't get info from Mangafox

### ISSUE THREAD

**Issue by Illyria77** [riderkick/FMD#1023]
It started with the last update. First, I couldn't update, updater would always get stuck and so I had to download FMD again (I had it for about year now... I had old version way back, too). After new download, it asked to update and I did it, it worked normally, so I went to Mangafox to try and download something. It gave me the following message:

Cannot get manga info. Please check your internet connection and try it again.

After several attempts and making sure internet is fine, I tried MangaHere and it worked as usual. Then I tried MangaInn and it gives me 404 error for each manga. However, I can not be sure if this is the same or the separate issue, really. 

I was just wondering what is going on and is it me or this version of FMD?

**Comment by kmvi** [comment]
Fixed in 148 release

**Comment by Illyria77** [comment]
Thank you, good to know :)
