### ISSUE TITLE
Broken Compatibility with Dynasty-Scan - still present

### ISSUE THREAD

**Issue by ralvarador** [riderkick/FMD#1024]
Sorry... the issue still is present:
![image](https://user-images.githubusercontent.com/30580377/36396949-74fb4a08-158e-11e8-838f-5af0582511ad.png)
#990

**Comment by riderkick** [comment]
The website name is changed from `Dynasty-Scans` to `DynastyScans`. You can try to use transfer favorites, and uncheck "Clear downloaded chapter list" to preserve the list.

**Comment by ralvarador** [comment]
It doesn't worked at all; when made second-mouse-button-clic on any dynasty-scans favorite the use the option "transfer website" show the webpages in use except the DynastyScans... SO... deleted all the Dynasty-scans and then re-added them.

**Comment by riderkick** [comment]
Can you send me your favorites.db

**Comment by ralvarador** [comment]
No problem; at least - I figure out how to "solve" this.
It's not like I will "Demand" solution, when simply you are helping us, and believe me - the last thing that I want to do is add another headache when it's possible get a solution / workaround instead a fix :)
