### ISSUE TITLE
BUG: task failed even though the download is complete

### ISSUE THREAD

**Issue by 0xh3LL0** [riderkick/FMD#1031]
as the title said, the download is run just fine, and manga download successfully, but its says task failed...
its not a big deal since the manga is downloaded anyway,
but for those who dont know, user may redownload it without knowing that the manga already downloaded...

edit:
using FMD with latest update
manga site: mangahere

**Comment by Tmp341** [comment]
Do you have a log?

**Comment by riderkick** [comment]
Task failed status mean there is some file not downloaded. Even though you think its complete. It can be credits file or even ads. You should post your log so we can see what's going on and maybe exclude that page if necessary.

**Comment by 0xh3LL0** [comment]
screenshot of the failed task
![task failed](https://user-images.githubusercontent.com/23132217/36515541-7c656330-17ac-11e8-9b13-2e7bfacaeb7b.png)

where is the log? i didnt see any log in FMD directory, it just changelog, but you didnt mean this file right?
![no log](https://user-images.githubusercontent.com/23132217/36515570-a86061ba-17ac-11e8-964d-e11d02a32e74.png)

**Comment by riderkick** [comment]
Options > Misc > Log

**Comment by kmvi** [comment]
It seems MangaHere doesn't allow to download images using more than 1 thread.

**Comment by 0xh3LL0** [comment]
okay, so here is the log

=== Log Session Started at 23/02/2018 8:24:08 by Free Manga Downloader ===
08:24:08:421 INFO: "Free Manga Downloader" started with [PID:2920] [HANDLE:4294967295]
08:24:08:421 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 0.9.148.0
               Product Version   : Win32 Debug
               Host Machine      : Windows XP
               FPC Version       : 3.0.4
               LCL Version       : 1.8.0.6
               WidgetSet         : Win32/Win64
               Target CPU-OS     : i386-Win32
               Build Time        : 2018/02/20 03:50:31
               Path              : D:\DL+Torrent\FMD\fmd.exe
               Process ID        : 2920
               MainThread ID     : 2252
08:25:06:843 WARNING: TTaskThread, checkforfinish failed=1/26 [MangaHere]"ReLIFE" > "/manga/relife/c219/"
W
08:25:06:843 WARNING: TTaskThread, download failed. "ReLIFE" "ReLIFE 219" "/manga/relife/c219/"

**Comment by 0xh3LL0** [comment]
using latest relese atm, no download issue any more...
