### ISSUE TITLE
Solution for Kissmanga would't download.

### ISSUE THREAD

**Issue by garybempo** [riderkick/FMD#1034]
First, thanks admin for this incredible program!!
And feel free to mark this issues as closed.

To do it,
Open FMD -> Go to "Settings -> Websites -> Options" tab. -> Under Kissmanga option, untick the checkbox of "Use Google DCP".
Save.
That's it.

Half an hour ago I have problem download manga on kissmanga site with FMDv0.9.126.0 ; but last week I had no problem download with it. While latest version of FMD was always unable download manga on Kissmanga for me, only 126 is working, but not today.
This method did solved my problem.
It also solved the current FMDv0.9.148.0 too. This enable me to continue using the latest FMD version.

Just hope this can help other Kissmanga user out there with same problem like I have.

Cheer.

**Comment by karehaqt** [comment]
I've found that whenever I have an issue downloading from Kissmanga, I just open the site up in a web browser then downloads work again.

**Comment by Tmp341** [comment]
They have a protection, sometimes you gotta do what you've said. Open up their main page and it works.

**Comment by kmvi** [comment]
added to [faq](https://github.com/riderkick/FMD/wiki/FAQ)
