### ISSUE TITLE
BUG: merakiscans and LHtranslations have stopped working

### ISSUE THREAD

**Issue by muto4013** [riderkick/FMD#1035]
Meraki downloads brings only the first page, rest will not be downloaded.
FMD shows the download green in downloads tab but log entry shows
17:28:45:248 ERROR: 
17:28:49:007 ERROR: 

problem exist in fmd 147+, works fine in fmd 141 
don't have versions between 141 and 146 so can't test since which version the bug started.

also LHTranslations has stopped working, FMD 147+ throw error, 141 working well.
FMD error : 
17:45:26:823 ERROR: 
17:45:27:886 WARNING: TTaskThread, checkforfinish failed=1/1 [LHTranslation]"Grancrest Senki" > "/grancrest-senki-chapter-16/"
W
17:45:27:886 WARNING: TTaskThread, download failed. "Grancrest Senki" "Grancrest Senki - Grancrest Senki Chapter 16" "/grancrest-senki-chapter-16/"
17:45:28:337 ERROR: 
17:45:29:386 WARNING: TTaskThread, checkforfinish failed=1/1 [LHTranslation]"Grancrest Senki" > "/grancrest-senki-chapter-16/"
W
17:45:29:386 WARNING: TTaskThread, download failed. "Grancrest Senki" "Grancrest Senki - Grancrest Senki Chapter 16" "/grancrest-senki-chapter-16/"

hope this helps the debug.

**Comment by kmvi** [comment]
It has already been fixed, will be available in the next release

**Comment by riderkick** [comment]
@kmvi you can commit the temporary fix for wpmanga. We can revert it back after new release.  New release will be delayed until 1020.
