### ISSUE TITLE
Mangadex having multiples of the same manga

### ISSUE THREAD

**Issue by Purplem** [riderkick/FMD#1040]
Picture says it http://puu.sh/ztx4H/804500db08.png

**Comment by Tmp341** [comment]
Did you update it manually? Updating manga list manually seems like doubling even tripling the list.

**Comment by Purplem** [comment]
Yeah, it started getting bigger after I updated all my mangalists at once

**Comment by Leguron** [comment]
@Tmp341 Could you please upload the mangadex library so that I don't need to update and can just download from your server?

**Comment by Tmp341** [comment]
Well i can, but they are duplicate now and i dunno if it is up to date.

**Comment by Tmp341** [comment]
@riderkick One with id one with manga name.

Example:

``https://mangadex.com/manga/3993/``
``https://mangadex.com/manga/3993/2-kaime-no-hajimete-no-koi``

**Comment by riderkick** [comment]
It seems the admin change the link. There is no other choice than rebuilding the database from scratch.

**Comment by kmvi** [comment]
db has been updated on server
