### ISSUE TITLE
manga go

### ISSUE THREAD

**Issue by reiko23426** [riderkick/FMD#1042]
Hi there 
so I have this problem with the software which is that I can't download from mangago but I can download from other sites^^l...?

**Comment by kmvi** [comment]
#953

**Comment by reiko23426** [comment]
what do i do?
^^"?

**Comment by Tmp341** [comment]
You can't do anything, it is explained there.

> descrambling also broken

I've tried to explain:

> **Mangago download errors:** This one is the real pain. They most likely watching this project and adding some encryptions/scramblers to their code. Either read online or change your favorites until it is fixed. Even after it is fixed, you most likely don't have much time, because they are changing their code pretty quick like you are stealing their own pay per chapter works.

**Comment by reiko23426** [comment]
waaaaah T^T what a pain
