### ISSUE TITLE
Remove *original* manga name from folder (not renamed one)

### ISSUE THREAD

**Issue by GhostWriterTNCS** [riderkick/FMD#1049]
Hi!

If I rename a manga, FMD tries to remove the custom title from chapter's names on download.

For example I have renamed "_Dungeon ni Deai o Motomeru no wa Machigatte Iru Darou ka_" to "_DanMachi_", but when I download a chapter, the folder's name is "_DanMachi - Dungeon ni Deai o Motomeru no wa Machigatte Iru Darou ka - ###_".

I think it will be better if FMD removes the original manga name.

Thanks.

**Comment by Tmp341** [comment]
Check:
> Options -> Save To -> Renaming

**Comment by GhostWriterTNCS** [comment]
I'm sorry: I understood the _real_ problem: if I rename a manga, FMD shows both the renamed title and the original title.
But still I think it will be better to show only the renamed one (in my example: "_DanMachi - ###_"). Or even better: let the user choose what he/she prefers.

Thanks for your reply.

**Comment by riderkick** [comment]
Does your download task had the new name? Rename methods should follow download task title. Except if you download it manually with "view manga info", then it will fetch the original name. Depend on the website module, some overwrite the title and some don't.

**Comment by GhostWriterTNCS** [comment]
Here two screenshots for the same manga and same settings (I've opened the manga with "View manga info" in both cases).

If I leave the original title I got:
![immagine1](https://user-images.githubusercontent.com/26646085/36657017-210ee43a-1acb-11e8-81cd-f4f734159882.jpg)

If I rename it I got:
![immagine2](https://user-images.githubusercontent.com/26646085/36657023-28b4a2b0-1acb-11e8-9d25-b0115fe67668.jpg)

I expect the chapters' names to be always like in the first screenshot.

Thanks for your reply.

**Comment by riderkick** [comment]
Well, the original name have been lost.

**Comment by GhostWriterTNCS** [comment]
Maybe you can add a new variable to fix this small issue (such as original_title).
I prefer not to try fixing it because I don't know where to edit (pascal or lua?).

**Comment by riderkick** [comment]
This is not small. where do have to store the original_title?
Currently we use SQLite databases. There is no way to add a field except to rebuild entire databases. 
That's why I create this issue #1019.
Another way to consider is to not send the title to getmangainfo thread so it will re-fetch the original title. But keep the download locations intact.

**Comment by riderkick** [comment]
Please test and close if ok.

**Comment by GhostWriterTNCS** [comment]
Solved.
Thank you very much.

**Comment by GhostWriterTNCS** [comment]
Clarification; if I have "%MANGA%" in chapter's name, FMD adds the renamed title only if the download has been launched by "Check for new chapters". If I manually download a chapter, it adds the original title.
This is not a problem for me, but I thought best to report it.

You can reclose the issue.
