### ISSUE TITLE
MangaDex Manga Chapters

### ISSUE THREAD

**Issue by Meliodas-Sama** [riderkick/FMD#1050]
First of all, thank you for your hard work FMD developers.
If the manga has more than 100 chapters FMD shows just the first 100 (the rest goes to other indexed pages 1,2,3....).
EX: [https://mangadex.com/manga/7195/nanatsu-no-taizai](url)

**Comment by riderkick** [comment]
https://github.com/riderkick/FMD/commit/5c1bce3def10f0a7d7b2975506257e6179165993
