### ISSUE TITLE
Update Failed to 0.9.149

### ISSUE THREAD

**Issue by 0xh3LL0** [riderkick/FMD#1053]
![failed to update](https://user-images.githubusercontent.com/23132217/36649928-11b0d270-1ad3-11e8-9de9-f60799fb5c84.png)

here is the log:

=== Log Session Started at 26/02/2018 8:50:54 by Free Manga Downloader ===
08:50:54:343 INFO: "Free Manga Downloader" started with [PID:2156] [HANDLE:4294967295]
08:50:54:343 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 0.9.148.0
               Product Version   : Win32 Debug
               Host Machine      : Windows XP
               FPC Version       : 3.0.4
               LCL Version       : 1.8.0.6
               WidgetSet         : Win32/Win64
               Target CPU-OS     : i386-Win32
               Build Time        : 2018/02/20 03:50:31
               Path              : D:\DL+Torrent\FMD\fmd.exe
               Process ID        : 2156
               MainThread ID     : 2160
08:54:55:296 INFO: TMainForm.FormClose
08:54:55:296 INFO: TMainForm.CloseNow, disabling all timer
08:54:55:296 INFO: TMainForm.CloseNow, backup downloads
08:54:55:406 INFO: TMainForm.CloseNow, backup favorites
08:54:55:406 INFO: TMainForm.CloseNow, backup all data to file
08:54:55:421 INFO: TMainForm.CloseNow, close other forms
08:54:55:421 INFO: TMainForm.CloseNow, stop ipc server
08:54:55:421 INFO: TMainForm.FormDestroy, freeing all objects
08:54:55:796 INFO: "Free Manga Downloader" exit normally [PID:2156] [HANDLE:4294967295]

**Comment by riderkick** [comment]
Where do you live?
Can you open https://sourceforge.net

**Comment by 0xh3LL0** [comment]
> Where do you live?

Indonesia

> Can you open https://sourceforge.net

of course i can, so i need to manually download from sourceforge and overwrite the existing FMD?

**Comment by riderkick** [comment]
Then maybe it's the mirror server that can't be reached. Just try again. Maybe it will pick another server.
Basically it just load the page with curl user-agent which will be redirected by sf to their mirror.
