### ISSUE TITLE
Mangadex problem?

### ISSUE THREAD

**Issue by ratbunuts** [riderkick/FMD#1054]
I cant access any manga on mangadex. Is it just me or there really is something wrong with the site?

**Comment by riderkick** [comment]
Same here, their server is very slow. In the their website they mention about preparing a new server.

**Comment by Tmp341** [comment]
I read something like prepairing new server's protections. They're taking precautions i think.

**Comment by ralvarador** [comment]
is still presenting issues with MANGADEX?
I'm not being able download from that server; Update Checking = Works, "View manga info" = Works; the exception - when downloading! 
It could be something about the "time" that is set to start downloads from MANGADEX?, I still using the same "Settings": 1 file(2) per task, 1 task(s) at time.

14:33:13:295 WARNING: TTaskThread, download failed. "Komi-san wa Komyushou desu." "Komi-san wa Komyushou desu. - Ch. 126 - Friend chocolate" "/chapter/118941"
14:43:10:957 WARNING: TTaskThread, checkforfinish failed=6/6 [Mangadex]"Komi-san wa Komyushou desu." > "/chapter/118952"
14:24:24:713 WARNING: TTaskThread, download failed. "Komi-san wa Komyushou desu." "Komi-san wa Komyushou desu. - Ch. 127 - Friday the 13th" "/chapter/118952"
14:33:13:295 WARNING: TTaskThread, checkforfinish failed=14/14 [Mangadex]"Komi-san wa Komyushou desu." > "/chapter/118941"

**Comment by anfgomezmo** [comment]
About Mangadex, something I noticed, the program is capturing an extra page. For example, if the chapter has 13 pages, it tries to catch 14 pages. Since the application is requesting an additional page that doesn't exist on the server will fail. If you check, it downloads all the pages but can't create a cbz, zip, or will complete the task because that extra page isn't there. Can you confirm if this is happening?

**Comment by anfgomezmo** [comment]
I will request a pull if I have time but change the Lua for mangadex 
 for i=0,task.pagelinks.count-1
change suggestion
 for i=0,task.pagelinks.count-2
In that way, it will finish the tasks. It is a quick solution and worked for me. I didn't have the time to read all the codes

**Comment by riderkick** [comment]
It's because of the extra "," on the last array. Should be trim them instead of remove items.
I will push the fix.
