### ISSUE TITLE
Madokami does not list any chapters

### ISSUE THREAD

**Issue by molitar** [riderkick/FMD#1056]
I can see how many chapters there is when I update the list but when I check for any chapters for the manga none exists.. 0 chapters.  If I go to read online the manga is there.

**Comment by adustyspectacle** [comment]
There were changes in the Account options, so I think you might have to login again.

Although, I still can't login myself. It keeps giving me the Invalid status despite the username/password I'm using works perfetly well when I try it in my browser.

**Comment by molitar** [comment]
Nope I can log in just fine in browser but it's broke in FMD.

**Comment by molitar** [comment]
closed but it's still broken when I just tried with .150.   When I go to accounts my login and password says invalid when it's not.. I can log into site just fine with my login.

**Comment by mastafrooper** [comment]
It's fixed they just haven't pushed a new release with the fix yet.

.151 when it gets pushed will have it.
