### ISSUE TITLE
Downloads from MangaStream (readms.net) only have duplicate pages

### ISSUE THREAD

**Issue by rastaufiq** [riderkick/FMD#1058]
Tried it on [One Piece](https://readms.net/manga/one_piece) and [One Punch Man](https://readms.net/manga/onepunch_man), it downloads the right amount of pages but all of them are just duplicates of the first page of each chapters. Redownloading usually fixes it but this time it doesn't.

![image](https://user-images.githubusercontent.com/5691305/36665152-60dae99e-1b19-11e8-8cb4-35dcb2aa7394.png)

**Comment by riderkick** [comment]
Which chapter?

**Comment by Tmp341** [comment]
@riderkick Ss shows it as ch895.

**Comment by rastaufiq** [comment]
Whoops seems like an old resolved issue. Applied #922 and all is fine.
