### ISSUE TITLE
m h 1 6 0 not able to download

### ISSUE THREAD

**Issue by abhi98** [riderkick/FMD#106]
hello there, I am not able to download chapter(s) from m h 1 6 0 Chinese site. When i go to browser, the chapter images does load up though. So I don't know what's happening there. Please help and please try to fix it. Thanks :)

**Comment by riderkick** [comment]
domain changed, or the website is dead. idk. I can't open this website.

**Comment by abhi98** [comment]
try this http://www.mh160.com/kanmanhua/14242/

**Comment by abhi98** [comment]
it gives me a warning though so I don't think it is good site anymore

**Comment by abhi98** [comment]
welcome back

**Comment by riderkick** [comment]
I can't. it took forever until timeout. sometimes it return 522 from cloudflare. that's mean the server is down.
