### ISSUE TITLE
Number of downloaded tasks at the time - different websites

### ISSUE THREAD

**Issue by subnighter** [riderkick/FMD#1060]
Would it be feasible to add an option for "Number of downloaded tasks at the time" to apply to different websites only? For example, if that number is set to two and in a queue there are manga from websites in such an order: mangahere, mangahere, mangafox, and onetimescans, FMD  would download the first and the third manga instead of the first and the second manga.

**Comment by Tmp341** [comment]
Check: 
Options -> Websites -> Advanced

You can set your settings.

**Comment by subnighter** [comment]
Thanks, I hoped for some global setting but this will work,
