### ISSUE TITLE
weird problems with FMD

### ISSUE THREAD

**Issue by Tomoko23** [riderkick/FMD#1062]
https://i.gyazo.com/8f2f7c1bc99a775eeb601f4761bbcb09.png
Doesn't do anything when I press update. it just keeps increasing modules count and my favorites list got wiped. all preferences reset too. what's going on?
CPU usage is 28% and RAM usage is going up as I write this. its currently 260 mb from 200 mb minutes ago. should I just force close it?

**Comment by leoteesh** [comment]
it's wiped part o my favourites though - would you know how to get this back? 
the ones i copied from the previous version starts with Ge

**Comment by riderkick** [comment]
#1059
