### ISSUE TITLE
Mangadex

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [riderkick/FMD#1063]
The script seems to have issues connecting to at least some chapters: it manages to connect (i.e. read the title and number of pages), but spents a lot of time downloading nothing, leaving me with an empty folder.

**Comment by muto4013** [comment]
ATM mangadex has a lot of problems, even the website behaves erroneously. Maybe it will be better if they finish the announced transfer to another server. But mangadex is not the only mangasite with problems, a lot of sites behind cloudflare are suffering lags and dropped connections.
My opinion:  Just give it some time, i doubt it's a FMD problem.

**Comment by l-l-l-l-l-l** [comment]
Okay, checked again and found that whjen downloading from Mangadex, one of the two following patterns happen:
-creates the folder but doesn't download anything, returning an error.
-downloads everything but still returns an error (if "compressing into a file" is checked, it skips that step, but if it's not the download is as good as complete except for the "error" state).

From what I see, which pattern happens is highly dependent on the chapter: everytime you try to download a pattern-1 chapter it will download nothing, no matter if you resume the download or create a new one, while if you try to download a pattern-2 chapter it will always download everything without problems other than the "error" alert (and not zipping it).

**Comment by riderkick** [comment]
You should give an example. Or better post your downloads.db. I just download 1 chapter and it's working just fine. But it's very slow indeed. Maybe your connection's timeout is too low?

**Comment by l-l-l-l-l-l** [comment]
Connection timeout is default 30 seconds, and like I said it's always the same with the same chapters.


[downloads.db.txt](https://github.com/riderkick/FMD/files/1764866/downloads.db.txt)

The example files are Asa Made Jugyou Chu! ch.42 (no download) and Murenase Shiiton Gakuen ch.42.5 (downloads everything, but returns error; it seems that the page counter is wrong and it tries to download a final page that doesn't exist). As a side note, in Asa Made chapters before that one seem to download as type 2 (it works, but it counts one page too many, or at least the couple I tried), while those after are type 1 (no download).

**Comment by Owyn** [comment]
Same, progress stuck as 0/69 pages
Tried to dl https://mangadex.com/chapter/119011

**Comment by riderkick** [comment]
It seems some chapter using external server and others using mangadex server. No wonder their website is slow. Some chapter's images still stored in the same server with their web pages.

Mangadex module updated. Please test and close if ok.

**Comment by Owyn** [comment]
each try it downloads 68 pages then says Failed, try resuming

**Comment by riderkick** [comment]
You have to re-add the download again.

**Comment by riderkick** [comment]
Now you should be able to resume your failed tasks.
