### ISSUE TITLE
Manga searching function is not working?

### ISSUE THREAD

**Issue by gooreat** [riderkick/FMD#1064]
I'm not sure what is wrong with the application but after manually updated it from 0.9.149.0 to 0.9.150.0 (due to this problem: https://github.com/riderkick/FMD/issues/1059), the manga search function (under the Manga dropdown menu) on the Manga Info tab is not working anymore? When I typed something in, it just doesn't make any response lol.

Favorite's search bar is working however.

Also, is there a way to make an automated backup everytime the app making an update? Just in case something is going wrong and we can make a rollback to prev version.

Thanks~

EDIT:
Also, for some reason Mangadex's manga list keep disappearing and downloading it from the server always leads to 404 error. :(

**Comment by rs3mk** [comment]
options-> websites-> websites -> check scans

**Comment by riderkick** [comment]
There is a chance your config is broken due to erroneous in #1059.
Options> General > Live search.
