### ISSUE TITLE
FMD errors upon opening with "EScannerError" exception class

### ISSUE THREAD

**Issue by WaitWhat4355** [riderkick/FMD#1067]
I can't use FMD, after updating it, and manually updating it to 0.9.150.0 doesn't help either. 

At first, after letting it update by itself, it would just repeatedly open and close the Exception info window, and after manually updating it myself, the Exception appears and stays.

> Unhandled exception!
> Application       : Free Manga Downloader
> Version           : 0.9.150.0
> Product Version   : Win32 Debug
> Host Machine      : Windows 10 64-bit
> FPC Version       : 3.0.4
> LCL Version       : 1.8.0.6
> WidgetSet         : Win32/Win64
> Target CPU-OS     : i386-Win32
> Build Time        : 2018/02/26 19:34:43
> Path              : D:\Other Folders-Files\FreeMangaDownloader\fmd.exe
> Process ID        : 2928
> MainThread ID     : 11940
> Thread ID         : 11940
> Time              : 26/02/2018 23:25:00.327
> Exception Class   : EScannerError
> Message           : string exceeds end of line
>   $0057BD89
>   $0057C3D7
>   $0057BD75
>   $0057CE85
>   $0057D1AC
>   $0057CE85
>   $0057D31C
>   $0057CEA2
>   $0057CC91
>   $00462A0B  TMAINFORM__TMSTARTUPTIMER,  line 1768 of ./forms/frmMain.pas
>   $0056ABF0
>   $73DBE0BB
>   $73DC8849
>   $73DCAED1
>   $73DB8E1C
>   $73DB8C20
>   $00507B95

I've tried going through each folder and replacing everything or deleting it if it doesn't seem like it holds info I'd like to keep, but to no avail. 

S.O.S
Send Help

**Comment by Tmp341** [comment]
I think you're using x86 version. Have you ever tried x64 one? Just thinking.

**Comment by WaitWhat4355** [comment]
No, but just tried it, works, thanks.
Idk why it had the issue before I tried manually updating it though.

**Comment by riderkick** [comment]
EScannerError can be triggered when reading broken json file.
