### ISSUE TITLE
Feature Request: Move/Rename completed

### ISSUE THREAD

**Issue by greenaar** [riderkick/FMD#107]
It would be really handy to have FMD tag or move completed comics.. in a folder with over 500, it's sometimes hard to tell what's been finished, and what's ongoing.

Possible? Hard?

**Comment by riderkick** [comment]
Just save as cbz/zip/pdf. Then you can tell what's completed and not.

**Comment by greenaar** [comment]
Sorry, I wasn't clear -- I meant when a series is completely done, and I have all the chapters, it'd be nice to be able to ID a 'finished' set vs an 'ongoing'.  I already do .cbz for my own sanity.  Even an extra file in the comic dir (ie 'completed.txt') would aid in sorting.  As it is, I go through my folders maybe twice a year, comparing the list against the folders, then checking to see that indeed, the comic is actually done.

Don't know what the level of effort to any of these things would be, but it's a feature no comic downloader i've used has.
