### ISSUE TITLE
Exception when searching

### ISSUE THREAD

**Issue by Meliodas-Sama** [riderkick/FMD#1072]
First of all, thank you for your hard work FMD developers.
When I try to search for website name or sitting name in:
Options->Website->Advanced.
This exception shows:

Program exception!
Application       : Free Manga Downloader
Version           : 0.9.150.0
Product Version   : Win64 Debug
Host Machine      : Windows 10 64-bit
FPC Version       : 3.0.4
LCL Version       : 1.8.0.6
WidgetSet         : Win32/Win64
Target CPU-OS     : x86_64-Win64
Build Time        : 2018/02/26 19:33:47
Path              : D:\setup\Tools\Manga\Fmd\FMD\fmd.exe
Process ID        : 2408
MainThread ID     : 6352
Thread ID         : 6352
Time              : 27-02-2018 12:51:19.293
Exception Class   : EAccessViolation
Message           : Access violation
  $000000010026CC5F
  $000000010003A7B6 line 767 of ../baseunits/uBaseUnit.pas
  $0000000100536BFF line 68 of forms/frmWebsiteSettings.pas
  $00000001002CEF22
  $00000001002CE1DD
  $000000010017B53E
  $000000010020FF39
  $000000010017B4F0
  $000000010020FEF3
  $000000010015E141
  $0000000100010905
  $000000010015FDB9
  $00000001001559D5
  $000000010017B141
  $00000001001ECBF0
  $000000010013B701
  $000000010013BD4C

**Comment by riderkick** [comment]
What do you type? I can't reproduce it.

**Comment by Tmp341** [comment]
@riderkick I tried to type "Helvetica", but right after "h", got the same error.

**Comment by riderkick** [comment]
It seems only happen with win64 version.

**Comment by Meliodas-Sama** [comment]
Sorry, I didn't reply to your comment, I didn't open GitHub until now.
It didn't matter what I type.
I will try to explain more next time.
Thank you for your hard work.

**Comment by Tmp341** [comment]
@Meliodas-Sama It must be fixed with [0fcde01](https://github.com/riderkick/FMD/commit/0fcde01b92b0801af0ae9cceea68b6b51ae61ee1), we'll see with the new release.
