### ISSUE TITLE
MyReadingManga list doesn't show all available manga

### ISSUE THREAD

**Issue by g4269159** [riderkick/FMD#108]
The list is up to date, but doesn't have all of the manga available from website.
For example
Tag: TETSU-SABI (Fumidzuki-ji A)
There are 6 titles available on MyReadingManga under this tag, but only 1 shows up in FMD. I can't find the remaining 5 by titles either, so they're not in the list at all.

**Comment by riderkick** [comment]
Just update your list manually. book icon >update manga list.
you can download without manga list!. Just put the url in "url box" on "manga info" tab. or just drag and drop your url to dropbox, options > view > show drop box. Usually, if you're on search result or manga directory(on your browser) dragging the thumbnail will do.
