### ISSUE TITLE
Cannot Auto-extract update from 0.9.150.0 to 0.9.152.0

### ISSUE THREAD

**Issue by Ruma-eong** [riderkick/FMD#1081]
Hi, sir.
When it 0.9.149.0 to 0.9.150.0, update notif appears then when it finished download, it doesn't extract.
I extract manually and replace all file.
I see it bug has been reported.
Then now, I have same issue when update 0.9.150.0 to 0.9.152.0
Thanks.
:)

**Comment by ralvarador** [comment]
Me neither, but I just update it manually...
go to https://github.com/riderkick/FMD/releases , download the FMD newest version according with the "Architecture" that you are using (X86 7 X64); decompress over your current FMD's Folder; overwrite on prompt!

**Comment by Ruma-eong** [comment]
Yes, it can be done with that methode, or simply extract "updatepackage.7z" manually in FMD folder when auto-update has downloaded file.
![36728378-88eff31e-1b8e-11e8-9b26-40b708cdca35](https://user-images.githubusercontent.com/36926295/36795859-a45cfbee-1cd6-11e8-8d04-f36e8212271e.png)

**Comment by Ruma-eong** [comment]
The issue that I reported that Auto-extract doesn't like previous version.
Maybe there's problem with updater code i think.
:)

**Comment by Tmp341** [comment]
You gotta extract that updatepackage.7z or download from server and extract it. There was a problem with updater, so, it couldn't extract update package.
