### ISSUE TITLE
mangadex blank?

### ISSUE THREAD

**Issue by ratbunuts** [riderkick/FMD#1082]
Is just me? or  other's too? My mangadex when I check the manga info it is blank.

**Comment by anfgomezmo** [comment]
Mine is working; sometimes it takes time because the servers are slow or you need to update the list

**Comment by ratbunuts** [comment]
i did update the list. I dont know what wrong with mine

**Comment by ratbunuts** [comment]
Do i need to have an account on mangadex?

**Comment by muto4013** [comment]
If this happens directly after the list update there is a high chance that you have been banned. 
Go to mangadex website and try to open the info, if you are banned you get an error message.

**Comment by Tmp341** [comment]
Mangadex changed it's domain from mangadex.com to mangadex.org. So, you should wait until next update.

Fixed wit this: [32b9f52](https://github.com/riderkick/FMD/commit/32b9f52c29d480ac656e22a3a2634afee68e5e42)
