### ISSUE TITLE
Mangadex has moved from .com to .org

### ISSUE THREAD

**Issue by gooreat** [riderkick/FMD#1083]
Not really an issue, but saw someone posted on r/manga saying that Mangadex has moved to a new site, mangadex.org. Not sure if this will have any effect on FMD later on (I'm not an expert :P), since I can still access/download manga from their website.

Just wanted to let you guys know about it. :)

**Comment by anfgomezmo** [comment]
Well, Mangadex.com redirects to mangadex.org. It isn't affecting yet

**Comment by gooreat** [comment]
Yeah yup, hopefully it'll stay that way. :)
