### ISSUE TITLE
Website: failed to extract, Unable to create

### ISSUE THREAD

**Issue by codeduph** [riderkick/FMD#1084]
I'm having this problem with FDM 0.9.152.0

![2018-03-01_113109](https://user-images.githubusercontent.com/16449014/36826428-42aa21f2-1d48-11e8-9040-c4019b070ce0.png)
![2018-03-01_113142](https://user-images.githubusercontent.com/16449014/36826429-42efa326-1d48-11e8-99bd-0f75739c54c2.png)
![2018-03-01_113200](https://user-images.githubusercontent.com/16449014/36826430-433266fc-1d48-11e8-8e18-6010563e096e.png)

_ - _ - _ - _

![2018-03-01_114213](https://user-images.githubusercontent.com/16449014/36826431-437e873a-1d48-11e8-8ee9-5ea4354c5642.png)
![2018-03-01_115647](https://user-images.githubusercontent.com/16449014/36826432-43c1d4cc-1d48-11e8-8b40-4fb1657f112f.png)
![2018-03-01_115659](https://user-images.githubusercontent.com/16449014/36826433-4409dab0-1d48-11e8-9ba3-eba463275caa.png)

**Comment by kanatos-kun** [comment]
i have the same problem :(

**Comment by Tmp341** [comment]
Where you keep your fmd files?

**Comment by codeduph** [comment]
> https://sourceforge.net/projects/newfmd/files/data/

goes back to this download manually
