### ISSUE TITLE
Madokami not working

### ISSUE THREAD

**Issue by Souravi785** [riderkick/FMD#1086]
I logged in with my madokami account but its showing invalid in fmd. I'm logged in my actual account in madokami but not working in fmd. Can u solve this problem plz?

**Comment by mastafrooper** [comment]
Make sure you a running version 0.9.152.0.

It may need a manual update. Pretty sure I had to.

**Comment by SilentNN** [comment]
Still getting fails on latest build 0.9.152.0. Really unsure if it's just me.

Some examples are Go-Toubun no Hanayome ch 29, Kumo desu ga, Nani ka? ch 25-1 and 24.2, Chihayafuru 193, Ragna Crimson 8.2.
