### ISSUE TITLE
mangago and mangafox

### ISSUE THREAD

**Issue by sadeghp88** [riderkick/FMD#1088]
is there any plan to fix downloading from these sites?
if not please recommend another site.

**Comment by rs3mk** [comment]
check https://github.com/riderkick/FMD/issues/1085

**Comment by Tmp341** [comment]
> **Mangago download errors:** This one is the real pain. They most likely watching this project and adding some encryptions/scramblers to their code. Either read online or change your favorites until it is fixed. Even after it is fixed, you most likely don't have much time, because they are changing their code pretty quick like you are stealing their own pay per chapter works.

For mangafox:

MangaFox | http://fanfox.net | - | Not working in some countries
-- | -- | -- | --

When you have a problem with a site, first check this [wiki](https://github.com/riderkick/FMD/wiki/Websites)
