### ISSUE TITLE
Auto opening FMD

### ISSUE THREAD

**Issue by Slasar41** [riderkick/FMD#1089]
I open FMD and get the notification for modules update, I press yes. Then it will ask to exit, I press no.
Now if I exit manually, FMD will open again.
I enabled 'Auto restart' in Modules tab.

**Comment by Tmp341** [comment]
``Settings -> Websites -> Modules``

There is an option named "Auto restart".

**Comment by Slasar41** [comment]
I already enable "Auto restart".
What I mean is if I intentional press no when FMD itself ask to exit, and then I exit normally by myself, FMD will auto open again.
Which is it shouldn't do that, I mean to exit not to open FMD again.

**Comment by Tmp341** [comment]
That is strange. I've never experienced that.

**Comment by Slasar41** [comment]
Yes, if I disable "Auto restart", it will not open FMD again when I manually close it.
