### ISSUE TITLE
Access violation error while updating database manually [E-Hentai]

### ISSUE THREAD

**Issue by Tmp341** [riderkick/FMD#1090]
```
Program exception!
Application       : Free Manga Downloader
Version           : 0.9.152.0
Product Version   : Win64 Debug
Host Machine      : Windows 10 64-bit
FPC Version       : 3.0.4
LCL Version       : 1.8.0.6
WidgetSet         : Win32/Win64
Target CPU-OS     : x86_64-Win64
Build Time        : 2018/02/28 06:48:31
Path              : D:\Program Files\Portable\Fmd\fmd.exe
Process ID        : 3840
MainThread ID     : 2528
Thread ID         : 10344
Time              : 02.03.2018 14:38:08.693
Sender Class      : TUpdateListThread
Exception Class   : EAccessViolation
Message           : Access violation``

  Website : E-Hentai
  CS      : CS_DIRECTORY_COUNT

  $000000010052C972 line 88 of ../baseunits/modules/EHentai.pas
  $000000010052CBBE line 119 of ../baseunits/modules/EHentai.pas
  $0000000100406516 line 683 of ../baseunits/WebsiteModules.pas
  $0000000100407D14 line 126 of ../baseunits/uData.pas
  $0000000100247B0E line 141 of ../baseunits/uUpdateThread.pas
  $000000010005255D
  $0000000100003B86
  $0000000100015237
  $00007FF937E61FE4
  $00007FF93992EFC1
```
- Even my username is added.

**Comment by dianfajar** [comment]
Get same problem

Program exception!
Application       : Free Manga Downloader
Version           : 0.9.152.0
Product Version   : Win64 Debug
Host Machine      : Windows 10 64-bit
FPC Version       : 3.0.4
LCL Version       : 1.8.0.6
WidgetSet         : Win32/Win64
Target CPU-OS     : x86_64-Win64
Build Time        : 2018/02/28 06:48:31
Path              : C:\Users\Dian\Downloads\Compressed\fmd_0.9.150.0_Win64\fmd.exe
Process ID        : 5880
MainThread ID     : 8100
Thread ID         : 6320
Time              : 08/03/2018 11:44:18.037
Sender Class      : TGetMangaInfosThread
Exception Class   : EAccessViolation
Message           : Access violation
  $000000010052C972 line 88 of ../baseunits/modules/EHentai.pas
  $000000010052D191 line 211 of ../baseunits/modules/EHentai.pas
  $0000000100406694 line 717 of ../baseunits/WebsiteModules.pas
  $000000010040801A line 173 of ../baseunits/uData.pas
  $0000000100251DAC line 102 of ../baseunits/uGetMangaInfosThread.pas
  $0000000100251802 line 140 of ../baseunits/uGetMangaInfosThread.pas
  $000000010005255D
  $0000000100003B86
  $0000000100015237
  $00007FFB3DFC1FE4
  $00007FFB3FFFEF91
