### ISSUE TITLE
FMD crash when downloading manga

### ISSUE THREAD

**Issue by Ruma-eong** [riderkick/FMD#1091]
Hi Sir, Here's screenchot when I downloading file.
When browsing manga, it's fine, then when I download manga FMD gimme crash.
It's FMD v0.9.152.0

![ashampoo_snap_friday march 02 2018_20h21m29s_004_](https://user-images.githubusercontent.com/36926295/36901000-058d2da8-1e58-11e8-888a-0ace7435766d.jpg)

**Comment by Tmp341** [comment]
Have you tried fresh install?

**Comment by Ruma-eong** [comment]
I try to download latest version from main download release, then extract and replace anything in FMD folders.
For now, it's fine.
:)
