### ISSUE TITLE
Scanlation site request(s)

### ISSUE THREAD

**Issue by adustyspectacle** [riderkick/FMD#1094]
Requesting 5 (sorry ^^;;;) scanlations sites, all with FoOlslide readers:

Bunny Scans: http://bns.shounen-ai.net/read/
Canis Major Scans: http://cm-scans.shounen-ai.net/reader/
Hoshikuzuu Scans: http://hoshiscans.shounen-ai.net/
Yaoi is Life Scans: http://yaoislife.shounen-ai.net/reader/
Fujoshi Bitches: http://fujoshibitches.shounen-ai.net/reader/

These five are the ones that update frequently, as the other groups from that domain that I can find all stopped/moved/etc years ago.

**Comment by rs3mk** [comment]
you can add it manually here
https://github.com/riderkick/FMD/edit/master/lua/modules/FoOlSlide.lua

**Comment by adustyspectacle** [comment]
Okay, I'm not too familiar with Lua but reading through it I just have to add them in the `getdirurl` function and at the `Init` function, yeah?
