### ISSUE TITLE
Can't open fmd

### ISSUE THREAD

**Issue by Maxhimilian** [riderkick/FMD#1099]
Process ID        : 9772
MainThread ID     : 16112
Thread ID         : 16112
Time              : 05/03/2018 23:39:50.755
Exception Class   : EJSONParser
Message           : Error at line 1, Pos -9786528:Unexpected EOF encountered.
  $00000001001CD001
  $00000001001CC90B
  $00000001001CCCB0
  $00000001001CC9B0
  $00000001001CCDEA
  $00000001001CC9D4
  $00000001001CC792
  $00000001002B91F8 line 341 of forms/frmLuaModulesUpdater.pas
  $00000001002BB7A3 line 974 of forms/frmLuaModulesUpdater.pas
  $00000001002BB1FD line 847 of forms/frmLuaModulesUpdater.pas
  $00000001000211D1
  $000000010001F752
  $0000000100025DD7
  $000000010007421A line 1226 of forms/frmMain.pas
  $00000001000211D1
  $000000010001F752
  $0000000100025DD7

Downloaded the latest version, replaced all the files, and nothing. Help, please.

**Comment by kmvi** [comment]
Try to remove `config\luamodules.json` and run FMD

**Comment by Maxhimilian** [comment]
Didn't work...

**Comment by Maxhimilian** [comment]
YES! it's working now, thank you!
