### ISSUE TITLE
LHtranslation stopped working

### ISSUE THREAD

**Issue by muto4013** [riderkick/FMD#1109]
seems LHtranslation have changed their website from .com to .net, so FMD doesn't work with them.
Could someone please confirm and maybe update FMD ?

**Comment by Tmp341** [comment]
Inside ``lua\modules\LHTranslation.lua``

Find the line below : 
```m.RootURL = 'http://lhtranslation.com'```

and change to this : 
```m.RootURL = 'http://lhtranslation.net'```

**Comment by muto4013** [comment]
thanks, it works.
