### ISSUE TITLE
Mangadex multiple entries after update manga list

### ISSUE THREAD

**Issue by admiralmikan** [riderkick/FMD#1111]
![2018-03-10 12_13_41-free manga downloader](https://user-images.githubusercontent.com/17843605/37238617-dab59ca4-245c-11e8-801e-e97b5748d29d.jpg)
I always got these after updating my Mangadex from their server directly whenever I found new manga on bakaupdates that I like. 

Any solution for this?

**Comment by Tmp341** [comment]
I had the same problem and after the recent mangadex.lua changes, it is fixed. But i think you should delete mangadex.db file.

**Comment by kmvi** [comment]
#1040
