### ISSUE TITLE
Mangasteam just...gone from the website list?

### ISSUE THREAD

**Issue by lin4t** [riderkick/FMD#1113]
I recently manually updated to the 0.9.152.0 version and I found out that the mangastream list just disappeared entirely when I saw updates on the site but not in my downloads. The favorite bookmarks are still there but aren't responding. Manually inputting a series URL in brings up the information that the URL is not supported.

I'm not sure if this was a version issue or something else since I have a download from the site that dates to the 5th of March and I can't remember precisely when I actually updated the software.

**Comment by Tmp341** [comment]
Have you tried fresh install? It seems like your config might have messed up. Because i can reach mangastream.

**Comment by lin4t** [comment]
Ah thanks. After comparing to a fresh install, I noticed that apparently I needed to update the Website Modules that appeared on the new download. I was apparently missing a lot of the scanlation websites it seemed since only three appeared before. Just needed to update it to fix it since it didn't automatically update for some reason.

**Comment by Tmp341** [comment]
There were problems with some modules, so, the core changed from time to time.
