### ISSUE TITLE
Problems With Sites

### ISSUE THREAD

**Issue by Tmp341** [riderkick/FMD#1115]
- [x] ~~LHTranslation.net was working after i've changed and added PR. But when i was downloading 7 chapters, it stopped working after 3rd chapter. Fmd gives an error. ``(My default settings are "1" tasks at the same time, "2" files at the same time.)``~~

- [x] ~~I couldn't be able to download from kissmanga even i had "DCP" option unselected. And i even tried browser trick. But it worked itself, finished downloading when i wasn't looking at fmd. I thought i should check kissmanga, i came accross with a "Are you human?" captcha. This might be the cause.~~ Today, downloaded a manga without an error.

**Comment by bloodsucker3011** [comment]
All the adult site is down too .............. only Porncomix and Freeadultcomix is working but it fail to download any comic
