### ISSUE TITLE
Will Batoto's revision affect FMD?

### ISSUE THREAD

**Issue by Tenome** [riderkick/FMD#112]
http://bato.to/forums/topic/23683-batoto-becoming-private/

**Comment by Tenome** [comment]
http://bato.to/forums/topic/23703-moving-forward-upcoming-changes-and-schedules

**Comment by Twoearle** [comment]
Maybe an account management option should be added for sites that require login info such as madokami and lately batoto?

**Comment by riderkick** [comment]
https://github.com/riderkick/FMD/issues/114
