### ISSUE TITLE
Kissmanga and MangaInn shows no chapter.

### ISSUE THREAD

**Issue by rro123** [riderkick/FMD#1122]
After i update my FMD to 0.9.152.0, those 2 sites no longer accessable. Could you fix it?

Also, i see that some sites requires preparing first before downloading, such as mangafox, which makes the downloading time become much longer.  Is it possible to skip those preparing sequence and go immediately for the download? If yes, then how to set it? Thanks.

**Comment by Tmp341** [comment]
For mangafox, check [FAQ](https://github.com/riderkick/FMD/wiki/FAQ).

For kissmanga, i can check and download without a problem.

**Comment by rro123** [comment]
I made a video to show this problem.

https://streamable.com/45dqh

I tried downloading the program from source forge, and use the new one instead. But the problem still exist in the new FMD. Both kissmanga and mangainn is still inaccessable. Also, in case of mangainn, the manga that i try to download changed into 404 Page Not Found, just like shown in the video.

As for mangafox, it's not that i can't download or a skip problem like shown in the faqs. What i meant is, when i download from mangafox and some other sites, such as kissmanga and mangapanda, there's a preparation period, where the download bar has yellow colour instead of blue one. But when i download from mangainn and mangarock, there's no preparation period, and immediately downloading the file (blue bar), as shown in the video. I don't know what makes it different between those sites, but is it possible to remove this preparation period, to reduce the amount of time needed to download manga? Thanks.

**Comment by kmvi** [comment]
I've updated MangaInn database, re-download it from server.

As for MangaFox, it's not possible. We should enumerate all chapter pages before we can download images. Most sites provide all images at the first chapter page, but MangaFox is not.

I can't reproduce KissManga issue.

**Comment by rro123** [comment]
Thanks for solving the issue about MangaInn. It's a pity that nothing can be done to remove the preparation sequence, but no matter.

As for kissmanga, it seems that it was recently added to blocked list a few days ago by my ISP. I remember that i can access it normally before (the last time i download from kissmanga is at 10/3/2018). But now i can't access it anymore. I guess that's the reason why i can't connect to it. Anyway, thanks for the help.
