### ISSUE TITLE
All my favorites were deleted.

### ISSUE THREAD

**Issue by sky1206** [riderkick/FMD#1127]
I update my manga list per week, and this week when I opened up FMD, all my favorites were gone? Now I need to manually favorite them again, I want to ask though, I can't seem to find an export button to export my favorites list. Help pls.

**Comment by Tmp341** [comment]
They are stored in a database file. You can add them manually, but needs a lot of effort.

You might have accidentally deleted ``favorites.db`` file inside ``works\`` folder.

**Comment by sky1206** [comment]
Thank you sooo much! Apparently my favorites.db was still there. They just didnt show up after opening FMD with the latest update. I simply redownloaded FMD, update, and transfer my works folder and all is good again.
