### ISSUE TITLE
nhentai not supported on latest version

### ISSUE THREAD

**Issue by kevin01523** [riderkick/FMD#1134]
![image](https://user-images.githubusercontent.com/8380242/37727442-d292f796-2d72-11e8-8795-9bf88adc1d99.png)

it says not supported on latest version and nhentai is missing on website options
![image](https://user-images.githubusercontent.com/8380242/37727376-9a885b66-2d72-11e8-9194-b912cab82a10.png)
i can still download on via fmd on older versions like version 129

**Comment by Tmp341** [comment]
It is working here. I've checked your link, even got a response, for example artist is ``ichihaya``.

Your settings are corrupted it seems. You should have **nhentai, hentairead, luscious, pururin and readhentaimanga** sites too. 

Backup these listed files and folders below, delete everything else:

- ``Works\favorites.db`` ``works\downloads.db`` and ``works\downloadedchapters.db
- ``data`` folder. You can delete xxxxx.db files if that xxxxx site isn't working properly. You can rebuild them later.

**Comment by kevin01523** [comment]
ah i got the bug when you update fmd from an older version nhentai and some sites do end up get missing since i tried it on a clean older version fmd then downloaded some nhentai chapters then updated fmd on the latest one i reproduced it just now ill try it on the test fmd folder if it works after i delete some db files

**Comment by kevin01523** [comment]
ok it got fixed when i updated the modules thingy i guess that was what was broken when i updated fmd after 5 months
