### ISSUE TITLE
neumanga.tv error

### ISSUE THREAD

**Issue by 1klkl** [riderkick/FMD#1137]
view manga info:
Ajin (60) become N/A (60)

**Comment by Tmp341** [comment]
``0060 - Ajin - 0056``

I can see chapter list completely. You should check your connection and/or settings.

**Comment by 1klkl** [comment]
Title:
N/A >>>>>> (Ajin)

Author(s):
Miura Tsuina

Artist(s):
Sakurai Gamon

Genre(s):
Action, Adventure, Mystery, Horror, Supernatural, Seinen


list neumanga.tv in FMD
N/A (60)
