### ISSUE TITLE
Mangadex can't view chapters

### ISSUE THREAD

**Issue by bennettn** [riderkick/FMD#1140]
The manga list for mangadex will populate, but when navigating to a specific title, no chapters are displayed. Most recent chapter for all favorites is 0 from mangadex.

**Comment by Tmp341** [comment]
I can see without a problem.

- Check if you can connect mangadex via browser.
- Redownload mangadex module.

**Comment by bennettn** [comment]
No problems connecting via browser, redownloading the module did not change anything.

Below is a picture of a manga that I just checked through browser and read the most recent chapter of, but won't update or load in fmd
![](https://puu.sh/zPg1b/9e26bd4a99.png)
