### ISSUE TITLE
[Closed] Kissmanga not working

### ISSUE THREAD

**Issue by taigalover** [riderkick/FMD#1148]
Kissmanga is showing chapters but isnt downloading. I've tried some of the other solutions like opening the browser the downloading. And un-checking "Use Google DCP". But still nothing. 

The download is stuck at 1 chapter and keeps checking, turning blue and yellow. Then it eventually fails.

Is the only solution left is to downgrade to a previous version? 
Am using ver. 0.9.152.0.

**Comment by Tmp341** [comment]
1.    Open kissmanga.com -> Open a manga chapter's first page.
2.    Right click -> inspect element -> choose "console"
3.    Type "chko" and hit enter. Copy and paste what has returned from that code to a blank text file. For example "mshsdf832nsdbash20asdm".
4.    Now type "CryptoJS.enc.Hex.stringify(iv)" and hit enter. Copy and paste what has returned from that code to a blank text file. For example "a5e8e2e9c2721be0a84ad660c472c1f3"
5.    Open FMD -> Go to "Settings -> Websites -> Options" tab. Paste those codes to "Key" and Initialization Vector".
6.    Save.
7.    Restart FMD.
8.    Check again.

**Comment by taigalover** [comment]
Works perfect now. Thanks so much. Appreciate it.
