### ISSUE TITLE
MangaHere bait and switch

### ISSUE THREAD

**Issue by greenaar** [riderkick/FMD#115]
Mangahere just started putting up a placeholder gif just prior to displaying the image pages.  This results in FMD capturing the wrong image.

**Comment by corpse69** [comment]
shits breaking all over the place lately x,x

**Comment by Wolfpup67** [comment]
I just tried a different down loader program and it was able to properly download the images from mangaher site because it looks for a specific line in the page and then uses that for the DL link for the imiage.

**Comment by g4269159** [comment]
It's been like 2 months since the last FMD update, download everything you can before it breaks down even more.

**Comment by corpse69** [comment]
i dont think its wise to give them another reason to clamp down, ridekick will be back~
