### ISSUE TITLE
error- fmd closing - ptogram execution

### ISSUE THREAD

**Issue by leoteesh** [riderkick/FMD#1154]
hi, getting the below error when i open fmd
![image](https://user-images.githubusercontent.com/21075197/38176468-59722300-35e7-11e8-9d44-47b79700ab1c.png)
![image](https://user-images.githubusercontent.com/21075197/38176474-76168f00-35e7-11e8-9a4d-9ef29310a27a.png)
![image](https://user-images.githubusercontent.com/21075197/38176485-b31678de-35e7-11e8-93cb-3305d9235836.png)

any ideas? thanks so much

**Comment by Tmp341** [comment]
Download FMD again, copy and paste ``Images`` folder inside.
