### ISSUE TITLE
Can't download from MangaGo

### ISSUE THREAD

**Issue by Illyria77** [riderkick/FMD#1157]
As title says, MangaGo shows info and everything, but when I try to download, it stops at 0bps and nothing happens from there. Version 0.9.152.0. Any ideas what's going on?

**Comment by 0xh3LL0** [comment]
what manga you want to download? maybe i can test...

**Comment by Tmp341** [comment]
MangaGo | http://www.mangago.me | Broken | -
-- | -- | -- | --

In the [Wiki](https://github.com/riderkick/FMD/wiki/Websites), MangaGo stated as **broken**.

**Comment by LakotaGray** [comment]
Continuous Obfuscation technique changes is one of the drawback of open source stuff... :( It'd be nice if they just got their heads out of their asses and let it go....

**Comment by Tmp341** [comment]
And the hilarious point is, they must be feeling like we are stealing what they sell.

Most of the online readers are getting their materials from other sites.
