### ISSUE TITLE
Find all new manga locks up FMD

### ISSUE THREAD

**Issue by molitar** [riderkick/FMD#1158]
I did a find for all new manga for all sites.  Than I went to double click to review the info on a manga that sounded interesting and it just froze up.  I had to end task to close it.

Can't we figure out a better way to find new manga's?  Current method is severely lacking and difficult to find.. Domdomsoft had this feature down pat.

**Comment by Tmp341** [comment]
Other than first Mangadex problems, i don't have a ``doubleclick on manga and crash`` error.

You can get new mangas by:

- Update manga list manually.
- Copy and paste links and favorite it.

You might have a problem on your settings.

How you get that error? Give me steps, so i can reproduce it.

**Comment by wuhugm** [comment]
I also experienced that and mentioned in the previous thread :

https://github.com/riderkick/FMD/issues/1149

**Comment by molitar** [comment]
Ok here is what I am searching for.

Have all Genre checked.  [Ecchi, Fantasy]  (typically search for 2 or 3) 
Search only new Manga
Search in all manga sites

I'll test the latest release and see how it's working.
