### ISSUE TITLE
KissManga (CF Anti-DDoS)

### ISSUE THREAD

**Issue by Davoxe** [riderkick/FMD#116]
When checking for chapters, FMD is stuck on manga from KissManga. I also can't view the manga info for any of the manga even when manually pasting it into FMD.

**Comment by R-Jimenez** [comment]
Seems like Kiss is using some browser checker now, which is most likely causing an issue with FMD. First Batoto, and now this? This is truly the end of days.

**Comment by nille02** [comment]
I can confirm this. Since this morning, kissmanga is broken :/ (Yesterday i switches everything from batoto to kissmanga ...)

Today i looked at the loader tools that kissmanga advertise (its free but you some important features you has to pay) and test it with a 1 year subscription. btw, this tool supports batoto with the login oO

**Comment by corpse69** [comment]
i know how you feel nile i did that 2 days ago with the favorites it took me ages to redo my list

**Comment by Davoxe** [comment]
@nille02 Yeah, i just switched everything over to KissManga, tried to run the update to check for new chapters and nothing was happening :/

What site are you using now?

**Comment by nille02** [comment]
i'm using batoto and kissmanga (for the one where batoto has get dcma takedowns). Kissmanga advertise another tool for downloading but the free use is limited and for the important features you has to pay each year or you can buy a lifetime license. 

For some other mangas i use animea. 

Kissmanga alone is not a good choice.  Some sites are deleted from the hosters that kissmanga use (e.g. blogspot). there is some kind of nude filter. 

As a reader i use a android tablet with around 7" and mangawatcher as app. The mangas are synced with syncthing from my computer to the tablet. Important: store the mangas as cbz archives or mangawatcher get some troubbles about the sorting :/ a alternative app is perfect view for android. nice tool.

**Comment by skules** [comment]
Is this going to get updated or is it dead?

**Comment by carljbai** [comment]
Bump as this is still broken.

**Comment by echoPN** [comment]
so the problem is Kissmanga use Cloudflare to prevent Third App access...
:rofl:

**Comment by echoPN** [comment]
So that the case...
I though they prevent Third App, so just they change the Encryption Keys...
