### ISSUE TITLE
Mangadex doesn't work

### ISSUE THREAD

**Issue by muto4013** [riderkick/FMD#1162]
maybe it's just me but mangadex stopped to work with fmd.
Favorites show 0 chapter, same in mangainfo.
Have already tried the following: reinstalled fmd from backup, updated lua,, did a fresh install, have used different machines. Different ip's, proxies, vpn even a remote session from other country didn't work.
Changing the user agent was also a no-go. Also exchanging the mangadex.db (backup and fresh) didn't work.
Mangadex works in browser, even with jdownloader i could download some pages.

Now i am out of options, anyone with new ideas ?

**Comment by jokosablenk** [comment]
same problem on my end 0 chapter.

**Comment by muto4013** [comment]
ok, have updated the lua again, either kmvi found the fix or mangadex had a server problem, few chapters are re-appeared.
