### ISSUE TITLE
Favorites UI column bug

### ISSUE THREAD

**Issue by ronny1982** [riderkick/FMD#1167]
<img width="1106" alt="capture" src="https://user-images.githubusercontent.com/27136773/38467081-6ffc10da-3b33-11e8-8791-374f872adba7.PNG">
Maybe only on high-res displays?

**Comment by Tmp341** [comment]
![ssss](https://user-images.githubusercontent.com/1683388/38467972-366dc844-3b48-11e8-8186-af32cac98dca.jpg)

**Comment by Ouxhi** [comment]
I'm getting the same issue, just updated FMD to 0.9.153 and there are huge black columns on the screens for the Favorites and Downloads tabs.

**Comment by Tmp341** [comment]
[Fresh Install](https://github.com/riderkick/FMD/wiki/FAQ#fresh-install-steps) should solve your problem. Because, it is on your end.

**Comment by ronny1982** [comment]
Maybe the problem is not reproducible on your end.
As i wrote in my first post the problem appeared on a 4k screen, not tested with other screens they may work just fine. Maybe it isn't even the screen and it is something else...

**Comment by Tmp341** [comment]
We need other 4k users then.

**Comment by phage80** [comment]
I am also having this issue  at 2560x1440 and 4k if I turn resolution down to 1080p it works fine.
I had not had this issue previously.

**Comment by Ouxhi** [comment]
Seems to be fixed with the latest release for me.
