### ISSUE TITLE
Mangafox chapters downloading, but failing still.

### ISSUE THREAD

**Issue by TheKrister2** [riderkick/FMD#117]
Some series (The Gamer for an example) downloads the chapters successfully but others do not (Saikin, Imouto no Yousu ga Chotto Okashii n da ga for an example) I do not know why this is happening but it probably comes from Mangafox and not the program itself.
I have yet to try out other manga services in the program simply because I like Mangafox and the somewhat better quality standard when it comes to how they handle page-by-page.

**Comment by TheKrister2** [comment]
The images do get downloaded but they are not compressed into a zip file

**Comment by riderkick** [comment]
Probably some files permanently deleted from server. Sometimes it's occurred on old series.
You have to check it manually with your browser.
