### ISSUE TITLE
E-/ExHentai Issues

### ISSUE THREAD

**Issue by leknaat345** [riderkick/FMD#1176]
Attempting to get manga info from ExHentai gives me "Cannot get manga info. Please check your internet connection and try again."; same message applies after changing connections. In E-Hentai, a pop-up appears with the ff info:

Program exception!
Application       : Free Manga Downloader
Version           : 0.9.153.0
Product Version   : Win32 Debug
Host Machine      : Windows 7
FPC Version       : 3.0.4
LCL Version       : 1.8.0.6
WidgetSet         : Win32/Win64
Target CPU-OS     : i386-Win32
Build Time        : 2018/04/08 13:22:38
Path              : D:\Torrent\Downloads\Mangas\Free Manga Downloader\fmd.exe
Process ID        : 6548
MainThread ID     : 6052
Thread ID         : 8032
Time              : 09/04/2018 21:04:40.120
Sender Class      : TGetMangaInfosThread
Exception Class   : EAccessViolation
Message           : Access violation
  $00881FDC  GETWITHLOGIN,  line 88 of D:/user/_src/FMD/baseunits/modules/EHentai.pas
  $00882614  GETINFO,  line 211 of D:/user/_src/FMD/baseunits/modules/EHentai.pas
  $00788D8B  TWEBSITEMODULES__GETINFO,  line 717 of D:/user/_src/FMD/baseunits/WebsiteModules.pas
  $0078A1D3  TMANGAINFORMATION__GETINFOFROMURL,  line 173 of D:/user/_src/FMD/baseunits/uData.pas
  $00612362  GETMANGAINFO,  line 102 of D:/user/_src/FMD/baseunits/uGetMangaInfosThread.pas
  $00611E67  TGETMANGAINFOSTHREAD__EXECUTE,  line 140 of D:/user/_src/FMD/baseunits/uGetMangaInfosThread.pas
  $00447655
  $00412E1E
  $76EDEF8C
  $7733367A
  $7733364D

Followed by the same message from Ex. Any help or advice is greatly appreciated, thank you in advance.

**Comment by Tmp341** [comment]
Yeah, got the same error when i was trying to add an E-Hentai link.

**Comment by kmvi** [comment]
#1090
