### ISSUE TITLE
cant download from kissmanga

### ISSUE THREAD

**Issue by simps613** [riderkick/FMD#1187]
^ as the title says

**Comment by bunularlaki** [comment]
same as me.. i cant opened.. just long time loading, in the end text show up just say check your internet connection.. even though my connection just fine..

**Comment by simps613** [comment]
its working again now

**Comment by Tmp341** [comment]
Check [FAQ](https://github.com/riderkick/FMD/wiki/FAQ#cannot-download-from-kissmanga)
