### ISSUE TITLE
Refuses to dl from Mangago

### ISSUE THREAD

**Issue by Shianelle** [riderkick/FMD#1192]
I can't download from Mangago. I've tried other places and they work just fine, but Mangago won't download and sometimes it tells me the url is invalid, even though I'm trying to download an updated chapter from a url that worked previously.

**Comment by Tmp341** [comment]
`

MangaGo | http://www.mangago.me | Broken | -
-- | -- | -- | --

As it is stated in [here (Wiki)](https://github.com/riderkick/FMD/wiki/Websites) and [here (FAQ)](https://github.com/riderkick/FMD/wiki/FAQ#cannot-download-from-mangago), mangago is broken. They are watching this project (most likely) and breaking FMD each time it is fixed.

`

**Comment by Shianelle** [comment]
Thank you for the info!

**Comment by ronny1982** [comment]
I don't know why so many people like MangaGo (they use re-compressed stolen images from other sites which leads to poor quality), but HakuNeko can download from MangaGo if you really want to download from them...
