### ISSUE TITLE
Better instruction how to compile

### ISSUE THREAD

**Issue by AsukaLangleyfag** [riderkick/FMD#120]
Well, I've managed to find all libs you use as in readme, but it's still hard to make it works (or I'm just dumb and managed to fail horribly). Can you include the libs you use in the source code or perhaps the better instruction how to build FMD?

**Comment by riderkick** [comment]
What problem you got. If there is error message. You should be able to follow the hint how to fix the issue. For novice programmer, it may hard at the beginning. I suggest to check lazarus forum.
