### ISSUE TITLE
Do not redistribute debug symbols

### ISSUE THREAD

**Issue by ChocolateOtaku** [riderkick/FMD#1202]
The debug symbols (fmd.dbg) are currently distributed in the 7z archive.
Without the debug symbols the archive can save 3-3.5 MB (30-40% of archive size).
This would save bandwidth and users with slow internet would benefit from faster auto updates.

<img width="501" alt="size" src="https://user-images.githubusercontent.com/38581381/39082327-9f405a9a-4551-11e8-8317-9142098ca099.png">

**Comment by kmvi** [comment]
Without dbg file, the stack traces will not be informative
