### ISSUE TITLE
Customize LUA modules and create compiled LUA modules

### ISSUE THREAD

**Issue by ChocolateOtaku** [riderkick/FMD#1203]
I found that FMD uses LUA modules for its websites, but there seems to be no way to modify the modules permanently (overwritten by update) or add my own modules.

**Comment by kmvi** [comment]
You can create your own files, they will be scanned and added automatically on program start

**Comment by ChocolateOtaku** [comment]
So modified lua files will not be overwritten by server updates, or i have to clone and rename them?

Also directory scanning seems not to work for compiled lua files, but only for source lua files.
Source lua files are easy to edit, but also easy for websites like MangaGo to analyze and make counter measurements, while compiled lua files have the advantage of being some kind of hard to read.

=> changed title
