### ISSUE TITLE
Failed to download DesuMe.DB

### ISSUE THREAD

**Issue by Broccoli-nyu** [riderkick/FMD#1206]
Can you fix this?

![2018-04-24_16-00-09](https://user-images.githubusercontent.com/38692648/39188557-c184d066-47d8-11e8-8bf0-f25c05a9ac7b.jpg)

**Comment by kmvi** [comment]
You can track changes here -> #1021 
Many databases are missing, since filling them takes a very long time. Until the database is available, you can just copy-paste the manga URL into 'Input URL here' textbox.
