### ISSUE TITLE
Failed to download Manga

### ISSUE THREAD

**Issue by Broccoli-nyu** [riderkick/FMD#1207]
I'm trying to download a certain manga from mintmanga.com
Do not want to download the specific manga: Yuuna-san's Ghost Inn.
More precisely - the program does not determine the number of chapters, as a result of which the download does not start(https://i.imgur.com/lm1uYr6.png).
At the moment there are 101 chapters on that site (https://i.imgur.com/O5gBHby.png).

***
Added links to pictures, so that it was obvious. Unfortunately, the uploader built into this site did not want to take screenshots.

**Comment by kmvi** [comment]
It's because the manga url has been changed to http://mintmanga.com/yuuna_san_s_ghost_inn We need to update mintmanga database again.

**Comment by kmvi** [comment]
database has been updated
