### ISSUE TITLE
[Major Update]HatigarmScans Changes Domain and Readers

### ISSUE THREAD

**Issue by JokoeSukri** [riderkick/FMD#1262]
**Previously** 
Domain : https://www.hatigarmscans.eu/
Reader : https://hatigarmscans.eu/hs/[manga_title]

**New**
Domain : https://www.hatigarmscans.net/
Reader : https://www.hatigarmscans.net/manga/[manga_title]

**Comment by kmvi** [comment]
already updated #1259
