### ISSUE TITLE
Manga sites changed their scripts again?

### ISSUE THREAD

**Issue by StormJumper** [riderkick/FMD#128]
I just checked on OnePunch-Man on various sites and those very same sites are blocking or changed their access to their sites again. I think you might have to rewrite the scripts again.
KissManga, Manga2u, MangaGo (loads but no manga downloaded), MangaHere (same as MangaGo).

**Comment by StormJumper** [comment]
I was able to download from MangaGo but MangaHere for OnePunch-Man doesn't download still. It starts but the folders are empty.

**Comment by riderkick** [comment]
this series was licensed on some website. So it's not available to view/download.
