### ISSUE TITLE
[TMO / TuMangaOnline] Change domain [Spanish]

### ISSUE THREAD

**Issue by GATOQSECOMIO** [riderkick/FMD#1283]
old domain : https://www.tumangaonline.com/

new domain [Beta test] : https://www.tumangaonline.me/

**Comment by ralvarador** [comment]
I just came here to write... X2

**Comment by ralvarador** [comment]
Thanks for the fix!
Is there a way to change the ".com/biblioteca/mangas/" to ".me/library/manga/" in a batch way, directly on the favorites list?
I know I can use a SQL query to export the list of URLs, next, use the "Search and Replace" then add the new URLs... One by One :V

**Comment by kmvi** [comment]
There is no easy way to do this, you should use any sqlite editor (for example, https://sqlitebrowser.org/) to modify favorites.db:
- make a backup of `works/favorites.db`
- open favorites.db in the editor and execute the following sql:
```sql
update favorites
set link=replace(link, 'biblioteca/mangas', 'library/manga'),
websitelink=replace(websitelink, 'biblioteca/mangas', 'library/manga')
where website='Tumangaonline'
```

**Comment by sophie5555** [comment]
thanks [🙄](https://eduwriter.ai/) waiting....
