### ISSUE TITLE
KissManga fails to download manga

### ISSUE THREAD

**Issue by BluePlasticCup** [riderkick/FMD#1284]
No amount of retries fixes it.
Please help?
KissManga has a lot of series that I can't get anywhere else.

**Comment by traitorAIZEN** [comment]
Options>Websites>Options>Kissmanga> check or uncheck the "Use Google DCP"

**Comment by BluePlasticCup** [comment]
Immediate fix.
Thanks mate.

**Comment by Tmp341** [comment]
There is a [FAQ](https://github.com/riderkick/FMD/wiki/FAQ) page contains infos about common errors/questions.
