### ISSUE TITLE
Tumangaonline

### ISSUE THREAD

**Issue by Alexcr86** [riderkick/FMD#1291]
dejo de funcionar para esa pagina :(

**Comment by ralvarador** [comment]
Until last release of tumangaonline.lua, I was able download from tumangaonline.me... 2018-06-16,17,18...
but not today 2018-06-20.

Probably TMO have made changes.
![image](https://user-images.githubusercontent.com/30580377/41697765-fc124158-74df-11e8-97bf-b80b7f40bf9a.png)
