### ISSUE TITLE
Problems setting up build enviroment

### ISSUE THREAD

**Issue by Wolfpup67** [riderkick/FMD#131]
Im trying to set up the build environment for this project on my Windows 10 64bit system using Lazarus v1.2.4. I'm unable to get RichMemo and InternetTools to install into Lazarus at all as i keep getting rebuild errors for the ide.

**Comment by StormJumper** [comment]
Did you try to contact Lazarus support as this is their software and it isn't something FMD can do about.

**Comment by riderkick** [comment]
You should provide more information of your problem, what error message you got?

**Comment by Wolfpup67** [comment]
thx to the Lazarus forum i was able to get it configured. But when i try to build FMD i get the following error:

synautil.pass(398,19)Error: Unicodechar/string constants cannot be converted to ansi/shortstring at compile time

there are 11 of these errors and they are all related to the atl languages for the months/days in the program.

**Comment by riderkick** [comment]
Because we had -dEnableUTF8RTL on compiler options, its expect all file to be encoded in UTF-8.
Just change synautil.pas encoding to UTF-8 without BOM. Or grab synautil.pas from this repo. https://github.com/riderkick/FMD/commit/f6733d75a656d98af265d10534fb77883203bd3f

**Comment by Wolfpup67** [comment]
Now i have this error:

md.lpr(65,1) Error: Undefined symbol: WSRegisterCustomRichMemo

**Comment by riderkick** [comment]
https://github.com/riderkick/FMD/issues/44
