### ISSUE TITLE
can't update toonkor site,.?

### ISSUE THREAD

**Issue by bunularlaki** [riderkick/FMD#1317]
![1](https://user-images.githubusercontent.com/38377161/42181327-ab042c66-7e64-11e8-8cf5-258c59525f8c.png)
![2](https://user-images.githubusercontent.com/38377161/42181376-d14dd048-7e64-11e8-9f37-de18503f9739.png)

i just add tonkor site in my fmd and see it can not update, please what should i do.

**Comment by kmvi** [comment]
fixed

**Comment by bunularlaki** [comment]
thanks :)
btw there are some cases like this, on some websites, can not be updated.like HoduComics and AccQQcom. I check first. I'll let you know later.
