### ISSUE TITLE
error can't update!!

### ISSUE THREAD

**Issue by bunularlaki** [riderkick/FMD#1320]
I checked there are some sites that can not be updated in fmd, like my question before https://github.com/riderkick/FMD/issues/1317 these list i'm sorting out based on manga english and raw manga, here's the list.
MangaEnglish/MangaRaw.
▬AcQQcom▬ComiExtra▬DM5▬MangaForest▬MangaFoxFun▬MangaFreak▬MangaHereFun▬MangaHereIO▬ManHuaGui▬MangaKakalotFun▬MangaOnlineTo▬MangaOnlineToday▬MangaReaderSite▬MangaRoom▬MangaSupa▬ManHuaTai▬MyMangaMe▬PlusComico▬ReadMangaEU▬Rocaca▬SundayWebEvery▬Taadd▬YoungeAceUp▬ZingBox▬HoduComics▬

▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
![screenshot_1](https://user-images.githubusercontent.com/38377161/42258097-3c9999b6-7f84-11e8-96d4-86e09ed2a40a.png)
![screenshot_2](https://user-images.githubusercontent.com/38377161/42258118-590c8c34-7f84-11e8-995c-323cc26bcb62.png)
![screenshot_3](https://user-images.githubusercontent.com/38377161/42258119-59a05950-7f84-11e8-9596-0ec00a1ae6c7.png)
![screenshot_4](https://user-images.githubusercontent.com/38377161/42258120-5a1569f2-7f84-11e8-9011-58f990e1c7e6.png)
![screenshot_5](https://user-images.githubusercontent.com/38377161/42258122-5a91cee8-7f84-11e8-84f7-76950103084b.png)
![screenshot_6](https://user-images.githubusercontent.com/38377161/42258123-5b2e1334-7f84-11e8-84cd-79ea35112f61.png)
![screenshot_7](https://user-images.githubusercontent.com/38377161/42258125-5c41a5ec-7f84-11e8-8d20-98e200518d16.png)
![screenshot_8](https://user-images.githubusercontent.com/38377161/42258126-5e7717fc-7f84-11e8-9049-b635e6b32c20.png)
![screenshot_9](https://user-images.githubusercontent.com/38377161/42258127-5f742c4e-7f84-11e8-8543-a71757ba34fc.png)
![screenshot_10](https://user-images.githubusercontent.com/38377161/42258130-62f52ada-7f84-11e8-8fea-d5bf76352f49.png)
![screenshot_11](https://user-images.githubusercontent.com/38377161/42258133-66bc8f5a-7f84-11e8-93a7-6655d07e3c60.png)
![screenshot_12](https://user-images.githubusercontent.com/38377161/42258137-6ba2717e-7f84-11e8-9dd3-a9b6250b2c5e.png)
![screenshot_13](https://user-images.githubusercontent.com/38377161/42258138-6efe7de0-7f84-11e8-93c1-8506db3f5b71.png)
![screenshot_14](https://user-images.githubusercontent.com/38377161/42258141-72265a42-7f84-11e8-9306-d6c0f046fecd.png)
![screenshot_15](https://user-images.githubusercontent.com/38377161/42258142-7298a250-7f84-11e8-852f-c3e338ec8ec9.png)
![screenshot_16](https://user-images.githubusercontent.com/38377161/42258148-779c2e0c-7f84-11e8-80c7-2e719f77a07a.png)
![screenshot_17](https://user-images.githubusercontent.com/38377161/42258149-7afb8f20-7f84-11e8-8bf8-49c13622cda9.png)
![screenshot_18](https://user-images.githubusercontent.com/38377161/42258150-7cd947ec-7f84-11e8-8319-593ced245c31.png)
![screenshot_19](https://user-images.githubusercontent.com/38377161/42258151-7ed00dec-7f84-11e8-9dc5-a350825b4649.png)
![screenshot_20](https://user-images.githubusercontent.com/38377161/42258154-842d8026-7f84-11e8-816f-5f702d4835d8.png)
![screenshot_21](https://user-images.githubusercontent.com/38377161/42258159-876de2da-7f84-11e8-8f13-00b8448b6528.png)
![screenshot_22](https://user-images.githubusercontent.com/38377161/42258161-8a9a01c8-7f84-11e8-96ec-dfa80286b45c.png)
![screenshot_23](https://user-images.githubusercontent.com/38377161/42258165-8ffd84a0-7f84-11e8-8a5f-d940b47cde88.png)
![screenshot_24](https://user-images.githubusercontent.com/38377161/42258168-920ee694-7f84-11e8-86ff-10ce70eede09.png)
![screenshot_25](https://user-images.githubusercontent.com/38377161/42258440-fc5b1936-7f85-11e8-8dd9-f63facf5dc26.png)

**Comment by kmvi** [comment]
i don't have enough time to update all of dbs, you can check their status here #1021
you can also build a db manually using the 'update manga list' command
