### ISSUE TITLE
Mangadex Title: (legitielts2018@yahoo.com)Buy nebosh/

### ISSUE THREAD

**Issue by convertion** [riderkick/FMD#1322]
Please delete this entry, it's still fetched for the updating FreeMangaDownloader's updating of Mangadex manga list as of 2018-07-06. Or maybe Mangadex devs still haven't seen this entry.

https://mangadex.org/manga/27501/legitielts2018-yahoo-com-buy-nebosh-pte-gmat-certicicates-in-yemen-australia

![image](https://user-images.githubusercontent.com/40881875/42363082-a95e8174-8128-11e8-999d-61632e871555.png)

**Comment by Tmp341** [comment]
> Warning: Manga #27501 does not exist.

I think they've removed it.
