### ISSUE TITLE
.db file 

### ISSUE THREAD

**Issue by bunularlaki** [riderkick/FMD#1341]
can you teach me how to create one .db file, because I need to add some sites that, or can you show some references because many .db files can't be updated in your software fmd.

**Comment by tranhoangcore** [comment]
You can use [SQLite](https://www.sqlite.org/index.html) for editing files.

**Comment by ChocolateOtaku** [comment]
I think it was planned to replace SQLite with JSON, which makes editing way more convenient.
But looking at the activity on this project it seems that will not happen before 2043...

**Comment by Tmp341** [comment]
You don't have to use db. Recent lua implemention is just what you need.

**Comment by bunularlaki** [comment]
@Tmp341 and what software i need to modify the file? can you recommend.  I'm a beginner but I quickly learn it.

**Comment by Tmp341** [comment]
For lua? Even you can open them with ``notepad``. But i would recommend ``notepad++``, it has a lot of customization.
For db, you can use ``SQLiteDatabaseBrowser``.

**Comment by bunularlaki** [comment]
thanks brother. :) +1:

**Comment by bunularlaki** [comment]
thanks brother :) :+1:
