### ISSUE TITLE
can't download from hentai cafe and update list from that

### ISSUE THREAD

**Issue by rakhmat12** [riderkick/FMD#1350]
have problem with it cause the update list can't work and can't download from website using url i think the website domain change or have problem please fix it

sorry for my english

**Comment by Tmp341** [comment]
Have you tried pasting links directly? It will temporarily help your problem until it is fixed.

Copy hentai link and paste it to fmd's address bar.

**Comment by bunularlaki** [comment]
@rakhmat12 use proxy. option >> connections >>use proxy.
free proxy= https://free-proxy-list.net/
btw are u indonesian?

**Comment by rakhmat12** [comment]
no i can't used that way either
yeah i am

**Comment by rakhmat12** [comment]
btw thank's that i used proxy is way better

**Comment by rakhmat12** [comment]
it's show N/A (0)

**Comment by rakhmat12** [comment]
it's work when iam refreshed it thank's with that proxy thing
