### ISSUE TITLE
What's happen to heaven manga?

### ISSUE THREAD

**Issue by wuhugm** [riderkick/FMD#1358]
It changed it's domain to http://heavenmanga.website

Thus FMD doesn't work anymore since it's still ttp://heavenmanga.world

**Comment by Tmp341** [comment]
Open fmd root folder, ``\lua\modules`` enter here, find HeavenManga and edit it with notepad.

I only saw one entry:
``m.rooturl = 'http://heavenmanga.world'``

to 

``m.rooturl = 'http://heavenmanga.website'``

**Comment by wuhugm** [comment]
^thanks man

Sadly I've transferred my favorites :(

must port back
