### ISSUE TITLE
Looks like tumangaonline know that it is being scrapped

### ISSUE THREAD

**Issue by ralvarador** [riderkick/FMD#1362]
Today, all the downloads from tumangaonline have detected a new chapter (indeed, the last one available), but - curiously, all of them by the same "scanlation group": ** Scrapping from TumangaOnline. **

The downloads fail.
Is it possible that they are using something like "User Agent" to detect the request from the APP (or something like that)?

![imagen](https://user-images.githubusercontent.com/30580377/43671079-6e5a530e-9759-11e8-9979-620e708997ac.png)

**Comment by ralvarador** [comment]
OMG, I've got banned by TumangaOnline :)

**Comment by ronny1982** [comment]
Can you provide a screenshot from the browser stating that your ip has banned?
And if possible the source code of the web page.

**Comment by ralvarador** [comment]
well, today, I was able again to access to tumangaonline services, however, the new tumangaonline isn't so good at usability as the old one; it is difficult keep track of the mangas following.

I will try to use the software through a VPN or a free proxy and check if I still receive the same message.

I will try to use the firefox to get the files. I use the APP to read the mangas when offline, which is very convenient.
