### ISSUE TITLE
Unable to check/view latest manga chapters on MangaDex

### ISSUE THREAD

**Issue by gooreat** [riderkick/FMD#1367]
Tried to check latest chapters of my manga from MangaDex, but they all highlighted in red. Doubt my IP was banned since I can visit the site without any problem.  

I guess MangaDex has upgraded their server or something? Other sites work fine.  

Thanks. 

EDIT:
Oh, just noticed MangaDex has went v3. Guess we'll just have to wait for devs to update FMD then.

**Comment by KeithHanzhel** [comment]
Waiting....

**Comment by wuhugm** [comment]
v3 has the same link with the old one but the layout changed so FMD doesn't work anymore

**Comment by ChocolateOtaku** [comment]
In the meantime you may just use another manga downloader…

**Comment by gooreat** [comment]
@KeithHanzhel hopefully it won't take long lol. heard dev

@wuhugm probably because of that yeah. new layout looks nice

@ChocolateOtaku any recommendation?

**Comment by ChocolateOtaku** [comment]
@gooreat My alternatives are [HakuNeko](https://github.com/manga-download/hakuneko) and [HDoujin Downloader](url)

**Comment by Tmp341** [comment]
As I said in #1366 you should check for other downloaders.

**Comment by Anvirol** [comment]
This has now been fixed by kmvi.

You can close the issue.

**Comment by gooreat** [comment]
@JokoeSukri @ChocolateOtaku Thanks! Will keep those suggestion on my list :D

Yup, as said by @Anvirol, looks like @kmvi has fixed it. Many thanks~
