### ISSUE TITLE
MangaID not working???

### ISSUE THREAD

**Issue by Xivaln** [riderkick/FMD#1369]
Well, the site have change from "http://www.mangaid.net" to "http://www.mangaid.co". So, i hope you can fix it....
thanks..........

**Comment by Tmp341** [comment]
Change the line inside ``myReaderMangaCMS.lua`` inside ``FmdRoot\Lua\Modules\``
from 
`  AddWebsiteModule('MangaID', 'http://mangaid.net', c);`

to

`  AddWebsiteModule('MangaID', 'http://mangaid.co', c);`

**Comment by Xivaln** [comment]
GREATTT!!!
thanks you so much....

**Comment by ChocolateOtaku** [comment]
Has this been solved?

Seems not, it still shows `mangaid.me` instead of suggested `mangaid.co`:
https://github.com/riderkick/FMD/blob/master/lua/modules/myReaderMangaCMS.lua

**Comment by Tmp341** [comment]
> 
> 
> Has this been solved?
> 
> Seems not, it still shows `mangaid.me` instead of suggested `mangaid.co`:
> https://github.com/riderkick/FMD/blob/master/lua/modules/myReaderMangaCMS.lua

It seems they've changed to ``https://mangaid.me`` domain.
