### ISSUE TITLE
[Site Request] Account support for madokami

### ISSUE THREAD

**Issue by Ianunaut** [riderkick/FMD#139]
I'm trying to add accounts to my FMD, but the account manager is only showing me ExHentai in the drop-down menu (despite not even having ExHentai activated). It does also show me Batoto as an existing account since I used the advanced.ini workaround to add the cookie, and it even works, so I guess it's some legacy bug turned into a feature; but I don't see any way to add anything but ExHentai at the moment. I'm mostly interested in adding Madokami. Help?

**Comment by riderkick** [comment]
Currently there is only batoto and exhentai who had account support, so just those two will be showed up in drop-down menu. Selected website only affected on manga list selection/filter, you don't need to activate anything to download, you don't even need manga list to do basic task like download or add favorite, just put the url in url input on manga info tab.
batoto script will not read any cookies from advanced.ini, so it's not used anymore. you have to add your account in account manager to access full batoto.
I need to rewrite madokami script to add account support, so just wait patiently.

**Comment by Ianunaut** [comment]
I love you man, this is perfect!
