### ISSUE TITLE
All manga incorrectly recognized as Completed

### ISSUE THREAD

**Issue by blue-lightning** [riderkick/FMD#14]
Example:
Ongoing:
http://truyen.academyvn.com/manga/21/himouto!-umaru-chan

Hiatus:
http://truyen.academyvn.com/manga/340/otogi-taisen-fantasma

All show up as "Completed" when pasted in the Manga Infos URL bar

**Comment by riderkick** [comment]
fmd only had "ongoing" and "completed" as status. So hiatus will be recognizes as ongoing. Refer to this commit https://github.com/riderkick/FMD/commit/6ecd3c48cc6c91aafeec011b61d9f92424b49b3b
