### ISSUE TITLE
ZingBox not working

### ISSUE THREAD

**Issue by ChocolateOtaku** [riderkick/FMD#1434]
Cannot even update manga list

**Comment by Tmp341** [comment]
Dude, why you've opened issues for every not working website out there?

**Comment by ChocolateOtaku** [comment]
Because each of the website is not working.
I doubt that they break for the same reason and can be solved with the same single fix.
One bug one ticket... simple developer rule.

**Comment by SilverSlyver** [comment]
you spamming issues here, and let me tell you it won't help you

**Comment by Tmp341** [comment]
You can list all that "not working" sites... Convenient developer rule.

**Comment by ChocolateOtaku** [comment]
And btw, I didn’t make those tickets to “help me” i make it to help improve the software, i don’t care for the broken websites!

But don’t worry, i see my effort is not appreciated so i won’t help again.

**Comment by Tmp341** [comment]
I'm not the developer (i wish i knew coding). Creating 30 issues won't improve anything (especially near abandoned apps like this), this is not bugzilla. It isn't developed by multiple developers. What i said is, it would be more convenient to open an issue, list all the not working sites and wait. 

If i saw "at least 1 person fixing fmd almost every week", i thought i would apply for a role, kinda moderator and lower the number of issues. But it is abandoned like you said and we have 317 issues as i'm typing this.
