### ISSUE TITLE
change url and module MangaID

### ISSUE THREAD

**Issue by AbidZakaria** [riderkick/FMD#1456]
![image](https://user-images.githubusercontent.com/19544118/44967856-5d37c700-af6e-11e8-9788-b5d2262cffe8.png)

![image](https://user-images.githubusercontent.com/19544118/44967878-7e98b300-af6e-11e8-8401-647e76e1ed39.png)

![image](https://user-images.githubusercontent.com/19544118/44967894-9e2fdb80-af6e-11e8-95d0-6ff3c8ab5550.png)

even though I have changed it still can't

Can someone help me

**Comment by Xivaln** [comment]
Change the line inside myReaderMangaCMS.lua where you can find in the location FmdRoot\Lua\Modules\

from

AddWebsiteModule('MangaID', 'http://mangaid.net', c);

to

AddWebsiteModule('MangaID', 'http://mangaid.co', c);

**Comment by AbidZakaria** [comment]
but the site leads to the mangaid.me site

**Comment by bunglon07** [comment]
Bikin baru aja..
Hapus AddWebsiteModule MangaID di myReaderMangaCMS.
Coba pake ini http://www.solidfiles.com/v/dkvyXeqMgLQXK. Kalau ada yang kurang tinggal ditambah

**Comment by AbidZakaria** [comment]
Bagaimana cara menambah script lua kamu ke app FMDnya
Soalnya saya cek disini tidak masuk

**Comment by bunglon07** [comment]
copy file lua ke folder module. buka fmd opsi-web-indonesia, centang module
yang baru di copy

**Comment by AbidZakaria** [comment]
Arigatou senpai
Cuman kadang ada beberapa komik yang tidak bisa update chapter
Mungkin sinyalnya 😋

**Comment by AbidZakaria** [comment]
Btw ajarin aku edit module fmd ini
Agak kurang ngerti aku
