### ISSUE TITLE
raw sen manga load chapter directly

### ISSUE THREAD

**Issue by Nekobana** [riderkick/FMD#146]
I'm very like raw senmanga, but the site now using captcha system, the chapter lists only appear if you enter the right captcha, it's annoying now FMD cannot display the chapter lists. The only way to get lists is enter captcha and save the html file after the lists show.

Please, could you add option to load html file to solve this problem. Filename of html file must contains the site name. Please consider it, and sorry for my bad english

**Comment by riderkick** [comment]
I don't know where to at this. This will need rewrite a lot of thing. I don't think it's worth the hassle.
I will try to add special care for this on drop box to load chapter directly, so you can drag n drop the chapter to drop box.

**Comment by Nekobana** [comment]
Cool, i hope that feature implemented on the next release

**Comment by riderkick** [comment]
Now we can populate full chapter list through one of chapter link, if you want to add to favorite, your favorite must come from this url. mangainfo>paste url(with chapter link)>add to favorite. You will be able to check new chapter automatically this way.
