### ISSUE TITLE
can't download

### ISSUE THREAD

**Issue by 1klkl** [riderkick/FMD#1461]
can't download all lastest mangas released at lhscan.net

**Comment by AbidZakaria** [comment]
check the site through a web browser

**Comment by 1klkl** [comment]
web browser no problem, but can't download.

https://lhscan.net/read-sekai-ka-kanojo-ka-erabenai-raw-chapter-18.html
https://lhscan.net/read-saikyou-no-shuzoku-ga-ningen-datta-ken-raw-chapter-5.html
https://lhscan.net/read-100-man-no-inochi-no-ue-ni-ore-wa-tatte-iru-raw-chapter-28.html
https://lhscan.net/read-katsute-kami-datta-kemonotachi-e-raw-chapter-44.html
etc

**Comment by PanzerIVF** [comment]
All of lhscan cannot be download to be exactly.
