### ISSUE TITLE
.It seems something wrong with LHScans?

### ISSUE THREAD

**Issue by PanzerIVF** [riderkick/FMD#1463]
403 Error?? Downloading LHScan from FMD only to get this?
![explorer_2018-09-12_18-28-47](https://user-images.githubusercontent.com/22032292/45422278-f5922200-b6b9-11e8-9b1c-4ef26e35140f.png)

**Comment by ralvarador** [comment]
U.u)
Going to the website, there is a message (but I don't know if it's reffering the same issue):
" Sorry for the error displaying the image. We will fix soon. Thank you. 
HELP US MAINTAIN THIS WEBSITE! 
Thank you so much. "

**Comment by adamwiro** [comment]
I have same Problem
