### ISSUE TITLE
I can't download from Kissmanga.

### ISSUE THREAD

**Issue by Habwuson** [riderkick/FMD#1464]
It just appears as if it's downloading one single image but it doesn't download anything, it's just an empty folder. This has been happening for almost a week now, it was just fine before.

**Comment by Habwuson** [comment]
Not sure how but it works again.

**Comment by Habwuson** [comment]
Nvm it downloaded a few chapters and stopped working again.

**Comment by muto4013** [comment]
kissmanga has switched to cloudflare and FMD doesn't work well with cloudflare.
Just wait few hours/days or change to another hoster

**Comment by Habwuson** [comment]
Oh, so that was it then. Thank you.
