### ISSUE TITLE
cant download from mangashiro and mangaid from indonesia server

### ISSUE THREAD

**Issue by LordStreet** [riderkick/FMD#1466]
please fix mangashiro and mangaid, this web change from mangaid.net to mangaid.me... thx

**Comment by AbidZakaria** [comment]
Untuk mangashiro cek di browsermu 
Apakah bisa dijalankan

Untuk manga id
Baca link ini https://github.com/riderkick/FMD/issues/1456

**Comment by bunglon07** [comment]
x.xpathhrefall mangashiro sekarang beda.
saya pake //div[@class="lch"]/a

**Comment by kmvi** [comment]
8f0d23d3
