### ISSUE TITLE
FMD does not package .png's correctly from PNG to PDF

### ISSUE THREAD

**Issue by Ketama303** [riderkick/FMD#1467]
Hi,

I was downloading the latest chapter of One Piece (917) today and FMD kept giving me a blank page as the third manga page. I checked if it did download the .png's correctly and it did, but once it had to package it into a .pdf, the program gave the issue, so I had to download the chapter as .png's and combine them online myself. It downloaded it from Jaimini's Box, but I don't think it is the websites issue, because it does download the png's correctly.

I am on the latest version. (0.9.156.0)

**Comment by kevin01523** [comment]
??

**Comment by Ketama303** [comment]
I have closed the issue... since it has been resolved for quite a while now.
