### ISSUE TITLE
FMD Won't Open

### ISSUE THREAD

**Issue by MasuRii** [riderkick/FMD#1468]
Last time when I open FMD it still working then tried downloading 5 manga from different sites but it was save on F: External then eventually I change it to D: External then later on the FMD won't open [<a href="https://ibb.co/f1Yo9p"><img src="https://thumb.ibb.co/f1Yo9p/Capture.png" alt="Capture" border="0"></a>](url)

**Comment by AbidZakaria** [comment]
it looks like the downloadchapter.db database is corrupt
