### ISSUE TITLE
LH Translation Doesn't Working Anymore

### ISSUE THREAD

**Issue by JokoeSukri** [riderkick/FMD#1471]
Since LH Translation Website Got DDOS attack, Their website changing. And FMD cannot grab images.
I cant download it anymore, Please fix ASAP

**Comment by JokoeSukri** [comment]
![screenshot_12](https://user-images.githubusercontent.com/32964994/45620091-9582ed80-bab6-11e8-8fff-08f4e4eec6b7.jpg)

**Comment by Leguron** [comment]
I think we might need a similar fix like they did on kissmanga.
