### ISSUE TITLE
add seemh.com

### ISSUE THREAD

**Issue by abhi98** [riderkick/FMD#148]
Hi there Can you please add http://www.seemh.com/ this website. Its a Chinese Raw site. Its quiet fast then last one too. Please take your time. Thanks

One of the comic links:- http://www.seemh.com/comic/10778/

One of the chapters of the comic above link:- http://www.seemh.com/comic/10778/208946.html#p=1

Thanks

**Comment by riderkick** [comment]
Where is the full directory list?
Is there any sorted list by last added?

**Comment by abhi98** [comment]
http://www.seemh.com/list/

http://www.seemh.com/list/lianzai/

http://www.seemh.com/list/wanjie/

they are all list thanks

**Comment by riderkick** [comment]
I can't get the image url.

**Comment by abhi98** [comment]
the image url of the chapters of the comic book ?

**Comment by abhi98** [comment]
i am able to get the the link 
http://ilt1.seemh.com:88/ps3/w/%E6%AD%A6%E5%8A%A8%E4%B9%BE%E5%9D%A4%5B%E7%A5%9E%E6%BC%AB%5D/%E7%AC%AC38%E8%AF%9D/manhua_12_20151212_2015121206442890252.jpg

http://ilt1.seemh.com:88/ps3/w/%E6%AD%A6%E5%8A%A8%E4%B9%BE%E5%9D%A4%5B%E7%A5%9E%E6%BC%AB%5D/%E7%AC%AC38%E8%AF%9D/manhua_12_20151212_2015121206443515083.jpg

**Comment by riderkick** [comment]
It's created in the DOM. But where its come from? I can't find the source of it. Right-click > View Page Source.
I'm trying to follow the javascript, looks very complicated. With many eval. I lost track.
I know they create the img element in core_xxxxx.js
like this one http://ccache.duapp.com/scripts/core_8E102C27039C5DC5B08112FE3E2EFCB0.js
this line.
`u = '<img src="' + pVars.manga.filePath + encodeURIComponent(cInfo.files[pVars.page]) + '" alt="" data-tag="mangaFile" />',`
But where is pVars, cInfo come from?
And there is server list above that will turn the server in pVars.
Really complicated.  :confused:

**Comment by abhi98** [comment]
Yup It is indeed complicated. Thanks for the effort. Try this site http://www.manhuatai.com/wudongqiankun/ because I think this one is not that complicated and will be able to find the source of it.

**Comment by abhi98** [comment]
So were you able to find the source for the above website ?

**Comment by riderkick** [comment]
Please transform the javascript.
I don't really well with javascript.

**Comment by abhi98** [comment]
sorry i don't understand what are you trying to say ?

**Comment by riderkick** [comment]
I can't construct the image url, I'm not really well with javascript. Please tell me how if you understand its mechanism.

**Comment by kavin-90** [comment]
<script>
            var mh_info = {
                imgpath: "X&3G&F7&BE&B7&F6&9B&B9&F5&C:&CF&F6&:E&B5&3G&F8&BD&BD49&F9&BG&:E&F7&9B&B3&F6&BF&:E&3G",
                startimg: 1,
                totalimg: 25,
                mhid: "wudongqiankun",
                mhname: "武动乾坤",
                pageid: 961951,
                pagename: "第38话 抢宝",
                pageurl: "38qb",
                readmode: 1,
                maxpreload: 5,
                defaultminline: 1,
                domain: "manhuatai.com"
            };
        </script>
Link = http://www.manhuatai.com/wudongqiankun/38qb.html

pageurl: "38qb", == Chapter url link.
domain: "manhuatai.com" == site.
pagename: "第38话 抢宝", Chapter Title
mhname: "武动乾坤", === Series Name
 mhid: "wudongqiankun", ==== series slug

**Comment by abhi98** [comment]
For some reason I cannot upload the java script. So you can just save the page from the internet and then in the folder there should be java script and that's how I did it.  also it is confusing though :)

**Comment by riderkick** [comment]
I'm not talking about how to save javascript file. I'm asking how this javascript works.

**Comment by abhi98** [comment]
Then I don't know sorry :(

**Comment by abhi98** [comment]
Well thanks for the hard work :)
