### ISSUE TITLE
Batoto missing many pages when downloading.

### ISSUE THREAD

**Issue by formigao** [riderkick/FMD#149]
when you put fmd to download from batoto 90% of the time i get a error.
and when i check the manga i see some pages missing.

i need resume the task many times till the program download what is missing.

i think the program should double check if any page is missing and try to download again automatically

**Comment by riderkick** [comment]
Of course there is various validity check, from image url, directory, filename, saved file, etc. There is already double or triple or even more, I don't recall correctly.
If image fail to download it will retry to download as many as max retry count in options > connection.
if its still fail then download task status will become "Failed" in the end of download task thread.

That's what you got. It's simply means its already trying to "automatically" redownload as many as you command but still failed.
You can try to increase retry times in options>connections. You can even set to -1(infinite), but beware it can go forever.

If I recall correctly, there is server side limitation on ba to to. If there is request more than certain limit from the same ip, their server will reply with "503 service temporary unavailable". The limit is about 4 or so.
I already set the limit for batoto to 1 task 3 thread. maybe there is some changes on their server. Try to lower the concurrent download per task. It may help.

**Comment by formigao** [comment]
thanks, configured to try 10 times and now i dont have the problem anymore
