### ISSUE TITLE
"Download manga list from server" problem.

### ISSUE THREAD

**Issue by Qizmo** [riderkick/FMD#1490]
Hi I seldom click on the "Download manga list from server", but from what I remember it is quite fast. But from 2 days ago, for every manga sites that I try "Download manga list from server" the loading is veryyy slow, then after a short while it stop loading and after sometime an error is shown. 

However "Update manga list" is still fine. It is loading very quickly.

**Comment by Qizmo** [comment]
Oh the problem seems to be solved. Just now I try "Download manga list from server" again and every manga site can be downloaded very quickly :D

**Comment by Tmp341** [comment]
Those files are stored on Sourceforge servers. They were probably working on something, like maintenance.
