### ISSUE TITLE
mangamint aka mangabird is not working for chapter

### ISSUE THREAD

**Issue by radiaku** [riderkick/FMD#15]
Hello sir nurcholif,
mangamint aka mangabird is not working for chapter
![2015-04-29_051606](https://cloud.githubusercontent.com/assets/5983350/7381575/edbb43ec-ee2e-11e4-8234-ab9700f1fa76.png)

Iam using fmd,  0.9.8.9

and congratulation for migrating to github., ( I dont know you migrating here ) :)

**Comment by riderkick** [comment]
I'll completely remove MangaBird and add MangaMint instead. Manga list update seems doesn't work either, it's better to rewrite it from scratch.
