### ISSUE TITLE
cannot update and cannot import bookmark

### ISSUE THREAD

**Issue by codeduph** [riderkick/FMD#151]
I can't update manga sites Kissmanga & MangaFox. Also, it cannot import bookmark from domdomsoft.

[http://imgur.com/jMAVsUa]

**Comment by riderkick** [comment]
Those HTTP response code indicate server error. Maybe temporary server error or your firewall/ISP block the connection.
Or download manually from here https://bintray.com/riderkick/FMD/data/db/view#files/db
Extract the content to "data" folder (should be contain *.db file)

Send me your bookmark.

**Comment by codeduph** [comment]
My DomDomS Bookmark: https://www.mediafire.com/?pioqwdm7bcjx9tz

still having an issue viewing manga:

kissmanga: http://i.imgur.com/GcTqc1d.jpg maybe because of their website access protection http://i.imgur.com/GDOSQ20.jpg

mangafox: mostly it works http://i.imgur.com/GgCOa6Q.jpg BUT sometime I still get this message http://i.imgur.com/fOo4B6z.jpg


I already made a rule on my firewall:  http://i.imgur.com/PFYwr6d.jpg

**Comment by riderkick** [comment]
Kiss manga refer to this thread https://github.com/riderkick/FMD/issues/116/. Fix already applied, just wait for next release.

For mangafox, probably just temporary server error.

You may need to include updater.exe to your exception list.

**Comment by riderkick** [comment]
I can import your bookmarks without any problem.

**Comment by riderkick** [comment]
I see, it was kiss manga, add to favorites will be fail if page fail to load/no information. Just wait for next release for kiss manga fix.

**Comment by codeduph** [comment]
ok! I'll wait for the next release.

-thanks
