### ISSUE TITLE
MangaDex: Migrate code to use the API

### ISSUE THREAD

**Issue by SDXC** [riderkick/FMD#1510]
MangaDex has a JSON based API for Mangas and Chapters like this:
https://www.mangadex.org/api/chapter/$id
https://www.mangadex.org/api/manga/$id

Example Love Hina:
https://www.mangadex.org/api/manga/2404
Example Chapter 1 of Love Hina:
https://www.mangadex.org/api/chapter/108872

Using the API is faster, doesn't strain the webserver as much and is more precise. There is also a difference in the ratio for site hits allowed: MangaDex main site (when calling "/title/" or "/manga/" url) is at 600 hits in 10 minutes I think and for the API it is 1500 per 10 Minutes.

Please consider a complete migration to the API some time, thanks.

**Comment by GDXN** [comment]
I second this
