### ISSUE TITLE
want to edit the lua script

### ISSUE THREAD

**Issue by AbidZakaria** [riderkick/FMD#1522]
some know where the script is located for mangafox and webtoons

**Comment by bunglon07** [comment]
Master file
.pas bukan lua

**Comment by Tmp341** [comment]
[Here](https://github.com/riderkick/FMD/tree/master/baseunits/modules). But, they aren't ``lua`` though.

**Comment by AbidZakaria** [comment]
can I recompile this program after I change the data

**Comment by Tmp341** [comment]
> 
> 
> can I recompile this program after I change the data

You can use [this](https://github.com/riderkick/FMD#build-instructions) instructions to build.

**Comment by AbidZakaria** [comment]
I failed when installing Besen and InternetTolls, can you teach me how to fix it, because this is my first experience in Pascal programming language

**Comment by Tmp341** [comment]
> 
> 
> or tell me the lazarus version you are using

I'm just a translator for this project. I don't know anything about programming. Sorry.

**Comment by 1aam2am1** [comment]
You should not install them. When working with sub-modules in 3rd directory. You should first initialize then pull them. Watch for errors, because there are. Then checkout them for master. And everything should work.
