### ISSUE TITLE
kissmanga https

### ISSUE THREAD

**Issue by kevin01523** [riderkick/FMD#1530]
it seems kissmanga upgraded into https recently or maybe i just noticed it now
fmd wont load kissmanga since https and fmd forces manga to or info to load via http and not https
![image](https://user-images.githubusercontent.com/8380242/48042760-15c3f600-e1be-11e8-9dc6-1555f12ea205.png)

i do think a minor fix might work i have no idea how tho

**Comment by kevin01523** [comment]
hmm seems to load fine now i dont know what happened but it wont even update earlier or yesterday my ip is the same although i get the site maintenance on firefox seems fine on chrome or they are aggressive even on fmd

**Comment by garybempo** [comment]
So sorry when I pop-out only when I got problem with kissmanga but I also facing same problem with op :(
I changed the url from http to https in the FMD browser but still don't work.

Hope admin willing to fix this problem.
Best Regards,
Gary

**Comment by fales13** [comment]
same here, FMD also won't download updates

hope, well be fixed soon...

**Comment by NhKPaNdA** [comment]
I was able to make KissManga work again by adding a `KissManga.lua` file into the `FMD Root/lua/modules` folder with the contents of the .lua file being:

```
function AddWebsiteModule(name, url)
  local m = NewModule()
  filldef(m)
  m.website = name
  m.rooturl = url
  m.category = 'English'
  m.lastupdated='November 11, 2018'
  m.ongetinfo='getinfo'
  m.ongetpagenumber = 'getpagenumber'
  m.ongetnameandlink = 'getnameandlink'
  m.ongetdirectorypagenumber = 'getdirectorypagenumber'
  m.onbeforedownloadimage = 'beforedownloadimage'
  m.ondownloadimage = 'downloadimage'
  return m
end

function Init()
  AddWebsiteModule('KissManga', 'https://kissmanga.com')
end
```

The content could probably be better refined or whatever but it works so I've just left it as such which I stole from the `MangaGo.lua` file.

**Comment by kevin01523** [comment]
i made it work by unchecking the google dcp an checking info on a random kissmanga manga then rechecking dcp again
also make sure you arent getting the maintenance message

**Comment by ArturStoeber** [comment]
Tried the DCP thingy, while I actually could check my favourites again, I still couldnt download a chapter.

![image](https://user-images.githubusercontent.com/36422961/48448773-5ca68280-e7a0-11e8-880e-5dedf35f80a0.png)

**Comment by Srxjo** [comment]
The lua file worked for me, so just try doing that.

**Comment by ArturStoeber** [comment]
I tried the lua file too, but I honestly dont know what it should changed, it doesnt even get loaded by the program. (There is a part where the lua files are listed, the Kissmanga file isnt part of that list)

**Comment by ArturStoeber** [comment]
Actually the hint by @kevin01523 worked, I got the maintenance message... Switched Ip, disabled dcp and enabled again, but after a chapter or two, im back to maintenance...

**Comment by sardinac** [comment]
@Srxjo having trouble compiling fmd

**Comment by sardinac** [comment]
I was wondering if it would be possible to post a compiled version of FMD with the fix.

**Comment by sardinac** [comment]
> The lua file worked for me, so just try doing that.

Could you post a copy of the fixed FMD?

**Comment by Tmp341** [comment]
I've written the method i'v been using, it is working for me without ``https``

Check [this](https://github.com/riderkick/FMD/wiki/FAQ#cannot-download-from-kissmanga) out.

**Comment by Renvix** [comment]
https://github.com/riderkick/FMD/issues/1530#issuecomment-438933775

nothing comes out after typing in the console or rather the text "not defined"

**Comment by kevin01523** [comment]
you have to press enter

**Comment by Tmp341** [comment]
> 
> 
> [#1530 (comment)](https://github.com/riderkick/FMD/issues/1530#issuecomment-438933775)
> 
> nothing comes out after typing in the console or rather the text "not defined"

This is what i've written:

> Type chko and hit enter

**Comment by Tmp341** [comment]
Can you show me a screenshot?

**Comment by Renvix** [comment]
![untitled](https://user-images.githubusercontent.com/29302760/50055269-457ff980-017f-11e9-8b53-02b0c78bc2b7.png)

**Comment by NhKPaNdA** [comment]
You are on the home page. You need to go into the first chapter of any manga and then try again.

**Comment by Tmp341** [comment]
Just like @NhKPaNdA said, open a chapter and try again. It has been working like that for months, i don't think they've changed it now.

**Comment by forvy** [comment]
@kmvi it's not working again atm. 

![image](https://user-images.githubusercontent.com/17746819/54339879-ab89f900-4668-11e9-8532-d5cd97d7c8c9.png)
![image](https://user-images.githubusercontent.com/17746819/54339891-b2b10700-4668-11e9-907f-c079694d17c2.png)
![image](https://user-images.githubusercontent.com/17746819/54339952-dd9b5b00-4668-11e9-88d6-9cd77ff764a7.png)
