### ISSUE TITLE
Change of domain from tumangaonline to tmofans

### ISSUE THREAD

**Issue by TheDoom95** [riderkick/FMD#1534]
Recently they changed the domain of tumangaonline. It seems that they have planned to change it every 1 or 2 years, that is what they publish in the forum.

**Comment by ralvarador** [comment]
Ping!

**Comment by ralvarador** [comment]
well, modifying the "TuMangaOnline.lua"
Line 80 (aprox) from m.rooturl = 'https://tumangaonline.me' , to m.rooturl = 'https://tmofans.com', fix the "issue" (ATM)

**Comment by Soumase** [comment]
I tried to download and it download perfectly with this change. Thanks for the info

**Comment by GATOQSECOMIO** [comment]
> well, modifying the "TuMangaOnline.lua"
> Line 80 (aprox) from m.rooturl = 'https://tumangaonline.me' , to m.rooturl = 'https://tmofans.com', fix the "issue" (ATM, I didn't tried download a thing, only check the manga in the favorities list)

works!
