### ISSUE TITLE
fix Tumangaonline -Not Working-

### ISSUE THREAD

**Issue by alphadct** [riderkick/FMD#1540]
Not working tumangaonline, spanish page, fix please please.

Change webname tumangaonline.me -> https://tmofans.com/

**Comment by GATOQSECOMIO** [comment]
not resolve the problem but check this issue [#1534 / Change of domain from tumangaonline to tmofans](https://github.com/riderkick/FMD/issues/1534)

**Comment by C0RPS3** [comment]
update the .lua (tumangaonline) module in options/web sites/ modules 

automatic updated today.
