### ISSUE TITLE
MAngafox/fanfox update

### ISSUE THREAD

**Issue by ragna0011** [riderkick/FMD#1542]
i think fan fox/mangafox upgraded their website, i cant check my updates or list. pls update too. thanks

**Comment by kevin01523** [comment]
yeah just noticed it now i was abnle to update a few hours ago

**Comment by ragna0011** [comment]
still no fix? or did he stopped updating here? cuz i cant seem to find a better manga downloader than this... if anyone knows how to fix this, pls help.

**Comment by kevin01523** [comment]
i think its easy to fix just looked at the code of mangafox and compared the html code on devtools
the thing is its hardcoded into fmd and not on lua module yet so its hard to update unless someone did recompile fmd with the fixes or someone make a lua version of the module for mangafox

**Comment by ragna0011** [comment]
did you fix yours? cuz i wanna try if i can. i'm not proficient to programming tho

**Comment by kevin01523** [comment]
i'm still attempting even though im new to pascal since the code is human readable. lmao

**Comment by traitorAIZEN** [comment]
it would have been easier if fmd can also use xml data file like domdomsoft.

**Comment by kevin01523** [comment]
```
coverLink := MaybeFillHost(Module.RootURL, XPathString('//*[@class="detail-info-cover"]/img/@src'));
          if title = '' then title := XPathString('//title/substring-before(.," Manga - Read")');
          authors := XPathString('//div[@id="title"]/table/tbody/tr[2]/td[2]');
          artists := XPathString('//div[@id="title"]/table/tbody/tr[2]/td[3]');
          genres := XPathString('//div[@id="title"]/table/tbody/tr[2]/td[4]');
          summary := XPathString('//p[@class="fullcontent"]');
          status := MangaInfoStatusIfPos(XPathString('//div[@id="series_info"]/div[5]/span'));
          for v in XPath('//ul[@class="chlist"]/li/div/*[self::h3 or self::h4]') do
          begin
            chapterLinks.Add(StringReplace(XPathString('a/@href', v), '1.html', '', [rfReplaceAll]));
            chapterName.Add(XPathString('string-join(.//*[not(contains(@class,"newch"))]/text()," ")', v));
```
managed to fix the picture and summary atleast i have no idea how to fix the chapter grabbing pattern haha my attempts seems to fail


im getting compile error on this part of the code on frmmain
```
 s:=ReplaceRegExpr('\.*$',s,'');  

made it work by putting a null as a placeholder
 s:=ReplaceRegExpr('\.*$',s,'',null);  
```

![image](https://user-images.githubusercontent.com/8380242/48706832-631d7a00-ec38-11e8-8c50-21bd55855050.png)

**Comment by ChocolateOtaku** [comment]
> [...] cuz i cant seem to find a better manga downloader than this... [...]

Its up to you, do you want the super fancy manga downloader that does not work, or a boring looking manga downloader that is regulary updated and get the job done?

Personally I prefer to get my stuff done instead of waiting for annual fixes...

You can try HDoujin Downloader or HakuNeko

**Comment by ragna0011** [comment]
Almost there mab. You can do it...

**Comment by kevin01523** [comment]
like i said this beyond me 
and the fix i have done is hacky and doesn't even compare to the original
i still cant get fmd to show the chapters

**Comment by anfgomezmo** [comment]
Where did you change it? If I have time I will check it

**Comment by kevin01523** [comment]
https://github.com/riderkick/FMD/tree/master/baseunits/modules
find mangafox.pas
well you have to recompile fmd to make it work but if someone made a lua module it will work withot recompiling fmd

**Comment by 1aam2am1** [comment]
`function getinfo()
  mangainfo.url=MaybeFillHost(module.RootURL, url)
  http.cookies.values['isAdult'] = '1'
  if http.get(mangainfo.url) then
    x=TXQuery.Create(http.document)	
    mangainfo.title=x.xpathstring('//title/substring-before(.," Manga - Read")')
    mangainfo.coverlink=x.xpathstring('//*[@class="detail-info-cover-img"]/@src')
    mangainfo.authors=x.xpathstring('//*[@class="detail-info-right-say"]/[starts-with(.,"Author(s):")]/substring-after(.,":")')
    mangainfo.artists=''
    mangainfo.genres=x.xpathstring('//*[@class="detail-info-right-tag-list"]')
    mangainfo.status=MangaInfoStatusIfPos(x.xpathstring('//*[@class="detail-info-right-title-tip"]'))
    mangainfo.summary=x.xpathstring('//*[@class="fullcontent"]')
    v=x.xpath('//ul[@class="detail-main-list"]/li')
    for i=1,v.count do
      v2=v.get(i)
      mangainfo.chapterlinks.add(x.xpathstring('a/@href',v2))
      mangainfo.chapternames.add(x.xpathstring('a/div/p',v2))
    end
    InvertStrings(mangainfo.chapterlinks,mangainfo.chapternames)
    return no_error
  else
    return net_problem
  end
end
`

This is what I have created in lua. But i can't get getpagenumber() because xpath is not working :( , but what do the functions: getdirectorypagenumber() and getnameandlink() ???

**Comment by 1aam2am1** [comment]
I have only the part that loads summary and authors, well the info.
I'm trying to get the number of pages in chapter now.
```
function getinfo()
  mangainfo.url=MaybeFillHost(module.RootURL, url)
  http.cookies.values['isAdult'] = '1'
  if http.get(mangainfo.url) then
    x=TXQuery.Create(http.document)	
    mangainfo.title=x.xpathstring('//title/substring-before(.," Manga - Read")')
    mangainfo.coverlink=x.xpathstring('//*[@class="detail-info-cover-img"]/@src')
    mangainfo.authors=x.xpathstring('//*[@class="detail-info-right-say"]/[starts-with(.,"Author(s):")]/substring-after(.,":")')
    mangainfo.artists=''
    mangainfo.genres=x.xpathstring('//*[@class="detail-info-right-tag-list"]')
    mangainfo.status=MangaInfoStatusIfPos(x.xpathstring('//*[@class="detail-info-right-title-tip"]'))
    mangainfo.summary=x.xpathstring('//*[@class="fullcontent"]')
    v=x.xpath('//ul[@class="detail-main-list"]/li')
    for i=1,v.count do
      v2=v.get(i)
      mangainfo.chapterlinks.add(x.xpathstring('a/@href',v2))
      mangainfo.chapternames.add(x.xpathstring('a/div/p',v2))
    end
    InvertStrings(mangainfo.chapterlinks,mangainfo.chapternames)
    return no_error
  else
    return net_problem
  end
end

--[[
Code that is not working: getpagenumber, getimageurl, getdirectorypagenumber, getnameandlink here
--]]

function Init()
  m=NewModule()
  m.category='English'
  m.website='MangaFox'
  m.rooturl='http://fanfox.net'
  m.lastupdated='February 17, 2018'
  m.ongetinfo='getinfo' --done
  m.ongetpagenumber='getpagenumber' --I am working on it.
  m.ongetimageurl='getimageurl'
  m.ongetdirectorypagenumber='getdirectorypagenumber' --What this do?
  m.ongetnameandlink='getnameandlink' --What this do?
end
```

**Comment by ragna0011** [comment]
figures, i dont understand a thing. i leave it to smart people... maybe i should start learning programming too, for the sake of this

**Comment by kevin01523** [comment]
i think some of the fixes on this repo https://github.com/manga-download/hakuneko/commit/76697c085146d5950be43e1c60ba7d36d8e27875 

https://github.com/manga-download/hakuneko/commit/ac0a0449970640c911680b261ce8f840c0a53942

can be used here as reference

**Comment by 1aam2am1** [comment]
```
function getpagenumber()
  task.pagenumber=0
  if http.get(MaybeFillHost(module.rooturl,url)) then
    local s = StreamToString(http.document)
    local n = tonumber(string.match(s, "imagecount=(.-);"))
    if n then
      task.pagenumber=n
      return true
    else
      return false
    end
  else
    return false
  end
  return true
end
```

**Comment by 1aam2am1** [comment]
Now I am working on getimageurl(). To get the url of the image that need to be downloaded, but mangafox HTML don,t have the necessary data. The url is created in javascript

**Comment by kevin01523** [comment]
yes they are caching the image after the javascript got the image kinda similar to mangarock since mangarock works on fmd it might be a good idea to look the getimage function for reference

**Comment by 1aam2am1** [comment]
The get the image in function getpagenumber() as pagelinks.

**Comment by 1aam2am1** [comment]
http://fanfox.net/manga/name_of_manga/chapter_number/chapterfun.ashx?cid=488343&page=20&key=
The prat to chapterfun.ashx is easy to get. cid is easy to. page is page that we want.
But the page is returning javascript code. And the result of the code is that we get array d with urls of images. But how to run the javascript code or get data from it. I don't know. Someone?

**Comment by kevin01523** [comment]
`            this.script = `
                let promises = [...( new Array( imagecount ) ).keys()].map( p => {
                    return $.ajax( {
                        url: 'chapterfun.ashx',
                        data: {
                            cid: chapterid,
                            page: p+1,
                            key: guidkey
                        }
                    } )
                    .then( script => {
                        eval( script );
                        let anchor = document.createElement( 'a' );
                        anchor.href = d[0];
                        return Promise.resolve( anchor.href );
                    } );
                    promises.push( promise );
                } );
                Promise.all( promises )
            `;
        }`

this is the sinppet  from hakuneko

**Comment by 1aam2am1** [comment]
eval( script ); => We can'd do this. **This is javascript. We don't support javascript!!!**

**Comment by kevin01523** [comment]
reminds me kissmanga js gives a encrypted manga url and fmd do use a js to decrypt said url so we can download the images

https://github.com/riderkick/FMD/blob/master/baseunits/modules/KissManga.pas

**Comment by 1aam2am1** [comment]
Nope it is not encrypted is it only packed as javascript code. We can: unpack it, execute it on some server. Or get another method of getting the urls of images.

**Comment by kevin01523** [comment]
so can fmd then download the js atleast copy the js as string of a specific manga chapter then save it offline then unpack it locally?
just a question haha


i was saying atleast on kissmanga's case its encrypted but this is on pascal
```
GETWithCookie(DownloadThread.FHTTP, Module.RootURL + '/Scripts/lo.js', Module)
```
im not 100% sure on this lmao


i do think there are some online service that do this but im not sure

some  more reference that might help
https://stackoverflow.com/questions/48851011/is-it-possible-to-connect-lua-and-javascript

**Comment by ronny1982** [comment]
1. Open the HTML page for the chapter
2. Extract the `chapterid` variable
3. Extract the `imagecount` variable
4. Extract the [packed script and evaluate](https://gist.github.com/ronny1982/b7ae3aa737d99b3e71b351f29ca566c1) it in FMD using e.g. BESEN library => this will give you access to `guidkey`
5. Take the URL of the chapter but replace the last part with `chapterfun.ashx` => this will give you a URL, i will call it [pageScriptURI](https://gist.github.com/ronny1982/9b605e774024938ad6b5eed64c6c69d4)
6. Now loop through all page numbers from `1 ... imagecount` (i will call it pageIndex) and make a GET request for each page to `pageScriptURI` but attach the following parameters: key=`guidkey` & cid=`chapterid` & page=`pageIndex`
7. Each GET request will give you a packed script which can be evaluated in FMD with e.g. BESEN library => this will give you access to the array `d` where the first element is the image URL of the requested pageIndex

**Possible pitfalls which come to mind:**

- If the evaluation of the guidkey script did not work, you may need to create a javascript mock for the `$` function which takes a single parameter and return something with the val property => prepend this javascript mock script before the guidkey script

**Comment by 1aam2am1** [comment]
BESEN library?

**Comment by kevin01523** [comment]
> BESEN library?

its an implemetation of e5cma 5th edition  scripting in pascal for lazarus and that is one of the things that makes FMD run and get images from ei kissmanga 

https://github.com/riderkick/FMD/tree/master/3rd

**Comment by 1aam2am1** [comment]
This is what i have created in meantime:
```
function getdirectorypagenumber()
  page = 0
  if http.get(module.rooturl..'/directory/') then
    x=TXQuery.Create(http.document)
    v=x.xpath('//div[@class="pager-list-left"]//a/text()')
    for i=1,v.count do
      v2=v.get(i)
      local n = tonumber(v2.ToString)
      if n then
        if n > page then
          page = n
        end
      end
    end
    return no_error
  else
    return net_problem
  end
end

function getnameandlink()
  if http.get(module.rooturl..'/directory/'..IncStr(url)..'.html') then
    TXQuery.Create(http.document).xpathhreftitleall('//ul[@class="manga-list-1-list line"]/li/a',links,names)
    return no_error
  else
    return net_problem
  end
end
```
But i don't know how to use this jsunpack if it is for javascript. Is there some way to use BESEN in lua?
And if there is then how?

**Comment by kevin01523** [comment]
jsunpack is located here https://github.com/riderkick/FMD/blob/master/baseunits/JSUnpack.pas

**Comment by ronny1982** [comment]
jsunpack seems to be a simple javascript deobfuscator for HEX obfuscation, it is not a JS engine to execute javascript

**Comment by 1aam2am1** [comment]
jsunpack then does not enter game.

PS. I have changed fragement of get info 
`mangainfo.chapterlinks.add(string.match(x.xpathstring('a/@href',v2), ".*/"))`
To easier getimageurl. If there is some way to execute javascript in lua then the code to get url image will be complete. I will put in all lua code here with comment how to complete the fragment with javascript execution.

**Comment by 1aam2am1** [comment]
My complete code: In lua i don't have BESEN library therefore it is not complete.
```
function getinfo()
  mangainfo.url=MaybeFillHost(module.RootURL, url)
  http.cookies.values['isAdult'] = '1'
  if http.get(mangainfo.url) then
    x=TXQuery.Create(http.document)	
    mangainfo.title=x.xpathstring('//title/substring-before(.," Manga - Read")')
    mangainfo.coverlink=x.xpathstring('//*[@class="detail-info-cover-img"]/@src')
    mangainfo.authors=x.xpathstring('//*[@class="detail-info-right-say"]/[starts-with(.,"Author(s):")]/substring-after(.,":")')
    mangainfo.artists=''
    mangainfo.genres=x.xpathstring('//*[@class="detail-info-right-tag-list"]')
    mangainfo.status=MangaInfoStatusIfPos(x.xpathstring('//*[@class="detail-info-right-title-tip"]'))
    mangainfo.summary=x.xpathstring('//*[@class="fullcontent"]')
    v=x.xpath('//ul[@class="detail-main-list"]/li')
    for i=1,v.count do
      v2=v.get(i)
      mangainfo.chapterlinks.add(string.match(x.xpathstring('a/@href',v2), ".*/"))
      mangainfo.chapternames.add(x.xpathstring('a/div/p',v2))
    end
    InvertStrings(mangainfo.chapterlinks,mangainfo.chapternames)
    return no_error
  else
    return net_problem
  end
end

function getpagenumber()
  task.pagenumber=0
  if http.get(MaybeFillHost(module.rooturl,url)) then
    local s = StreamToString(http.document)
    local n = tonumber(string.match(s, 'imagecount[ ]*=[ ]*(.-)[ ]*;'))
    if n then
      task.pagenumber=n
      return true
    else
      return false
    end
  else
    return false
  end
  return true
end

--[[
We can move the getimageurl to the getpagenumber and then
task.pagelinks.clear()
task.pagelinks = d
But only when we got it working
--]]
function getimageurl()
  local s=AppendURLDelim(url)..(workid+1)..'.html'
  if http.get(MaybeFillHost(module.rooturl,s)) then
    s = StreamToString(http.document)
    local chapterid=tonumber(string.match(s, 'chapterid[ ]*=[ ]*(.-)[ ]*;'))
    local comicid=tonumber(string.match(s, 'comicid[ ]*=[ ]*(.-)[ ]*;'))
    local page=workid+1
    local uid=tonumber(string.match(s, 'userid[ ]*=[ ]*(.-)[ ]*;'))
    local guidkey=''

    local script=''
    x=TXQuery.Create(http.document)
    v=x.xpath('//script[not(@src)]/text()')
    for i=1,v.count do
      v2=v.get(i)
      local str = v2.ToString
      if string.find(str, 'guidkey') then
        script = str
        break
      end
    end

    if not (string.len(script) > 0) then
      return false
    end

    --[[
        eval(script) -- run the script

        guidkey = result(guidkey)
    -- ]]

    if not (string.len(guidkey) > 0) then
      guidkey = ''
    end

    local history = ''
    if userid > 0 then
      history = 'readHistory.ashx'
    else
      history = "history.ashx"
    end

    http.reset()
    --Get the history of the chapter that we need. If we don't do this then in the next http inquiry we will get empty string
    if http.get(MaybeFillHost(module.rooturl, AppendURLDelim(url)..history.."?cid="..chapterid.."&mid="..comicid.."&page="..page.."&uid="..uid)) then
      if http.get(MaybeFillHost(module.rooturl, AppendURLDelim(url).."chapterfun.ashx?cid="..chapterid.."&page="..page.."&key="..guidkey)) then
        local script = StreamToString(http.document)
        --[[
        eval(script) -- run the script

        local d = roArray(result_of_eval) --get the result the d table

        task.pagelinks[workid] = d[workid]
        -- ]]
        return true
      end
    end
  end
  return false
end

function getdirectorypagenumber()
  page = 0
  if http.get(module.rooturl..'/directory/') then
    x=TXQuery.Create(http.document)
    v=x.xpath('//div[@class="pager-list-left"]//a/text()')
    for i=1,v.count do
      v2=v.get(i)
      local n = tonumber(v2.ToString)
      if n then
        if n > page then
          page = n
        end
      end
    end
    return no_error
  else
    return net_problem
  end
end

function getnameandlink()
  if http.get(module.rooturl..'/directory/'..IncStr(url)..'.html') then
    TXQuery.Create(http.document).xpathhreftitleall('//ul[@class="manga-list-1-list line"]/li/a',links,names)
    return no_error
  else
    return net_problem
  end
end

function Init()
  m=NewModule()
  m.category='English'
  m.website='MangaFox'
  m.rooturl='http://fanfox.net'
  m.lastupdated='February 17, 2018'
  m.ongetinfo='getinfo'
  m.ongetpagenumber='getpagenumber'
  m.ongetimageurl='getimageurl'
  m.ongetdirectorypagenumber='getdirectorypagenumber'
  m.ongetnameandlink='getnameandlink'
end
```

**Comment by kevin01523** [comment]
https://github.com/BeRo1985/besen
this the besen repo
this is a required package when im compiling FMD on lazarus pascal

**Comment by kevin01523** [comment]
hmm i we go the lua way yeah we ay need py
or we could do that on the mangafox.pas
like this and mix it with lua i think the lua module can call fucntions from mangafox.pas
https://gist.github.com/frostney/954706
not sure tho

**Comment by 1aam2am1** [comment]
If someone do a BESEN Lua wrapper. Better would be global object or local one created in Lua script by new?

**Comment by kevin01523** [comment]
still no updates huh
