### ISSUE TITLE
MangaRock - no longer can scrape from site or update favourites

### ISSUE THREAD

**Issue by rocktock** [riderkick/FMD#1545]
Manga rock was working flawless a few days back now I update my favourites and I get a carpet bomb of red and current chapter 0.

**Comment by traitorAIZEN** [comment]
i hope this gets fixed

**Comment by Nerozin** [comment]
Seriously
as NO OTHER site hosts all of the manga that i read
They either have some not all or don't have any of them at all
And i really like using this tool been using it for a while now
So plz fix it quickly as i don't want to change it but will if hinders my leisure.

**Comment by Jentosss** [comment]
Same for me. Everything in my "Favoritetes" I download from mangarock...

**Comment by ayase-tan** [comment]
me too, i hope this will be fixed

**Comment by styleindeath** [comment]
same here.... all zero chapter

**Comment by kevin01523** [comment]
it seems that mangarock api is dead or broken getting 405 errors

**Comment by kevin01523** [comment]
https://github.com/manga-download/hakuneko/commit/04800c50b8af2c865c94c8de33119e0cdae1202e#diff-7dcff009cf386d6e825b0d8cd0e57f57

**Comment by noering** [comment]
All zero chapter, cannot update favorite

**Comment by kevin01523** [comment]
![image](https://user-images.githubusercontent.com/8380242/48907911-d0811300-eea3-11e8-8935-9046b65e841a.png)
works now 
lets wait for @riderkick or @kavin-90  or @kmvi  to recompile FMD and add new fmd version to releases

**Comment by traitorAIZEN** [comment]
any chance you can share the edited file(s)?

**Comment by kevin01523** [comment]
@traitorAIZEN its here https://github.com/riderkick/FMD/pull/1547

**Comment by kevin01523** [comment]
[fmd2.zip](https://github.com/riderkick/FMD/files/2611719/fmd2.zip)
just extract to fmd dir

**Comment by rocktock** [comment]
Thank you very much for fixing this kevin01523, tested the executable it works like a charm.

**Comment by admiralmikan** [comment]
> [fmd2.zip](https://github.com/riderkick/FMD/files/2611719/fmd2.zip)
> just extract to fmd dir

Thank you very much for the fix bruh. I'm ashamed I just couldn't understand how to compile it.

**Comment by H4nZ83** [comment]
the application cannot start correctly

**Comment by traitorAIZEN** [comment]
Shinihime commented Nov 23, 2018
As I couldn't get this project to compile I just opened fmd.exe with a hex-editor and searched for "web400" (3 times in there), replaced it with "web401" and mangarock works again.
----
solved the problem. Although it triggered my avast once, no error appeared again after adding it to exclusions.

**Comment by H4nZ83** [comment]
wow your method works like magic

**Comment by H4nZ83** [comment]
but there some problem with mangafox

**Comment by iDeception** [comment]
yeah something wrong with mangafox too

**Comment by 1aam2am1** [comment]
Mangafox changed the html code. And need to be rewritten.

**Comment by H4nZ83** [comment]
@kevin oh you have a 32 bit version?

**Comment by iDeception** [comment]
So there is a manga Nidome no Yuusha https://mangarock.com/manga/mrs-serie-100192031
FMD can't find it for some reason.
https://i.imgur.com/ghJq3h2.png

What's the problem? Is it mangarock or FMD?

**Comment by Nerozin** [comment]
> ## Shinihime commented Nov 23, 2018
> As I couldn't get this project to compile I just opened fmd.exe with a hex-editor and searched for "web400" (3 times in there), replaced it with "web401" and mangarock works again.
> solved the problem. Although it triggered my avast once, no error appeared again after adding it to exclusions.

Thanks Man seriously saved my day.
Salute!

**Comment by TIAIAN** [comment]
i don't know why but even though i changed web400 to web401, the same thing happened but not just with mangarock, it happens to the other sites i use such as rawqv also.

**Comment by Rheneii** [comment]
how do i change the web400, i found 3 of the them. How do i change the string into ds?
