### ISSUE TITLE
Is there something wrong with mangago?

### ISSUE THREAD

**Issue by spamtaztik** [riderkick/FMD#1548]
I've never really used that site before, but I can only find one of the series I followed at mangago. Well, at least the one that's updated until the last chapter... When I tried using FMD it failed and I only got empty folders. Has this been an ongoing issue? Any suggestions on what I can do to circumvent this, at least temporarily (maybe like the problem with Kissmanga a long time ago)?

Thanks much!

Edit: By the way I can access the mangago site and read mangas there through browser just fine.

**Comment by Tmp341** [comment]
[Wiki](https://github.com/riderkick/FMD/wiki/FAQ#cannot-download-from-mangago)

> Cannot download from Mangago
> 
> They add some encryptions/scramblers to their code each time FMD fixes it. Either read online or  change your favorites until it is fixed. But don't expect too much, it will be broken again.


They were doing something when this project was developed actively. I haven't tested it out recently. You can try adding ``UserAgent`` and maybe some cookies under ``Options -> Websites -> Advanced -> Mangago``. That's all i can advice.

**Comment by spamtaztik** [comment]
Hmm, that so? Dang. Well, can't be helped then. 

Thanks for the reply.
