### ISSUE TITLE
List item color needs to use system text color rather than hardcoded black

### ISSUE THREAD

**Issue by Matoro** [riderkick/FMD#155]
Very low priority issue here as I'm sure not many people have this type of customization, however high-contrast themes on Windows will override application styles.  Mine in particular is green text (#00ff00) on a black background (#000000), however it seems that the text color for writing out list items has been hardcoded to black rather than the default Windows text color (sometimes called "Automatic" I believe?).  Known locations this issue affects include:
- Favorites list
- Download tasks
- Series list in left panel
- Chapter list on "Manga Info" tab
- List of websites in "Options" tab
- Likely applies to "Accounts" section under "Options" tab but I have not used that yet.

So far I have been able to get by though using highlighting to view each item in turn, however a fix for this would be appreciated!  Screenshots below.
- Favorites item: https://i.imgur.com/YFs6VNZ.png
- Series list item: https://i.imgur.com/i78X35B.png
- Chapter list item: https://i.imgur.com/b6nB68v.png

**Comment by riderkick** [comment]
Font color is default for all component (clDefault). Those are Virtual Tree View component, I'll check it out.

**Comment by riderkick** [comment]
There is indeed a bug in VirtualTreeview.
http://bugs.freepascal.org/view.php?id=29008
Fix should be included in next version.

**Comment by Matoro** [comment]
The bug tracker indicates that this issue was fixed in revision 4410.  Any idea on when this will make its way down to the project?
