### ISSUE TITLE
Mangafox New Updated Site into Fanfox.net 

### ISSUE THREAD

**Issue by jras13** [riderkick/FMD#1560]
hey there, i figured theres new update from old mangafox.me into fanfox.net, 
and i think the FMD cant grab the link of the mangas because the new interior, its divided in the table form, so i guess the script is kinda screwd up cause new design of the website. 

and i didnt have any idea about what im talking about,. my brain hang cause i starved for mangafox update these 3 months =~=)

**Comment by kevin01523** [comment]
its been fanfox for a while now and and fmd can grab images from fanfox/mangafox no problem until recently. a fix is on the way and just need to be verified by the author
https://github.com/riderkick/FMD/issues/1542
