### ISSUE TITLE
madokami ID/pass not working anymore

### ISSUE THREAD

**Issue by ivanm48** [riderkick/FMD#1570]
Entered my account for madokami in FMD and after trying to download something it seems that they've been erased from madokami and now the account I entered in fmd says it's invalid.
It's like I never registered in the first place.

**Comment by Tmp341** [comment]
But, does the User System still work? They might have deleted all users, or a data error etc maybe.

**Comment by ivanm48** [comment]
Still doesn't work, I've been using it for over a year but when I tried to access madokami through fmd I stopped being able to sign in to the website.

I'm just mentioning this so people don't lose their accounts like me, I heard from someone on their IRC channel that they automatically ban people who try to access madokami through fmd or other programs.

**Comment by Tmp341** [comment]
They both banned you and your IP then?

**Comment by matoro** [comment]
@ivanm48 I have a proxy configured that you can use if it would help.

Edit:  on second thought I will just post the link here:  [redacted] .  It passes through my creds so you can use madokami without an account :)

**Comment by ivanm48** [comment]
Oh my god thank you so much matoro. 

I don't know what to say to this, I won't use it so often as I used to before with my account seeing as I'm going through you.

To reply Tmp341, yeah it seems they banned me but I haven't yet tried signing in from a different PC.

But I don't know why seeing as others used their accounts in FMD with no problem.

Maybe it has something to do with my personal location or it's a glitch or something I don't know

**Comment by matoro** [comment]
Good to hear.  Please make sure the ticket is closed so the wonderful maintainers here have one less thing to worry about :)

**Comment by ivanm48** [comment]
It seems now that I'm getting "502 Bad Gateway".

**Comment by matoro** [comment]
@ivanm48 Not sure what happened there, nginx restart fixed it.  In the future you can email me with issues but I make no guarantees re: uptime, bandwidth, etc:  [redacted]

Please re-close this issue as it's not related to FMD.

**Comment by ivanm48** [comment]
Oh, I aplogize. I didn't have your e-mail so I didn't know how to contact you.

I'll close the issue but please just tell me if I ever cause you problems by using your account in any way.

My email is ivanmladja24[at]gmail.com
