### ISSUE TITLE
Kissmanga failed task

### ISSUE THREAD

**Issue by srishak34** [riderkick/FMD#1571]
it can still function properly when it search for new chapters but not downloading them. also if this is a repost, may someone please delete this? im not logging into github very often.

**Comment by Tmp341** [comment]
Have you tried [these](https://github.com/riderkick/FMD/wiki/FAQ#cannot-download-from-kissmanga)?

**Comment by srishak34** [comment]
the key is the only one that different. also im sorry that i haven't checked the faq and didnt bother with these option, im going to be thorough next time.
