### ISSUE TITLE
E-Hentai/Ex-Hentai gallery download problem

### ISSUE THREAD

**Issue by Ouxhi** [riderkick/FMD#158]
Obviously the following links are **NSFW** but I'm using them as an example of an issue. [Gallery Ex-hentai url] (http://exhentai.org/g/740286/8490fa3b13/) or [Gallery E-hentai url] (http://g.e-hentai.org/g/740286/8490fa3b13/)

The above gallery is incorrectly downloaded with fmd_0.9.29.1_Win64 when using either url. This version of FMD downloads 80 images instead of 44 and misses some of the images in the gallery.

However, fmd_0.8.13.1_Win64 is able to correctly download the images from [E-hentai url] (http://g.e-hentai.org/g/740286/8490fa3b13/)
These 2 versions of FMD are the only ones I've tested the gallery with.

**Comment by riderkick** [comment]
Just missing "=" in url parameter. Which causing it to send "?p1" instead "?p=1". So it's always scraping the first page.
