### ISSUE TITLE
Request for Websites

### ISSUE THREAD

**Issue by Weischbier** [riderkick/FMD#159]
Hi there!
I'd like to request 3 new sources.
http://www.mangakoi.com/
http://yomanga.co/
https://gameofscanlation.moe/forums/projects-releases.9/

Thank you in advance.

**Comment by riderkick** [comment]
You should create an issue for each request. So issue be more organized, easier to search.

**Comment by Weischbier** [comment]
I'll keep that in mind!
Thanks a ton for adding these.
