### ISSUE TITLE
Problem with Meraki

### ISSUE THREAD

**Issue by spamtaztik** [riderkick/FMD#1598]
Earlier today (or was it yesterday?) there were module updates for several websites, and after those updates I noticed that I can't download from Merakiscans, and all bookmarked mangas from Meraki came up as having 0 chapters. I couldn't remember if Meraki was included in those updates or not. Anyone have any idea why?

Oh, and HAPPY NEW YEAR! Thanks for a great year with FMD, and looking forward to many more!

Edit: Yes I can open the website and read chapters through a regular browser.

**Comment by jokosablenk** [comment]
got the same problem.
