### ISSUE TITLE
Donations for the developers

### ISSUE THREAD

**Issue by SDXC** [riderkick/FMD#1612]
@kmvi @riderkick 
I'd really like to give you both a little something for your continuous hard work.
I can't count how much time FMD saved me and still does.
Really, thank you!

Please let me know if you have a PayPal-Account, so I can send you a little present.
You could share the links in the "README.md".

**Comment by ChocolateOtaku** [comment]
I hope you also donate to the websites where you are downloading from, because they are way more important and without them FMD would be just a piece of junk...

**Comment by SDXC** [comment]
@ChocolateOtaku I donate 100$ every month to MangaDex since the very beginning.
