### ISSUE TITLE
Please add https://otakufile.com/

### ISSUE THREAD

**Issue by Riztard** [riderkick/FMD#1618]
Please add this site https://otakufile.com/
Thanks :D

**Comment by Riztard** [comment]
sorry why i still cant download from otakufile?
and im already update the modules  
there is no otakufile in website list and when i try download by link (url not supported) 
i use this link https://otakufile.com/hunter-age-bahasa-indonesia/
or is it not yet added? 
sorry :(

**Comment by Tmp341** [comment]
> 
> 
> sorry why i still cant download from otakufile?
> and im already update the modules
> there is no otakufile in website list and when i try download by link (url not supported)
> i use this link https://otakufile.com/hunter-age-bahasa-indonesia/
> or is it not yet added?
> sorry :(

Check your ``MangaShiro.lua`` module. If it was updated 4 hours ago, then you have the latest file.

**Comment by Riztard** [comment]
thanks i solved it
cuz there is no update while i check module update so i copy the code manually :)
sorry for bothering
