### ISSUE TITLE
Batoto (EN) broken

### ISSUE THREAD

**Issue by Weischbier** [riderkick/FMD#162]
There seems to be an issue with Batoto(EN) currently.
It doesn't load 99% of the time no chapters. Even after updating the manga list.

I made a video showcasing it for both versions.
https://youtu.be/n2ounj-OzDU 
(*as the time this issue is posted: YouTube is still processing the Video*)

There may be issues with other sources as well but I only use Batoto(EN) as one of my main sources, besides MangaFox, MangaKoi, GameofScanlation, Mangacow and YoManga.
**MangaFox, MangaKoi, GameofScanlation, Mangacow and YoManga all work fine.**

**Comment by blue-lightning** [comment]
Bato to now requires a user account to see all chapters. Create one and then add it to FMD at Options -> Account.

**Comment by riderkick** [comment]
Batoto require an account. Just visit their website, you will understand.

**Comment by Weischbier** [comment]
Ahhh my bad.
