### ISSUE TITLE
Question, what is Lua scripts, what is they use?

### ISSUE THREAD

**Issue by Playcool92** [riderkick/FMD#1625]
See alot of people mentioning, but no one seems to bother to give it an explanation (not everyone here knows programming or more than your average internet guy)...

**Comment by 1aam2am1** [comment]
Lua script is script writed in Lua language. We can change it and we don't need to recompile program.
In FMD it is used for checking sites and so one.

**Comment by 1aam2am1** [comment]
Lua script is script writed in Lua language. We can change it and we don't need to recompile program.
In FMD it is used for checking sites and so one.

**Comment by Tmp341** [comment]
[These](https://github.com/riderkick/FMD/tree/master/lua/modules) files are written in Lua language. It is a lot more easy to use. For example, when a website only changed it's domain from ``.co`` to ``.me`` for example, you can change it without waiting for an update.

**Comment by Tmp341** [comment]
You should be able to download from mangadex. At least I can download.

Mangapark is blocking my ip with all it's domains. Tried with a vpn, it works as you can see: 

![ssssss](https://user-images.githubusercontent.com/1683388/51079168-82ce9d00-16d3-11e9-8f9b-d3565db4f2c9.jpg)

**Comment by Playcool92** [comment]
> You should be able to download from mangadex. At least I can download.
> 
> Mangapark is blocking my ip with all it's domains. Tried with a vpn, it works as you can see:
> 
> ![ssssss](https://user-images.githubusercontent.com/1683388/51079168-82ce9d00-16d3-11e9-8f9b-d3565db4f2c9.jpg)
> 
> What kinda problems you have?

So you opening mangapark with a vpn? Then copying that link to FMD and it works??
(why are they blocking your IP?)

I cant for mangadex, and no is giving me solutions that work, and with mangapark my previous source not working... could you try to download the lastest FMD, have it run vanilla like on another folder (dont use any vpn), and see if it is working for you?
I get this url is not valid all the time...

**Comment by Playcool92** [comment]
> You should be able to download from mangadex. At least I can download.
> 
> Mangapark is blocking my ip with all it's domains. Tried with a vpn, it works as you can see:
> 
> ![ssssss](https://user-images.githubusercontent.com/1683388/51079168-82ce9d00-16d3-11e9-8f9b-d3565db4f2c9.jpg)
> 
> What kinda problems you have?

So you opening mangapark with a vpn? Then copying that link to FMD and it works??
(why are they blocking your IP?)

I cant for mangadex, and no is giving me solutions that work, and with mangapark my previous source not working... could you try to download the lastest FMD, have it run vanilla like on another folder (dont use any vpn), and see if it is working for you?
I get this url is not valid all the time...

**Comment by Tmp341** [comment]
I dunno. I couldn't open mangapark, tried all the urls. My fmd freezes (cant download) when downloading from mangapark. So vpn solved it.

Can you open mangadex via browser?

**Comment by Playcool92** [comment]
> I dunno. I couldn't open mangapark, tried all the urls. My fmd freezes (cant download) when downloading from mangapark. So vpn solved it.
> 
> Can you open mangadex via browser?

I can open both mangadex and mangapark just fine... if you can open mangadex, mind sharing me your FMD or the Lua for it?

**Comment by Tmp341** [comment]
My lua files are default, so you should be able to get those yourself. I don't think they're needed in your case.

Can you send me screen shots of your Fmd's ``About`` , ```Website\Modules``, ``Websites\Advanced\MangaDex`` and ``Websites\Advanced\MangaPark``? Or send me your FMD, so i can crosscheck.

**Comment by Playcool92** [comment]
![image](https://user-images.githubusercontent.com/46245430/51109506-57d86c00-17ed-11e9-85fb-15f43a34adc6.png)
![image](https://user-images.githubusercontent.com/46245430/51109623-a980f680-17ed-11e9-8245-7fd24313da58.png)
![image](https://user-images.githubusercontent.com/46245430/51109748-0ed4e780-17ee-11e9-8058-c5475dd2af70.png)

This is all vanilla, the version you can get from here, didnt change anything, other than when opening the program, says some LUA changed and ask to update those, which I do, and then restarts the program with them installed.

**Comment by Playcool92** [comment]
I have just realized, but your solution is with the basis I m not deleting my folders... I m, nothing is left, I download the rar, extract and run it up, I m not using previous folder at all.

**Comment by Tmp341** [comment]
I'm out of ideas.

**Comment by Playcool92** [comment]
> I'm out of ideas.
> 
> You don't have `Mangadex` advanced options for example. But you should, at least after the fresh install.
> ![ss](https://user-images.githubusercontent.com/1683388/51230385-d7427880-1970-11e9-896f-0ca60c50521b.jpg)

Can you compress the folder you have, or download FMD lastest version again on another folder, test out that it works with said sites I said, compress and let me give it a try on it?
IF it works for you, but then I download and doesnt, it may not be a problem with the software itself.

**Comment by 1aam2am1** [comment]
Do you know that this FMD is new FMD. Not the old one. Many issues come from people who downloaded the old FMD that is not developed.

The old one:
<br/>
https://sourceforge.net/projects/fmd/

The new one:
<br/>
https://sourceforge.net/projects/newfmd/

**Comment by Playcool92** [comment]
> Do you know that this FMD is new FMD. Not the old one. Many issues come from people who downloaded the old FMD that is not developed.
> 
> The old one:
> https://sourceforge.net/projects/fmd/
> 
> The new one:
> https://sourceforge.net/projects/newfmd/

Bro, all I know is that I get all my FMD versions from here:
https://github.com/riderkick/FMD/releases

And I have tried deleting, then downloading and extracting the newest versions more than once, and I still get the same problem.

**Comment by 1aam2am1** [comment]
1. Set config for saving logs.
2. Delete all lua files
3. Start program
4. Wait for lua updates if it is updated. Then update manually by update lua button in settings. 
5. Restart and check if you have mangadex available.
6. If not close fmd and watch logs for problem. 
7. If you don't find problem on your own. Paste us your logs for crosschecking. 
8. Send us your program (optional if it is from github release)

**Comment by Playcool92** [comment]
> > Can you compress the folder you have, or download FMD lastest version again on another folder, test out that it works with said sites I said, compress and let me give it a try on it?
> > IF it works for you, but then I download and doesnt, it may not be a problem with the software itself.
> 
> I don't think that the problem is the app itself, as we all can use it. But anyway, here it is:
> [FMD.zip](https://github.com/riderkick/FMD/files/2767402/FMD.zip)

Tried, didnt work.

> 1. Set config for saving logs.
> 2. Delete all lua files
> 3. Start program
> 4. Wait for lua updates if it is updated. Then update manually by update lua button in settings.
> 5. Restart and check if you have mangadex available.
> 6. If not close fmd and watch logs for problem.
> 7. If you don't find problem on your own. Paste us your logs for crosschecking.
> 8. Send us your program (optional if it is from github release)

Did what you just said.
Deleted luas, let it update, then tried manual updating (didnt do anything), restarted program, tried again, still getting the same error.
![image](https://user-images.githubusercontent.com/46245430/51357303-27772300-1ab6-11e9-863c-9176159b1cfa.png)

Previous this I tried a VPN, also didnt work, also tried to disable ad block, reloading page, then copying the link, everything, always leads me to the same error:
![image](https://user-images.githubusercontent.com/46245430/51357353-6b6a2800-1ab6-11e9-8132-d814082234c9.png)

**Comment by Tmp341** [comment]
Why you have that ``Transferencias`` folder name? Can you rename it and try again? It might not be the case, but give it a try.

**Comment by Playcool92** [comment]
> Why you have that `Transferencias` folder name? Can you rename it and try again? It might not be the case, but give it a try.

Why does that matter? You realize not everyone here is english right?
I have had FMD for ages in the same folder structure and it has always worked.
I m sure not being able to get links inside, has nothing to do with that.

THAT above is what I said, before trying this out, I have now put FMD on upper folder structures, and mangadex is working now, both that and mangapark ARE. WTF??
Will anyone explain to me. why can other websites work fine, and mangapark did for all this time, but now doesnt?!
What is the relation here?
Are the names of the links just too big considering FMD is located inside a few subfolders itself?

**Comment by Playcool92** [comment]
BTW, while both are now getting the links inside FMD, mangapark gives error to any and all chapters it tries to download, but mangadex is working fine, so I will stop caring for now, lost too much time on this already, and community seems enough supportive here, so I will let you guys know if something happens.
As long as I get mangadex working, I m happy.

**Comment by 1aam2am1** [comment]
Before the sites where parsed in pascal. Now we parse it in Lua and from what can I see. We can't open Lua files with these letters in path.

**Comment by Tmp341** [comment]
> 
> 
> > Why you have that `Transferencias` folder name? Can you rename it and try again? It might not be the case, but give it a try.
> 
> Why does that matter? You realize not everyone here is english right?
> I have had FMD for ages in the same folder structure and it has always worked.
> I m sure not being able to get links inside, has nothing to do with that.
> 
> THAT above is what I said, before trying this out, I have now put FMD on upper folder structures, and mangadex is working now, both that and mangapark ARE. WTF??
> Will anyone explain to me. why can other websites work fine, and mangapark did for all this time, but now doesnt?!
> What is the relation here?
> Are the names of the links just too big considering FMD is located inside a few subfolders itself?

I'm not English either, but some apps use different structures, become confused with those special characters. 

Man, i wanna help you, but im out of ideas. Have you checked if you can use mangapark via browser?

**Comment by Playcool92** [comment]
Those are not special characters though... it is just the Portuguese of Downloads, Transferências, the folder where shit I download via browser go too, and FMD always worked there previous.

![image](https://user-images.githubusercontent.com/46245430/51419104-d3d10c00-1b7f-11e9-8636-b7a94d0babf9.png)
Dunno what to do either, I may try mangarock for those updates mangadex doesnt cover.

**Comment by Tmp341** [comment]
That is not a standard character for English, just like ``Ö`` or``Ç``.

Give this a try, use mangapark with free a vpn. This is the last opinion i can give. I'm not a coder, so, i'm not sure what is going on.

**Comment by Playcool92** [comment]
Ah, you meant ~, well but I had been using this before just fine with FMD for years, so I dunno what prompted the change.
As for mangapark, I think I tried before with some cheap "free" vpn, there is no difference, for starters I can acess and read from mangapark normally without one.
VPNs are a waste of money for me, had PIA for a year, didnt needed it.

**Comment by Playcool92** [comment]
> Before the sites where parsed in pascal. Now we parse it in Lua and from what can I see. We can't open Lua files with these letters in path.

So that is the reason that now FMD cant be inside folders that contain letters outside of english alphabet...
