### ISSUE TITLE
Random System Sounds with v0.9.31.0

### ISSUE THREAD

**Issue by Weischbier** [riderkick/FMD#163]
There seems to be an issue regarding random Systemsounds playing when using fmd_0.9.31.0.
This does not happen with the prior versions.

I made a video showcasing it for both versions.
https://youtu.be/n2ounj-OzDU?t=4m

**Comment by riderkick** [comment]
I don't recall write any `beep`, nor I've seen them anywhere in the source.
What sound. Maybe it just notification when download complete? That's controlled by Windows.

**Comment by Weischbier** [comment]
I tested this thoroughly yesterday and it only happens with the current version and only when updating the lists. I'm confused as well because this is pretty random.

**Comment by riderkick** [comment]
maybe just notification, or persistent dialog. or other app.

**Comment by Weischbier** [comment]
maybe, I just muted it in the sound manager. thanks anyway, seems to be a windows 10 issue, maybe? :D Well, whatever. It's not like it is app breaking.
