### ISSUE TITLE
Madara - WordPress Theme for Manga

### ISSUE THREAD

**Issue by rs3mk** [riderkick/FMD#1633]
Can anyone create the module for this WP theme?

demo: http://demo.mangabooth.com/manga/hajime-boyfriend/

script: https://mega.nz/#!fH4hhYbS!n25ob5jJ_IKSFGO4pl3Rcjz9z4UXCioJizfTV2AIGXM

Thank you!

**Comment by kmvi** [comment]
see Madara.lua
