### ISSUE TITLE
Mangahere not working since today [2019-01-17]

### ISSUE THREAD

**Issue by spamtaztik** [riderkick/FMD#1636]
I'm using the latest version of FMD and the modules as well, but for some reason I can't connect to mangahere. Favorite checks show 0 chapter for all series from mangahere, and the "manga info" page came up empty. However, if I take the URL from the manga info page (say http://www.mangahere.cc/manga/lv999_no_murabito/) and put it in my browser, the page opens just fine. Any idea why?

EDIT: if I dbl-click any of the manga titles in the left window of manga info page, it will also came up blank like so:
![error](https://user-images.githubusercontent.com/25314447/51317374-fe409d80-1a89-11e9-8938-4fc061662c9c.jpg)

**Comment by ralvarador** [comment]
Looks like mangahere has adopted the mangafox template.
That template seem no being managed through LUA modules, I guess that it will be needed hardcoding to have it back!

**Comment by spamtaztik** [comment]
It's working again after a module update. Thank you! Praise the modules (and whoever wrote it)! 
:)
