### ISSUE TITLE
DigitalTeam not working

### ISSUE THREAD

**Issue by ChocolateOtaku** [riderkick/FMD#1637]
Re-opened, because #1629 is still not fixed:
Try download any chapter from "Infection" => Failed ...

**Comment by ChocolateOtaku** [comment]
Now it shows duplicate mangas in the list ...

![image](https://user-images.githubusercontent.com/38581381/51416957-25779780-1b7c-11e9-8122-3b6ccaeed3b7.png)

**Comment by Tmp341** [comment]
I think when a website changes it's manga url, like from ``/manga/ch1`` to ``mng/ch1`` for example, and if you update without deleting ``db`` file, fmd finds latest, but also keeps previous mangas. So, you will have 2 mangas with the same name, aka duplicates.

**Comment by ChocolateOtaku** [comment]
Sounds to me like a software bug then
