### ISSUE TITLE
Custom Genre buggy

### ISSUE THREAD

**Issue by Weischbier** [riderkick/FMD#164]
There seem to be issues with the custom genre strings.

For example:
!OneShot <= works
whereas
!One,!Shot <= does not work.

The problem why I want to use it like the latter case is because the hosters write it in two different ways.
MangaFox writes it as **OneShot** but MangaKoi writes it as **One Shot** with whitespace.

Maybe you guys can add it as a checkbox genre.

**Comment by riderkick** [comment]
Just use `!OneShot,!One Shot`, every genres treated as 1 item.

**Comment by Weischbier** [comment]
Been there done that. That way doesn't work as well.

**Comment by riderkick** [comment]
Working fine here.
![sshot-3](https://cloud.githubusercontent.com/assets/4972676/12481571/0c62f028-c085-11e5-82b6-e7177e19d9b1.jpg)
![sshot-1](https://cloud.githubusercontent.com/assets/4972676/12481576/12238f86-c085-11e5-8db6-dc53f381c4b6.jpg)
