### ISSUE TITLE
Problem with goodmanga (can't open favorites)

### ISSUE THREAD

**Issue by spamtaztik** [riderkick/FMD#1645]
I just noticed that all my GoodManga favorites came up as 0 chapters. The manga info page came up blank, and if I entered the URL in my browser (say http://www.goodmanga.net/7244/uq-holder), it opens up Mangareader's main page. Even when I tried opening www.goodmanga.net it would open Mangareader. I understand they might be the same company or whatever, but my question is: what will happen to all my favorites from goodmanga? Do I need to transfer them to mangareader? Is goodmanga dead?

**Comment by kevin01523** [comment]
you can transfer it to a new website i havent tested this feature yet lmao and i only discovered it just now since its not that easy feature to discover unless you really thoroughly check everything
![image](https://user-images.githubusercontent.com/8380242/51596546-9af8b480-1f3c-11e9-8b06-8a4bc05b5c4a.png)

**Comment by kevin01523** [comment]
update make sure to backup you work folder before doing this since it moves the favorites instead of copying it

**Comment by spamtaztik** [comment]
Yes, I know I can transfer them to another site, been doing that since the days of domdomsoft. It's just -sometimes- moving mangas to a different website re-download the whole thing from the beginning (which I then have to sort and such).

So Goodmanga IS dead, then? 
Whooboy....

Oh well, nothing can be done about it I guess.

**Comment by kevin01523** [comment]
yeah good manga has manga that no other site has like what anime44 did b4 it has ancient subs like pokemon subbed that is hard to find nowadays


well i did manually transfer the invalid one and did organize the folders and only downloaded misssing chapters from what i downloaded from goodmanga
