### ISSUE TITLE
Lhtranslation download problem & Feature Request

### ISSUE THREAD

**Issue by Tmp341** [riderkick/FMD#1649]
- [ ] I can check and read from Lhtranslation, but can't download from there, download freezes.
- [ ] When FMD checks favorites, newly found mangas are shown. But, if you press cancel, fmd finds them again on next check. If you add it to download list, it is marked as ``Downloaded`` even if you've deleted that task without downloading.
- [ ] A button etc, lets users to download or pack a chapter with cbz. It will download pages normal, then it will also pack that selected chapter.

**Comment by ratbunuts** [comment]
I have the same problem although 5/10 will be downloaded and the rest of the chapters will fail. Its very random the same with a raw site RawQQ

**Comment by wuhugm** [comment]
Me too unable to download from LH since forever
