### ISSUE TITLE
FMD 0.9.31.0 (64bit) Failed to Download Orange Yane no Chiisana Ie.

### ISSUE THREAD

**Issue by ChronoSX007** [riderkick/FMD#165]
For some reason i cannot download this series all folders are empty

link to the manga: http://bato.to/comic/_/comics/orange-yane-no-chiisana-ie-r1043

**Comment by Weischbier** [comment]
You have to log into your account with FMD.
I made the same mistake.

http://prntscr.com/9srsx3

**Comment by ChronoSX007** [comment]
Forgot to add that i am already log-in i can download other series fine but not this series.... O_0

**Comment by riderkick** [comment]
Which chapter?
![sshot-4](https://cloud.githubusercontent.com/assets/4972676/12482066/78b3fc7e-c088-11e5-9609-d24f26dce5d5.jpg)

**Comment by ChronoSX007** [comment]
All the English chapters.

**Comment by riderkick** [comment]
![sshot-5](https://cloud.githubusercontent.com/assets/4972676/12483953/b1ea25e0-c092-11e5-88b1-47f7f1f97e6f.jpg)

**Comment by riderkick** [comment]
I believe it's related to this https://github.com/riderkick/FMD/commit/ea333508c80de2fe1d317dee53f600a7e1f7e80a , https://github.com/riderkick/FMD/commit/b7aa807a57e818c356cd291db28135b52c96f1c3
