### ISSUE TITLE
nHentai database

### ISSUE THREAD

**Issue by traitorAIZEN** [riderkick/FMD#1658]
Does anyone have an uptodate nhentai database?
the one downloaded from server is taking so much time to update

**Comment by traitorAIZEN** [comment]
Edit: Nevermind, i managed to update it after 12hrs
For those interested : [MEGA][nHentai DB] http://bit.ly/nHentaiDB

**Comment by Tmp341** [comment]
I have thought that i should start a repo for up-to-date databases (on github), but this project is almost dead. I just thought "forget about it".
