### ISSUE TITLE
Stuck while checking favorites

### ISSUE THREAD

**Issue by spamtaztik** [riderkick/FMD#1660]
I know this issue has been mentioned several times in the past, but my problem "SEEMS" to be different than those people's. Here's what happens:
1. From time to time (rarely), favorites check would be stuck at one or two mangas from certain website (usually from WhiteCloudPavilion).
2. Other times (also rarely), it would be stuck at SOME mangas with very high chapter count from SOME sites (say OnePiece from Mangadex, 916 chapters) but other high chapter count mangas would be fine (Hajime no Ippo from Mangahere, 1248 chapters).

FMD manages to complete the check for every other favorites, but only those 1-2 mangas would be stuck, no matter how long I wait. To get things rolling again I have to disable those mangas, let the newly released chapters be added to download list, then re-enable those disabled mangas. But 99% of the times the favorite check would be completed just fine. I have the "number of retry if task have download problems" set to 3, and "number of retry if task failed" to 2, so nothing that would cause the infinite wait time.

Any idea what's causing this? I'm using the latest version of FMD and the modules.
Thanks.

**Comment by Tmp341** [comment]
1. That occurs when a website's code is changed.
2. If that happens while using mangadex, the site has some ddos attacks.

**Comment by spamtaztik** [comment]
Hmm, not exactly what I meant. Like I said, it happens rarely (but it does happen), so most of the times the check will finish just fine. So one time the check will stop at one of the mangas from WhiteCloudPavilion, but the next time it will be fine. Btw the favorite check for all mangadex mangas always succeeded, even during the ddos.

Anyway, I assumed the "number of retry if task have download problems" or the "number of retry if task failed" options -should- have just ignore the check for that particular manga after x failures, but apparently it would stay at that one particular manga for whatever amount of hours unless I disabled it. Are those options for # of retries only apply for download tasks and not for favorites check?

**Comment by Tmp341** [comment]
Yes, it is just for tasks.
