### ISSUE TITLE
FDM Out of Memory

### ISSUE THREAD

**Issue by Ramdhani04** [riderkick/FMD#1668]
if i open fdm I get a message like this
![screenshot_219](https://user-images.githubusercontent.com/47376384/52320915-8d473280-2a04-11e9-88e2-f37de634f453.jpg)

and i show detail i got this

Unhandled exception!
Application       : Free Manga Downloader
Version           : 0.9.158.0
Product Version   : Win32 Debug
Host Machine      : Windows 7 64-bit
FPC Version       : 3.0.4
LCL Version       : 1.8.4.0
WidgetSet         : Win32/Win64
Target CPU-OS     : i386-Win32
Build Time        : 2019/01/06 11:02:18
Path              : C:\Program Portable\Free Manga Downloader\fmd.exe
Process ID        : 7292
MainThread ID     : 884
Thread ID         : 884
Time              : 06/02/2019 11:29:39.515
Exception Class   : EOutOfMemory
Message           : Out of memory
  $00411C89
  $00411FB7
  $007B3F4B
  $007B278D
  $007B23DD
  $007A0E43
  $007A2C91
  $007A2D04
  $00465463  TMAINFORM__TMSTARTUPTIMER,  line 1788 of ./forms/frmMain.pas
  $00586AEF
  $00586A67
  $00512F4F
  $766962FA
  $76697B16
  $766979C7
  $7669788A
  $00513B6D

but if i remove favorites.db the program running fine...
Is there a problem with my favorites.db

**Comment by Tmp341** [comment]
Backup your ``Favorites.db`` and reinstall FMD with these steps : [Fress Install in FAQ](https://github.com/riderkick/FMD/wiki/FAQ#fresh-install-steps)

Also, check out your system usage.
