### ISSUE TITLE
Downloads log/history disappeared

### ISSUE THREAD

**Issue by wuhugm** [riderkick/FMD#1681]
Suddenly my downloads log/history disappeared
The ones in Completed/Failed tabs
This never happened before
I had more than 10000 in that list since 2017
Now it's gone

**Comment by Tmp341** [comment]
If your ``Works\downloadedchapters.db`` file was deleted, your history is gone.

**Comment by wuhugm** [comment]
It's still there 3 MB large
But it said last accessed was on the 11th
there's another one called **downloadedchapters.db-journal**
This one is recently accessed

**Comment by Tmp341** [comment]
Latest one means fmd is still running. Copy that ``downloadedchapters.db-journal`` to Desktop, rename it to ``downloadedchapters.db`` and If you're sure your fmd is closed, check from task manager and close it (I think there is a second one running).

Then rename (downloadedchapters.db.bak for example) or move original``Works\downloadedchapters.db``, then paste the one from Desktop to Works folder.

**Comment by wuhugm** [comment]
^Wait a minute, surely the correct one is the large one (the not journal one)
If I renamed it, then it won't be accessed anymore, right?

**Comment by zackad** [comment]
@wuhugm, yes the '-journal' one is the temporary data that hasn't been written to the 'real' database history.
backup your history to other folder and delete the -journal' one, then start fmd.

as always, backup your database (including mangalist, and favorite) before starting troubleshooting. you might need it later.

**Comment by wuhugm** [comment]
^So, after quitting the FMD this time
The journal is gone too
So only downloadedchapters.db is left
BUT!
When starting FMD again
Every tabs (completed, stopped, etc) became 0 again

**Comment by Tmp341** [comment]
> 
> 
> ^So, after quitting the FMD this time
> The journal is gone too
> So only downloadedchapters.db is left
> BUT!
> When starting FMD again
> Every tabs (completed, stopped, etc) became 0 again

But, i said back up original ``downloadedchapters.db`` file, rename ``downloadedchapters.db-journal`` to ``downloadedchapters.db`` and open FMD.

Or you can open that file with a SQLite browser. If it contains anything, it will be empty.

**Comment by wuhugm** [comment]
^Done
Still empty after restarting

Btw, what is this downloads.db file does?
This one is almost 23 MB large

**Comment by Tmp341** [comment]
It is your ``downloads`` list. I guess i've made a mistake. This file contains what you've been asking for.

**Comment by wuhugm** [comment]
^So, what do I do with this?
I mean it's still there without replacement like journal one

**Comment by Tmp341** [comment]
Like i said, you can check what it contais. You can use apps like [SQLiteDatabaseBrowser](https://portableapps.com/apps/development/sqlite_database_browser_portable)

**Comment by wuhugm** [comment]
^I just want to incorporate it back to the system (if it's not), what should I do?

**Comment by wuhugm** [comment]
So I delete the downloads.db and now I can retain a list again (though I lost the history)
It seems that it just can't hold tens of thousands items in the history
