### ISSUE TITLE
Error site

### ISSUE THREAD

**Issue by riedhows** [riderkick/FMD#1686]
some site from Indonesia get Error

Neumanga.tv - Can't rename chapter
Komikstation.com - Can't rename chapter
Kiryuu.co - Can't fetch chapter 

for kiryuu it show blank on chapter list

thanks

**Comment by ghost** [comment]
pakai web yang lain aja bro

spt mangaid, komikcast, mangaindo

[modul fix for indonesia source.zip](https://github.com/riderkick/FMD/files/2930124/modul.fix.for.indonesia.source.zip)
