### ISSUE TITLE
MangahubIO can't download new manga

### ISSUE THREAD

**Issue by 6io** [riderkick/FMD#1689]
Hello 
can you please check mangahubIO
this site from 21 feb all new updates can't be download 
but all manga before 21 feb can be download 

thanks

**Comment by ghost** [comment]
[MangaHubIO.zip](https://github.com/riderkick/FMD/files/2930111/MangaHubIO.zip)

replace lua with my lua
sorry bad english language

**Comment by 6io** [comment]
thanks
