### ISSUE TITLE
Save folder as url

### ISSUE THREAD

**Issue by Ruriko** [riderkick/FMD#169]
Is it possible to save the folder name as the site's album url (mainly for hentai sites only) as long you remove http:// it should then work on windows naming system.

**Comment by riderkick** [comment]
If you want to add website name, you can use `%WEBSITE%` in manga folder/chapter. Options>Save to.
Or you mean the entire url? `www.domain.com/xxx/xxx/xxx/xxx/xxx/title` like that. That would be crude, there is a lot of unexpected character/symbol. Keep in mind FMD had a lot of website. A feature should-be/will-be applied to all website.
What are you trying to achieve? For what purpose?

**Comment by Ruriko** [comment]
oh the %WEBSITE% is exactly what I'm looking for
