### ISSUE TITLE
Add support for 9anime or KissAnime

### ISSUE THREAD

**Issue by ChocolateOtaku** [riderkick/FMD#1692]
It would be nice if FMD could also download anime episodes from one or both of the suggested websites.

**Comment by 1aam2am1** [comment]
I think this is idea for April fool's day.
FMD IS FOR MANGA not for anime.
And many websites like that have security means, that only people (real brownser) could download from them (even programs simulating input to brownser's are not good.)
PS. FMD is in state of paralysis. It is not actively developed, have many problems and many new sites to implement and repair.
PS2. If you want implemented this implement it yourself and make pull request.

**Comment by ChocolateOtaku** [comment]
Hey Mr. Fools Day,

i'm well aware of the current struggling with FMD development. I hope you will give this answer to all those other issues to let them know FMD is incative and not just response this to my ticket.

I also hope you will give your answer "You want this, do it yourself and make a pull request" to all the other issues too or is there some special diskliking regarding just me?

On topic:
Websites for manga and anime are basically the same, one is just images, the other video.
Furthermore HakuNeko is also "just" a manga downloader and you know what, they added support for KissAnime and 9anime, thats why i suggested it for FMD in the first place (because it seems doable). But you said its to difficult, not even real Browser automation can do it right? Don't believe it? Then go check for yourself. Modern manga website protection is also very sophisticated and FMD breaks it.

Sorry to tell you, but this time it wasn't me who made a fool of himself...

**Comment by ghost** [comment]
you can use the application AnimeDLR
For download anime

**Comment by Tmp341** [comment]
Most of the developers are looking for money. If it is a paid app, then "lets roll". If it is not, "i have my own problems irl".

I can understand latter, but changing ``readme`` file and making it a ``read-only`` (for "this app is a goner" message) shouldn't be hard. 

This app was a good example of "open source" and "support them all" terms. If you're unsure, just check the source code. If you want a site added, just ask. Nice, isn't it?

There might be a fork, but unless someone picks this officially, those forks will mean nothing to us. 

--------------------------------------------------------------------------------------------

For the topic: It will need new codes. So, we are back to square one: having nobody.

**Comment by Ianunaut** [comment]
Please do not abuse GitHub for your weaksauce trolling.

**Comment by ChocolateOtaku** [comment]
This seems to never happen on this fork => closed
