### ISSUE TITLE
for KMVI

### ISSUE THREAD

**Issue by ghost** [riderkick/FMD#1694]
please add 3rd party libraries and components
in folder 3rd
I want to improve the program

sorry
my english is bad

**Comment by Tmp341** [comment]
> 
> 
> please add 3rd party libraries and components
> in folder 3rd
> I want to improve the program
> 
> sorry
> my english is bad

Since last updated module is from almost 2 months ago, just make a project fork for yourself, then add components to that, then make a pull request. If someone approves it, we won't have a problem. If not, you can be the main developer. 😃
