### ISSUE TITLE
Sen manga Doesn't Work

### ISSUE THREAD

**Issue by abhishekanime98** [riderkick/FMD#17]
Sen manga Doesn't work. Chapters don't show up. Please fix. Thank you
![capture](https://cloud.githubusercontent.com/assets/11986516/7447793/440e7188-f1d6-11e4-8a1e-f73d582b6541.JPG)

**Comment by abhishekanime98** [comment]
Sen Manga RAW is not working anymore just letting you know thanks

**Comment by riderkick** [comment]
It should work since version 0.9.9.5 upward.

**Comment by abhishekanime98** [comment]
Now its working Thanks :) and sorry I forgot to say thank you last time. So, Thanks, you are best

**Comment by rajlaksh** [comment]
They removed all Banned that why it is working.

before I tested 0.9.10.0 it was not working.

**Comment by riderkick** [comment]
They still have a ban. Their website is only allowed to be opened from firefox. And it's the particular one, at the morning, it was working with win8.0, but at the afternoon they ban it, so I've to change it again. At the past they only allowed to be view from the latest browser version.  You can see I change user-agent a lot just for it.
https://github.com/riderkick/FMD/commit/8273b207ce0413e2db6dc65667af7eadae6969ec
https://github.com/riderkick/FMD/commit/f884d2ea1d4825f9b0adb3f1fe1f88d1b7b65f0e
https://github.com/riderkick/FMD/commit/24d21babb33f055fd2caf4934e50d056c7634c3a
...

**Comment by rajlaksh** [comment]
Nope. I can open it from Chrome, Firefox and able to read chapters from it. :+1:

**Comment by riderkick** [comment]
Yes, they lift a ban for manga information page. But, ma n ga directory  is still  banned from other than firefox. that's why I change it to firefox.
Their user-agent rules is very strict. OS version is matter.

**Comment by rajlaksh** [comment]
yeah. x64 was banned. Now it removed.

**Comment by riderkick** [comment]
Please use space when talking about specific sites problem(e.g. s en man ga). Our conversion appeared on the first page of g 0ogle search result. 😓

**Comment by rajlaksh** [comment]
Sen Manga not s en man ga :disappointed: 

FMD can't update Manga List can't Update.

**Comment by riderkick** [comment]
I'm talking about avoiding go0 gle search result.
Now it's not working anymore. 😅
That's why I'm telling you to not blatantly talk about it. 😑

**Comment by rajlaksh** [comment]
Your Version?

**Comment by riderkick** [comment]
Manga directory is what's not working.

**Comment by rajlaksh** [comment]
You already know it has Banned.

**Comment by riderkick** [comment]
It's not banned yesterday.

**Comment by rajlaksh** [comment]
It was from 0.9.10.0 version

**Comment by riderkick** [comment]
We use ff 37 win8.1 wow64 for 0.9.10.0, it's banned. 😆

**Comment by riderkick** [comment]
What's your user-agent. Mine banned here. Using mac os user-agent seems not blocked. I just change it.

**Comment by rajlaksh** [comment]
okay.

**Comment by riderkick** [comment]
Haha 😂. Just after I change it, they block it again. 😈

**Comment by rajlaksh** [comment]
it does not works.

**Comment by riderkick** [comment]
My last commit should make it work. I'll release it tomorrow. You can compile it yourself if you eager to use it.

**Comment by abhishekanime98** [comment]
So many comments and The talk is confusing me. So, s en man ga is blocking  specific browsers that you use. Oh man this is confusing. Can some one explain in more simple way ? Please Thanks

**Comment by rajlaksh** [comment]
yes, they're block specific browsers.

**Comment by abhishekanime98** [comment]
Damn they are strict, Thanks for the explanation though :)

**Comment by riderkick** [comment]
Yesterday just after a hour I change the ua, they block it, I change it again, they block it again.
I've a bad feeling, they may watch this project. 👿
But if they keep block the ua, then there will be no one can open their website. 😒

**Comment by riderkick** [comment]
They just block my last ua too. 😂

**Comment by abhishekanime98** [comment]
I have the Same feeling that they keeping a watch on this project

**Comment by radiaku** [comment]
maybe they blocking using some ajax sending cookies to prevent scraper? Some website do this :)

**Comment by riderkick** [comment]
We didn't store cookies(except for some case). we always using fresh new connection.
They block the ua, just try to use ua changer, and try yourself, it's really strict, every char is matter.

**Comment by rajlaksh** [comment]
It stopped Working :cry:

**Comment by rajlaksh** [comment]
Not Working :joy:

**Comment by abhishekanime98** [comment]
doesn't work anymore they put the new thing where you have to put the captcha in and then it will load chapters

**Comment by rajlaksh** [comment]
They're in Under Development Site so what you expect from them.

**Comment by riderkick** [comment]
Those captcha is something hard to follow.
