### ISSUE TITLE
mangafoxfun can't download any picture

### ISSUE THREAD

**Issue by JunkCreek** [riderkick/FMD#1701]
mangafoxfun can't download any picture.

it did found and "downloading" the chapters as folder, but no pics downloaded

here is some of the log

`13:51:32:726 WARNING: TTaskThread, checkforfinish failed=1/1 [Batoto]"Star Martial God Technique [EN]" > "/chapter/1233980"
W
13:51:32:726 WARNING: TTaskThread, download failed. "Star Martial God Technique [EN]" "0160 Ch.160 - Read Online" "/chapter/1233980"
13:51:35:349 WARNING: TTaskThread, checkforfinish failed=1/1 [Batoto]"Star Martial God Technique [EN]" > "/chapter/1236430"
W
13:51:35:349 WARNING: TTaskThread, download failed. "Star Martial God Technique [EN]" "0162 Ch.162 - Read Online" "/chapter/1236430"
13:51:51:460 WARNING: TTaskThread, checkforfinish failed=1/1 [Batoto]"Star Martial God Technique [EN]" > "/chapter/1233980"
W
13:51:51:460 WARNING: TTaskThread, download failed. "Star Martial God Technique [EN]" "0160 Ch.160 - Read Online" "/chapter/1233980"`

it started at least a mounth ago, and I just realizing now, because none of my favorite in mangafoxfun getting any update.

would you please fix the problem, please.

**Comment by 1aam2am1** [comment]
#1647

**Comment by JunkCreek** [comment]
already downloaded a few days ago and i replaced all files to the one within the newest fmd "package"

trying to downloading it again and just extract the exe to if it would solved the problems.

**Comment by JunkCreek** [comment]
still, can't get it work

`15:59:15:889 WARNING: TTaskThread, checkforfinish failed=1/1 [MangaFoxFun]"Azumi" > "/chapter/azumi/chapter-220"
W
15:59:15:889 WARNING: TTaskThread, download failed. "Azumi" "0220 #220 - Vol.30 Chapter 220 Random Attack" "/chapter/azumi/chapter-220"
15:59:18:404 WARNING: TTaskThread, checkforfinish failed=1/1 [MangaFoxFun]"Azumi" > "/chapter/azumi/chapter-221"
W
15:59:18:404 WARNING: TTaskThread, download failed. "Azumi" "0221 #221 - Vol.30 Ch.221" "/chapter/azumi/chapter-221"
15:59:22:391 WARNING: TTaskThread, checkforfinish failed=1/1 [MangaFoxFun]"Azumi" > "/chapter/azumi/chapter-222"
W
15:59:22:391 WARNING: TTaskThread, download failed. "Azumi" "0222 #222 - Vol.30 Ch.222" "/chapter/azumi/chapter-222"
15:59:24:396 WARNING: TTaskThread, checkforfinish failed=1/1 [MangaFoxFun]"Azumi" > "/chapter/azumi/chapter-220"
W
15:59:24:396 WARNING: TTaskThread, download failed. "Azumi" "0220 #220 - Vol.30 Chapter 220 Random Attack" "/chapter/azumi/chapter-220"
15:59:26:538 WARNING: TTaskThread, checkforfinish failed=1/1 [MangaFoxFun]"Azumi" > "/chapter/azumi/chapter-221"
W
15:59:26:538 WARNING: TTaskThread, download failed. "Azumi" "0221 #221 - Vol.30 Ch.221" "/chapter/azumi/chapter-221"
15:59:29:014 WARNING: TTaskThread, checkforfinish failed=1/1 [MangaFoxFun]"Azumi" > "/chapter/azumi/chapter-222"
W
15:59:29:014 WARNING: TTaskThread, download failed. "Azumi" "0222 #222 - Vol.30 Ch.222" "/chapter/azumi/chapter-222"`

**Comment by 1aam2am1** [comment]
Try checking if in online brownser work. And if work try adding task one more time.

**Comment by JunkCreek** [comment]
I have checking via browser and MangaReader apps on android, and it's working normal.

But FMD only downloading chapter title as chapter folder, no images downloaded.

**Comment by ghost** [comment]
https://github.com/riderkick/FMD/issues/1689#issuecomment-469601871

download MangaHubIO.zip
ekstrak to module
and replace
and try again

**Comment by 1aam2am1** [comment]
**Delete and create new task to download chapters**
Because mangafox changed their API the URL of chapters changed and the URL chapter/azumi/chapter-222 don't exist anymore. Now would it be manga/azumi/v30/c222

**Comment by JunkCreek** [comment]
> 
> 
> **Delete and create new task to download chapters**
> Because mangafox changed their API the URL of chapters changed and the URL chapter/azumi/chapter-222 don't exist anymore. Now would it be manga/azumi/v30/c222

should I do that to all my favorited manga on FMD?

**Comment by JunkCreek** [comment]
> 
> 
> **Delete and create new task to download chapters**
> Because mangafox changed their API the URL of chapters changed and the URL chapter/azumi/chapter-222 don't exist anymore. Now would it be manga/azumi/v30/c222

already did, but got the same result.

I downloaded AbidZakaria #1689 (comment) download MangaHubIO.zip and it works.

so the problem is with the lua file

**Comment by JunkCreek** [comment]
> 
> 
> [#1689 (comment)](https://github.com/riderkick/FMD/issues/1689#issuecomment-469601871)
> 
> download MangaHubIO.zip
> ekstrak to module
> and replace
> and try again

thankyou, your lua works great!!!

**Comment by Tmp341** [comment]
> 
> 
> [#1689 (comment)](https://github.com/riderkick/FMD/issues/1689#issuecomment-469601871)
> 
> download MangaHubIO.zip
> ekstrak to module
> and replace
> and try again

You should fork this project, and continue developing.

**Comment by SDXC** [comment]
Find fixes and changes in the newly forked release:
[Free Manga Downloader - 0.9.160.0](https://github.com/fmd-project-team/FMD/releases/tag/0.9.160.0)

**Comment by SDXC** [comment]
@JunkCreek Please close this ticket if everything is okay for you. It's easier for me to check the old tickets in riderkicks repo if the actually fixed/added/etc. issues are closed.

**Comment by JunkCreek** [comment]
> 
> 
> @JunkCreek Please close this ticket if everything is okay for you. It's easier for me to check the old tickets in riderkicks repo if the actually fixed/added/etc. issues are closed.

oke. thx. would love to give your "taking over fmd" project would gonna be work.

so many manga site I see in there.

:) :D
