### ISSUE TITLE
Download - Mangahasu not working

### ISSUE THREAD

**Issue by leoteesh** [riderkick/FMD#1706]
Hi,

Is anyone else having error in downloading from mangahasu from last night? i have checked the website and that works fine?

![image](https://user-images.githubusercontent.com/21075197/54749316-1341c600-4bcc-11e9-9f31-ec4b9780ceeb.png)

Thanks

**Comment by SDXC** [comment]
CloudFlare is blocking FMD. You can add the CF cookies to FMD and it'll work after that. See: https://github.com/riderkick/FMD/wiki/FAQ

**Comment by leoteesh** [comment]
thank you for this - i am a bit confused. this is for mangadex and kissmanga, how would i use this for mangahasu? i did the below but it does not work. could you please advise as what i am doing wrong?
![image](https://user-images.githubusercontent.com/21075197/54881128-91100680-4e44-11e9-8c3d-4b6d3104010e.png)

**Comment by SDXC** [comment]
There are 3 cookie settings, that you should copy and paste correctly into FMD:

![MangaHasuCFWorkaround](https://user-images.githubusercontent.com/5290260/54881728-2914ec80-4e53-11e9-9f06-2dcb85bb55cf.png)

The cookie settings in FMD should be in the following format:

__cfduid=xxxxxxxxxxxxxxxxxxxxxxxx;
cf_clearance=xxxxxxxxxxxxxxxxxxxxxxxxxx;
ci_session=xxxxxxxxxxxxxxxxxx

Please take note to correctly place the '=' and ';' characters!
Also don't forget to "Apply" the settings.

The sessions won't last that long, so you have to repeat this regularily.

**Comment by Tmp341** [comment]
But that ``UpdateDirectoryPagenumber`` isn't correct. For example, it is ``267`` for Kissmanga.

For mangahasu, try ``856``.

**Comment by leoteesh** [comment]
Thanks,
i managed to make it work yesterday but it stopped working again today! 
![image](https://user-images.githubusercontent.com/21075197/54921963-02ac8b00-4eff-11e9-9ef3-d76c359b0e1f.png)
i updated the cookie setting again but still doesn't work
![image](https://user-images.githubusercontent.com/21075197/54922009-1e179600-4eff-11e9-8167-d5fe48fff9a6.png)

**Comment by SDXC** [comment]
That's what I meant by "The sessions won't last that long, so you have to repeat this regularily."

I think after 30 minutes of inactivity CloudFlare re-issues your id and you therefore get new cookies that you, once again, have to put into FMD.

**Comment by leoteesh** [comment]
Thanks - i updated it but unfortunately it still didn't work - will try again.

**Comment by Tmp341** [comment]
Try to do it in one line :
`__cfduid=xxxxxxxxxxxxxxxxxx; cf_clearance=xxxxxxxxxxxxxxxxxxxxxxxxxx; ci_session=xxxxxxxxxxxxxxxxxx`

**Comment by leoteesh** [comment]
tried it but still no luck :(

![image](https://user-images.githubusercontent.com/21075197/54958225-f64f1f00-4f4c-11e9-8068-e5c05d58f91b.png)

__cfduid=ddd9e91cc06abdc5dc65c0da7d5f9ea651526811293;cf_clearance=c6f638a4103513896893214392b90f30aa6bcb41-1553519504-28800-150;ci_session=a51ihtjhjlte02dbmueeco4k7o0ifd7l 
![image](https://user-images.githubusercontent.com/21075197/54958183-d28bd900-4f4c-11e9-8506-0a77ef936c99.png)

**Comment by SDXC** [comment]
That's how I did it right now, which worked:

Using Firefox, go to one of the manga pages on MangaHasu. Enable debugging (F12) and open one of the chapters (for example: http://mangahasu.se/karakai-jouzu-no-takagi-san/vol-99-returning-the-favor-c672942.html )

If CloudFlare pops up, you'll get new cookie settings, which can be found in the debugging tools after the chapter page has been loaded completely (when you finally see the chapter images).

Put the new cookie settings in FMD now and apply. Now you should be able to download again.


-> You only get new cf_clearance or __cfduid after you actually witnessed the CF page, because that is actually more or less the one responsible for giving you new ids.

**Comment by leoteesh** [comment]
Great thanks so much :) 
So guess will have to do this each time i restart FMD

**Comment by SDXC** [comment]
@leoteesh Please close this ticket if everything is okay for you. It's easier for me to check the old tickets in riderkicks repo if the actually fixed/added/etc. issues are closed. A general Cloudflare bypass is planned.

**Comment by leoteesh** [comment]
Hi, still having problems with it but using the above in mean time. 
Thank you for the help
Will close
