### ISSUE TITLE
Cannot Download from Japscan

### ISSUE THREAD

**Issue by megacin** [riderkick/FMD#1708]
Hey

**Comment by SDXC** [comment]
Probably is CloudFlare the problem here as well.

Please try the CF workaround in the FAQ -> https://github.com/riderkick/FMD/wiki/FAQ

If you need more specific help, let me know.

**Comment by SDXC** [comment]
@megacin Cloudflare is actually the problem (JapScan). You can find a Cloudflare workaround for JapScan here:
https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-JapScan

For scan-fr the lua script has to be fixed.

**Comment by SDXC** [comment]
Find fixes and changes in the newly forked release:
[Free Manga Downloader - 0.9.160.0](https://github.com/fmd-project-team/FMD/releases/tag/0.9.160.0)
