### ISSUE TITLE
New version adds nothing to list

### ISSUE THREAD

**Issue by Ruriko** [riderkick/FMD#171]
When the program finishes downloading the the series list from source site it adds nothing to the list. I tried with any other sites it gives the same result.

**Comment by riderkick** [comment]
I don't understand what are you trying to say. 
After download finish, the list is disappear?
Look at download tab(besides manga list tab).
![sshot-1](https://cloud.githubusercontent.com/assets/4972676/12549253/f02f67e6-c396-11e5-8a4a-95ad35efe8cf.jpg)

**Comment by Ruriko** [comment]
Sorry what I meant
![manga](https://cloud.githubusercontent.com/assets/5670857/12549362/98e9750a-c3a8-11e5-9693-527643cdccbe.jpg)
 to say is the Manga List tab shows up empty after trying to update the manga list

**Comment by riderkick** [comment]
When download finish, there is a brief info on updater window, "Unpacking xxx". Does it appear?
Maybe your antivirus block the process.You may need to exclude updater.exe and 7zip,exe on your antivirus.

**Comment by Ruriko** [comment]
oh thanks that did the trick
