### ISSUE TITLE
Cannot download all chapters from Manga-Tr

### ISSUE THREAD

**Issue by aelbuz** [riderkick/FMD#1710]
Hi.

Today I tried to download chapters from manga-tr.com but the site uses Ajax for changing chapter list page.

In example: https://manga-tr.com/manga-kaguya-sama-wa-kokurasetai-tensai-tachi-no-renai-zunousen.html

Manga page contains 3 pages for listing all chapters and they're updating without refreshing or changing the manga page link. So when I try to get the chapters, I only get the first page's chapters from 94 to 142 like this:

![example](https://user-images.githubusercontent.com/21218001/54948711-60b48f00-4f4e-11e9-8f91-d73345f3f7a0.PNG)

Thanks.

**Edit:** Issue reopened and linked on new project page: https://github.com/fmd-project-team/FMD/issues/54

**Comment by SDXC** [comment]
Please bear with it for a bit.
I need some time to get into the source code of FMD.

But I already found the part where and how to fix this, so I'll do my best.

**Comment by aelbuz** [comment]
No problem, good luck!
