### ISSUE TITLE
Komikcast only showing #NA title

### ISSUE THREAD

**Issue by admiralmikan** [riderkick/FMD#1715]
![2019-03-27 22_30_24-Window](https://user-images.githubusercontent.com/17843605/55090034-fe3fc800-50e0-11e9-9f1e-64e32dc73008.jpg)
![2019-03-27 22_37_26-Window](https://user-images.githubusercontent.com/17843605/55090035-fe3fc800-50e0-11e9-887c-5ffc29468db8.jpg)
![2019-03-27 22_41_14-Window](https://user-images.githubusercontent.com/17843605/55090494-c8e7aa00-50e1-11e9-8767-f9209e0d90a8.jpg)

Just found it today. All title only listed as #NA. Is it still related to CF issue or what? I only put __cfuid since that's the only one i know. Should I put another one? Which one?

**Comment by ghost** [comment]
I'm fixing, so wait for me

**Comment by ghost** [comment]
[MangaShiro.zip](https://github.com/riderkick/FMD/files/3016087/MangaShiro.zip)
update 2019-03-28 10:41 AM

first close FMD
extrack and replace with my LUA file
and try again

**Comment by megacin** [comment]
Hey any one here can help me with japscan or scan-fr is not working any more

**Comment by SDXC** [comment]
Find fixes and changes in the newly forked release:
[Free Manga Downloader - 0.9.160.0](https://github.com/fmd-project-team/FMD/releases/tag/0.9.160.0)

**Comment by SDXC** [comment]
@admiralmikan Please close this ticket if everything is okay for you. It's easier for me to check the old tickets in riderkicks repo if the actually fixed/added/etc. issues are closed.
