### ISSUE TITLE
Problem javascript 

### ISSUE THREAD

**Issue by megacin** [riderkick/FMD#1716]
whene i try to downlaod chapitre from japscan and scan-fr

![japsacan](https://user-images.githubusercontent.com/48812724/55252797-010efa00-5254-11e9-9eb3-e3e8cac8d00a.PNG)

**Comment by SDXC** [comment]
@megacin Cloudflare is actually the problem (JapScan). You can find a Cloudflare workaround for JapScan here:
https://github.com/SDXC/FMD/wiki/CF-Workaround:-JapScan

For scan-fr the lua script has to be fixed.

**Comment by megacin** [comment]
can you explain how i do it for scan-fr plz

**Comment by SDXC** [comment]
The lua script for scan-fr does not work anymore and has to be fixed. I will try to fix it and let you know, when it's done.

**Comment by megacin** [comment]
thnx you very mutch just one more question who i will decompile this progreme

**Comment by megacin** [comment]
it is fexit now thnx [http://www.scan-op.com](url) scan vf

**Comment by SDXC** [comment]
Find fixes and changes in the newly forked release:
[Free Manga Downloader - 0.9.160.0](https://github.com/fmd-project-team/FMD/releases/tag/0.9.160.0)

**Comment by SDXC** [comment]
@megacin Please close this ticket if everything is okay for you. It's easier for me to check the old tickets in riderkicks repo if the actually fixed/added/etc. issues are closed.
