### ISSUE TITLE
Can't download tmo 

### ISSUE THREAD

**Issue by megumixd** [riderkick/FMD#1726]
when fmd check my favorite list all the mangas on tmo didnt work they are all on  0 chapter i dont why but i tried two or three times doing the same but nothing happend :c  help please :c

**Comment by ghost** [comment]
Try using new FMD
Please go to https://github.com/fmd-project-team/FMD/releases/tag/0.9.161.0

**Comment by megumixd** [comment]
i did that but is not working maybe is the page there is something in the forum about moving to other host :c maybe is that why i cant download anymore from there :c well thanks i hope it can fix

**Comment by Tmp341** [comment]
If your problem still exist, create an issue here:

https://github.com/fmd-project-team/FMD/issues

**Comment by ralvarador** [comment]
Have you already tried open a TMO URL in your web-browser?
I commited an error: Sort the favorites by server, then check the TMO's items; as consequence of that I got banned, I guess, due to the multiple connections.
I hope the develop team put Mangadex alike parameter - "interval betweens requests" to another servers. That will not avoid the cloudflare protection, nor its banning... but I think it could be help.
BTW: Using the OPERA's VPN fetarure, I could access to TMO's website; no domain change, yet!

**Comment by megumixd** [comment]
well before opening de web the page ask me to check if im not a robot and after that i can enter to the page, everytime i open my web browser, by the way i use chrome so sometime to time i clean the cookies and the history and after opening the page there is no picture :c i will do that i will open an issue maybe is the page or maybe not well thanks for the help

**Comment by ralvarador** [comment]
If cloud flare captcha appears, or the one which "check your browser capabilities" - appears in your web browser, the FMD will not be able to download.
There is a "method", using /copying the TMO'S Cloud Flare Cookies values from your web browser to FMD.
In some FMD's commentaries you can find how to do that. Or, at the new FMD fork - in it's GitHub, appears how to do it (https://github.com/riderkick/FMD/issues/1726#issuecomment-480108177).
Also, you can try "mimicking" the web browser's user agent string in FMD.

**Comment by Tmp341** [comment]
I've explained in here https://github.com/fmd-project-team/FMD/issues/71

**Comment by ralvarador** [comment]
Well, it only left that @megumixd confirm if that works and then close the ticket.
By my side, the explanation goes to my FDM's notes 😎

**Comment by megumixd** [comment]
well i did all what you says but didnt work :c i dont know more what to do i put  all the cloud flare cookies values the user agent and all what you say it was a little bit confused find the user agent xD but  i guess is a failed for me :c so thanks anyway

**Comment by ralvarador** [comment]
It's sad read that.
ATM I am banned so I can't try it by myself (at least "my house" IP).

**Comment by megumixd** [comment]
oh i already fix it i find a way to hide my ip i do not now  if it is legal but it work :c i dont banned me >< thanks for the help guys :D

**Comment by ralvarador** [comment]
Now, please, close the ticket

**Comment by Tmp341** [comment]
You can't hide your IP, since you need it to connect the net. You can only change it, which means your IP is banned too.
