### ISSUE TITLE
Error ar line 1, Pos -9217184:Unexpected EOF encountered

### ISSUE THREAD

**Issue by PanzerIVF** [riderkick/FMD#1728]
I was trying to open FMD and I go this error

![fmd_2019-04-06_12-25-44](https://user-images.githubusercontent.com/22032292/55665357-18f40880-5868-11e9-8de8-b1523a21fea3.png)

Can someone help me what the problem?? And what solution that I need to do?

**Comment by ghost** [comment]
Wrong issue place
Please create issue to https://github.com/fmd-project-team/FMD/issues

**Comment by PanzerIVF** [comment]
Oh ok, thx!
