### ISSUE TITLE
Program exception

### ISSUE THREAD

**Issue by AsukaLangleyfag** [riderkick/FMD#173]
Log:
Program exception!
Application       : Free Manga Downloader
Version           : 0.9.31.2
Product Version   : Win64 Debug
FPC Version       : 3.1.1
LCL Version       : 1.7
Target CPU_OS     : x86_64_Win64
Host Machine      : Windows 7 64-bit
Path              : C:\opt\fmd\fmd.exe
Proccess Id       : 32720
Thread Id         : 27616
Time              : 2016.01.25 18:11:23
Ignored Exception : EImagingError,ERegExpr
Sender Class      : TDownloadThread
Exception Class   : EAccessViolation
Message           : Access violation
  In TDownloadThread.Execute : CS_DOWNLOAD
  Website : Batoto
  URL     : /reader#22407b175590f8a9
  Title   : Monster
  Chapter : Vol.04 Ch.25 An Abandoned Woman [Mangascreener]

Exception Address : $000000010000A23A
  $000000010000A2C2
  $00000001003A5FCF line 337 of ../baseunits/uDownloadsManager.pas
  $000000010006454D
  $0000000100003346 line 65 of md.lpr
  $00000001000146A7
  $00000000771959ED
  $00000000773CB831
Happens every time. But chapter 25 looks downloaded perfectly (all 26 pages).

**Comment by riderkick** [comment]
I don't have this problem.
I don't have any idea what causing this. If you look at the source this line just doing download progress update. "EAccessViolation" only can happen if TDownloadManager doesn't exist in the memory. That mean the whole program should be crash.

**Comment by AsukaLangleyfag** [comment]
I don't have this on clean setup either. Also strange thing is this exception. It should crash the program, but it doesn't! You just click Continue and everything fine.
