### ISSUE TITLE
Mangas with names too long produce chapter overwritten files

### ISSUE THREAD

**Issue by typhoe** [riderkick/FMD#1738]
Hi,

on manga tittles too long, FMD won't write correctly the chapters (they overwrite).

Ex: 
https://mangadex.org/title/36763/the-labyrinth-raids-of-the-ultimate-tank-the-tank-possessing-a-rare-9-999-endurance-skill-was-expelled-from-the-hero-party

I use Folder = %MANGA%
And Chapter = %MANGA% - %CHAPTER%

But in this case, the name is shorted as:
The Labyrinth Raids of the Ultimate Tank ~The Tank Possessing a Rare 9,999 Endurance Skill was.cbz
(so %MANGA% is truncated and %CHAPTER% is not even used, thus the chapter files are not unique and are overwritten)

Would it be possible to define a limit for %MANGA% field to be sure %CHAPTER% could be use?

Thank you

**Comment by Slasar41** [comment]
Hi,
Please open the issue on the new fork release and use this version:
https://github.com/fmd-project-team/FMD

**Comment by typhoe** [comment]
Hi, 

oh thank you I didn't notice there was a fork of the project.

First I'll try the new release to see if the problem is still there and then, if necessary I'll open a new issue.

Regards
