### ISSUE TITLE
EGScans DB is outdated and conflicts with updated manga lists

### ISSUE THREAD

**Issue by Weischbier** [riderkick/FMD#174]
There seems to be a huge reconstruction on EGScans site.
If we take the default DB that FMD offers it is pretty outdated and when you update the list you have almost every entry as a double in it.

http://prntscr.com/9vtoam

**Comment by riderkick** [comment]
I barely maintain those prebuild manga list. So, don't rely on it. Build your own from scratch.

**Comment by Weischbier** [comment]
Wouldn't it be better to remove this whole database download thing and instead run a scan on the sites and populate from there?

**Comment by riderkick** [comment]
Populating the list from the sites will takes hours if not days.
