### ISSUE TITLE
request for new wesbsite

### ISSUE THREAD

**Issue by Kayizoku** [riderkick/FMD#1746]
Hi.

Would it be possible to add support for "https://toonily.com/"?

**Comment by Slasar41** [comment]
It's already supported in the new FMD https://github.com/fmd-project-team/FMD/issues/142
Use that version: https://github.com/fmd-project-team/FMD/releases/tag/0.9.164.0

**Comment by Kayizoku** [comment]
WOW! I didn't know there existed another version. 

But, how do I import my settings and favorites? I tried using the import method and setting the path to the path tom y old FMD folder but it didn't work, any solutions?

Thank you! ^^

**Comment by Slasar41** [comment]
Yes, because this version seems to be dead.

Follow these: https://github.com/fmd-project-team/FMD/wiki#useful-informations

**Comment by Kayizoku** [comment]
Thank you, I was able to import my favorites. It would not be fun to do over so many of them.

Much appreciated! ^^

**Comment by Kayizoku** [comment]
Oh, one more thing there are some websites data I am unable to download from the server.

How can I do this manually?

**Comment by Slasar41** [comment]
Did you mean there's some manga that not in the website's database even if you already click `Update manga list`?

**Comment by Kayizoku** [comment]
Yes.

I could update for Toonily for instance, but there seem to be too few mangas so I am sure I am missing a handful of them.

**Comment by Kayizoku** [comment]
Never mind, the amount of manga seems to correspond to the amount on the website.

All of my issues are solved. 

Thank you for your snappy replies and help! ^^

**Comment by Slasar41** [comment]
No problem. :D
