### ISSUE TITLE
ReadMe file error fmd_0.9.31.3_Win64.7z

### ISSUE THREAD

**Issue by StormJumper** [riderkick/FMD#175]
Bug ReadMe file error when FMD launched.

Unhandled exception!
Application       : Free Manga Downloader
Version           : 0.9.31.3
Product Version   : Win64 Debug
FPC Version       : 3.1.1
LCL Version       : 1.7
Target CPU_OS     : x86_64_Win64
Host Machine      : Windows 7 64-bit
Path              : E:\fmd_0.9.31.3_Win64\fmd.exe
Proccess Id       : 6812
Thread Id         : 4496
Time              : 1/28/2016 6:12:00
Ignored Exception : EImagingError,ERegExpr
Exception Class   : EFCreateError
Message           : Unable to create file "E:\fmd_0.9.31.3_Win64\readme.rtf"
Exception Address : $000000010005C7BA
  $000000010005C6B2
  $0000000100063494
  $0000000100045B7C line 1727 of forms/frmMain.pas
  $0000000100041BA0 line 995 of forms/frmMain.pas
  $000000010001FC61
  $000000010001E3B1
  $00000001000244D7
  $000000010002B637
  $0000000100003300 line 62 of md.lpr
  $0000000100003346 line 65 of md.lpr
  $0000000100018293
  $0000000100018D36
  $00000000772559ED
  $000000007738B831

**Comment by riderkick** [comment]
Probably readme.rtf was opened by other application with share deny write flag.

**Comment by StormJumper** [comment]
That's odd never had that happen before. But it was for the first time when I started FMD 0.9.31.3 that it logged that error. But I haven't seen it do it again.
