### ISSUE TITLE
can't download from Tmofans

### ISSUE THREAD

**Issue by horacio881** [riderkick/FMD#1753]
Today suddenly the whole manga of tmofans.com cannot be downloaded. Favorite update check works well, also see manga information and add new manga work without problems.
I just can't download anything.

**Comment by akir42019** [comment]
new FMD fork: https://github.com/fmd-project-team/FMD

**Comment by horacio881** [comment]
> new FMD fork: https://github.com/fmd-project-team/FMD

I downloaded the latest version and it still doesn't work.

**Comment by SDXC** [comment]
has been fixed now.

**Comment by horacio881** [comment]
Thanks for fixing it.
