### ISSUE TITLE
Add ShoujoSense

### ISSUE THREAD

**Issue by Weischbier** [riderkick/FMD#177]
Add ShoujoSense scanlator.
http://shoujosense.com/index.php?board=5.0

**Comment by riderkick** [comment]
Aren't they already available in http://reader.shoujosense.org ?

**Comment by Weischbier** [comment]
Oh you put that under the English tab. Should move that to the scanlator group :P
I never bothered looking there. My bad.

**Comment by riderkick** [comment]
Just create an issue here. You can read the source if you want to know how its work.

**Comment by riderkick** [comment]
https://github.com/riderkick/FMD/commit/59a3b9bc76772b01167093841de17568fd2062be
