### ISSUE TITLE
Porncomix changed their URL

### ISSUE THREAD

**Issue by SL-Gundam** [riderkick/FMD#1778]
Hi

http://www.porncomix.info/ changed their URL to https://bestporncomix.com/

They also changed the URL structure
https://www.porncomix.info/[title]/ has become https://bestporncomix.com/gallery/[title]/

**Comment by Slasar41** [comment]
Please use the fork of FMD which is being actively developed: https://github.com/fmd-project-team/FMD
Make an issue on there.
