### ISSUE TITLE
Champion Scans to Project Time

### ISSUE THREAD

**Issue by Riztard** [riderkick/FMD#1784]
http://reader.championscans.com/series/exterminator/
change to
https://read.ptscans.com/series/exterminator/

**Comment by Slasar41** [comment]
Has been changed on the fork of FMD https://github.com/fmd-project-team/FMD/commit/70db8299638966df003e75481a58af6035ece721
Please use this version: https://github.com/fmd-project-team/FMD/releases

**Comment by Riztard** [comment]
> Has been changed on the fork of FMD [fmd-project-team@70db829](https://github.com/fmd-project-team/FMD/commit/70db8299638966df003e75481a58af6035ece721)
> Please use this version: https://github.com/fmd-project-team/FMD/releases

oh so thats why i didnt get update. thx
