### ISSUE TITLE
Cannot download from kissmanga

### ISSUE THREAD

**Issue by AravindPalli** [riderkick/FMD#1792]
its not showing chapters 
its not loadind even after adding cookies 
so, can you please send me a file which is properly working
![1](https://user-images.githubusercontent.com/57879642/69210036-792d8580-0b7f-11ea-84ea-c9a08f38f6e9.jpeg)

**Comment by Slasar41** [comment]
Please use the new FMD fork.
https://github.com/fmd-project-team/FMD

**Comment by AravindPalli** [comment]
> Please use the new FMD fork.
> https://github.com/fmd-project-team/FMD

Thank you very much. It's now working.
