### ISSUE TITLE
Requesting favorite editor

### ISSUE THREAD

**Issue by azraei97** [riderkick/FMD#1793]
Requesting feature:

    Ability to export / backup "Favorites"
    Ability to edit "Favorites" in batch or directly from that backup "Favorites" aka Favorites Editor.

I was trying to change disk drive for all my current "Favorites" but lazy to "right click" and change them one by one for more then 300manga. So I trying to edit it directly from "Favorites" data using notepad. I changed location from C:\Manga into D:\Manga using function in notepad "Replace All" word that match to what we want in 1 click. Then I save it. When I test open FMD, it can't read that modified "Favorites".

Hope you consider to make this features in future update.

**Comment by Slasar41** [comment]
You can open the database using DB Browser for SQLite and change all the drive letter on that program.
Fortunately, the new FMD fork already implemented changing multiple favorites on FMD itself.
https://github.com/fmd-project-team/FMD/commit/fbb868ace891fe32522a69c5eb0a4d207afa561f

**Comment by azraei97** [comment]
I already use latest FMD. Can someone teach me how to change multiple favorites directly from FMD?

**Comment by Slasar41** [comment]
Move the manga you want to change from C:\Manga to D:\Manga
Select the titles you want to change then right click -> Change "Save to"
Point it to the new path (D:\Manga)

**Comment by azraei97** [comment]
How to select multiple of it? Sorry noob question

**Comment by Slasar41** [comment]
You can multiple select it by holding Ctrl+left click for manual selection or Shift+left click for a range selection or Ctrl+A for select all.

**Comment by azraei97** [comment]
It's works.
Thanks for help. 😊

**Comment by Slasar41** [comment]
Great.
You can close this issue.
