### ISSUE TITLE
Kissmanga under maintenance??

### ISSUE THREAD

**Issue by echoPN** [riderkick/FMD#1795]
Is it just me, or Kissmanga really down for maintenance???

**Comment by Slasar41** [comment]
What do you mean?
Are you unable to access their website from browser?

**Comment by echoPN** [comment]
that's too...
but the most important is that I can't update my Favorite list because most of them are from Kissmanga...

**Comment by Slasar41** [comment]
There's a trick if you want able to access their website again.
Do you already use the new FMD fork?

**Comment by echoPN** [comment]
yes, I do...
I update it not long ago...

**Comment by Slasar41** [comment]
To be able to access their website again, you must clear the cookies for KissManga in the browser settings. Next, install Tampermonkey extension then install [this script](https://greasyfork.org/id/scripts/4900-kissanime-anti-adblock-blocker) OR disable your Adblock when accessing their website.

You should open this issue on the FMD fork...
Few days ago cloudflare change their mechanism resulting FMD can't access some manga website that have cloudflare.
For workaround, you can use this: https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-JapScan

**Comment by echoPN** [comment]
It's work...
Thanks you...
