### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by abhishekanime98** [riderkick/FMD#18]
What happened to Senmanga for Raw chapters ? Is removed from FMD foreever or something ? Please add it if you can Thanks for FMD or updating it

**Comment by riderkick** [comment]
It seems senmanga raw website have been changed lately. Yesterday I can't access it, it's return "You're not authorized to access this Page.". As mentioned on this issue https://github.com/riderkick/FMD/issues/17
Today I can open raw.senmanga.com but still some page say "not authorized", and redirected to www.senmanga.com Probably they change something on their website. Their page source seems changed too. I'll add it later when their website ready.

**Comment by riderkick** [comment]
For a question like this you comment directly on the related commit.
