### ISSUE TITLE
Exhentai list not downloading from server

### ISSUE THREAD

**Issue by TheKrister2** [riderkick/FMD#180]
When I updated to the new update 0.9.32.2 today, I noticed Exhentai, so I tried to add it but I cab't download the list from the server. The file is not found, 404 file not found basically.
Just wanted to notify you.

**Comment by riderkick** [comment]
As you can see there is no prebuild manga list for exhentai at the moment.
I move the data files to https://sourceforge.net/projects/newfmd/files/data/
For anyone who want to help me to maintain the manga list can drop me a message.
Exhentai had a very long list, which take a long time to build the list. Also there is a limit per IP, and we will get banned if there is to much request per day.
FYI, it took me almost a month to build e-hentai list.

Actually you don't really need manga list at all. Just drag n drop the link you want to drop box or directly to download list. It also support multiple links. So just select your interest and drag it to download list or drop box and release. It will automatically load the links, if it's supported of course.
You can also add it to favorites by doing the same to favorite list.
I strongly recommended this way. So we can keep visit their website. They need out visit to keep their website alive, with ads of course.

**Comment by TheKrister2** [comment]
I see, thank you for the quick reply.
