### ISSUE TITLE
MyReadingManga.info does not work.

### ISSUE THREAD

**Issue by Reyeselda95** [riderkick/FMD#1800]
From a time till now, i cannot download anything from the site. When the links load, there is no name and the download fails.
Can you check this please?
Thanks for your work.
Regards.

**Comment by Slasar41** [comment]
Please use the new FMD fork: https://github.com/fmd-project-team/FMD
If the issue persist, create an issue on there.

**Comment by Reyeselda95** [comment]
It works propperly now.
Thanks.
