### ISSUE TITLE
Downloading from Manga Rock

### ISSUE THREAD

**Issue by Elsorandril** [riderkick/FMD#1803]
Hello
As shown in the picture I can't download from manga rock since three to four days ago.
Manually downloading them doesn't work either.
![pb manga rock](https://user-images.githubusercontent.com/59393094/72224784-7f881e80-357e-11ea-8434-654ee09f1f79.png)
I have no issues to download the list of chapters and the favorite checker is working too.
My version is up to date. And I also tried to reinstall the last version but I was confronted to the same issue.
Thanks in advance for the help.

**Comment by Slasar41** [comment]
You should use the new FMD fork.
It seems you can only read it on their app.
https://github.com/fmd-project-team/FMD/issues/716

**Comment by Elsorandril** [comment]
Thank you for your quick answer.
Because it seem that nothing more can be done for now I'll be marking this issue as closed.
