### ISSUE TITLE
[0.9.32.2] Unable to process entries with very long titles

### ISSUE THREAD

**Issue by reyaz006** [riderkick/FMD#181]
Trying to process some manga from russian portal. The URL reported by FMD:
<pre>http://ru.ninemanga.com/manga/%D0%9E%D1%82%D1%87%D0%B5%D1%82%20%D0%BE%20%D0%B7%D0%B0%D0%BC%D0%B5%D1%81%D1%82%D0%B8%D1%82%D0%B5%D0%BB%D0%B5%20%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D1%83%D1%8E%D1%89%D0%B5%D0%B3%D0%BE%20%D0%A8%D0%B8%D0%BD%D1%81%D0%B5%D0%BD%D0%B3%D1%83%D0%BC%D0%B8%2</pre>
It can't display any info about it and even [Read Online] button doesn't work.

Actual working URL:
<pre>http://ru.ninemanga.com/manga/%D0%9E%D1%82%D1%87%D0%B5%D1%82%20%D0%BE%20%D0%B7%D0%B0%D0%BC%D0%B5%D1%81%D1%82%D0%B8%D1%82%D0%B5%D0%BB%D0%B5%20%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D1%83%D1%8E%D1%89%D0%B5%D0%B3%D0%BE%20%D0%A8%D0%B8%D0%BD%D1%81%D0%B5%D0%BD%D0%B3%D1%83%D0%BC%D0%B8%20%D0%A5%D0%B8%D0%B4%D0%B6%D0%B8%D0%BA%D0%B0%D1%82%D0%B5%20%D0%A2%D0%BE%D1%88%D0%B8%D1%80%D0%BE%20%28%D0%B8%D0%B7%20%D0%B0%D0%BD%D1%82%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D0%B8%20Hijikata%20Kurogane%20no%20Onigami%29.html</pre>

It seem to me that there is a limit of 256 symbols for URL file path.

**Comment by riderkick** [comment]
I don't have any problem.
![sshot-2016-02-04- 23-04-43](https://cloud.githubusercontent.com/assets/4972676/12818921/c33193c2-cb93-11e5-949c-64f7bf472529.jpg)
