### ISSUE TITLE
fmd_0.9.32.2_Win64

### ISSUE THREAD

**Issue by StormJumper** [riderkick/FMD#182]
First problem in fmd_0.9.32.2_Win64 log.
[fmd_0.9.32.2_Win64.zip](https://github.com/riderkick/FMD/files/117095/fmd_0.9.32.2_Win64.zip)

**Comment by riderkick** [comment]
How to reproduce the problem?

**Comment by StormJumper** [comment]
It happened when I just let FMD running where it checks every 60 min is when I saw that the error.

**Comment by riderkick** [comment]
I can't fix anything if I can't reproduce the problem.

**Comment by StormJumper** [comment]
Ok, I let it run and the Manga that caused the glitch didn't happen again nor did any other manga favorites cause the same error.

**Comment by StormJumper** [comment]
Updating to 0.9.32.3 and will see what happens.
