### ISSUE TITLE
Config initialization problem in 0.9.32.3

### ISSUE THREAD

**Issue by StormJumper** [riderkick/FMD#184]
When running FMD the first time using previous data and folder migrated. I got config initialization problem in 0.9.32.3.
[fmd 0.9.32.3.zip](https://github.com/riderkick/FMD/files/119041/fmd.0.9.32.3.zip)
2.3.

**Comment by riderkick** [comment]
Your config.ini is locked. or there is not enough permission.
It can be caused by other app that used that file. or antivirus.
