### ISSUE TITLE
Can't download from NHentai

### ISSUE THREAD

**Issue by ILikeCrayons** [riderkick/FMD#1862]
Every time I try to open a link to nhentai.net, whether it's clicking one randomly or inputting my own, it requests I turn on JavaScript and reload the page. This does not happen for any other site
![Screenshot 2022-05-01 202523](https://user-images.githubusercontent.com/104742089/166171048-91087031-4476-4fa6-8afe-42f115613023.png)

**Comment by ILikeCrayons** [comment]
It seems to have fixed itself

**Comment by purimasdev** [comment]
mine still have the same problem, what do you do to fix that?

**Comment by ILikeCrayons** [comment]
Honestly I just left it until I was able to visit nhentai without seeing the cloudflare protection screen. I think FMD has issues with getting past it, so unless a workaround is implemented, I believe the only way to fix it at least when this is the issue, is to just wait until the period that they don't have this protection buffer running
![image](https://user-images.githubusercontent.com/104742089/176205808-c7492ab3-4c98-40bd-8662-060a00472dc3.png)

**Comment by ILikeCrayons** [comment]
@purimasdev Hello, I found a workaround for this issue rather than just waiting for whenever theyre not using cf. This link tells you how to do it. It's using FMD2 but it should still work for FMD1
https://github.com/dazedcat19/FMD2/issues/996
