### ISSUE TITLE
Unable to download from AcademyVN

### ISSUE THREAD

**Issue by blue-lightning** [riderkick/FMD#188]
FMD can't download any manga except one-shot from [AcademyVN](http://truyen.academyvn.com/manga/all).

**Comment by riderkick** [comment]
I don't have any problem with non-oneshot.

**Comment by blue-lightning** [comment]
Sorry, looks like it's a problem with manga containing _!_ in their title. Try this [one](http://truyen.academyvn.com/manga/21/himouto!-umaru-chan).
