### ISSUE TITLE
data base was disappear

### ISSUE THREAD

**Issue by augustinlibert** [riderkick/FMD#189]
Hi, thanks for the great app, but I wondering what happen that all the data base in data folder was gone by itself when I click Download all list from server at once ever since I upgraded from 0.9.32.2 to 0.9.33.0, even I roll back to older version still can't . 

When I go to data folder, I can see every single zip file downloaded/unzip and disappear, end of update I see nothing there and I could get any manga list there, where can I download the data base at once in such case? I just found your post in sourceforge, the data file can only be downloaded individual. :)

**Comment by riderkick** [comment]
Maybe there is not enough permission to write in your fmd folder. Its using 7z to extract to data folder, check your antivirus too.
I believe you can bulk download using download manager. In firefox you can use flashgot to get the list, and use wget to download.

**Comment by augustinlibert** [comment]
I just reformatted my com and I am downloading it without any antivirus installed, so strange, 
anyway thanks, I will try using firefox to download those data file then. many thanks for your prompt reply... :)
