### ISSUE TITLE
Eat manga

### ISSUE THREAD

**Issue by radiaku** [riderkick/FMD#19]
Hello 
I want to report 2 bug on eatmanga.com

fmd  0.9.9.0

First
there is no cover in manga infos
![2015-05-06_095103](https://cloud.githubusercontent.com/assets/5983350/7486832/7ee6c78c-f3d5-11e4-9190-c182cbf14db1.png)

Second
When all chapter downloaded ( succeeds ) but in fmd  said its ***failed***.  in this case http://eatmanga.com/Manga-Scan/Combat-Continent/ ) from chapter 25 - 30.
Tried one chapter instead, same result. download is success but in status is failed.

![2015-05-06_095627](https://cloud.githubusercontent.com/assets/5983350/7486845/2eb7a186-f3d6-11e4-8810-06c8c566fb6b.png)

thanks :)

**Comment by riderkick** [comment]
Its failed because some chapter/page failed to download.

**Comment by riderkick** [comment]
Are you sure there is manga cover on their website? Because I don't see it, nor author, artist, etc. It's just plain title and chapter list.

**Comment by radiaku** [comment]
Ah yeah,sorri my mistake. Its doesnt have cover.

And yes, in for each chapter I found that sometimes/always ( last image always failed  to download ).

**Comment by riderkick** [comment]
This commit should fix this issue https://github.com/riderkick/FMD/commit/f9852e90fa1b72c08d4d54378c06e74a7bb07fa5

Is there any limitation on eatmanga? I found out on downloadmanager eatmanga only permit 1 connection at a time.

**Comment by riderkick** [comment]
I remove the limitation with this commit https://github.com/riderkick/FMD/commit/79bc1efd7e862f0673c4f8798230cd21066f0d16
I'll try to download bunch of title and see if there is limitation from eatmanga server.

**Comment by riderkick** [comment]
It seems there is no limitation whatsoever.

**Comment by radiaku** [comment]
Yeah, same here . I have found no limitation. 

[OOT]
in .net i user profiler from redgate to identified memory leak and thread safety. How do you do this in fpc?

**Comment by riderkick** [comment]
I'm using heaptrc.
