### ISSUE TITLE
wrong languages downloading after update 

### ISSUE THREAD

**Issue by corpse69** [riderkick/FMD#190]
its picking up chapters in other languages on batoto after recent FMD update  ive been having to sort through them carefully

**Comment by corpse69** [comment]
aswell as a majority of downloads failing from batoto

**Comment by Ianunaut** [comment]
The most recent update had the "Show all language" option checked in the menu Options > Misc > Batoto. Uncheck it to only get English-language chapters back.

I haven't noticed failing downloads from Batoto as of yesterday.

**Comment by corpse69** [comment]
that's one issue fixed many thanks.

yeah i dont know whats up with DL's failing its only batoto though

**Comment by blue-lightning** [comment]
have you put your batoto account in FMD ?

**Comment by corpse69** [comment]
yes of-course, the downloads are failing instantly or after a few pages
