### ISSUE TITLE
failed to download because too long dir?

### ISSUE THREAD

**Issue by ariffinsetya** [riderkick/FMD#191]
after last update, somehow i cant download manga to existing directory, it used to be fine but when i check my favorite and download new chapters it shows errors and too long dir? alert shows up.

my old directory : (perfectly fine)
![err1](https://cloud.githubusercontent.com/assets/10893171/13067089/3a69c87e-d49f-11e5-9048-21d28e4b411d.PNG)
after update then download favorite manga chapters like usual :
![err2](https://cloud.githubusercontent.com/assets/10893171/13067105/65bbc1bc-d49f-11e5-8c7e-bfdfb05728ad.PNG)

some manga can be downloaded fine if they have short name (ex : Helck)
and if i change my directory to shorter directory (ex : D:/) then it works....
though it's just weird that it used to be fine but now too long dir name? even though i set my generated chapter folder name to be just %Numbering%
Hopefully can be fixed soon

**Comment by riderkick** [comment]
please provide your works.ini

**Comment by ariffinsetya** [comment]
this is my works.ini
[works.zip](https://github.com/riderkick/FMD/files/133818/works.zip)

**Comment by riderkick** [comment]
It working fine here. I need to know your output directory when it fails.
That alert doesn't always mean the directory path is too long. It just indicate the directory is failed to create. It can be permission issue, invalid character, invalid drive, or something else that prevent fmd to access this directory.
https://github.com/riderkick/FMD/blob/master/baseunits/uDownloadsManager.pas#L1305

**Comment by ariffinsetya** [comment]
thank you for the respond, now that you mention permission issue, i tried to run fmd with administrator privilege and it works... though i never run it as administrator before though...
but thanks for your help, this is simply my favorite manga downloader compared to others.....
