### ISSUE TITLE
Request Linux binary

### ISSUE THREAD

**Issue by Matoro** [riderkick/FMD#195]
So I've been using FMD for upwards of a year now and it has been a fantastic experience.  Unfortunately, I recently switched to a Linux system and have been unable to find a manga downloader & tracker with all of the same great features as FMD.  In particular, there is not a single program that can download from the new mangatraders.org site.  Therefore I would be very grateful if you could make a quick build for Linux OS.  I am not looking for a complete development branch, just a single binary release or perhaps, say, every 0.x.0.0 or so.  It doesn't even have to have any of the more complicated features like notifications--just be able to check for new chapters and download (for the most part, I only use MangaTraders anyway).

I did try compiling myself and was able to get all dependencies loaded in, however I was unable to figure out how to change the build target to a Linux system, plus I was not sure if there was anything else I would have needed to do.

Thank you for all your hard work on this project.

**Comment by riderkick** [comment]
In lazarus. project > project options > compiler options > config and target

**Comment by Matoro** [comment]
Would you be kind enough to compile and upload a binary somewhere?

**Comment by riderkick** [comment]
Like I said, I don't have linux system right now.
Can you try to run it with Wine?

**Comment by Matoro** [comment]
It does work via Wine, but with terrible formatting and general difficulty.  Is it not possible to simply compile without testing it and upload the resulting binary?

**Comment by riderkick** [comment]
Like I said, I don't have linux. It need to be compiled on linux.
