### ISSUE TITLE
Cant download manga from Tsumino

### ISSUE THREAD

**Issue by Hexaf** [riderkick/FMD#197]
I can update manga list but I cant download manga.

**Comment by riderkick** [comment]
It has captcha to read download, you need to add the cookie to advanced.ini.
Open with your browser, read something, verify the captcha, copy the cookie to advanced.ini

**Comment by Hexaf** [comment]
how I should copy the cookie? I try copy the cookie from google browser
"chrome://settings/cookies" and I copy-paste this
Name: Tsumino_Web
Content: xn45ov0juwzx3jmpzqoizuig
Domain: www.tsumino.com
Path: /
Send for: Any kind of connection
Accessible to script: No (HttpOnly)
Created: Sunday, February 28, 2016 at 4:39:39 PM
Expires: When the browsing session ends

to advanced_temp.ini. but it doesnt work. Maybe I was wrong. Please help.
Best Regards

**Comment by blue-lightning** [comment]
Check #114 comments.

**Comment by Hexaf** [comment]
1. *When I inspect element, i cant find cookies:sessionid just like what
   you did **https://cloud.githubusercontent.com/assets/4972676/11413242/c5643f40-9421-11e5-90b9-98c7feca66d6.jpg
   <https://cloud.githubusercontent.com/assets/4972676/11413242/c5643f40-9421-11e5-90b9-98c7feca66d6.jpg>*
   2. *but I found like this, what should I copy for the script?*
   3. cookie:
   __cfduid=d43d1c8502df04ba8479fba9883b231851456592852;
   Tsumino_Web=xn45ov0juwzx3jmpzqoizuig

**Comment by riderkick** [comment]
The important part is `Tsumino_Web=xxx`.
The easiest way is to open developer tools/inspect element on your browser after you verify the captcha (ctrl+shift+i). can be any page on tsumino.
Open tab network, if it's empty click reload. select the first row, you will see request header with its cookie. copy all of them, or just the important part.
![sshot-2016-02-29- 06-55-41](https://cloud.githubusercontent.com/assets/4972676/13382583/10665a92-deb3-11e5-859a-852722d80c13.jpg)

Rename advanced_temp.ini to advanced.ini. Add `[Cookies]` section if it's not exist. And put the cookie in this section with standard ini file format `Key=Value`, or in this regard `Website=Cookie`
```
[Cookies]
Tsumino=Tsumino_Web=xxx
```
