### ISSUE TITLE
Submanga list isn't working 

### ISSUE THREAD

**Issue by VulkHead** [riderkick/FMD#2]
I tried to download from submanga and is not working at all, I clicked on whatever manga I wanted to download but it doesn't come out those chapters they don't even load.. Every manga downloader that I know have the same issue DomDomsoft, HakuNeku, ect.. Please Fix.

**Comment by riderkick** [comment]
Try version 0.9.8.3.
Look at this commit https://github.com/riderkick/FMD/commit/267dcb70f1bbd057909de9ab934bb4472760f62f
