### ISSUE TITLE
FMD only shows the latest chapter for some manga

### ISSUE THREAD

**Issue by Galebourn** [riderkick/FMD#200]
Instead of showing me the entire chapter list, some manga on Madokami or Batoto only list the latest chapter. Also, the options are set to English, but FMD always lists foreign languages.
Screenshot: http://i.imgur.com/X5Ht5nD.jpg
Is there any way to fix this?

**Comment by blue-lightning** [comment]
List chapters: #139 
Foreign language: FMD>Misc>Show all language.

**Comment by Galebourn** [comment]
Welp, the reason was that the Batoto login account was wrong.
