### ISSUE TITLE
pages mixed up when saving as .pdf

### ISSUE THREAD

**Issue by taishidaioh** [riderkick/FMD#201]
Hi!
When I download any manga and choose the option to save them as pdf, the pages seem to get mixed up in a more or less random order.

Does anyone else have this issue or am I doing something wrong?

Regards
tai

**Comment by riderkick** [comment]
How if you save it without compression? does it still mixed up?
What is the website, title and chapter, so we can test it.

**Comment by Matoro** [comment]
I can vouch for this issue.  The specific chapters I first noticed on were the first ones downloaded with the most recent release, which was Hidamari Sketch from MangaGo.  I've been through about 10 chapters and the pages are randomized.  I saved without compression, i.e. with a value of 100 for the PDF compression level setting.

**Comment by riderkick** [comment]
Sorry, I mean without saving to pdf. It can be website specific.

**Comment by riderkick** [comment]
Please be more specific. website, title and chapter. I can't reproduce the issue.
