### ISSUE TITLE
cant download on mangapark and gos

### ISSUE THREAD

**Issue by alvarexoz** [riderkick/FMD#204]
excuse me, i have problem to download in mangapark and gos. The updater (on server) is still work, but not for download (dont have check box). I dont know if it has bug or not, but i'm looking forward for your work later. Please fix it, they are my fav site.

**Comment by riderkick** [comment]
Both website working fine here.

**Comment by alvarexoz** [comment]
i re-checked again on both, but only mangapark worked fine. So, the remain
is gos. please, re-check again

2016-03-08 1:05 GMT+07:00 riderkick <notifications@github.com>:

**Comment by riderkick** [comment]
gos working fine here.
![sshot-2016-03-11- 12-16-28](https://cloud.githubusercontent.com/assets/4972676/13693172/334a1336-e783-11e5-9ee5-121d39adc083.jpg)

**Comment by alvarexoz** [comment]
well, i still have those problem.

​clearly, no checkbox on it.

2016-03-11 11:17 GMT+07:00 riderkick <notifications@github.com>:

**Comment by riderkick** [comment]
Can you open it with your browser?
Maybe you're banned or there is some sort of ban based on country or ip.
![sshot-2016-04-03- 13-31-21](https://cloud.githubusercontent.com/assets/4972676/14230946/abde29c0-f9a0-11e5-889d-4f7809358991.jpg)

**Comment by alvarexoz** [comment]
Ban?
well, i dont think so. Beside them, some which have problem are Eggscans,
dynastyscans, mangainn. The rest worked fine. i can access those sites
(include all site from my list) in browser.
maybe, you can expect other reply to solve the problem.
P.S : i wonder if you are indonesian, do all operator have "Mercusuar" and
"Internet Positif"?

2016-04-03 12:33 GMT+07:00 riderkick <notifications@github.com>:

**Comment by riderkick** [comment]
Run updater.exe from command prompt from fmd directory
`updater.exe -a http://mangapark.me/manga/aoi-hikaru-ga-chikyuu-ni-itakoro` 
Look for `aoi-hikaru-ga-chikyuu-ni-itakoro` file in fmd directory, change the extension to .txt and post it here.

Internet positif is must for ISP in Indonesia. Usually changing dns will do the trick. But some ISP even intercept the dns query. So vpn is the only solution.

**Comment by alvarexoz** [comment]
hello, sorry to disturb you.
i got problem as title said or my comments above.
Those list which i cant : mangapark, gos, yomanga, mangainn, eyesonmanga. (Many broken sites since i updated from my last comment )

Hope you fix the bug or root of this problem. I'm counting on you, sir. Thanks before.
