### ISSUE TITLE
petition of  add another site of spanish manga

### ISSUE THREAD

**Issue by C0RPS3** [riderkick/FMD#206]
if it's possible you can add this site http://www.tumangaonline.com to the spanish sites in fmd
this site heve mangas that others sites doesn't have, furthermore the quality it's much better.

i have already translated to spanish, but doing a proofread in text (some are very long and don't fit in the UI) whem they are done if you like i can give it to you for share in the package.

**Comment by riderkick** [comment]
Do they even have online read?
I just found the download link to file hosting, even with ppc url shortener. Or I miss something.

**Comment by C0RPS3** [comment]
yes they have it, i'll try to explain...

example: go to this manga in specific
http://www.tumangaonline.com/listado-mangas/manga/9008/Fate+-+stay+night+Comic+Battle

in the blue rectangle says Cápitulo (chapter) you must choose a chapter( in this example just have one chapter), then click on Leer (read), then appear a pop up (i guess is that you mention, with a download link and other stuff), click on Leer again, now you are in the viewer
example:
http://www.tumangaonline.com/visor/Fate+-+stay+night+Comic+Battle/9008/1/10/1


all manga titles are stored here:
http://www.tumangaonline.com/listado-mangas

**Comment by riderkick** [comment]
I see.
IIRC, not all chapter has this "Leer" button. That's why I ask.
I forget which one it is since I just click random title.

**Comment by riderkick** [comment]
You can make a pull request for translations or just send me the .po file.
