### ISSUE TITLE
Mangafox watermark at the bottom of the page

### ISSUE THREAD

**Issue by 21246685** [riderkick/FMD#208]
Anychance this can be removed?

**Comment by riderkick** [comment]
Options>Misc>Mangafox>Remove watermark

**Comment by 21246685** [comment]
Seems to work on some but not on others?

For example - http://mangafox.me/manga/ultimate_antihero/ 
It doesn't work on chapter 5.

**Comment by riderkick** [comment]
You can try to download 3 file that I committed above and put it in `extras/mangafoxtemplates` then restart fmd.
