### ISSUE TITLE
Tsumino cant download

### ISSUE THREAD

**Issue by Hexaf** [riderkick/FMD#209]
It strange, I have been copy tsumino cookies and it work. But a few hours earlier it didn't work. I check web, and I can read them online.

**Comment by riderkick** [comment]
I don't understand, Its work or not?

**Comment by Hexaf** [comment]
No

**Comment by Hexaf** [comment]
no, it doesn't work

**Comment by Hexaf** [comment]
I got issue again with tsumino. I cant download even I copy paste cookies to config like this.
Tsumino=ASP.NET_SessionId=irurmeouzsmvrn0talhrjjmc;
