### ISSUE TITLE
Downloading fails for some images in e-hentai/exhentai

### ISSUE THREAD

**Issue by bet-force** [riderkick/FMD#213]
Download task from e-hentai/exhentai sometimes fails because some images fails to load..
And I have to manually click "Click here if image loading fails" on the website to download it..

Does FMD add an ' nl ' parameter for when the image fails to load?

**Comment by riderkick** [comment]
Yes. See https://github.com/riderkick/FMD/blob/master/baseunits/modules/EHentai.pas#L326
Give me the link.

**Comment by bet-force** [comment]
Looks like FMD adds only one ' nl ' parameter, but sometimes adding ' nl ' fails to load the image..

You should add more ' nl ' in case the first nl fails..

Take an example.. http://g.e-hentai.org/s/ad5672a9f1/916550-16?nl=7042-405215&nl=312-405215&nl=311-405215

Here the first nl (7042-405215) was added when it didn't load the first time, the second nl (312-405215) was added when the first nl url failed, the third nl (311-405215) was added when the second nl failed and so on..

A new nl is added each time you click "Click here if image fails loading" on the website.

So, my request is add upto atleast 3 nl parameter if image loading fails..

**Comment by riderkick** [comment]
Its work as you expected. nl parameter always generated for every retry. See https://github.com/riderkick/FMD/blob/master/baseunits/modules/EHentai.pas#L290-L335

**Comment by riderkick** [comment]
It seems your problem because sometimes it's fail to find, due to different html source format, sometimes its obfuscated.
