### ISSUE TITLE
Hitomi.la 404

### ISSUE THREAD

**Issue by hatabbich** [riderkick/FMD#214]
when i try downloading manga list, have respond "file not found 404 file not found" :(
help

**Comment by riderkick** [comment]
Working fine here.
Give me the link.

**Comment by hatabbich** [comment]
sorry, but what link do you mean?

**Comment by riderkick** [comment]
The url that produce 404 file not found

**Comment by hatabbich** [comment]
again, im in confuse where i can see this url?

**Comment by riderkick** [comment]
How you got 404 file not found?

**Comment by hatabbich** [comment]
[https://picload.org/view/wwalllg/error.jpg.html](url)
here my actions

**Comment by riderkick** [comment]
There is no hitomi.la manga list at the moment. Build your own from scratch. Book icon>Update manga list.

**Comment by hatabbich** [comment]
ok, thx for help )

**Comment by riderkick** [comment]
You can download available manga list at http://sourceforge.net/projects/newfmd/files/data

Actually you don't need manga list, just drag n drop the urls to download list area or use drop box. Multiple urls supported, also html format. Usually dragging the thumbnails will do.
