### ISSUE TITLE
Downloaded chapters on all manga under favorites not recognized

### ISSUE THREAD

**Issue by jecomoria** [riderkick/FMD#216]
As the title says. Can I import them again to be recognized?

edit: This happened after I updated to 0.9.42.0
![fmd](https://cloud.githubusercontent.com/assets/18043908/14008555/13ac0680-f1bd-11e5-9f31-fbc13f858856.jpg)

**Comment by riderkick** [comment]
Check your works/downloadedchapters.ini. Does it contains your favorites.

**Comment by riderkick** [comment]
Edit:
Due to rewrite of mangafox, the chapters contains now '/1.html' and the end of its url, but old code remove this part, so its appear different when comparing.
Just ignore mangafox at the moment until the next update.

**Comment by jecomoria** [comment]
Yes it contains my favorites, and I downloaded v0.9.41.0 and copy the all the folders and it recognized my works/downloadedchapters.ini but i also downloaded and tried it on v0.9.43.0(fresh install) but the chapters are still not recognized. For now I'll stick to v.41, Thanks.
