### ISSUE TITLE
Images from e-hentai or exhentai are not being downloaded serially

### ISSUE THREAD

**Issue by nodevicefound** [riderkick/FMD#217]
Previously images from e-hentai/exhentai were saved as 001.jpg, 002.jpg, 003.jpg and so on.

But, since the change in #212 the images are being saved with the original filename.

Saving as original filename is good, but sometimes in e-hentai the original filenames are not ordered correctly.

So please change it, so that the file number is added before the original filename.
[Example]

| file number | Original filename |       Output      |
|:-----------:|-----------------:|:-----------------|
|      1      |   goodimage.jpg   | 001_goodimage.jpg |
|      2      |    niceimg.jpg    |  002_niceimg.jpg  |
|      3      |     getout.gif    |   003_getout.gif  |
|      4      |     sixder.jpg    |   004_sixder.jpg  |
|      5      |      foo.png      |    005_foo.png    |
|      6      |     afraid.gif    |   006_afraid.gif  |
|      7      |     batman.png    |   007_batman.png  |

**Comment by riderkick** [comment]
Most of the file name that I encounter is 01.jpg, 02.jpg, 03.jpg...
So, adding another number, it would appear as 001_01.jpg, 002_02.jpg, 003_03.jpg...
I dont't think that would be a good thing. What do you think?

**Comment by nodevicefound** [comment]
I don't think extra numbers in the filename would cause any problem.
What matters most is that the images are saved in the same order as it is in the website, otherwise reading order would vary too much in some cases.

**Comment by riderkick** [comment]
if what important is to maintain the order then I'd opted to just use serialized number without original filename.

**Comment by riderkick** [comment]
I will try another way to maintains the order.

**Comment by nodevicefound** [comment]
I think you should provide an option (a checkbox in Options > Save to > Renaming) for whether to preserve order or not. People can choose whatever they like.
This way everyone will be happy.
http://i.imgur.com/FFKLkBy.png

**Comment by riderkick** [comment]
This is website specific, which should have it's own option. 
I'm thinking to add the option to append filename for ehentai. But there is already many options, and designing the form is't pleasant. I'm planning to rewrite the website specific option so it can add option at runtime. Doesn't have time yet.

**Comment by riderkick** [comment]
New method above will preserve the order and serialize only if necessary, when order changed when sorted.
What do you think?

original  | output       
----------|-----------
1.jpg     | 1.jpg
2.jpg     | 2.jpg
3.jpg     | 3.jpg
4.jpg     | 4.jpg
5.jpg     | 5.jpg

original  | output       
----------|-----------
1.png     | 001.png
2.png     | 002.png
10.jpg    | 010.jpg
11.png    | 011.png
20.png    | 020.png

original  | output       
----------|-----------
goodimage.jpg     | 001_goodimage.jpg
niceimg.jpg	      | 002_niceimg.jpg	 
getout.gif	      | 003_getout.gif	 
sixder.jpg	      | 004_sixder.jpg	 
foo.png	          | 005_foo.png

original  | output       
----------|-----------
1.jpg     | 001_1.jpg 
2.jpg     | 002_2.jpg 
10.jpg    | 003_10.jpg
20.jpg    | 004_20.jpg
4.jpg     | 005_4.jpg

**Comment by nodevicefound** [comment]
Ok, this new method is great too. thanks.
