### ISSUE TITLE
FMD doesn't follow when disconnecting screens

### ISSUE THREAD

**Issue by Ianunaut** [riderkick/FMD#219]
I use a laptop that I hook up to an external monitor at the desk, extending my desktop over the standalone screen (primary) and the laptop screen (secondary). When I disconnect the external screen, Windows folds all open windows and running applications down again and moves them to the laptop screen which then serves as the sole (primary) screen again.

The only exception to this is FMD. FMD keeps sticking to the old two-screen setup for some reason, so if I had it open on the secondary screen, it stayed there (in a way) and didn't respond to anything anymore. This is not an urgent issue, I learned to keep FMD on the primary screen at any given time, but I figured it might be worth investigating at some points.

Thanks for all the hard work, riderkick! I appreciate it.

**Comment by riderkick** [comment]
I thought it was handled by the OS.
I don't have another monitor right now.

**Comment by Ianunaut** [comment]
I thought it's handled by the OS too, but since FMD is the only program that reacts this way, I believe it might be an issue with FMD after all.

But as I said, it's not a pressing issue. You can feel free to close it.

**Comment by riderkick** [comment]
Can you try to run this program, change the monitor and post the message in memo here.
Note: remove '.txt'

[project1.7z.txt](https://github.com/riderkick/FMD/files/191465/project1.7z.txt)

**Comment by riderkick** [comment]
Did you try the latest version? I add a code to move form to the default position (center) if fmd out of monitor. Does it move?

I need to know the exact position before and after. Please run this program.
[project1.7z.txt](https://github.com/riderkick/FMD/files/198102/project1.7z.txt)

Connect your external monitor, run the program, move the form to external monitor, click button "Read monitors". Disconnect the monitor. And post again the log.

**Comment by Ianunaut** [comment]
Sorry I didn't get back to you earlier. I wasn't around the place where I used my two-display setup for a while, and then my machine broke down and I had to get a new one. Now that I have a different configuration, I have no way of reproducing the issue I opened to ticket for. So I'd like to apologize for the confusion and keeping you both busy and hanging. You can consider this issue closed.
