### ISSUE TITLE
Serialized image renaming in e-hentai/exhentai is causing too big filename

### ISSUE THREAD

**Issue by nodevicefound** [riderkick/FMD#224]
Since you made the change to rename the output files into 001_orignalfilename.jpg from originalfilename.jpg only when FMD detects different order from that in the website stated in #217 

But, it is creating unnecessary long filenames.. http://i.imgur.com/ciyRlGU.png (original names were 1, 1a, 1b, 2, 2a, 2b, 3, 4, 5, 6....)

So, I am requesting what I said earlier.. Append the original filename after the serial number regardless of whether the original filename creates order or not.

**Comment by riderkick** [comment]
Can you give me the link?
That was caused by the method called several times.
