### ISSUE TITLE
Add mangaton.com source

### ISSUE THREAD

**Issue by Weischbier** [riderkick/FMD#227]
http://www.mangaton.com/

Please add a http://www.mangaton.com/ as a RAW source.

**Comment by riderkick** [comment]
where is the manga list? 
does it have manga info?

**Comment by Weischbier** [comment]
Well, you got me there. I can't find a proper page either.
Just close this request, after researching a little further this page is pretty inconsistent
and not worth the trouble. 
Thanks anyway :)

**Comment by kavin-90** [comment]
Seems like That site SenManga Ripper.

**Comment by Weischbier** [comment]
There we go. Can be closed then :)
