### ISSUE TITLE
Add korean http://webtoon.daum.net/

### ISSUE THREAD

**Issue by Weischbier** [riderkick/FMD#234]
If possible, add http://webtoon.daum.net/
It's like webtoons.com from Naver.

**Comment by kavin-90** [comment]
Online Manga Downloader Works.

**Comment by riderkick** [comment]
Where is the manga directory and manga info?

**Comment by Weischbier** [comment]
I can't find one myself, but then I don't speak let alone read any korean. If someone with some korean knowledge could help out here that'd be great!

**Comment by Weischbier** [comment]
I *think* this could be it.

http://webtoon.daum.net/league#level=major&sort=recent&genreId=all&pageNo=1

there are 20+ pages of webtoons. I't also split into Parts? I think?
At leats thta's what googles translates it to.

http://prntscr.com/b6b8tr

**Comment by riderkick** [comment]
Declined, website is confusing.

**Comment by kavin-90** [comment]
Here is Index page of Weeks

http://webtoon.daum.net/#day=mon&tab=day

current day will be marked as red. Ajax gets today's releases i.e current day :laughing: 

Click on day it will give that day series :laughing:
