### ISSUE TITLE
Add korean http://page.kakao.com/main

### ISSUE THREAD

**Issue by Weischbier** [riderkick/FMD#235]
Please add http://page.kakao.com/main.
It's the same as webtoon.com from Naver or daum.

**Comment by riderkick** [comment]
Where is the manga directory and manga info?

**Comment by Weischbier** [comment]
I can't find one myself, but then I don't speak let alone read any korean. If someone with some korean knowledge could help out here that'd be great!

**Comment by riderkick** [comment]
Declined, website is confusing.
