### ISSUE TITLE
Exceptions during sync

### ISSUE THREAD

**Issue by ConteZero76** [riderkick/FMD#236]
A lot of stuff is happening, first of all I had to create a fake .dat to avoid some nasty error when downloading the anime list... this is it:

`Fermaposto!%~/fermaposto.html!%~Fermaposto!%~Fermaposto!%~Fermaposto!%~1!%~Fermaposto!%~1!%~0!%~0!%~`

Then MangaFox sync works, for some time... and then it crashes with not one but two (struck) error windows:

http://i.imgur.com/SPQEG6u.jpg

**Comment by riderkick** [comment]
Looks like you still use the old version by akarink. grab the latest here https://github.com/riderkick/FMD/releases

**Comment by ConteZero76** [comment]
Thank you.
