### ISSUE TITLE
YoManga is broken

### ISSUE THREAD

**Issue by Weischbier** [riderkick/FMD#238]
The website is fine on my end but FMD doesn't update the list nor favorites anymore, as well as Manga Information cannot be loaded with it.
It gives me an error that states the following:
`Cannot get manga info. Please check your internet connection and try again`

Everything is fine with the other sites.

**Comment by riderkick** [comment]
yomanga.co ?
![sshot-2016-05-03- 16-07-10](https://cloud.githubusercontent.com/assets/4972676/14977732/35c71b3c-1149-11e6-8ae1-75b16a565537.jpg)

**Comment by Weischbier** [comment]
Weird, but by the time I reported the issue I was able to browse their website.
Seems like they have some issues over there.
