### ISSUE TITLE
Cant' update manga list

### ISSUE THREAD

**Issue by Hexaf** [riderkick/FMD#239]
Can't update manga list on yomanga and hentai2read

**Comment by kavin-90** [comment]
same here can't get KissManga Manga list

**Comment by riderkick** [comment]
hentai2read and kissmanga working fine here.

**Comment by kavin-90** [comment]
@riderkick i tried to update manga list but return 404 error then try to build but return 0 results.

**Comment by riderkick** [comment]
What website you're talking about? 
Update from server or from website?

**Comment by kavin-90** [comment]
1st i tried update from server which return 404 is ok.

But from website return 0 results.

**Comment by riderkick** [comment]
Both working fine here. What is your fmd version?

**Comment by kavin-90** [comment]
latest version. wait a sec i check.

**Comment by riderkick** [comment]
![sshot-2016-05-07- 14-13-10](https://cloud.githubusercontent.com/assets/4972676/15090571/08619010-145e-11e6-850a-f5ec6a503e41.jpg)
![sshot-2016-05-07- 14-13-59](https://cloud.githubusercontent.com/assets/4972676/15090570/07d63768-145e-11e6-89f9-103ce526c464.jpg)

**Comment by riderkick** [comment]
The list should be consistent with the website.

**Comment by kavin-90** [comment]
But i got 404 error

http://fs5.directupload.net/images/160507/zvom7mep.png

**Comment by riderkick** [comment]
Can you download it manually from here https://sourceforge.net/projects/newfmd/files/data/

**Comment by kavin-90** [comment]
ok thanks.

**Comment by riderkick** [comment]
What is your updater.exe version. If you always use automatic update, there is some issue with updater a long time ago. It has to be replaced manually. I put a notice in changelog.

**Comment by kavin-90** [comment]
i just download latest version recently because i don't have any FMD version so i think there is no issue. I use x64 i think

**Comment by riderkick** [comment]
The fact it's return `404 File not found`, that's mean it's working fine. It just the server that reply with file not found.
Can you download it manually? I heard some isp blocking sourceforge.

**Comment by kavin-90** [comment]
okay thanks
