### ISSUE TITLE
Not auto-downloading new chapters after checking favorites

### ISSUE THREAD

**Issue by rhoen91** [riderkick/FMD#24]
I don't know if it's just me but, the newer versions doesn't seem to be downloading the new chapters after checking the favorites list for updates. I tried using 0.9.9.1, where I copied the same "favorites.ini", "config" folder, and "data" folder as I used on 0.9.9.4, and it worked as normal. I also checked 0.9.9.3 and 0.9.9.2, it seems to have stopped working at 0.9.9.2.

**Comment by riderkick** [comment]
Yes. I forgot to add that thing after I rewrite favorite manager.
