### ISSUE TITLE
Can't download from yomanga

### ISSUE THREAD

**Issue by Hexaf** [riderkick/FMD#240]
After yomanga maintenance. I cant download

**Comment by riderkick** [comment]
I still can't open yomanga website. It is yomanga.co right?

**Comment by dianfajar** [comment]
yomanga website down for everyone.. http://isup.me/yomanga.co

**Comment by Weischbier** [comment]
YoManga is getting DDOS'd like mad. That's the info I've gotten so far.

**Comment by Hexaf** [comment]
yomanga is up again. And everything is fine

**Comment by riderkick** [comment]
It is working fine now?
