### ISSUE TITLE
CBZ converter seems to be getting a little wonky.

### ISSUE THREAD

**Issue by Weischbier** [riderkick/FMD#245]
Since version 0.9.51.0 the failure rate of the *.cbz converter has increased dramatically.
It ends up creating 0kb *.cbz files in 4 out of 10 chapters.
Here's a picture: [Link](http://img.prntscr.com/img?url=http://i.imgur.com/VNoAJfL.png)
The folders itself are fine. The pictures downloaded within the folders are fine as well.

It seems to happen randomly, but when it does it locks up the nessecary files until you force close FMD.

**Comment by riderkick** [comment]
I need your config and works file.

**Comment by Weischbier** [comment]
I'll that I I'll give you work file where it happenend...I usually remove all completed tasks.
Nonetheless, here's my config file:
https://www.dropbox.com/s/wy26cgwno4ekp8j/config.zip?dl=0

**Comment by riderkick** [comment]
Please try with the latest version.

**Comment by Weischbier** [comment]
Yeah, seems to be fixed. Downloaded over 1000 chapter across all the sources i use and never failed.
Thanks for whatever you did xD
