### ISSUE TITLE
software hang when downloading favorites or update to newer version

### ISSUE THREAD

**Issue by augustinlibert** [riderkick/FMD#248]
Hi,

I was playing around with the software and I notice it will hang when added select all from one of manga list example mangafox, I update all list and select all to add them to favorites, sometimes it completed within few mins, but most of time it hang while downloading, and if favorites is too many, it unable to update to new version at all.

By the way, you guys are doing really good, love this software so much... keep it up... :)

**Comment by riderkick** [comment]
Not hang, just busy. Just wait until its done. 
Add from list run on main thread, because we need to block selected state. And fetching from database using step, which is 25 records at a time to minimize memory consumption. So there will be take a time if you add too much.
