### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Alter00** [riderkick/FMD#25]
I get this error when I update FMD;
http://prntscr.com/73mquv
Thanks in advance.

**Comment by riderkick** [comment]
What do you update, FMD or manga list?
Based on those error message. It lead to TDataProcess.LoadFromFile. error seems occurred when loading the manga list from file. Probably the manga list file is broken.

**Comment by Alter00** [comment]
Yeah, it occur because of S2scans.
Thanks, I fixed it.
