### ISSUE TITLE
Speed of Bato.to

### ISSUE THREAD

**Issue by Weischbier** [riderkick/FMD#253]
Is there a reason why downloads from Batoto are like reaaaaally slow?
Takes a considerable amount of time to download anything with FMD.

If that is due to Bato.to then there's nothing we can, but if it's not, maybe revisit the code?

**Comment by riderkick** [comment]
You may search the issues tracker, or google it before making an issue. There is conversation about this before.
Yes, batoto is slow on server side, nothing we can do.
