### ISSUE TITLE
can't download from mangaAe

### ISSUE THREAD

**Issue by Lafriakh** [riderkick/FMD#255]
when i download from mangaAe manga count become 0 and no chapters appear.
i thing the problem from cloudflare block my rdp IP, because many downloads.
is there any solution  :smile:

**Comment by riderkick** [comment]
It's working fine here.

**Comment by Lafriakh** [comment]
yes it's work from my laptop but as i seed from my rdp not work, i thing because cloudflare block my ip address because too many downloads.
is there any solution.

**Comment by riderkick** [comment]
I think that's just temporary. Alternatively you can add the cookies after you solve the captcha.

**Comment by Lafriakh** [comment]
how can i add cookies? what is the format?

**Comment by Lafriakh** [comment]
i use Editthiscookie from chrome but not work?

**Comment by riderkick** [comment]
Right click>Inspect element>Network or Ctrl+Shift+I. If empty, then refresh the page. Select the first item, or any item that related to main domain(manga ae). Copy all the cookies. And the user-agent as well if necessary.
![sshot-2016-05-27- 00-29-48](https://cloud.githubusercontent.com/assets/4972676/15582260/a2289646-23a2-11e6-86cb-ba53cdbb323d.jpg)
