### ISSUE TITLE
Cannot Download 

### ISSUE THREAD

**Issue by abhi98** [riderkick/FMD#258]
So After I checked my favorites and then add the tasks(chapters) to the queue they all show up as stopped and when I click resume(all) nothing would happen Please Help. Thanks for your Hard Work.

**Comment by riderkick** [comment]
Where is your works.ini

**Comment by umesh1134** [comment]
yes FMD not downloading anything. Please remove the bug ASAP.

**Comment by riderkick** [comment]
I need your works.ini because it's working fine here.

**Comment by abhi98** [comment]
Ok I have uploaded the works.ini file here :- https://www.mediafire.com/?8rr96f6e98n1d0n

**Comment by umesh1134** [comment]
Here's mine work.ini [

](https://www.datafilehost.com/d/6256ab8e)

**Comment by riderkick** [comment]
Your downloads location point to drive J:\. Does this drive even exist(connected)?

**Comment by abhi98** [comment]
Yes it is. I have been downloading like that for like 1 year.

**Comment by riderkick** [comment]
It's working fine here after I change the downloads location to existing drive on my machine.

**Comment by abhi98** [comment]
But FMD is also on the other drive and the issue started after the update.

**Comment by abhi98** [comment]
So I updated the FMD just now and Now it is working fine. I can't figure out what as wrong ?

**Comment by riderkick** [comment]
Try to add a download with different location, from manga info tab, change the `Save to:`, and download.
Do "Open folder" or "Open ..." work?

**Comment by riderkick** [comment]
Maybe there is permission issue. Or your antivirus interfere.

**Comment by abhi98** [comment]
Yes "Open folder" or "Open ..." do work. The downloads from Manga info tab is also working fine. I didn't touch my antivirus at all and I had it for a long time.

**Comment by riderkick** [comment]
Modern antivirus has sandbox mode that run a new program(new file) on read only access. Usually it's only happen on first run, and only take a few seconds. But sometimes odd happen.
