### ISSUE TITLE
Batoto doesn't work

### ISSUE THREAD

**Issue by VulkHead** [riderkick/FMD#259]
Doesn't load chapters as shown in the capture. Is the same for every manga I've tried to download (Batoto) not sure if applies to all mangas in the list.
![screenshot from 2016-05-28 04 38 57](https://cloud.githubusercontent.com/assets/11966520/15626272/9e241ab8-246d-11e6-871c-6ebf787040c4.png)

**Comment by riderkick** [comment]
You need batoto account, `Options > Accounts`.
