### ISSUE TITLE
A pair of issues with Submanga

### ISSUE THREAD

**Issue by VulkHead** [riderkick/FMD#260]
Covers of mangas missing as shown in capture (Pretty sure all of them).
![screenshot from 2016-05-28 04 50 34](https://cloud.githubusercontent.com/assets/11966520/15626325/dac83250-246e-11e6-9c8c-9395b3028842.png)

It is **very** common to find mangas without description and genre, as shown below.
![screenshot from 2016-05-28 05 02 43](https://cloud.githubusercontent.com/assets/11966520/15626379/0c91fa90-2470-11e6-8ca5-35d7cd59f774.png)

Thanks for the amazing support so far.

**Comment by riderkick** [comment]
Do you even check the website?
They don't have it!
