### ISSUE TITLE
Missing descriptions NineManga_ES

### ISSUE THREAD

**Issue by VulkHead** [riderkick/FMD#261]
NineManga has descriptions in almost every manga, but NineManga**_ES** doesn't. It is pretty common to find a manga without description in NineManga**_ES**.. Below a comparison between  NineManga and NineManga**_ES** with the same exactly manga.

**Good**
![screenshot from 2016-05-28 05 18 17](https://cloud.githubusercontent.com/assets/11966520/15626536/6041a5fc-2473-11e6-9653-8ac9dad793bb.png)

**Bad**
![screenshot from 2016-05-28 05 19 19](https://cloud.githubusercontent.com/assets/11966520/15626541/71a70d8c-2473-11e6-89b8-81944810403f.png)

This happens most of the time with NineManga**_ES**, while NineManga descriptions are always almost perfect..

**Comment by riderkick** [comment]
Do you even check the website?
They don't have it.
