### ISSUE TITLE
Can't update manga list

### ISSUE THREAD

**Issue by madowl** [riderkick/FMD#263]
Cant' update manga list MintMangaRU, ReadMangaRU and MangaChanRU, «File not found».

**Comment by riderkick** [comment]
There is no manga list data for that website yet. Make your own.
https://sourceforge.net/projects/newfmd/files/data/

**Comment by madowl** [comment]
Can you please tell me, how to do that?

**Comment by riderkick** [comment]
Book icon > Update list
