### ISSUE TITLE
ReadComicOnline

### ISSUE THREAD

**Issue by StormJumper** [riderkick/FMD#265]
Trying to do a update on this manga site stalls? But I can go to the site and have no problem reading manga? Is this a script update they did to block FMD from updating?

**Comment by riderkick** [comment]
It seems the domain has changed, and they use cloudflare anti-ddos which block the access without valid browser.

**Comment by StormJumper** [comment]
Great...I removed them along with MangaStreamTo so it doesn't affect when I do updates. If they don't let me see then I guess then I don't go there.
