### ISSUE TITLE
Adding chapter filename option

### ISSUE THREAD

**Issue by 7h3Cub3** [riderkick/FMD#266]
Hello, love your work, thanks a bunch for it.

I wished to suggest for an additionnal option to the "saveto" tab, adding a box to decide how the files for each  chapter would be named. when i download a bunch of chapters or a whole manga it's always nice to be able to read it in one swoop,having all the chapters files properly numbered and assembled into the same folder for uninterrupted (by having to change folder) reading.

Would be grateful for this ^_^
Cheers.

PS : is the link for donation on the blog still current ?

**Comment by riderkick** [comment]
Can you elaborate more. Please provide an example.

That donation link is for akarink. I don't know if she is still around. Never reply my email anymore since 2 years ago.
I don't expect any donation.

**Comment by 7h3Cub3** [comment]
Sure, lemme make a little example.

At the moment under the saveto, you have the option to set 

Manga Folder Name
Chapter folder Name

that allow you to have a folder tree like

```
Naruto
   | _Chapter 01 - Uzumaki Naruto
           |_001.png
           |_002.png
```

My request is to also have the option

Chapter File Name

That would allow you to have something like this.

```
Naruto
   | _Chapter 01 - Uzumaki Naruto
           |_Naruto_c01_001.png
           |_Naruto_c01_002.png
```

It wouldn't need to get the current chapter name or filename from the remote server because depending of the remote manga website that could change so it could have variables based on %MANGA_NAME% (maybe %CHAPTER_NAME% if available) and %CHAPTERS_NUMBERS

This would be great because ATM when i read multiple chapters of the same manga you have to switch between folders at the end of each chapters, when it would be easier to just search for all the image in the manga folder, and get all the chapters pages already named/numbered, for uninterrupted reading.

As for donation, if you ever change your mind i would be willing to participate again (i gave a few years back), and give a bit because you are doing a damn good job :)

Cheers.

**Comment by riderkick** [comment]
You may need check the `Options>Save to` again.
There is "Auto generate folder based on manga's name", paired with manga folder field that you can 
customize with `%WEBSITE%`, `%MANGA%`, `%AUTHOR%` and `%ARTIST%`.
Also chapter folder name field to customize with `%WEBSITE%`, `%MANGA%`, `%AUTHOR%`, `%ARTIST%`, `%CHAPTER%` and `%NUMBERING%`

You can use manga reader for uninterrupted reading. you can save as cbz or zip, or just plain folder. I believe popular image viewer replacements also can do that.

**Comment by 7h3Cub3** [comment]
Yes for all you said, i already checked thoses options thoroughtly, but what i was interested in, is to have the ability to rename the image files as show in my example above,  your current save to system only interact with folders and sub-folders for variable renaming, not the image files hence my request. This is the one feature that make me hesitant to switch from DomDom and it's a shame because FMD is so much better and by a long shot. Maybe i'll look at a solution with some scripted renamers.... Thanks anyway...

**Comment by riderkick** [comment]
So you want to put all the images from different chapter in one folder?
I have to check the code first, there is another difficulty with certain modules.

**Comment by 7h3Cub3** [comment]
Thanks alot ;)
