### ISSUE TITLE
Batoto Download Failed

### ISSUE THREAD

**Issue by chauvy** [riderkick/FMD#267]
Been trying to download from batoto but always failed today. I tested on the old uploaded manga, it downloaded just fine, but when i tried on the newly uploaded one, it give me error "(the manga title) failed, try resuming the task" or "failed to create directory"

This manga for example: http://bato.to/comic/_/comics/shisha-no-teikoku-r16539
I can download the first chapter, the second one that uploaded hour ago end up failed

http://bato.to/comic/_/comics/gun-ota-ga-mahou-sekai-ni-tensei-shitara-gendai-heiki-de-guntai-harem-wo-tsukucchaimashita-r15946 the latest chapter on this one give me failed to create directory.
I already refreshed my account, still failed.

**Comment by riderkick** [comment]
It's working just fine here. Failed to create directory mean it's fail to access your download location. Check your "Save to"

**Comment by chauvy** [comment]
Such strange thing because it's not working last night, I wonder is it related to the cloudflare or some other network problem on batoto side? The download seems working just fine now except this one http://bato.to/comic/_/comics/gun-ota-ga-mahou-sekai-ni-tensei-shitara-gendai-heiki-de-guntai-harem-wo-tsukucchaimashita-r15946 because it keep failed to create directory (the "save to" is working fine as the other title now can be downloaded and the the folder created just fine).

**Comment by riderkick** [comment]
Can you give me your works.ini

**Comment by chauvy** [comment]
Here's the works.ini but i change it to txt since i can't upload *ini here







[works.txt](https://github.com/riderkick/FMD/files/290646/works.txt)

**Comment by 7h3Cub3** [comment]
I have the same issue for gun ota, i think it may be related to the lenght of that manga name that make the full path + filename longer than 255 char, maybe  you should include some char limit in the variables ? i tried 3 different manga downloaders and they all seems to have this issue with very lenghty mangas (like shomin sample)

**Comment by riderkick** [comment]
Char limit and remove symbol have been implemented since I work on this project about 2 years ago.
It just seems the recent commit, which I clean up a lot of code causing a regression.
