### ISSUE TITLE
Question about the filter system

### ISSUE THREAD

**Issue by Weischbier** [riderkick/FMD#268]
Let's take Dynasty-Scans for this example.
Dynasty-Scans has a lot of Yuri genre Manga/Doujins/Anthologies, but with the filter system in 
FMD you don't get the most out of it.
Here's an example of FMD: http://i.imgur.com/XtVahTc.png
It only shows 6 as a result.
Here's the Website: http://i.imgur.com/rF5sFc8.png
Only with the tag Yuri you get 25 on the first page out of 20.
Maybe I'm doing it wrong but it seems off to me.

Here's an example of a series FMD is missing when using the filter:
http://dynasty-scans.com/series/age_15
FMD has the corrects tags.
http://i.imgur.com/iohEOg2.png

In general the whole filter system is wonky.

**Comment by riderkick** [comment]
Well, I got a lot.
Try to update the manga list.
![sshot-2016-06-01- 19-56-36](https://cloud.githubusercontent.com/assets/4972676/15708751/0645b318-2833-11e6-8d70-2eb46ea957cf.jpg)

**Comment by Weischbier** [comment]
Yes, in fact I did. I even deleted the db file and created a new list but it's still not showing more than what I already showed.
I just tried a completely new folder with a fresh FMD and it's no different from the previous one.

Btw, could we get a a button toggle all genres on/off?

**Comment by riderkick** [comment]
Give me your mangalist data.

**Comment by Weischbier** [comment]
Yea, it seems FMD misses to add the genres properly into the db files.
https://www.dropbox.com/s/ohmj1fsjls40l0c/data.7z?dl=0

**Comment by riderkick** [comment]
Your link expired.
It's work properly on my machine. I'm guessing you tick "Don't load manga information" in Options>Updates" don't you? That will break filter as the caption said.

**Comment by Weischbier** [comment]
Woops, sry
https://www.dropbox.com/s/ciyvfbyj290r4ho/data.zip?dl=0
there you go again.

That option was indeed turned on but it didn't change anythinig for me. It still only shows 4 titles with the tag. Incidently, it's those titles that have proper tags in the db files. But see for yourself :)

**Comment by riderkick** [comment]
That's what make filter not work. Because there is no data to filter.
If that option activated then when updating manga list it will not load the manga info, its only grab the title and link. You have to uncheck that option and make your list from scratch to be able to filter properly.
