### ISSUE TITLE
Ability to show only recently added entries.

### ISSUE THREAD

**Issue by Weischbier** [riderkick/FMD#269]
When you update a manga list, I'd love to have the ability to only show me these.
When you update a manga list of an aggregator site like Bato, then you have to scroll through the list and look for the blue highlighted entries.
Maybe add it into the context menu of the manga list?

**Comment by riderkick** [comment]
Please elaborate.
We don't know what recently added is. We don't keep the list of chapters. We only store downloaded chapters. So we only know if chapter already downloaded or not. New chapters in favorites is those are not in downloaded chapters.

**Comment by Weischbier** [comment]
I mean the entries when you update a manga list that are highlighted blue.
If we could show only them after an update of the manga list.
http://i.imgur.com/V1U4Sz6.png

Like Bato in this example has quite a large list and it's quite tedious to scroll through 16k+ entries to look for new additions.
So, I was wondering if we could get the ability to only show those highlighted then.

**Comment by riderkick** [comment]
You can use filter for that."Search only new manga".

**Comment by Weischbier** [comment]
That's not what I mean. I want to browse the new added entries without having to scroll through all the rest as well.

**Comment by riderkick** [comment]
That's what it does.
![sshot-2016-06-03- 09-53-00](https://cloud.githubusercontent.com/assets/4972676/15766471/7c42a8d4-2971-11e6-8840-418ba833680c.jpg)

**Comment by Weischbier** [comment]
Ha, I actually never thought it works this way.
Thanks.
