### ISSUE TITLE
Getting stuck while checking for new chapters for manga (kissmanga)

### ISSUE THREAD

**Issue by ratbunuts** [riderkick/FMD#271]
Hello, I dont know if Im the only one experiencing this but whenever I started "checking for new chapters" it always getting stuck at the first 3 titles of my Favorites list.

**Comment by riderkick** [comment]
Give me your favorites.ini
Check your "favorite" website with a browser. Maybe there some issue web the website. If the website is slow, then fmd will be slow too. Maybe the "stuck" is just waiting for server to reply.

**Comment by ratbunuts** [comment]
heres the link for favorites https://drive.google.com/file/d/0By6u0W9ZGVSyczl6NE9RUEV5Rlk/view?usp=sharing

**Comment by ratbunuts** [comment]
I did what you told me and check out kissmanga. It is Kissmanga I think coz I did sort by website and batoto was my first website and its running fine. The website for Kissmanga has a redirecting thing before going to the site so maybe its that

**Comment by riderkick** [comment]
Just wait until its done. It will follow the redirection. There is a wait time for a few seconds for first request.

**Comment by ratbunuts** [comment]
I'm gonna leave it running tomorrow then. I left it running for few hrs though and it's still stuck

**Comment by riderkick** [comment]
It's shouldn't take hours, checking your favorites just taking a minutes on my machine.
What version did you use. Make sure to grab the latest version here https://github.com/riderkick/FMD/releases

**Comment by ratbunuts** [comment]
I do have the latest version

**Comment by 7h3Cub3** [comment]
Hello,

I can confirm there is a problem with kissmanga, the favorite list is getting stuck on any kissmanga favorite i increased the number of concurrent connection to bypass the issue but kissmanga seems to be stuck in a loop indeed (weird that timeout setting doesn't work)

Cheers

**Comment by ratbunuts** [comment]
Yeah im gonna do that until the issue is resolved. I tried running the other website yesterday and they are running just fine.

**Comment by ratbunuts** [comment]
Oh I got question regarding batoto. How come only batoto doesn't show all chapters available for certain manga series? It only show the latest one? Before it's not like that? Just curious

**Comment by 7h3Cub3** [comment]
you need to authenticate to batoto to see all chapters, go in option > accounts, and add your batoto account, you will then see all chapters

**Comment by Weischbier** [comment]
Yeah, it is KissManga. I removed every kissmanga entry and it works now.

**Comment by riderkick** [comment]
Can you even open kissmanga's manga in manga info?

**Comment by ratbunuts** [comment]
I'm not sure I haven't tried it

**Comment by 7h3Cub3** [comment]
Nope you cannot open MANGA INFOS on kissmanga either

**Comment by riderkick** [comment]
It's hard coded to retry only 3 times, it's shouldn't getting stuck loop. It will fail but not stuck.

**Comment by 7h3Cub3** [comment]
yeah that's what was looking weird to me, it should timeout, but there must maybe be some bugs

**Comment by riderkick** [comment]
It's not waiting timeout, just caught in 3 loop. It should done in a few seconds. That's what happen on my machine. I can exit fmd after a few seconds.
cloud flare.
