### ISSUE TITLE
EyeOnManga stuck on update??

### ISSUE THREAD

**Issue by StormJumper** [riderkick/FMD#272]
Tried to use the latest version and update EyeOnManga and it just freezes and doesn't move. Version fmd_0.9.60.0_Win64.7z.

**Comment by ratbunuts** [comment]
That might be the same problem I have with kissmanga. Right now I just update new chapters on other website except for kissmanga

**Comment by riderkick** [comment]
Eyeonmanga website is down. Just check it with browser.

**Comment by StormJumper** [comment]
I figure as much I just uncheck so they don't show up on my list. I think MangaStreamTo is still offline tried last time and couldn't reach the site through the web.

**Comment by riderkick** [comment]
I will remove them if they still offline in a week.

**Comment by StormJumper** [comment]
ok, I'll close this for the 9.60 and report back if any problems happen on the next version.
