### ISSUE TITLE
Config INI Setting Typo

### ISSUE THREAD

**Issue by marstaik** [riderkick/FMD#273]
I opened the config.ini to check through some settings, and found this:

`
[MangaFox]
RemoveWatermak=1
SaveAsPNG=1
RemoveWatermark=1
`

upon deleting the said section, and reopening FMD, the config.ini sets these values:
`
[MangaFox]
RemoveWatermak=1
SaveAsPNG=0
`

I guess it was correct at some point but it was un-done?

**Comment by riderkick** [comment]
If I fix the typo then those value will be reset to default. Do I have to fix the typo?
