### ISSUE TITLE
Issue with combo saveto zip and auto generate manga folder disabled

### ISSUE THREAD

**Issue by 7h3Cub3** [riderkick/FMD#275]
Hey,

Noticed a lttle issue when you use in combo "save to as ZIP" and the "auto generate manga folder" option disabled,  it will zip the whole download folder and then erase it after zipping done, erasing the zip too in the process.

cheers

**Comment by riderkick** [comment]
Can you give me the screenshot of your "Save to" options.

We're not storing all filename that have been downloaded. So, we don't know what files is right, we compress all files in working folder. If no manga folder and no chapter folder, then it will compress all known format indiscriminately.
I assume whoever use compress feature would be use separate chapter folder. So its shouldn't causing any problem.

**Comment by 7h3Cub3** [comment]
Yeah i was assuming that's what was going on, instead of the source files it's the source folder that is compressed, it will do the same even if you put a manga folder, because all chapters will go into the same folder, it's fine, i will continue to use a chapter folder, my idea doing that was to shorten the end path for the files to resolve the issue of long pathname.

here is how i had my "save to" at the time

http://imgur.com/zJSK5O0

**Comment by riderkick** [comment]
Your setup is really weird. So you put all files in the same folder.
How you can even browse them?
```
Base folder
|_ Naruto Ch.1_001.png
|_ Naruto Ch.1_002.png
.
.
|_ Toriko 001_001.png
|_ Toriko 001_002.png
.
.
```

**Comment by 7h3Cub3** [comment]
Well the idea was to have only a download folder with all chapters for all manga compressed there, then i have a script that move them around to my "TO READ" folder, because i have some manga i follow but im a few chapters behind and some i get for reading later, but it's ok either way i can manage ;) thx for the changes though :)
