### ISSUE TITLE
Issue with long filename

### ISSUE THREAD

**Issue by 7h3Cub3** [riderkick/FMD#276]
Hey again,

i noticed that when you have very long chapter and/or manga name it can cause issue when downloading. i know you already enforced some rules about it in a previous update, but are you evaluating the variable lenght by itself or/and the whole file/folder name ? because with some settings, you can still have the issue.

Lemme give an example,

Site : Batoto
Manga : Ore no Kanojo to Osananajimi ga Shuraba Sugiru
Chapter : 28 - The day after ___Watching the fireworks together with Ai___ battlefi... [Japanzai]
Settings : 
Auto generate folder based on manga name - disabled
Remove manga name from chapter - disabled
Auto generate chapter folder set with %MANGA%_%CHAPTER%
Filename set with %CHAPTER%_%FILENAME%

if you try to download this chapter and some others that have long lenght , it's gonna create the folde,r try to download but timeout and go to the next task. I tried with shorter settings, and it work. so my query is, can you also evaluate the full lenght of the folder and/ or filename so that they get shortened more if needs be ?

Oh and also btw, i noticed that if you disable the "Auto generate folder based on manga name" it will grey out the box of settings, where if you do the same with "Auto generate chapter folder" it will not grey out the box.

Cheers

**Comment by riderkick** [comment]
The problem if we cut the long filename is we will lose the numbering too, if its on the last part. That will make fmd saving all files with the same name.

**Comment by 7h3Cub3** [comment]
Ah yeah i understand, depending on the manga site the end result would be different. Im adding chapter name basically because i wish to have the true chapter number, would it be hard or uncompatible or something to make a variable that capture only the true chapter number like %CHAPTER_NUMBER% ? that would make it enough for me (i don't care much about the chapter name ^^)

**Comment by riderkick** [comment]
Not all website have chapter number. And they are varies, it's hard to know which one is the chapter number.
Some of them are.
```
Manga name - Chapter 1
Chap.1
001
ch.001
chapter one
etc..
```
