### ISSUE TITLE
Dropping connections

### ISSUE THREAD

**Issue by Weischbier** [riderkick/FMD#277]
I noticed quite a while ago but never actually went and reported it but
FMD apparently drops connections but not really.
sounds weird? Yep, it does.
Here's a video: https://youtu.be/Zqvcdbnb5s8

I monitored FMD with Microsoft Network Monitor and apparently it doesn't lose connections or loses packages. But FMD just stops downloading. This does not happen with Bato or other big aggegrator sites but with the small ones like Dynasty, MangaPark or KissManga (still after the update).
It does pick the connection up again but only afer a considerable amount of time and not less than ~20 minutes. A Stop and Resume *sometimes* fixes it but it's usually better to stop the tasks and wait like ~30 seconds and then resume.

**Comment by 7h3Cub3** [comment]
it's probably some throttling on their side, you may want to reduce the amount of concurrent connection/files to download. from what i can see you seem to hammer quite heavily.

**Comment by Weischbier** [comment]
Yea, this is just for demonstration purpose. It happens even with a 1;1 setting.

**Comment by riderkick** [comment]
All downloads manage by tdownloadmanager, all website use this. So if the problem is with fmd, then it will affect all website too. Like comment above, probably it's just some throttling with their server.
