### ISSUE TITLE
Folder Hierachy

### ISSUE THREAD

**Issue by Weischbier** [riderkick/FMD#278]
Could we get the option to download mangas into Source folders?
Like downloads from Bato go into a Bato folder etc etc.

- Bato\ MangaName
- Dynsaty-Scans\ MangaName

Like this?
This would add a better oversight for people like me who download many chapters/mangas in general.

**Comment by riderkick** [comment]
With those changes you can use "\" in manga folder or chapter custom rename.
`%WEBSITE%\%MANGA%`
