### ISSUE TITLE
Ellipsis in filename crashes FMD/fails download

### ISSUE THREAD

**Issue by ghost** [riderkick/FMD#279]
If chapter has an ellipsis at the end of chapter's title, then if it's added at the end of cbz archive through %CHAPTER% ![1](https://cloud.githubusercontent.com/assets/19764834/15807711/480c72ca-2b65-11e6-8d40-941a27afa0b8.png) it will cause all sorts of problems. 

When downloading from batoto it simply fails the download (creates empty folder and fails).
![2](https://cloud.githubusercontent.com/assets/19764834/15807712/4839b596-2b65-11e6-8ffb-c887eddc84b0.png)
![3](https://cloud.githubusercontent.com/assets/19764834/15807713/483b331c-2b65-11e6-9a1f-c26d381181c1.PNG)
![4](https://cloud.githubusercontent.com/assets/19764834/15807714/483d69fc-2b65-11e6-858e-4060b7259e4f.PNG)

Kissmanga outright crashes client after some time (when the crash occurs, CPU usage skyrockets). I've managed to reproduce the error on different machines, with same results each time. Removing %CHAPTER% from naming fixes it, though galleries obviously aren't named with chapter's actual name.
![5](https://cloud.githubusercontent.com/assets/19764834/15807715/484082cc-2b65-11e6-9f13-8b43da3a33f7.PNG)
![6](https://cloud.githubusercontent.com/assets/19764834/15807716/4842ee18-2b65-11e6-9058-f95211cb5dd3.PNG)

**Comment by riderkick** [comment]
It seems Windows can't use folder that ended with dot.
Removing end dot fix the problem.
