### ISSUE TITLE
adding support for lofi.e-hentai.org

### ISSUE THREAD

**Issue by rbwz** [riderkick/FMD#280]
Well, usually one want to download the highest quality pictures from e-hentai... 

But the lofi version (lofi.e-hentai.org) offer significantly smaller file size, at the expense of image size/quality.

Might be good to add support for.

**Comment by riderkick** [comment]
Upon looking at the source. 720x is the same with what displayed in g.e-hentai.org, while 980x is the original resolution. So, there is no different.

**Comment by rbwz** [comment]
Ah, I see... Is there any way I can use FMD to download from g.e-hentai.org (and the exhentai.org) with 720x / 980x resolution then?

**Comment by riderkick** [comment]
`Website>Options>E-Hentai>Download original image`
If this option is turn on, it was 980x. Otherwise 720x.

**Comment by rbwz** [comment]
![snap](https://cloud.githubusercontent.com/assets/19768117/16023879/0c1d775c-31e9-11e6-820a-865ee859215b.JPG)

i compared the manually downloaded picture (by right click and save as in browser) and by FMD download...
it seems that FMD download the resized 1200x version instead of 780x resolution (the original image, in PNG, is even larger)...

note: in browser, i have changed my account settings in exhentai to resample online view images to 780x

**Comment by riderkick** [comment]
Can you give me the url?

**Comment by rbwz** [comment]
http://exhentai.org/s/e0382a37b6/943394-7

**Comment by riderkick** [comment]
The settings in exhentai is saved in browser(client side with cookies). There is no way fmd to know this.

**Comment by riderkick** [comment]
I'll add option for available resolution later. I need to rewrite the website options first.
