### ISSUE TITLE
Chapters names

### ISSUE THREAD

**Issue by moezmtk** [riderkick/FMD#281]
![94bf1b18-2b29-11e6-948d-8d57d28e3dd3](https://cloud.githubusercontent.com/assets/19761049/15811278/274bb674-2b9f-11e6-9bfc-a1c607affde5.png)

i have something bothering me in the latest fmd versions
The members in the picture i wont to get rid of them but i don't find the option to do so 
so can you help ?

**Comment by riderkick** [comment]
It's `%NUMBERING%` in Options>Save to>Chapter name
