### ISSUE TITLE
webtoon.com some chapter issues

### ISSUE THREAD

**Issue by Weischbier** [riderkick/FMD#284]
There are 2 webtoons on webtoons.com with issues.
Multiple chapters of those are not properly downloaded.
Here's the workfile:
[works.txt](https://github.com/riderkick/FMD/files/307109/works.txt)

i tried completely deleting the webtoons and re-downloading as well as a clean install of FMD (fresh folder, fresh download)

**Comment by riderkick** [comment]
It's working fine here.
![sshot-2016-06-10- 00-32-20](https://cloud.githubusercontent.com/assets/4972676/15937781/e36fd316-2ea2-11e6-8b95-1f8731e8084c.jpg)

**Comment by Weischbier** [comment]
It worked now for me too, but look when I added Salty Studio it was the 5th.
It just went through the chapters until it failed the retry count.
Weird thing...
