### ISSUE TITLE
Folder name are all CAPS?

### ISSUE THREAD

**Issue by StormJumper** [riderkick/FMD#287]
How come if I delete a folder - on re-download it becomes all CAPS?

Example
Before:
Ore ga Ojou-sama Gakkou ni Shomin Sample Toshite Rachirareta Ken
Now:
ORE GA OJOU-SAMA GAKKOU NI _SHOMIN SAMPLE_ TOSHITE RACHIRARETA KEN

Is this a setting? I do know in the past some were and some were not. Just deleting the manga volumes didn't make it CAPS.

**Comment by riderkick** [comment]
What website is this?
IIRC, there is a website with all caps title in their manga info page. While it's title case in manga directory. So, if you open manga info with popup menu "View manga info" it will only send the url to tgetmangainfothread. So the title will be loaded directly from website. If you open it via "Manga List" it will preserve the title from database and only load the rest from website.

**Comment by StormJumper** [comment]
MangaHere

**Comment by riderkick** [comment]
Yeah, title in mangahere all caps.
