### ISSUE TITLE
If posibble favorite mangas show up with the different colors in manga list just like new mangas

### ISSUE THREAD

**Issue by darkcity87** [riderkick/FMD#289]
If posibble favorite mangas show up with the different colors in manga list just like new mangas
Sorry my bad english.

**Comment by riderkick** [comment]
When checking favorites?
Check for new chapters executed at the end after checking all items.
Maybe it's the time to review the source code, I believe there is some code that need to be fixing.

**Comment by darkcity87** [comment]
Highlight for favorites in manga list

**Comment by riderkick** [comment]
To check the if it's in favorites we have to store it in mangalist, but this is not always valid. When removing a favorite, we have to alter the record in database too. While the database is closed, we need to open it first.
The other way is to check directly in favoritemanager, going through all the record to find the exact record. But considering how much the cell painted, it will just make the ui sluggish.
Both way will only burdening the system. To much sacrifice for a little gain. 
I opt to reject this request.

**Comment by darkcity87** [comment]
I see then close issue. Thank you for your effort.
