### ISSUE TITLE
add download speed

### ISSUE THREAD

**Issue by MammothJerk** [riderkick/FMD#29]
could it be possible to add some info on the download speed?

![](http://puu.sh/hRxyX/6ccb7359e4.png)
in this area it could say something like "downloading x chapters at 300kb/s" or something along those lines?

**Comment by riderkick** [comment]
It is. But because we use multi-thread per task. We have to synchronize all the thread and it's not that simple with current download manager, we need to restructure it to more easier. It's on my to do list. I don't have time to implement it yet.
