### ISSUE TITLE
SenManga doesn't load manga info

### ISSUE THREAD

**Issue by Melvinkooi** [riderkick/FMD#290]
When clicking on a manga in the manga list of the site SenManga, it doesn't load. The manga info page has three windows with the second having the title as N/A.
Updating the manga list from server of from the webpage doesn't resolve this issue. It seems updating via website doesn't either.

![fmd_2016-06-11_22-11-39](https://cloud.githubusercontent.com/assets/11279045/15987226/9a199000-3021-11e6-9ff2-788b9df623f1.png)

FMD version is 0.9.63.0.

**Comment by kavin-90** [comment]
Because they don't use WP-Manga that is why it stopped :laughing:
