### ISSUE TITLE
Weird behavior between fav or manual download

### ISSUE THREAD

**Issue by 7h3Cub3** [riderkick/FMD#291]
I noticed something going weird when you get chapters from the favorite check, or when you get them by manual downloads.

It seems that it doesn't apply the same filename naming scheme set in the option when it's the favorite checking that download the chapter. i've set my chapters filename to contain %CHAPTER%_%FILENAME% and that's it, i don't create any folders from manga or chapter name.

So the normal behavior would be to name the file  like the above variables, and then zip them.

But when it's the automatic downloader from fav chek  that will download, it's gonna create a folder with the manga name, then put the files named 001.png / 002.png and so on then compress the files to create the zip in the manga folder.

it's like all the settings in "save_to" aside from compress as archive are the default of FMD when automatic check is done. 

I tried to let FMD download the chapters automatically, and then download the chapter myself manually. the behavior is always the same.

Could you please check if you use the same routine between automated and manual chapter download when it come to saving the files ?

Cheers

PS : Here is my current settings 
![capture](https://cloud.githubusercontent.com/assets/17658582/15987619/4e1a9f2a-302e-11e6-9cef-3887de9d8594.PNG)

PS2 : here is 2 capture i made first one is with automatic favorite download and 2nd one when i tried to download manually the same chapters, as you can see both have very different behaviors even though the settings are the same and only the latter respect my settings, automatic doesn't (it use FMD default)

![capture1](https://cloud.githubusercontent.com/assets/17658582/15988170/6f6ea12c-3046-11e6-92a2-cee01965c827.PNG)

![capture2](https://cloud.githubusercontent.com/assets/17658582/15988171/73206062-3046-11e6-923d-0a18e825894e.PNG)

**Comment by riderkick** [comment]
Auto generate manga folder only add manga name in creation time. In this case when add a favorite.
So the "Save to" value is fixed.

About custom filename, you're right. I forgot to add custom filename procedure to tfavoritemanager.

**Comment by 7h3Cub3** [comment]
i see thx for the info :)

Hehe no biggie, happy to have been of help :)

keep up the good work as usual you rock ;)
