### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by MarcusGHub** [riderkick/FMD#292]
I'm on Windows 10 Pro x64.
FMD is not updating
Installed Version : 0.9.61.0
Latest Version    : 0.9.63.0

**Comment by riderkick** [comment]
Check your permission and your antivirus. Try to run as administrator.

**Comment by MarcusGHub** [comment]
It was my mistake. I had renamed the executable file, so it was updated and the new executable was downloaded but it didn't replace the renamed one I had. It came with the default 'fmd.exe'.
