### ISSUE TITLE
Checking For New Chapter

### ISSUE THREAD

**Issue by Purplem** [riderkick/FMD#293]
Whenever I run a check for a new chapter, it queues a download for everything on my list.

**Comment by nigredo-tori** [comment]
Same here. This started after 0.9.64.0 update.

**Comment by greenaar** [comment]
Occurs every run, regardless.

**Comment by Twoearle** [comment]
Same here, 0.9.63.0 works fine though

**Comment by StormJumper** [comment]
Same here re-download my manga but some had titles and some just had folder number for each episodes. Is this a check bug finding it's way back from previous?

**Comment by ratbunuts** [comment]
I have the same problem. Download the whole thing on my list

**Comment by chauvy** [comment]
i can confirm this issue too, for every run.

**Comment by rs3mk** [comment]
+1

**Comment by 7h3Cub3** [comment]
confirmed, the downloadedchapters.db seems to be filled in (even with the new chapters it queues for all your fav), but doesn't seems to be read when checking is done, so it will queue all th echapters from all your favorites each time the check is done.

**Comment by riderkick** [comment]
1 character that causing such trouble. :grin:
