### ISSUE TITLE
tumangaonline not complete list

### ISSUE THREAD

**Issue by rs3mk** [riderkick/FMD#294]
in web: http://www.tumangaonline.com/biblioteca/mangas/8652/Sousei-no-Onmyouji
![01](https://cloud.githubusercontent.com/assets/19628943/16077814/b1a7ef40-32c0-11e6-9c1e-6f48f4218561.png)

in FMD:
![02](https://cloud.githubusercontent.com/assets/19628943/16077925/618438b0-32c1-11e6-89bf-ab6a8ea85328.png)
![03](https://cloud.githubusercontent.com/assets/19628943/16077945/7d26919e-32c1-11e6-8add-5c983d6e85aa.png)

**Comment by riderkick** [comment]
The url was not valid. It's redirected to home page.

**Comment by ratbunuts** [comment]
no  update yet?

**Comment by riderkick** [comment]
Just rebuild your list from scratch, delete the data file Tumangaonline.db
