### ISSUE TITLE
checking new chapters shows every chapter available on website

### ISSUE THREAD

**Issue by adeelshuaib** [riderkick/FMD#297]
This is happening with the latest version.

whenever i check for new chapters for favorites, it shows all available chapters of the manga instead of showing just the latest chapter

**Comment by matoro** [comment]
Confirming this, although the issue is worded incredibly poorly.  Checks for new chapters of favorites are now downloading ALL chapters for ALL favorites, as well as overwriting old files, regardless of whether there are new chapters or not.

**Comment by riderkick** [comment]
duplicate of #293, #295
