### ISSUE TITLE
Comment not issue.

### ISSUE THREAD

**Issue by StormJumper** [riderkick/FMD#298]
With the last 0.9.6.4 manga update it did messed up alot of my series and I had to recover from the backup drive and hopefully this won't appear again. I think this is the second or maybe third time I've see this happen on FMD since I've used the program. But beyond that I think it's been a excellent project considering others I seen and tried were a hit and miss or you had to pay to use.

**Comment by 7h3Cub3** [comment]
Just wait a week or two before upgrading or make a backup. Dev is alone can't test everything, we're here for this lol, also it's provided for free...

**Comment by riderkick** [comment]
Please elaborate more.

**Comment by StormJumper** [comment]
@7h3Cub3, What exactly do you mean wait a week for stable release that is so vague it gives no real information to base on. I've download all release when I can expect 0.9.6.4(deleted now) because of the problem but FDM is stable already, the test is the many users using it already says it's stable.

**Comment by 7h3Cub3** [comment]
simple, when there is a new release of FMD, if you are afraid of breaking things, just wait a few days, then upgrade to it, this way if there is some sort of 0 days bugs you will not have any surprises or disagrements.

**Comment by StormJumper** [comment]
@7h3Cub3, Who said they were afraid of breaking things? And you have insider knowledge-when they will release updates? Bugs will be bugs, if your afraid of them your free to go use another software to read/download your manga.

**Comment by 7h3Cub3** [comment]
Now you confuse me, you were the one commenting having issue with FMD a few times, just giving you tips for the future to avoid having bad surprises.... Please close this confusing thread....

**Comment by riderkick** [comment]
You're talking about #293?
The bug have been fixed. And it's should not messed up your files. The bug is just mark downloaded chapters as new chapters, and shouldn't messed up your favorites.
