### ISSUE TITLE
failed task error

### ISSUE THREAD

**Issue by HypesS** [riderkick/FMD#30]
Since 0.9.9.3 (win64) i get some failed Task error , i delete the downloadedchapters.ini as you said: 
When i check for new chapters from my favorites it finds some new chapters (who didn't exist or better that wasn't released yet, i check the related manga site for any new chapter when i get this error) so when the task start in the download tab i get the task failed error.

i got this error both if i import my favorite list from the old 8.4.0 and also  if i manually add some favorites.
I try to delete the favorites.ini file and then manually add some mangas , belived was an import  problem from the old version, but still  the program give to me this problem when i check for new chapters

There is a way to fix it?

**Comment by riderkick** [comment]
I don't follow what you're talking about. And you didn't give enough information.
Every site had its own script. Maybe their script need to be change following website changes.

**Comment by HypesS** [comment]
i have my manga in the favorite list, same issue if i import my manga list from a previous version, or if i add manually the manga after deleting  favorite.ini and  downloadedchapters.ini 

i check for new chapter, after the check,  here the nagbox of new chapters
![1](https://cloud.githubusercontent.com/assets/12519425/7738146/b7100286-ff51-11e4-9fe4-2267f3618e21.JPG)

when i press download

![2](https://cloud.githubusercontent.com/assets/12519425/7738155/ccc80d1c-ff51-11e4-86fc-18829925d139.JPG)


if i check mangafox, no new chapter was released, last one for aoi for exemple was released the 5/5/2015.
so the program find new chapters that don't exist.

if i delete the tasks and i check for new chapters again the FMD find some other manga with updated chapters

![3](https://cloud.githubusercontent.com/assets/12519425/7738233/7a3ee2e0-ff52-11e4-9b53-400d58074c51.JPG)

and if i try to dowload since no new chapter was really released for those mangas i get
![4](https://cloud.githubusercontent.com/assets/12519425/7738249/94763e74-ff52-11e4-983d-cd4d82ccf0ef.JPG)

i dunno if is a problem just for mangafox couse i use only that site and mangahere for my mangas

**Comment by riderkick** [comment]
I just check it, it seems mangafox script for mangainfo doesn't work anymore. It causing the script to populate the wrong chapter's links, but show empty chapter on getmangainfo. Maybe the one from favorite doesn't clean up the broken chapter's links. So it's detected as new chapter. I will look for it.
