### ISSUE TITLE
kissmanga broken

### ISSUE THREAD

**Issue by 7h3Cub3** [riderkick/FMD#300]
well it seems they broke again kissmanga lol, website working well but not working with FMD.

cheers;

**Comment by rs3mk** [comment]
![sin titulo 12](https://cloud.githubusercontent.com/assets/19628943/16166005/055e0d7a-34ad-11e6-8117-80c70b9d2757.png)

Here it works.

But it has problems with titles that lead @

**Comment by 7h3Cub3** [comment]
Hum yep working again this morning, very weird, yesterday i had the error 'please check internet connection' even though the website worked properly. I don't see that same error you have rs3mk, but maybe it doesn't happen with all titles.
