### ISSUE TITLE
error open fmd_0.9.67.0_Win64

### ISSUE THREAD

**Issue by rubaru** [riderkick/FMD#303]
![capture](https://cloud.githubusercontent.com/assets/20039459/16186954/bcb53dc6-36f7-11e6-964d-d71482c46538.PNG)

**Comment by Mantus-TR** [comment]
I'm getting the same error -_- (Win-10, 64bit)

**Comment by 7h3Cub3** [comment]
Same here

**Comment by Wolfpup67** [comment]
Same here
![fmd_0 9 67 0_win64_error](https://cloud.githubusercontent.com/assets/8302307/16192725/ef56a57e-36b8-11e6-9b74-ec0f6343bdcd.png)

**Comment by chauvy** [comment]
after the last update i'm getting this error too

**Comment by rs3mk** [comment]
+1

returning to the previous version.

**Comment by riderkick** [comment]
It's doesn't throw an error with win32 version?
