### ISSUE TITLE
Exhentai returns N/A

### ISSUE THREAD

**Issue by Moranguinho** [riderkick/FMD#306]
Cannot seem to access Exhentai from the program, but can access it fine on the browser.

**Comment by riderkick** [comment]
You need an account, Options>Accounts

**Comment by Moranguinho** [comment]
Already added and was working fine, but after an update it stopped working, is there any other config that is required that was deleted by accident.

**Comment by riderkick** [comment]
It's working fine here.
![sshot-2016-06-22- 04-57-23](https://cloud.githubusercontent.com/assets/4972676/16246026/fc23864a-3835-11e6-90b1-4adfefe47f79.jpg)

**Comment by Moranguinho** [comment]
Is there anyway for me to be able to debug or get a log of what is the error ?

**Comment by riderkick** [comment]
Check your account again, make sure the status is "OK"

**Comment by Moranguinho** [comment]
![capture](https://cloud.githubusercontent.com/assets/20072883/16256549/3192f1a4-3853-11e6-90b0-36112c43a014.PNG)

Still no access..

**Comment by riderkick** [comment]
Can you try to use connection sniffer like smartsniff. it's http so you should be able to see it.
Post the response here as txt file.

**Comment by rs3mk** [comment]
It seems that blocks by location (country). When I change my ip I also happens.

![01](https://cloud.githubusercontent.com/assets/19628943/16271458/bcda6466-385f-11e6-9d51-cc6628182639.png)
![02](https://cloud.githubusercontent.com/assets/19628943/16271462/c0f5079a-385f-11e6-8592-87bc3e0879c7.png)

**Comment by Moranguinho** [comment]
Old response [TCP-Response.txt](https://github.com/riderkick/FMD/files/328600/TCP-Response.txt)

I fixed it by manually inputting the Get cookie from my browser to Websites > Advanced > Cookies for Exhentai.

**Comment by rs3mk** [comment]
Yes. It fix adding cookies EXHentai

![00](https://cloud.githubusercontent.com/assets/19628943/16281033/0de7e676-3888-11e6-8ee0-832a3342e3b6.png)

**Comment by riderkick** [comment]
Can be ip is temporary blocked. I don't have such problem, so I can't localize the issue.
