### ISSUE TITLE
favorites.ini not loading

### ISSUE THREAD

**Issue by bookimp** [riderkick/FMD#309]
When I updated to 0.9.69.0 my favorites are blank. I still have the works folder with favorites.ini  in it but the program is completely blank. Is there something I can do to have it keep my old settings? I would like to avoid having to find all my series again and re-setup the whole program.

**Comment by 7h3Cub3** [comment]
have you tried to rollback to previous version ?

**Comment by bookimp** [comment]
Sorry, whenever I open FMD it crashes now, I tried installing 
fmd_0.9.68.0_Win64 but it crashes when I try to save my options. Where 
is the favorites.ini folder supposed to go? When I open the zip there 
isn't a 'works' folder which is where it was prior to updating.


On 6/22/2016 10:11 PM, 7h3Cub3 wrote:
>
> have you tried to rollback to previous version ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/riderkick/FMD/issues/309#issuecomment-227951524>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ATK7CJiAWxQ5FDQvhxsIiubFA8FuIUfTks5qOhWOgaJpZM4I8ba7>.
>

-- 
--Angel

"If life gives you melons, you're dyslexic..."



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by 7h3Cub3** [comment]
the work folder doesn't exist in the release zip, to rollback you just had to keep what you had and just dezip the previous release of FMD over it.

**Comment by bookimp** [comment]
That is what I did... it's ok, I can re-create my favorites if I have 
to. I've now overwritten the folder with 68 & 69, neither of which 
worked. They have no favorites & crash when I try to update the options.


On 6/23/2016 9:32 AM, 7h3Cub3 wrote:
>
> the work folder doesn't exist in the release zip, to rollback you just 
> had to keep what you had and just dezip the previous release of FMD 
> over it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/riderkick/FMD/issues/309#issuecomment-228106937>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ATK7CP67btlpesvSqRkuXkhdFU91unx5ks5qOrUggaJpZM4I8ba7>.
>

-- 
--Angel

"If life gives you melons, you're dyslexic..."



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by riderkick** [comment]
works folder automatically created when there is none, so does all the config and favorites file.
Check your permission or antivirus. Try to run as administrator.

**Comment by bookimp** [comment]
Yes! 97 works and all my favorites/history is back!

**Comment by riderkick** [comment]
There is nothing changes related to this issue. I believe your issue is due to permission or your antivirus interfere. It's have been discussed before. Modern antivirus comes with sandbox mode which run new file in limited access, but they will run in normal mode once the files have been scanned and clean. Maybe you just don't give it enough time to scan.
