### ISSUE TITLE
Can't slide the splitter between downloaded chapters and the manga list

### ISSUE THREAD

**Issue by SilentNN** [riderkick/FMD#31]
I just manually updated from 9.9.1 to 9.11.0 (x64 for both) because the updater hasn't worked for that since back then. Now I can't slide the splitter between the downloaded chapters list and the manga list with the mouse. Going to config.ini and editing the line MainSplitter=x allows me to change the width of the manga list, but the slider appears to be on the left of the manga list and doesn't drag at all.

I'm not sure if I goofed on the update, but I made sure to delete downloadedchapters.ini and replaced everything asked for except for mangalist.ini.

**Comment by riderkick** [comment]
Yes, I accidentally move the splitter to the left side of manga list.

**Comment by SilentNN** [comment]
Thank you! Blazingly fast response. Excellent program.
