### ISSUE TITLE
tumangaonline change url

### ISSUE THREAD

**Issue by rs3mk** [riderkick/FMD#310]
old:
http://www.tumangaonline.com/#!/biblioteca/mangas/12131/Dragon-Ball-Super

new:
http://www.tumangaonline.com/biblioteca/mangas/12131/Dragon-Ball-Super

![sin titulo 40](https://cloud.githubusercontent.com/assets/19628943/16428751/f05b381e-3d38-11e6-8697-fff68b434536.png)

**Comment by riderkick** [comment]
If you able to see the manga info, that's doesn't matter. Because they use API to get the content.

**Comment by riderkick** [comment]
The problem is due to it's fail to get the chapter API url when there is multiple scanlation in 1 chapter.

**Comment by rs3mk** [comment]
It is right. The problem is with multiple scans in a chapter.
