### ISSUE TITLE
Visual glitch: Download list not displaying properly

### ISSUE THREAD

**Issue by rbwz** [riderkick/FMD#312]
Let's just say i got several hundreds of downloads, and some have completed, the other still in queue, and there are some stopped and failed too.

I use download list tab, then use filtered display (anything other than "all download")
When I change sort to something (from name to date added,, for example). The download list displayed would screw up, displaying mixed stopped and running, etc.

this can be cleared by "refreshing" the list by clicking once on the desired filter.

I suspect (and no more than suspicion alone) this is because when the filtered display is clicked, the program created a list (based on "all download" list) that fit the filter, and numbering it, then only display the tasks that's on the filter list.

However when the "sort to" is used, the "all download" list is rearranged, but the filter "list" does not being updated, and thus the filter displayed wrong tasks

**Comment by riderkick** [comment]
The list is virtual, only pointed to the index. Thus it need to recalculate again.
