### ISSUE TITLE
[Req.] Color highlighting on favorites list for manga that has no chapter.

### ISSUE THREAD

**Issue by GramMKII** [riderkick/FMD#316]
Sometimes Bato.to would remove chapters due to violations of their guidelines. It would be nice to have this so I would immediately know that I have to switch to a different manga website.

**Comment by riderkick** [comment]
The drawback is, currently current number only updated when there is new chapter found, this is to preserve the chapters count in case if there connection issue or server error. Without then the favorite will be shown with 0 chapters count. The program don't know if that count is valid or not, you're the one who have to investigate it.
Are you OK with that.

**Comment by GramMKII** [comment]
Yup, I'm OK with that.
