### ISSUE TITLE
Download menu cleared after updates

### ISSUE THREAD

**Issue by midi1996** [riderkick/FMD#319]
for some reason, after "some" updates, my downlaods list is cleared, and no, i did not clear it as i keep tracking my downloads and updates. After that, i do not get the latest releases of the mangas i added to favorite until i dl it manually and kinda "update" the latest downloaded chapter.
this happened to me from time to time when i update fmd. hope you fix this.
thanks

**Comment by riderkick** [comment]
Please elaborate more. What version. and other information.
"time to time" is very vague. Try to search the issue, maybe it's already fixed. I recall an issue about broken ini files have been reported before.
