### ISSUE TITLE
Kiss issue

### ISSUE THREAD

**Issue by 7h3Cub3** [riderkick/FMD#320]
I still seems to get issues with kissmanga, it doesn't hang at all, but it seems to not be able to get anything neither manga infos or chapters list, or favorite check. nothing work. I checked the connection retry and so on, any number (-1, 10, 1, 3, 5) nothing do.

Cheers :)

**Comment by Hexaf** [comment]
Try connection time out 300, number of retry 20. With that setting I got no prob with kissmanga.

**Comment by 7h3Cub3** [comment]
Thx for the tip, sadly even with that setting i get no result :(

**Comment by 7h3Cub3** [comment]
okay it seems that after a day or two you need to restart FMD so that kissmanga connect again, maybe something need to be reinitialised i dunno, when i see that kiss give you 0 chapters per manga, i just restart and it work directly again :)

**Comment by riderkick** [comment]
There is nothing need to reinitialize. Cookies always updated every request if necessary. It just CF server sometimes refuse the token. Try to increase retry times and connection timeout.
