### ISSUE TITLE
MangaHere Splitting update?

### ISSUE THREAD

**Issue by StormJumper** [riderkick/FMD#322]
I noticed lately for one series: 
ReZero kara Hajimeru Isekai Seikatsu - Daisanshou - Truth of Zero

In where the update always makes their own separate folder and never in the folder there suppose to go to but when I delete and redownloaded ReZero kara Hajimeru Isekai Seikatsu - Daisanshou - Truth of Zero instead the folder is all CAPS.
RE_ZERO KARA HAJIMERU ISEKAI SEIKATSU - DAISANSHOU - TRUTH OF ZERO then when it updates the update are in a separate folder: ReZero kara Hajimeru Isekai Seikatsu - Daisanshou - Truth of Zero
Is there something wrong in the MangaHere script that it can't seem to find the right folder to save to?

**Comment by StormJumper** [comment]
Found another series that was completed but did the very same problem.

E_ HEIBON DESU YO__

**Comment by StormJumper** [comment]
This is with version 0.9.74.0

**Comment by riderkick** [comment]
Mangahere using all caps for their info page. The proper case only available in directory. If you load not from mangalist it will all caps.
Favorites download location and manual download location is independent.

**Comment by StormJumper** [comment]
Not sure what you meant "if you load not from mangalist it will all caps?"

**Comment by riderkick** [comment]
Proper case only available in manga directory. Thus only work if you load the manga info from manga list. if you load it by putting the url in manga info tab, then it will be all caps. Just check the website.

**Comment by StormJumper** [comment]
You mean my favorite list right? If not can you give me a screen shot or instruction what your telling me to do?

**Comment by riderkick** [comment]
No, I mean the manga list on the left side.

**Comment by StormJumper** [comment]
I let it do auto update and that is when it breaks the manga series to a separate folder. And only when I delete both and redo download in selecting all the chapters does it return back to normal some are still CAPS and some lower case.

**Comment by riderkick** [comment]
Auto download from favorite will inherited the title and download location from favorite. Base download location will not change. But the sub folder can be changed if you change the "Save to" options, especially the custom folder.
But even if you change it, it will not alter the title(uppercase in mangahere), it will inherit the same title from favorite.
The commit above is just fixed "View manga info" from favorite doesn't copy the title from favorite.

My guess is, your favorite download location doesn't exist, or you delete it. Then you make the new download task manually which has uppercase title, that will make the uppercase folder. Since Windows is case-insensitive, directoryexist() and such will return true for any case.

**Comment by StormJumper** [comment]
No, it makes a totally new folder is what it does. Some mangahere if I just download the files and leave the folder it is fine but a few seems to want to create their own folder for updates. And I seen some where complete folder delete and the redownload folder was the same still as well.

**Comment by riderkick** [comment]
Favorite doesn't make folder, it's download task that made folder. And download task always follow "Save to" for download location. No website module made a decision for download location. It's all done in download manager. Following Save to options. So check your Save to options.
Give me your config.ini, favorites.ini and works.ini with troubled items.

**Comment by StormJumper** [comment]
ok, where do I send them to or do drag and drop them here?

**Comment by riderkick** [comment]
Just drop here. I believe github allow zip file. Or just append the filename with allowed extension.

**Comment by StormJumper** [comment]
Ok. 
[config.zip](https://github.com/riderkick/FMD/files/379261/config.zip)
[favorites.zip](https://github.com/riderkick/FMD/files/379262/favorites.zip)
[works.zip](https://github.com/riderkick/FMD/files/379263/works.zip)

**Comment by StormJumper** [comment]
Any updates to my problem?

**Comment by riderkick** [comment]
You don't even include your troubled task.
Like I said before, its follow "Save to" as download location. If it's automatic download from favorites it will take "Save to" from favorites to download task. The "Save to" is base location. It can appended with sub folder (chapter folder), or custom chapter in "Save to" options. It's always follow this simple rule. No website modules can change this.
If you download manually, the title may changed to reflect the website.  This title will be used as base folder if "Auto generate manga folder" checked.
Manual download and favorites download (auto) is two different thing. So don't expect them to be same.
Note that if download created from favorite's "View manga info" than it was manual download.

**Comment by StormJumper** [comment]
How do I get the "trouble task"? If it is splitting from the favorite save how do I make it save into the right location?

**Comment by riderkick** [comment]
I ask your works.ini with the troubled task.
There is no "KOI INU"  or "RE_ZERO..." in your works.ini.
The fact that you have uppercase title, that mean you open the manga info manually. Mangahere indeed has uppercase title in their manga info.

If you want to make it saved to the same location as your favorite, just set your "Save to" options the same as when you add the favorite. There is also "Save to" field in "Manga info" tab if you add the download manually from "Manga info".

**Comment by StormJumper** [comment]
The settings checked are the same nothing changed.

**Comment by riderkick** [comment]
Then it will be the same, just compare the "Save to" column in download list and favorite list.
