### ISSUE TITLE
Can't do redudancy for the list

### ISSUE THREAD

**Issue by jras13** [riderkick/FMD#323]
hey, thanks for recent update for different color i suggest before.... 
but now i have a lil problem, this is happened long time ago but now it really annoys me
can i remove manga from list? it's doubled and makes me hard for looking manga using scroll...
like this pics 
![aaaaaawdw](https://cloud.githubusercontent.com/assets/20046326/16760616/c8723cbc-4846-11e6-8e41-59c508a4d04e.PNG)
if anyone has a suggestion, please tell me...
thanks before, best regards

JrasDrasil13

**Comment by riderkick** [comment]
The primary key is the link. So if the website changed the url to the series this thing happen.
