### ISSUE TITLE
Feature request: Unsubscribe from downloads tab.

### ISSUE THREAD

**Issue by greenaar** [riderkick/FMD#325]
Sometimes I subscribe to something and it turns out to be rubbish.  It would be handy to be able to right click on it in the download tab, unsubscribe, and then delete task and data.

No clue if that's tough, if it is not possible please feel free to close this.

**Comment by riderkick** [comment]
I don't understand what you mean by unsubscribe. Do you mean to remove/reset downloaded chapter list for particular title?

**Comment by greenaar** [comment]
I mean if I've just downloaded a title (and it's in my downloaded tab), and i realize it's not my thing, I'd like to be able to right click on that title and choose unsubscribe, vs going to the favorites tab -- with a long list it'd be a huge timesaver.

**Comment by 7h3Cub3** [comment]
He meant, in the website manga list, you can right click "add to favorites" he want to also have "remove from favorites" i think it was asked quite some time ago but you replied that it would require @ the loading of the list that you check each favorite to put it under a specific color or something.

Maybe a workaround and i think it also would be interesting to have, would be to have a search box in the favorite tab like the one for the manga list, you enter a keywork and it search all matching entries in your fav.

just my humble opinion :)

**Comment by riderkick** [comment]
No it was different. Previous feature request is about highlighting the favorites in manga list. That will be requires to check the favorites very often. Going to loop every time it need to repaint is resource consuming. You know that when you scroll it will be repaint a lot, for each pixel the area moved.
What he asking is just to remove favorites from download list, that will be requires only one time loop(for each item).
Can be another sub menu in popup menu "Delete"
```
Delete > Task only
         Task + data
         Task + data + favorite
```
