### ISSUE TITLE
Add official Japanese manga reading sites

### ISSUE THREAD

**Issue by anonsubmitter** [riderkick/FMD#327]
Could you add these legitimate and official Japanese manga reading sites into FMD? You could probably get a pretty good idea of how the sites handle DRM and maybe even borrow some code by looking at the discontinued [Online Manga Downloader](https://github.com/atoxic/Online-Manga-Downloader/tree/0.1.0).

Sites:
[Club Sunday](http://club.shogakukan.co.jp/)
[GanGan Online](http://www.ganganonline.com/)
[Famitsu Comic Clear](http://www.famitsu.com/comic_clear/cl_list/)
[Manga On Web](http://mangaonweb.com/)
[NicoNico](http://seiga.nicovideo.jp/manga/)
[ComicWalker](http://comic-walker.com/)
More sites here: https://github.com/riderkick/FMD/issues/327#issuecomment-233966312

**Comment by kavin-90** [comment]
Gangan Online use Comic Walker Script same as Jump +

Club Sunday is easy to make.
Famitsu split image in 8 to 12 Parts.
NicoNico need Account

**Comment by anonsubmitter** [comment]
I can't find version 1.6.x in Online Manga Downloader's GitHub repo or on the [developer's blog](https://anonscanlations.blogspot.com/search/label/online%20manga%20downloader). Can you link to it?

Can you link to the Club Sunday PHP scraper?

**Comment by kavin-90** [comment]
you can save Image via F12 :)

**Comment by anonsubmitter** [comment]
I prefer to save it via Firefox's Media window, but yeah, inspect element works as well. It would be helpful to have a way to batch download it though so that I don't have to download ~200 images one by one.

**Comment by kavin-90** [comment]
My php code which is not good but it works

<?php 
error_reporting(E_ALL);
ini_set('display_errors', 1);

$string = "
var bookDir      = '/data_p/Tachiyomi/cl0461_0001',
        bookCode     = 'cl0461_0001',
        sId          = 'e7hjokjnf3kr5roaim8b9261cg7femem', // sidが渡されない場合は生成
        linkText1    = '',
        linkUrl1     = '',
        linkText2    = '',
        linkUrl2     = '',
        returnUrl    = '',
        startPage  = 1,
        endPage    = 0,
        openFlag     = true,
        expired      = false,
        hasSession   = false,
        supported    = true,
        
        refererHost  = 'club.shogakukan.co.jp',
        serviceName  = 'クラブサンデー',
        lastMenuNote = '',
        prefPageUrl =  '../pref.html',

        today        = '2016-04-28',
        //openDate     = '1456412400',
        
        AD_BANNER_FLAG = true,
        AD_SQUARE_FLAG    = false,
        TOP_PAGE_FLAG  = true,
        MENU_PAGE_FLAG = true,
        
        CDN_FLAG = true,
        CDN_AUTH_FLAG = true,
        CF_URL = 'http://d23tvpbm084vy2.cloudfront.net/',
        CF_KEY_PAIR = 'APKAI2FWA4UBOHOTAAYA',
        CF_PARAMS = {};
        CF_PARAMS['top_page0.png'] = '1461842419&GJok9ViIHdljwuD5UslZLyccf507l9y0NaTBdhRpHPliwLtTo~1O-LvOHeYwFOQvjsuN7jQuviTsMbeXX~FsFQEDyHyc1HAm570duKUTTu5X~mOa5kJ7-s1kNtpCTz3yAQt4w3B-AsGpcmWL~roaZspbBgW4uCwWZL6KCQ6sVgc_';
CF_PARAMS['top_page1.png'] = '1461842419&UBFBxYRdAWvE28a7ycjbnLR7H5KIfBglGjvEEyfqHFUgb-0aSNfs1Pp7HW~kC7yJNpIYv-8uoCN7hFFcJANvpxy-1ktNf4K9BLCATZrfOsqwd3DLqwWItfMDkCLxbf4LKlNABmCmqpseN2vdW53MXjikuRDTFGktoOH0Az-X6-k_';
CF_PARAMS['menu_page.png'] = '1461842419&T04qaOqhal9gi3Da73QFNGtfHMss2Yp7GKvochl3-v7RIkY-XYZNI2QxmWJNwprU9BvYPVY421kgL56j-igPpi7OeAkGDw1Wn~J~ECVIDrgyrJIpkqLQcqctFCVKLymbDylWzzCmrCG5G1X8vApjSXZMWkVvMyPJgvumjW4U1mM_';
CF_PARAMS['p00001.jpg'] = '1461842419&A3HZVfQuHNd-Kp0ayCMcSy7m3aIPlfO03fFVWxcD-ZNGUZa-uRYibBr6UlHHVQjmTuyNdO1EpUzsh7nD6-PUr3nDsZYsqWvoZ3Pqv-0QG4lw3njaaYxYZS~wENHBrJuFzrHLjfzW020HISC8rPXuZyQDUDolm~ZrkW3f0vN05oI_';
CF_PARAMS['p00002.jpg'] = '1461842419&LcRGLrg2dCvI2YMxkoi22E8~k-3XAXJleWxqDCLbK30yGpN123YCvSKo16zu9ekEsgnRLs06zi-VsAmGVo06CtrbS4pIN1vgdcFVILH6BHzoMaElCwSfw1Q34qPOd7sTV2wD0j0VnbzPaiHke6Dd3rMONkaiGjOGmXp82~IPB~8_';
CF_PARAMS['p00003.jpg'] = '1461842419&ZcvdHV5kpDf3Ppvmi0n67bHdab8oN7sGfBXXFQE66TQBJ7EI5~ooIK~10pEB4Nr34oAepYRMfaTzwTv7vwEMmdyJdfd~kgGh9FR50N1Sco9SeolmKlqJpnjG3RpWe6bFVzsO9eynvX4rxNhEJlMsgABEIMmdSpXSoydE5~jvnaE_';
CF_PARAMS['p00004.jpg'] = '1461842419&cU6nN4VfouEPFWb66vSqbg-pVZjIoI1XtYpCt1vEfqgBYzr5VFwlJy7EUHVN9sFHk~oZMk-bSulmExemDikMtFpO3Rh-QJ9mer8UfZWMBhP3o64AmSqSycTKuw6TangD07GMPqHP0fsIrSxNlWWFS-p4MiA-Jgq0SAFQX8BfSeY_';
CF_PARAMS['p00005.jpg'] = '1461842419&ZXr9S81zI3tXDxYU75WKvCGhTuQ28fOjqVzYe4Mj6tPtYbPJuS4QoJC2pRthulPe3WjKtg-DfMGo5oN3wFg0G2g8KbAI9N5yK-EpqhTpoYZx85lCV-kQxTY6cBMfx6WCK1OJJePfMBZ9jqV3IDrbC35uQwGBZ8V0vK8zFfWy6XE_';
CF_PARAMS['p00006.jpg'] = '1461842419&dC1dwOdTwDyDcpSU4-kTlo3ycq2J8OW7HCovkDZFfjDg5uO1WfbI~fsdPxFxBzxK63yiUdqPYWU3uRhs5A6ACdXAs7W1zjfZLkn32PaE8CcCLzM7POuqewXYKm3iRLiCshLbvhzR4aHSfiwe1SdQDZSZ2ZMvmBiSpSJ0-s32w18_';
CF_PARAMS['p00007.jpg'] = '1461842419&a0D0jN6tqOOgwLUfjSdMe3-mqx7LkeN4pIriY5qF5M9ShfhRZt52G5uf~jvOxglTJrkWXJ7v-Da-ZbkBh-wHLljRnEPPEZyjGRdvT0vu3-DG5RnPw~6wU1yBfm-FEOwroB9NrVsr81hrDdQQGjgid5J5XplC0mwPfuT2qCEGhL4_';
CF_PARAMS['p00008.jpg'] = '1461842419&inE4JCeftXLLLXPWoWHpZAVvgbhhT8Ph~kJc~tqZcFE5mrNZWJBif5UWypWk1Xa3J-m4C1izcb5QBw0wsTUWD3jNSDSqliNmOZeDktiuRBCwh52sOjS6~FFKPVsXo0GM43qIlI56klvStJc0EXItNI4eG6AdjH4SBTkyfm3Bq3U_';
CF_PARAMS['p00009.jpg'] = '1461842419&GL9liogO9Y8OUDQMSrISY8AduV6JsxHjvjxdsvrHVmJku4ABZBSguzd1AuM-lc2fAvVbPBq5p2xG1gtUoSqVMTdHGFUxDbDPYk2tySQr0BTaZq2EcdPNDqewWDLR73w2mm5ntB~gXil6Z~qD7asiJcht9OApa8UYXGeDnl1K2E4_';
CF_PARAMS['p00010.jpg'] = '1461842419&RSz~Oz8qG~WExAdso4IzqQwiIWMffMlpiEPYOeGe55qiJbXHs9g23LxOR7dwBiBsUpTQ35jgAVWKjX5TMc~xaJ2MEfiACzRXzMBadFB3r3MJvU6k1WEUOXY3yBXreLguN7nBuHBpiIKWLBVLFHNTvWrZ9nmRclRELOTpUhHW2hg_';
CF_PARAMS['p00011.jpg'] = '1461842419&IxcN9ZBioZNBjsDxbe8a2fd-XgxW~SXVrLUvOXXtRpoWIEmEx2v7DZJWbX5jD3V7rbFYzjaDzFLLDyRpARzPXPo2IdBe0b3D9r-bLmiZTRA7IXjMa6OTBZg9Bpl2AFpfZWyB2TCYnBoJrobJXGBNXRsMxbF2FvehICpgFNRzsuM_';
CF_PARAMS['p00012.jpg'] = '1461842419&HTWsRgUWVAxHfHAedB0ZkX83yGz0R~Q13Ra-vXQexszfo3kL2RRmzV4zIFK8m3SieysfBogi3MkkfCv~uRa2gjcl6FOF~UxMHHdyx48h~dp9QjwuylnaREc0oBUFVxgX9H~K9nTOe1LmdYJSSon72YZmZX5-L31d~MWQT6euPpo_';
CF_PARAMS['p00013.jpg'] = '1461842419&hqg08bBxNaeDbvrTsHvg5rC0BY7kXExoyYzuLhaIbkC236N5vJIGV-5NqZGiyDBJUhpT7zJo0YXd3d9lMzOfz-hmYHdOyUxLUp5j-PoSHkB~wsVnK~Bvwb7Iupi6bnPjIc0hxCQwyiiRWVNd2VozFLcjmkurrFAhwmOujQqHwe0_';
CF_PARAMS['p00014.jpg'] = '1461842419&e5i5JH4W6y3B5zNnIkxNxnW0azO3ovhW~ojg~d5Cc2Nfd5qKvhnOsENaw8O0g416ZCAB-G7l5lKLE~s0S4KOpfLmjy4WgGs897hDY0f9x0z5wegamXj75nuNfqaypMHRsGShgr9ZaIV8a~Jyt46~PjleNX0qBTWIzHNte096JQI_';
CF_PARAMS['p00015.jpg'] = '1461842419&EUUgC8ckDspPYl9GpX4TJceLrOAi5plpMLRpm-xz9gA5Sruxhb3kr8Z1153xng5qNRiwyCDm2LFhW16XcB93KEXy5d1iSk5ZjWQ0K7QnL0P2PeU73IQ1o~BZybrEkjTSWLXsOJ9XE1nDfAUMqmoBmKklF~r57tdkg5ZdwmEnmpg_';
CF_PARAMS['p00016.jpg'] = '1461842419&iZtRmQl3uKTmRZXUut-pw3DMJkXBG5mCc7KAuQDM21CYsofi5iYiHw8kQJlb35voSXzvSYicX8Rp1ahWhjIL50659yeF~LQo-2qKWF2YhSlZ9XRhbmLTkWfvMKlomUeV~ehoueutRCmESiAiqgJsZLJndaD7ajoNDC7UP63YRoE_';
CF_PARAMS['p00017.jpg'] = '1461842419&dH8tAw~4hkqz8-1s9jYDzDIA8dOWe49Y-DustSY26PcMxmsgVCHPAsJfvhxxfacvVO-8DIze20uTNPzwE0HBni3o-oSqP20pIExLDbZ3LLubCYQX6jxiY29T-IpB8Rir~LWl7sYYifAtbdyjia-m8xr4ZP1YjcsROPL4nJ0hYkg_';
CF_PARAMS['p00018.jpg'] = '1461842419&EaVmu0XmOShCR-6wrODFYFBpJRp6rBzaaL3E5JEEpxSwkwULjPIdG64ZgOUBhuQMp3thU1JGxw-aRS1bMMp6Vn044RmvN9JNZP1ZzsXQ907gO8KpwP3aP7BMpKLPuPIMCFl3NxppzVAwcBUOmo36wE394L~lAST0bbFRMEeiH4Q_';
CF_PARAMS['p00019.jpg'] = '1461842419&J-XbVxQ7D9c0Xf6KniqoEr8YZHnbOMszD17TPJEI9IteCFxQQO9xp9mUM7vfOFr6ssKDYaej-IIdJWW2cYulUeCKtvoaNX1nylGkzakY~T9sPFCcnMdVaruhyv63iuiVT5yMqqNQICw89rj4Lzyd8Hlf~D0lTR01H-lsZWiuucg_';
CF_PARAMS['p00020.jpg'] = '1461842419&GuaifB3utw~QV9D3rjEAKVAPpZgcpPD5d787qTYS9rF4io9iCJMHRwqdkxHxadKNhEkkJWsGXqvqRpCETF2SDlqrtTvw736EDvE7WfMgJpSppjDNyoX-rPHbtOl-o~CNSfyL9L-ffFgxJr0YMpXXIkPM97QhMtlZZMS02L3-aFc_';
CF_PARAMS['p00021.jpg'] = '1461842419&P6XZ7Hd1OBx-JnqUM6MDQ6nrUsimNyjW46LMaUKFYV0NzcJDQ8gP9lM4ug6uPKAsGBTa5dhhV3y-I5XhFFbHXND32yYjXafpUruQadWiOU3vKY5ihYJUkin6VapytRg3A7KBKEzebl144hgfSu~dnh2BEwv6DOGngU7mYAN1I1k_';
CF_PARAMS['p00022.jpg'] = '1461842419&W4XIf-HyoZzo6bY3OqGtgGXnUecI44gimUS5n6pY1WzyC1LNvkdCRNchdSzr4Pa-KlMhs44PEVQj7-frpPSRhxQ9x91AfeszrnQIhXyPlo~Lfl2EWEJa~sb4U1zSM7n8rWy8vh8HbytVUmRWf1ONQxJS8Q2GFbHIfjHGSnGZ6EU_';
CF_PARAMS['p00023.jpg'] = '1461842419&TCLAfT7OBQMbNS1CqjG4-pczcYnNvr5treVg3ysyujBlcLqNwcCfJigQ7kkjnOD4aYwsPwLkQLywhp2hU7deCy6hLRmibTqH3fkebiRdqofT6qaKSqVj9RbLM6-bOwNeUlESMdBotIopp7ESQXhtO4qjguYqOWVq8AqNJDGF4~I_';
CF_PARAMS['p00024.jpg'] = '1461842419&cchyA~17rYZswHU~Zw5sgX2oHNzKm5ks3wVCVB-TAKQnD5F9UU2W7QtBmx0brZ-U7D9vEYCGNYa-sJ5iXkRrIX1I26-nOnTkD1St3RZFR6br6nZErE~OOMt6YJOI~n2utNBNsNa6GUvFXRnDmLxcS4N7FRP6GQg7EwOeyoUpNEs_';
CF_PARAMS['p00025.jpg'] = '1461842419&TyuEOSM699pK6rHHlZ7BNn0RaSzrkKJ8KtXljJnEXw~Ex8fqmvaJ4yDhXUAM3glDLVHp3s9xa8fYKvx4FOAkj2p5rXT9rl7piWoqSmNpIyPkpiNFKqc5jnJDzPVy5Xwh6XBmN9PIEYh67ShS2H0wl860Bq7nnJYjICsmzfhf~QU_';
CF_PARAMS['p00026.jpg'] = '1461842419&F3yZjIZhFD3uDLCRuVohy2EJH9W60KegZBBsgrsY~WEMskor~4w-FvcCOhSwMULsmohQEZ5d8MFAcpQ7Aglia-TLXLCewy1k5zIfPmWp2PMio1W5tGOQGXUdF0XxFQ1yqLL7JRCeurjSjLRuH~7Y3rWcIe3i93S7-8ToBAyxJfU_';
CF_PARAMS['p00027.jpg'] = '1461842419&Qxm7~-AmqW~LuCH3uNypPJCrqJEuEFbntxnIlHP033lNtz6DP9Jd214ph99CiaOBzbRWppQIrWQDLmgSEz85UaGdHmxyFOUBOtpgVrc2VZbdIqUWZ3twhJN8PQWwZhGINiVKjVsA8UsCx1zsrLJSnBS10JS~hSMhI8KJKvifNJU_';
CF_PARAMS['p00028.jpg'] = '1461842419&TfyRiduxxZB7NOIZdJ7opLeda7q~ZwQlqM7FU7MnxuuOgZadJ3DO-yEXz5o0dMplHDcaJBG499tbsWNycIOU~gEOUlKR7n5WgeilXdl0ZP8Tv3X30aac8md-72AingENH2juoaAffwWJ80M3fZkfpxjYSuGW8sS2y7RS2omHngA_';
CF_PARAMS['p00029.jpg'] = '1461842419&kU1HuXrqVfMPO1g34Dtq7CzMnCEw5Xo7tAa2qTDgkt17C8-OkQ6kZFE2M6-RxBfu~r5mNGPbddlJIorTnvJiEWLcagXj5RPR8p88C4l4nt8oLeXaUuWSJLDAy6ir0Zii0GdNgLEv5TZ5S8n~fijMc1rEoEyjSI4lX3vDf8FI5Ko_';
CF_PARAMS['p00030.jpg'] = '1461842419&fJIf4aK5rwBFO3vNvO-B9PdFFVSsrrW2EU~TSLzDQkRIll4sF8DLC6RpTUeL6jxRcIyPajsReu44rGUByzQVPadx97dew-hHc4FQajyNDBPC-bn87gSi08whc8frubVO2uHtBwwsIYwxfXXePUslZZMnh5KurBNmDAshEdmMjZ8_';
        
        //alert(navigator.userAgent);
        //alert(IMAGE_URL);
        
";

preg_match("/bookCode     = '(.*?)',/i", $string, $book_code);
preg_match("/CF_KEY_PAIR = '(.*?)',/i", $string, $get_key);

preg_match_all("/CF_PARAMS\['(.*?.jpg)'\] = '(\d+)&(.*?)'/", $string, $output_array);

//$new_array = array_combine($output_array[1],$output_array[2],$output_array[3]);

$mi = new MultipleIterator();
$mi->attachIterator(new ArrayIterator($output_array[1]));
$mi->attachIterator(new ArrayIterator($output_array[2]));
$mi->attachIterator(new ArrayIterator($output_array[3]));


$key = $get_key[1];
$book_code = $book_code[1];

$i = 0;
foreach ( $mi as $value ) {
$i++;	
list($file_name, $expire, $signuture) = $value;


$url = "http://d23tvpbm084vy2.cloudfront.net/data_p/Tachiyomi/$book_code/$file_name?Expires=$expire&Key-Pair-Id=$key&Signature=$signuture";

$content = file_get_contents($url);
file_put_contents("oh/$file_name",$content);

}

**Comment by kavin-90** [comment]
My Club Sunday Scrapper

`<?php 
error_reporting(E_ALL);
ini_set('display_errors', 1);

function create_dom($url,$follow=1) {
$ch = curl_init();
curl_setopt( $ch, CURLOPT_USERAGENT, " Google Mozilla/5.0 (compatible; Googlebot/2.1;)" );
if($follow==1){
curl_setopt( $ch, CURLOPT_FOLLOWLOCATION, true );
}
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt( $ch, CURLOPT_REFERER, "http://www.google.com/bot.html" );
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 9999999999999);
curl_setopt($ch, CURLOPT_TIMEOUT, 9999999999999);
$result = curl_exec($ch);
return $result;
}


function get_page($url){

if(!isset($url)){

die("Invaild Url");
}

$string = create_dom($url);
preg_match("/bookCode     = '(.*?)',/i", $string, $book_code);
preg_match("/CF_KEY_PAIR = '(.*?)',/i", $string, $get_key);

preg_match_all("/CF_PARAMS\['(.*?.jpg)'\] = '(\d+)&(.*?)'/", $string, $output_array);

$mi = new MultipleIterator();
$mi->attachIterator(new ArrayIterator($output_array[1]));
$mi->attachIterator(new ArrayIterator($output_array[2]));
$mi->attachIterator(new ArrayIterator($output_array[3]));


$key = $get_key[1];
$book_code = $book_code[1];

$msg = '';

$i = 0;
foreach ( $mi as $value ) {
$i++;
list($file_name, $expire, $signuture) = $value;


$url = "http://d23tvpbm084vy2.cloudfront.net/data_p/Tachiyomi/$book_code/$file_name?Expires=$expire&Key-Pair-Id=$key&Signature=$signuture";

$content = file_get_contents($url);
if(file_put_contents("oh/$file_name",$content)) { $msg .= "Page Saved $i"; } else { $msg .= "Unable to Save Page $i : $url"; }
}

return $msg;
}



$get_url = "http://club-page.comsho.com/script/dl.php?param=tTifriLmv0kgdAG9GXJlBpBb3fnqcjRsMrrDxhW4XF4HeOTxeIC3ZDq7h1TeZTJbs%2BoN3uM6%2FnzFFzUjePs90HsgbzkhjuE%2Bhnx0j4b0UihtSuSct0SgISCgX7jPm9uT1dHk3nDYeqO1q0p5YNAxWbQpvuzky6ZtA4o8HYBp30CYrGSJ%2BL0Pfj7FlXZaJKI9";


echo get_page($get_url);


`

**Comment by kavin-90** [comment]
I also want Those site u mention :smile:

**Comment by anonsubmitter** [comment]
By the way, you mentioned Jump +. Is that an official manga reading site for the series in the JUMP magazines? If you have a link to it I'll add it to my original post. Feel free to suggest more official manga reading sites if you know any more of them.

**Comment by anonsubmitter** [comment]
How about replacing
`curl_setopt( $ch, CURLOPT_REFERER, "http://www.google.com/bot.html" );`
with
`curl_setopt( $ch, CURLOPT_REFERER, "https://www.google.com/bot.html" );`

TLS/SSL is always nice.

**Comment by kavin-90** [comment]
http://plus.shonenjump.com/
http://comic-meteor.jp/
http://comic-polaris.jp/
http://comic.mag-garden.co.jp/ [4 Magazines]
http://www.alphapolis.co.jp/

**Comment by riderkick** [comment]
I'm kinda busy, new website request priority will be at the bottom of my to-do list. Don't expect it to happen sooner. Adding new website is time consuming.

Pull request or patch is welcome.

**Comment by anonsubmitter** [comment]
Ok. Thanks for putting it on the to-do list anyway :)

**Comment by anonsubmitter** [comment]
@kavin-90 you should put your Club Shogakukan PHP batch downloading script on GitHub by the way. (But replace the http:// with https:// in http://www.google.com/bot.html if you put the script on GitHub.)

**Comment by kavin-90** [comment]
@anonsubmitter you can put it too i dump whole file here already :smiley: 

i've comico scrapper too but not good though.

I'm gonna create repo for it by name scrapper

**Comment by anonsubmitter** [comment]
Here are two more:

[Sunday Web Every!!!](https://www.sunday-webry.com/)
[CoroCoro](http://corocoro.tv/webmanga/index.html) ([CoroCoro's older manga reader](http://corocoro.tv/tachiyomi/pokemon2/00.html))

**Comment by kavin-90** [comment]
Sunday Web Every Scrapper done :)

**Comment by riderkick** [comment]
@kavin-90 Most of it in github. Only lazarus-ccr in SF for RichMemo.

**Comment by kavin-90** [comment]
okay thanks.

**Comment by anonsubmitter** [comment]
[LINE](https://manga.line.me/)
You have to have a Japanese IP address and it could tell that my VPN service was a VPN and blocked access. It couldn't detect [Hola VPN](https://hola.org/) though, but that VPN extension is browser only and not very trustworthy: [1](http://adios-hola.org/), [2](https://8ch.net/hola.html), [3](https://torrentfreak.com/hola-vpn-sells-users-bandwidth-150528/)

If possible I'd like to suggest that this to the top spot of the "RAW sites to-do list" since the site scramble all pages into a puzzle of smaller images, so downloading images manually and stiching them together to pages in Photoshop is a pain in the ass.

**Comment by anonsubmitter** [comment]
@riderkick, @kavin-90 has made [batch download scripts](https://github.com/kavin-90/Scrappers) for Club Sunday, comico and Alpha Polis. Can you add them into FMD?

**Comment by kavin-90** [comment]
@anonsubmitter i've modules for FMD you can grab latest raw from them soon i will work on SWF ripper which will work on comic meteor , comic-polaris,hanayumeonline , comic blade etc

**Comment by ZhaoSin** [comment]
Please update!

NicoNico
ComicWalker
Alphapolis
