### ISSUE TITLE
Behavior for double click in downloads list

### ISSUE THREAD

**Issue by Ianunaut** [riderkick/FMD#330]
It used to be the case that double clicking a finished download would open the folder the chapter was downloaded to. Starting with a couple of version ago, a double click now opens the first available file in that folder.

I vastly preferred the original behavior. Can you make this available again?

**Comment by riderkick** [comment]
If you double click on "Save to" column it will open folder.

**Comment by Ianunaut** [comment]
Oh, I did not know that. Thanks!
