### ISSUE TITLE
invisible tasks

### ISSUE THREAD

**Issue by M9k** [riderkick/FMD#333]
![img](https://cloud.githubusercontent.com/assets/9288402/17106433/961e34ba-528b-11e6-8da1-8966fe695788.jpg)
When I download one or more chapter the download start, the program create the folder and all work fine, but I can't see any "in progress" tasks in Donwload, I can only see completed task, once the download ended the task appear in the list.
I was downloading "Koe No Katachi" for example, the current download speed is correct.

**Comment by rbwz** [comment]
probably an oversight, but... try the filter tab (the tab with folder icon, beside manga list tab), then try selecting all download.

**Comment by M9k** [comment]
It work, I'm so stupid, I remembered I edit something about but I didn't find it.
If I can, I suggest to edit the layout for made this thing more oblivious for new user.
PS: and maybe add the posibility to search a manga in more than one site at time? It's just an idea.
