### ISSUE TITLE
Mangainn.me Cloudflare error

### ISSUE THREAD

**Issue by ithieve** [riderkick/FMD#334]
Cannot view or download from Mangainn, shows a cloudflare. Anyway to bypass this?
![capture045](https://cloud.githubusercontent.com/assets/6398344/17237125/7a1bbd5e-5570-11e6-95cb-15779ad4f867.jpg)

**Comment by riderkick** [comment]
This is captcha required, I can't bypass it. It needs full working browser.
IIRC this captcha security only appear if there is to much traffic from some ip, so it's temporary. Or you can bypass it using your browser and add the cookies to fmd.

**Comment by ithieve** [comment]
Thanks for the reply. I see, well sucks they are using captcha. I am on a shared IP so I guess thats normal.
But... How do I add the cookies to fmd?

**Comment by riderkick** [comment]
Options>Websites>Advanced
