### ISSUE TITLE
Delete task/data/favorite does not work as expected.

### ISSUE THREAD

**Issue by greenaar** [riderkick/FMD#336]
Delete task/data/favorite removes favorite and task, but does not delete data.

Latest version.

**Comment by riderkick** [comment]
It's working fine here. Maybe the file is used by other process?
It's using the same method with "Delete task + data", just extra code to delete favorite.

**Comment by greenaar** [comment]
It's possible, windows seems to do some weird file locking operations.  Feel free to close this, I'll re-test when i'm able.
