### ISSUE TITLE
Exception/Terminate

### ISSUE THREAD

**Issue by greenaar** [riderkick/FMD#337]
Some download runs (ie when the application closed with items in the queue) trigger an application freeze and/or an exception with an unclickable 'terminate'.

Newest version.

**Comment by riderkick** [comment]
What is the error message?

**Comment by greenaar** [comment]
I unfortunately rolled back after a dozen unavoidable crashes. I'll roll forward and let it run, and snapshot the error the next time it occurs.

**Comment by greenaar** [comment]
Program exception!
Application       : Free Manga Downloader
Version           : 0.9.75.0
Product Version   : Win64
FPC Version       : 3.1.1
LCL Version       : 1.7
Target CPU_OS     : x86_64_Win64
Host Machine      : Windows 10 64-bit
Path              : D:\My Documents\FMDNew_2\fmd.exe
Proccess Id       : 10580
Thread Id         : 196
Time              : 2016-08-01 6:57:46
Ignored Exception : EImagingError,ERegExpr
Sender Class      : TDownloadThread
Exception Class   : EAccessViolation
Message           : Access violation
  In TDownloadThread.Execute : CS_DOWNLOAD
  Website : MangaFox
  URL     : /manga/tomodachi_o_tsukurou/v01/c039/
  Title   : Tomodachi o Tsukurou
  Chapter : 039 Identity Crisis

Exception Address : $000000010021FCFC
  $000000010000F170
  $0000000100350902
  $000000010001818C
  $00007FFFD3B99B7D
  $00007FFFD3B2595C
  $00000001000180EC
  $00007FFFD3B99AFD
  $00007FFFD3B24FE9
  $00007FFFD3B26C94
  $00007FFFD0C31F28
  $0000000100017B88
  $000000010008A3E6
  $0000000100350DE6
  $000000010034FD14
  $000000010042E88C
  $00000001002C5C92

**Comment by riderkick** [comment]
Release 0.9.75.0 doesn't have debug info, can you try with the previous version. There is no changes in this part, so it's should be raise too.

**Comment by greenaar** [comment]
I've rolled back to the previous version -- it does not error at all.

**Comment by riderkick** [comment]
[Uploading bin.7z.zip…]()

**Comment by riderkick** [comment]
Try this. Remove ".zip"
[bin.7z.zip](https://github.com/riderkick/FMD/files/396168/bin.7z.zip)

**Comment by greenaar** [comment]
Trying that now.

**Comment by greenaar** [comment]
Program exception!
Application       : Free Manga Downloader
Version           : 0.9.75.0
Product Version   : Win64 Debug
FPC Version       : 3.1.1
LCL Version       : 1.7
Target CPU_OS     : x86_64_Win64
Host Machine      : Windows 10 64-bit
Path              : D:\My Documents\FMDNew_2\fmd.exe
Proccess Id       : 12200
Thread Id         : 14164
Time              : 2016-08-02 6:12:28
Ignored Exception : EImagingError,ERegExpr
Sender Class      : TDownloadThread
Exception Class   : EAccessViolation
Message           : Access violation
  In TDownloadThread.Execute : CS_DOWNLOAD
  Website : MangaFox
  URL     : /manga/baby_steps/v28/c267/
  Title   : Baby Steps
  Chapter : 267 Story of a Pro

Exception Address : $0000000100012C90
  $0000000100012DD5
  $0000000100012022
  $0000000100370C59 line 210 of ../baseunits/extras/MangaFoxWatermark.pas
  $0000000100371D54 line 411 of ../baseunits/extras/MangaFoxWatermark.pas
  $0000000100370684 line 114 of ../baseunits/extras/MangaFoxWatermark.pas
  $000000010047066C line 147 of ../baseunits/modules/MangaFox.pas
  $00000001002D4722 line 597 of ../baseunits/WebsiteModules.pas
  $000000010034C285 line 1029 of ../baseunits/uDownloadsManager.pas
  $000000010032CB04 line 349 of ../baseunits/uDownloadsManager.pas
  $0000000100071BCD
  $0000000100003316 line 62 of md.lpr
  $0000000100013EB7
  $00007FFFD3708102
  $00007FFFD3B4C5B4

**Comment by riderkick** [comment]
Does it only occurs when you close the application?
Can you try again by running fmd with parameter (via cmd). `fmd.exe -LOGACTIVE 4`
There will be log folder with txt file inside. Post the txt here.

**Comment by jras13** [comment]
i've meet the same problem here sir...
![a](https://cloud.githubusercontent.com/assets/20046326/17362851/46ce43d8-59a1-11e6-801a-751b2d7aa6ca.PNG)
and sometimes when i just press continue.. FMD crash and stop working
btw here's a free proxy for access mangafox via FMD if u want to sir

185.28.193.95
8080
HTTP
let the username and password blank

hope this can solve the problem
