### ISSUE TITLE
AcademyVN info unattainable

### ISSUE THREAD

**Issue by blue-lightning** [riderkick/FMD#34]
FMD can't get any manga cover or chapter list, only Authors, Genres and Status.

**Comment by blue-lightning** [comment]
Now the info is displayed correctly, but adding to favorites doesn't work. The link was set to blank and I had to manually change it. Also, just adding a manga to favorites automatically send all of its chapters to DownloadedChapterList, is that an intended behaviour ?

**Comment by riderkick** [comment]
Add to favorites working fine here.
Yes, when adding new favorite item it will store all current chapter as starting point.
The downloadedchapterlist in favorites and the one from manual download is separated. But, It will sync later if you download some manga.

**Comment by blue-lightning** [comment]
Just did a check this morning. The problem lies in the MangaInfo's Address bar. Add to favorite from the left column works as intended, but loading manga from the Address bar and then click "Add to favorites" resulting in broken favorite item.

**Comment by riderkick** [comment]
You should mention that earlier. I will check that later.
