### ISSUE TITLE
Why did the manga list is blank? 

### ISSUE THREAD

**Issue by cicient18** [riderkick/FMD#345]
After I download and open the file, I have update the mangalist of some page, but even it has completed update, but the manga list still blank like this. Can you tell me what should I do? 
![untitled](https://cloud.githubusercontent.com/assets/20905752/17480748/ddf7bf8c-5d25-11e6-8fb6-99acd3f79285.png)

**Comment by riderkick** [comment]
Just do "Update list"

**Comment by TehBotolSosro** [comment]
Doesn't work for all site
here the log 

__MangaHere_templist].InternalOpen.Error!
               ESQLDatabaseError - TSQLite3Connection : unable to open database file
                 $00000001003AD47F
                 $00000001003AD2A9
                 $00000001003C6AA8
                 $00000001003AF539
                 $00000001003C799E
                 $000000010034D31D  InternalOpen,  line 443 of ../baseunits/DBDataProcess.pas
                 $0000000100350D12  CreateDatabase,  line 1105 of ../baseunits/DBDataProcess.pas
                 $000000010033EFA5  Execute,  line 599 of ../baseunits/uUpdateThread.pas
                 $00000001000697BD
                 $0000000100003266  $main,  line 62 of md.lpr
                 $0000000100013D87
                 $00007FFD12E92D92
                 $00007FFD15389F64

**Comment by riderkick** [comment]
That indicating and error while creating the file, check your permission and data folder.

**Comment by cicient18** [comment]
> Just do "Update list"

> 

But I have download and update the list many times. If I choose download the list, nothing happens. And if I choose update list, the program will run to update, but the result still be blank. I have tried with many manga page, but nothing changed.

**Comment by TehBotolSosro** [comment]
Ah thanks for the info, it seem the fmd program can't create data folder even when fmd have proper permission or running as administrator, the solution is simply create data folder and it can create the db file correctly.

**Comment by TehBotolSosro** [comment]
Anyway mangatraders is still not working (empty list)

**Comment by riderkick** [comment]
IIRC I've been put forcedirectories for data somewhere, because someone already reporting this before.

**Comment by riderkick** [comment]
@cicient18 I just checked, mangahere update list is working fine, maybe you suffer the same issue as @TehBotolSosro. Make sure to create data folder if not exist. updater.exe is not included in latest version due to compiling error and not monitored by me when building the release with batch script. You can get the updater.exe from previous version.

**Comment by riderkick** [comment]
@TehBotolSosro, yep. Mangatraders update list is broken. Seems like it needs to be rewrite.

**Comment by TehBotolSosro** [comment]
awesome thanks man :)

**Comment by cicient18** [comment]
Have solve the problem :3 Thank you so much.
