### ISSUE TITLE
Filter 

### ISSUE THREAD

**Issue by AkumaNoKage** [riderkick/FMD#347]
Do not filter works for the Russian sites. Can you fix it?

**Comment by riderkick** [comment]
Please elaborate!

**Comment by AkumaNoKage** [comment]
When you apply a filter by genre, all files are eliminated. If you take away what that genre, nothing happens.
How to download manga from HentaiChanRu? There is such a situation: 
![default](https://cloud.githubusercontent.com/assets/20558955/17643376/44dfd7ee-6171-11e6-916a-25e1b4d582e4.jpg)

**Comment by riderkick** [comment]
What genre? What website?
You have to describe it in details. I can't reproduce the same thing as you got if I don't know what you do.

**Comment by AkumaNoKage** [comment]
Video: https://youtu.be/Ps1D2doXS4M
Please you can also add an alternative "Change all all unicode symbols to "_"" only instead of the symbol "_" delete a symbol. To sdelatt shorter name files and folders from Russian sites.

**Comment by riderkick** [comment]
Filter work as expected, in hentaichan there is no genre. So there is nothing to show.
Note that genres selection in checkbox is hard coded for English only, to filter custom genre/another language you have to input it in custom genres field.

**Comment by riderkick** [comment]
It's a bug with hentaichan that's show no chapter.
