### ISSUE TITLE
Release on Mac ?

### ISSUE THREAD

**Issue by Kota-Kun** [riderkick/FMD#349]
Should we expect the release of the Mac?
Since my main Mac OS , windows and I go just because of your program.
I can collect myself, but in the process of assembling lots of pop up errors.

**Comment by Kota-Kun** [comment]
In order to build FMD from the source code, you must install Lazarus latest version and Free Pascal Compiler v2.6.4. Then you must install the following 3rd party libraries and components:
 - RichMemo, https://sourceforge.net/projects/lazarus-ccr/
 - Virtual TreeView, https://github.com/blikblum/VirtualTreeView-Lazarus/tree/lazarus-v4
 - Synapse, http://synapse.ararat.cz/
 - InternetTools, https://github.com/benibela/internettools
 - BESEN, https://github.com/BeRo1985/besen
 - MultiLog, https://github.com/blikblum/multilog

Please. send me your 3rd folder with your 3rd party libraries and components.
On my mail aleksey-nyaka@yandex.ru or google drive or mediafire.
And i am try build on my Mac.

**Comment by riderkick** [comment]
You can download from the url above.

**Comment by Kota-Kun** [comment]
On the Mac a lot of mistakes ((
Basically complains packages

**Comment by riderkick** [comment]
What packages?

**Comment by Kota-Kun** [comment]
![image](https://cloud.githubusercontent.com/assets/4346662/17643637/b17fbc6e-6178-11e6-94f6-0150a3b17794.png)
![image](https://cloud.githubusercontent.com/assets/4346662/17643639/c5bec530-6178-11e6-9f9d-2bd8e6d57d26.png)

**Comment by riderkick** [comment]
You have to install the required packages first.
And try `tools > rescan fpc source directory`

**Comment by Kota-Kun** [comment]
![image](https://cloud.githubusercontent.com/assets/4346662/17646615/784ebe24-61da-11e6-9618-2299c226cb35.png)

**Comment by riderkick** [comment]
It seems you don't have a basic programming knowledge.
This problem should be easy to overcome if you have a basic knowledge.
Compiling to another system may not straight forward, you may need to change some code to system specific.
For synapse, just head to the line and give the requirements, if it want a pointer, then give the pointer.
For Internettools, you can get FLRE by BeRo or just use Sorokin's Regex. The define condition is in the head of xquery__regex.pas
I don't have Mac, so I don't know the system specific, you can try to target the carbon first, I don't know the status of cocoa widgetset, what I know it's not complete yet. Some bug fix may exist in Lazarus trunk.

**Comment by Kota-Kun** [comment]
In pascal yes. I am use php, ruby.
> It seems you don't have a basic programming knowledge.

Please. send me your 3rd folder with your 3rd party libraries and components.
On my mail aleksey-nyaka@yandex.ru or your google drive or your mediafire.
I'll try to build of your source

**Comment by riderkick** [comment]
My source is the same with what you will get from the link above. 
I don't change the library source code, if so then I should've already release the changes somewhere, comply with the GPL rules.
Like I said may can't compile it straight away. You may need to change it to your system specific, whether the fmd source code or the library source code or both.
You can read at the link above if there is any information regarding your system. If you can't compile then you can ask them if you can contact them.
I can only answer the question about this project that is match with my system, I can't answer something that I don't have.
Don't treat the library that's used by this project as part of the projects, we only use them, question about the library specific should be asked directly to the developers of library or someone who have experience with it.
Alternatively you can ask at the Lazarus forum. http://forum.lazarus.freepascal.org/. There is a lot of helpful people that may can help you.
Like what this guy did http://forum.lazarus.freepascal.org/index.php?topic=30750.0

**Comment by Kota-Kun** [comment]
Thanks!
