### ISSUE TITLE
Very slow loading long lists

### ISSUE THREAD

**Issue by timgorden11** [riderkick/FMD#35]
Both 0.9.12.2 and 0.9.13.0 are incredibly slow to load long lists (like 5 minutes plus) no trouble whatsoever on 0.9.12.1

**Comment by riderkick** [comment]
Really? I did change the natural sort method. There is flaw on previous logic. But, I don't expect it to be slowing down so much. Don't use the long list then, I presume your long list is those h site, right? FMD can work without manga list. Just put the url on manga info tab. Or you can use drop box which introduced in the latest version. You can drag the link (sometimes the thumbnail also contain the link) to this box.

**Comment by timgorden11** [comment]
Nope lol, no h sites. Just a site list like batoto (mine currently has 13972 titles)

Loads instantly when switching between site lists of any length with 0.9.12.1 but takes forever if the list has more than say Mangastream on 0.9.12.2 and 0.9.13.0

Seems to be all fixed in 0.9.13.1 thanks.
