### ISSUE TITLE
Mangatraders & Mangastream & Updater problem

### ISSUE THREAD

**Issue by TehBotolSosro** [riderkick/FMD#351]
Hi,

Thanks for fixing mangatraders, it can download the manga list fine now, but it seem it doesn't detect any chapter (all title have 0 chapter)

for mangastream they now use mangastream.com so the current fmd doesn't work for them

thanks

**Comment by riderkick** [comment]
It seems there is wait time before the chapter list can be see (5 second), by click the . You can check it yourself with your browser. 
Let's see what I can come up with.

**Comment by riderkick** [comment]
Mangastream is working fine here.

**Comment by TehBotolSosro** [comment]
Ah i made a mistake thinking mangastreamTO and mangastream is the same :D 

yeah it could be great if fmd could also detect volume list in mangatraders not just chapter list,
but will try it first as soon i can figure it out how to compile the fixed version using lazarus

thanks

**Comment by TehBotolSosro** [comment]
hi

i'm trying to compile the source file using lazarus, and i already add all the packages except the besenpkg, i have no idea how to include that, could you explain how to install the besenpkg? as there is no lpk file in https://github.com/BeRo1985/besen

thanks

**Comment by riderkick** [comment]
Apparently the volume list always empty. I can't find one with it. It seems they purge a lot of manga since their website changed, so most of it is empty.

It's in "3rd" folder. I just make it to disable debug info. So the debug only focus on fmd source, also save some bytes on debug file. You should disable most of the package too in package options.

You may need to use lazarus trunk version. Google "fpcup" for easier 
setup.
There is some code that use FPC 3.1.1 and Lazarus 1.7. Of course you strip that out with compensation of losing some feature.

**Comment by TehBotolSosro** [comment]
Thanks riderkick will try fpcup with lazarus trunk now, as the v1.60 lazarus seem have failed when building the fmd exe (Imagesize not defined) 

anyway using fmd 0.9.77.0 seem fmd doesn't convert + or space on mangastream resulting in error

FMD : http://readms.com:80/r/naruto/700+10/2843/1
result <p>The URI you submitted has disallowed characters.</p> </div>

Browser: http://readms.com:80/r/naruto/700%2B10/2843/1
result no problem

Assassination Classroom Extra #1
http://mangastream.com/r/assassination_classroom/Extra%20%231/3329/1
not found 

http://mangastream.com/r/cage_of_eden/185%20%28End%29/1755/1

thanks again

**Comment by riderkick** [comment]
I'm writting manually the image size and should be compile able with FPC 3.0.0. Seems like not all image format have imagesize implemented yet,  so I'll just write it myself. 

I've been check that too, with login the volume is still empty. It looks like they just migrate the content to new server,  so not all series available yet.
