### ISSUE TITLE
Mangatraders no chapters showing up on certain Manga

### ISSUE THREAD

**Issue by Beylers** [riderkick/FMD#352]
Goblin Slayer and some other Manga on MangaTraders don't have any chapters showing up, even though they show up on the Website
![15-08-_2016_01-25-45](https://cloud.githubusercontent.com/assets/13386163/17652819/55ee8eba-6287-11e6-9e08-f7bdeb719b51.jpg)
I use the latest fmd version.

**Comment by riderkick** [comment]
Duplicate https://github.com/riderkick/FMD/issues/351
