### ISSUE TITLE
Can't download from MangaFox

### ISSUE THREAD

**Issue by LittleGamie** [riderkick/FMD#353]
Everytime I try to download a manga series from MangaFox it downloads to the end then gives me a "Failed, try resuming this task!" error message. When I resume it starts over and says the same at the end.

**Comment by riderkick** [comment]
Give me your works.ini

**Comment by LittleGamie** [comment]
My works.ini appears to be blank/empty.

**Comment by riderkick** [comment]
Tell me the Manga title that you're  trying to download.

**Comment by riderkick** [comment]
And the chapters.

**Comment by LittleGamie** [comment]
yuru yuri and chapter 1 - 123 (all of them)

**Comment by riderkick** [comment]
It's working fine here. Can you open it with your browser? MangaFox block some region based on IP, appear as "this series have been licensed" something like that.

**Comment by LittleGamie** [comment]
Aw yeah that was the issue, I assume a VPN will be needed. Thank you!
