### ISSUE TITLE
Komikid & Mangacan error

### ISSUE THREAD

**Issue by redberry6** [riderkick/FMD#354]
Komikd not working after they're change new template,

Screenshot : 
<spoiler><a href="http://tinypic.com?ref=jkf7dx" target="_blank"><img src="http://i67.tinypic.com/jkf7dx.png" border="0" alt="Image and video hosting by TinyPic"></a></spoiler>

And after update to ver.0.9.78.0 manga info and list chapter in Mangacan blank 

Screenshot 1 : 
<a href="http://tinypic.com?ref=2re0c53" target="_blank"><img src="http://i64.tinypic.com/2re0c53.png" border="0" alt="Image and video hosting by TinyPic"></a>
Screenshot 2 : 
<a href="http://tinypic.com?ref=29frn91" target="_blank"><img src="http://i65.tinypic.com/29frn91.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by rs3mk** [comment]
the same happened with tumangaonline

![aa](https://cloud.githubusercontent.com/assets/19628943/17722128/7650eb2a-63f5-11e6-992d-6821cb721318.png)

![aa](https://cloud.githubusercontent.com/assets/19628943/17722134/89266c20-63f5-11e6-81f2-be6edf61fc06.png)

with version 0.9.77
![aa](https://cloud.githubusercontent.com/assets/19628943/17722214/1e56fe0e-63f6-11e6-8019-b3cc50a8dfda.png)
![aa](https://cloud.githubusercontent.com/assets/19628943/17722219/29a290e8-63f6-11e6-9489-e1382d432b78.png)
