### ISSUE TITLE
Out of Bounds error with manual download

### ISSUE THREAD

**Issue by Tenome** [riderkick/FMD#355]
Program exception!
Application       : Free Manga Downloader
Version           : 0.9.78.0
Product Version   : Win64 Debug
Host Machine      : Windows 7 64-bit
Target CPU_OS     : x86_64_Win64
FPC Version       : 3.1.1
LCL Version       : 1.7
Path              : U:\Downloads\fmd_0.9.24.0\fmd.exe
Process ID        : 3148
MainThread ID     : 2240
Thread ID         : 2240
Time              : 16/08/2016 23:56:01.820
Exception Class   : EStringListError
Message           : List index (5) out of bounds
  $00000001000696CF
  $000000010014663F
  $0000000100160CD0
  $00000001001612C7
  $0000000100150D7E
  $0000000100160BFC
  $000000010000F836
  $00000001001458E5
  $000000010013BD74
  $00000001001C5F80
  $0000000100121311
  $000000010012192C
  $0000000076EA9BD1
  $0000000076EA6AA8
  $0000000076EA6BAD
  $000007FEFB740BBF
  $000007FEFB7447FE

**Comment by MilesWilford** [comment]
Same problem starting with the most recent update

```
Program exception!
Application       : Free Manga Downloader
Version           : 0.9.78.0
Product Version   : Win32 Debug
Host Machine      : Windows 10 64-bit
Target CPU_OS     : i386_Win32
FPC Version       : 3.1.1
LCL Version       : 1.7
Path              : D:\Dropbox\Apps\fmd\fmd.exe
Process ID        : 5940
MainThread ID     : 4328
Thread ID         : 4328
Time              : 17/08/2016 00:16:38.091
Exception Class   : EStringListError
Message           : List index (1) out of bounds
  $0045AD93
  $00516FED
  $0050E6FF
  $00582764
  $004F84C3
  $004F8A0B
  $757C84F3
  $757A6C40
  $757A613A
  $757A5EE3
  $73CF95AB
  $73D2E853
  $757C84F3
  $757A6C40
  $757A69D7
  $004F48D4
  $004F824E
```

**Comment by leoteesh** [comment]
hi, having the same problem with manual downloads, after the recent update
Program exception!
Application       : Free Manga Downloader
Version           : 0.9.78.0
Product Version   : Win64 Debug
Host Machine      : Windows 7 64-bit
Target CPU_OS     : x86_64_Win64
FPC Version       : 3.1.1
LCL Version       : 1.7
Path              : C:\Users\Tesh\Documents\fmd_0.9.34.0_Win64\fmd.exe
Process ID        : 6180
MainThread ID     : 7240
Thread ID         : 7240
Time              : 17/08/2016 07:30:06.534
Exception Class   : EStringListError
Message           : List index (3) out of bounds
  $00000001000696CF
  $000000010014663F
  $0000000100160CD0
  $00000001001612C7
  $0000000100150D7E
  $0000000100160BFC
  $000000010000F836
  $00000001001458E5
  $000000010013BD74
  $00000001001C5F80

**Comment by dianfajar** [comment]
I got same error.

**Comment by rs3mk** [comment]
Program exception!
Application       : Free Manga Downloader
Version           : 0.9.78.0
Product Version   : Win64 Debug
Host Machine      : Windows 8.1 64-bit
Target CPU_OS     : x86_64_Win64
FPC Version       : 3.1.1
LCL Version       : 1.7
Path              : fmd.exe
Process ID        : 22084
MainThread ID     : 16652
Thread ID         : 16652
Time              : 17/08/2016 09:07:45.629
Exception Class   : EStringListError
Message           : List index (1) out of bounds
  $00000001000696CF
  $000000010014663F
  $0000000100160CD0
  $00000001001612C7
  $0000000100150D7E
  $0000000100160BFC
  $000000010000F836
  $00000001001458E5
  $000000010013BD74
  $00000001001C5F80
  $0000000100121311
  $000000010012192C
  $00007FFD4B9C250D
  $00007FFD4B9E5FF8
  $00007FFD4B9C5823
  $00007FFD47EA1259
  $00007FFD47EA1234

**Comment by rs3mk** [comment]
solved, use https://github.com/riderkick/FMD/releases/tag/0.9.77.0 :+1:
