### ISSUE TITLE
0.9.78.0 Freeze and termination

### ISSUE THREAD

**Issue by StormJumper** [riderkick/FMD#356]
I just tried to download gal and otaku from mangago and mangafox and both would freeze up and I had to terminate FMD. I did give me a error but didn't get it saved. Just tried to use MangaHere to download a series and now it freezes. I think the lastest release has issues and any new attempts will freeze the download. Older already saved favorites will update without problem but any new manga series will stop the download and freeze. On MangaHere I tried to download C.M.B. Manga and that would freeze.

**Comment by amayra** [comment]
it has been fixed now just wait for new release

**Comment by riderkick** [comment]
duplicate #355
