### ISSUE TITLE
Kissmanga doesn't fetch manga page AGAIN

### ISSUE THREAD

**Issue by zqjpymbk** [riderkick/FMD#358]
When I try to check manga's page on kissmanga, it always resolves to "Please wait 5 seconds..." like so:
![5s](http://i.imgur.com/b2ouz0C.png)

I've tried refreshing the page, different combinations of numbers of retries and connection timeout periods, but looks like FMD triggers their anti-DDoS protection again.

**Comment by riderkick** [comment]
Try again with the latest version.
It's working fine here.
