### ISSUE TITLE
Hitomi.la can't be viewed and downloaded

### ISSUE THREAD

**Issue by arrianda** [riderkick/FMD#359]
After updating to v 0.9.78.0, I can't get the manga info from hitomi.la. It will give this result
![report](https://cloud.githubusercontent.com/assets/17354390/17780607/38f04a8a-6596-11e6-981f-9f866384332a.JPG)

**Comment by arrianda** [comment]
Fixed in next update, thx.

**Comment by riderkick** [comment]
Try again with the latest version (0.9.79.0).
It's working fine here.
![sshot-2016-08-18- 23-59-05](https://cloud.githubusercontent.com/assets/4972676/17781000/046ec354-65a0-11e6-9f81-a30432003a55.jpg)
