### ISSUE TITLE
Chapters with decimal points failing

### ISSUE THREAD

**Issue by matoro** [riderkick/FMD#360]
Upon upgrading to v0.9.78.0, FMD attempted to re-download all chapters with decimal points from all my favorites.  Each one failed, leaving an empty folder with no images in the download location.  Now, whenever I try to download a new series, all chapters with decimals in them fail in the same manner.

https://i.imgur.com/rgcZyRU.png

Thanks for your continued hard work!

**Comment by riderkick** [comment]
Give me the urls or better your works.ini

**Comment by matoro** [comment]
Sorry, I'm without reliable internet access right now.  Here's what happens when I try to download all of Boku no Hero Academia from MangaTraders:

```
[general]
NumberOfTasks=1

[task0]
Website=MangaTraders
Link=/read-online/BokuNoHeroAcademia
Title=Boku no Hero Academia
SaveTo=Z:\home\matoro\documents\manga\Boku no Hero Academia\
Status=Failed, try resuming this task!
Progress=
Enabled=1
DateTime=42600.4489507639
CustomFileName=%FILENAME%
ChapterLinks=/index-1!%~/index-1!%~/index-1!%~/index-1!%~
ChapterName=Boku no Hero Academia -- [0054] No. 53.5!%~Boku no Hero Academia -- [0064] No. 62.5!%~Boku no Hero Academia -- [0074] No. 71.5!%~Boku no H$
TaskStatus=STATUS_FAILED
ChapterPtr=0
NumberOfPages=1
CurrentPage=0
```

Weird save path is due to running under Wine, hopefully that's not also where this problem is coming from.  Up until now FMD has been running beautifully.

**Comment by riderkick** [comment]
Your chapterlinks seems broken. Try to re-add the task manually.
Tried with latest version without any problem.
Its should be `ChapterLinks=/read-online/BokuNoHeroAcademia/chapter-53.5/index-1!%~`.

**Comment by matoro** [comment]
Hmm, that is weird.  It seems to have been fixed at some point.  Will re-open this later if it crops up again.
