### ISSUE TITLE
Support for Batoto in Spanish?

### ISSUE THREAD

**Issue by Mariolr93** [riderkick/FMD#362]
Please add support for batoto in spanish....
There a mangas that a like to download and Batoto have better quality!

Thanks! / Gracias!

**Comment by riderkick** [comment]
Sample url?

**Comment by Mariolr93** [comment]
Here.... http://bato.to/reader#2847b5c398000b2c
A chapter in spanish... 
Don't know if helps

**Comment by riderkick** [comment]
`Options > Websites > Options > Batoto > Show all language`
You need an account to see all the chapters.
`Options > Accounts`
![sshot-2016-08-21- 14-24-25](https://cloud.githubusercontent.com/assets/4972676/17835705/0da454a4-67ab-11e6-92fb-7ee411077dd4.jpg)

**Comment by Mariolr93** [comment]
Well.... Thanks
I didn't see that...
