### ISSUE TITLE
Not work download from TMO (some)

### ISSUE THREAD

**Issue by rs3mk** [riderkick/FMD#363]
It has only happened to me with this manga.
`http://www.tumangaonline.com/biblioteca/mangas/16186/The-Sister-of-the-Woods-With-a-Thousand-Young`

![sin titulo 11](https://cloud.githubusercontent.com/assets/19628943/17833819/f2de8d50-66ed-11e6-8fba-616f0b3ab67f.png)

Thanks

**Comment by riderkick** [comment]
You need to re-add the download task, because the old chapter uri is broken.
