### ISSUE TITLE
E-Hentai

### ISSUE THREAD

**Issue by TehBotolSosro** [riderkick/FMD#365]
Is there anyway for fmd to detect if we reach the bandwidth limit of e-hentai? since as of right now it will continue downloading those reached limit image.

**Comment by riderkick** [comment]
Can we?
I don't even know how much the limit is.
What is the reply when the limit is reached? It's redirect to a new page? Or reply with different image?

**Comment by TehBotolSosro** [comment]
fmd continue to download those reached limit image as if it were the real page
but i will let you know more as soon as i reach the limit again,
thanks

**Comment by riderkick** [comment]
Is there any workaround to bypass it? Or we just give up and stop the process?
