### ISSUE TITLE
Eatmanga.com Download Issue

### ISSUE THREAD

**Issue by MangaCactus** [riderkick/FMD#367]
I tried downloading from Eatmanga.com but it only loads some chapters or even just single pictures
the download also stops after a few minutes and the site is down for me
so after trying several times i now got almost all folders of the wanted manga but in most of them there are no files or only a few
manga is pocket monster special btw

**Comment by MangaCactus** [comment]
i dont know where else to post this but could you maybe add mymanga.me to the list? the problem above would be solved with that too^^

**Comment by riderkick** [comment]
It's working fine here. Though its sometimes slow, probably server issue. Maybe you hit timeout too often. Try to lower the concurrent download, and increase the retry count and connection timeout.

**Comment by MangaCactus** [comment]
okay thanks, the site doesnt crash and there are no empty chapters anymore
But there are still a few missing pages in every chapter, even if i turn down the downloading files per task to 1 (and only one task running at a time)
i dont know why but this only happens with eatmanga, i dont have these issues with other sites
and FMD is a brilliant application anyway : D

**Comment by riderkick** [comment]
Which series and chapters?
I've been tried to download a few chapter from various series without any problem.
Do the status is "Failed, try resuming this task"?

**Comment by MangaCactus** [comment]
it's Pocket Monster Special and there's no message popping up at all, the download speed just goes down to 0Kbps at some point and the bar stays yellow/blue
i'm re-downloading every chapter again at the moment but there are still some missing files every other chapter

**Comment by MangaCactus** [comment]
okay pretty sure the main issue are the double pages, somehow these wont download
