### ISSUE TITLE
Hentai2read can't update mangalist

### ISSUE THREAD

**Issue by Hexaf** [riderkick/FMD#368]
After website maintenance FMD cant update manga list.

**Comment by riderkick** [comment]
It's working fine here.

**Comment by Hexaf** [comment]
Update mangalist after 5.

![capture](https://cloud.githubusercontent.com/assets/16042929/18251074/2dc68cd6-73b1-11e6-95cd-c286c96f1616.PNG)

**Comment by riderkick** [comment]
What do you mean stop after 5? It's stuck or what?
This website has sorted list, so it will stop until the last records found in local database. In my case it was 50 or so.

**Comment by Hexaf** [comment]
It's not stop, it's just like abort.

**Comment by riderkick** [comment]
Like I said this website has sorted list. So fmd only load necessary page which not exist in local database.

**Comment by Hexaf** [comment]
Ok I get it. My fault. Sometime my ISP block this site, maybe that's the problem.
Thanks riderkick
