### ISSUE TITLE
New Manga sites Please

### ISSUE THREAD

**Issue by abhishekanime98** [riderkick/FMD#37]
Can you please add this sites http://casanovascans.com/ or http://www.readmanga.today/. Thank you ! If you don't want to add this to FMD. That's fine. Thank you so much for the effort :) Thanks

**Comment by MarcusGHub** [comment]
Is it necessary to add Casanova Scans? 
I mean they publish all their scanlations to Batoto. Here http://bato.to/group/_/c/casanova-r2549

**Comment by abhishekanime98** [comment]
Oh! than its fine. Thanks for your advice MarcusGHub.

**Comment by abhishekanime98** [comment]
thanks for adding readmanga.today :)
