### ISSUE TITLE
New update not working

### ISSUE THREAD

**Issue by PanzerIVF** [riderkick/FMD#372]
The new update 0.9.83.0 is not working. It always say Folder not found when updating to the new update. Here's the pic of it.

http://puu.sh/r1Yir/fd3c6c029c.png

**Comment by StormJumper** [comment]
What site was it? The info provided doesn't tell much other then the updater having issues with the site. Error 404 means site error not something necessary with FDM.

**Comment by riderkick** [comment]
It's simply there is no prebuild manga list yet. You can build it yourself. Stack of book icon > Update list.
List of available manga list `https://sourceforge.net/projects/newfmd/files/data/`
Note that most of the manga list there wasn't updated for long time.

**Comment by bookimp** [comment]
Mine keeps crashing. I'll turn it on, it'll start to look for new chapters, and then it'll crash anywhere from 15-60 minutes later without downloading anything. I'm sure I have stuff to download as I didn't realize it hadn't downloaded in 3 weeks.

**Comment by StormJumper** [comment]
@bookimp it would help if you would tell us what series and manga site it was on FMD. So others can see if it happens as well.

**Comment by bookimp** [comment]
It's not a specific series. I load the program, it still has all the completed downloads from last time (which don't stay cleared ever), it then begins to check my favorites for new files. Somewhere in the middle of doing that I'll get the explorer message that the program has stopped working and needs to close.

**Comment by StormJumper** [comment]
@bookimp that doesn't help if no one can duplicate your problem.

**Comment by bookimp** [comment]
Here is the error, if this helps?
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	fmd.exe
  Application Version:	0.9.83.0
  Application Timestamp:	00000000
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.1.7601.19135
  Fault Module Timestamp:	56a1c9c5
  Exception Code:	c0000005
  Exception Offset:	0000000000017bcb
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	902f
  Additional Information 2:	902f3b42dc2419b2ff4206f923e4dcdf
  Additional Information 3:	f998
  Additional Information 4:	f998a6aeac22a2b1cf5f98fd99307d08
