### ISSUE TITLE
Kissmanga won't display some manga

### ISSUE THREAD

**Issue by FMDD** [riderkick/FMD#373]
Hi, I'm trying to download some One Piece chapters off Kissmanga, but every time I load the manga info nothing is being displayed. I've checked the website showing me the chapters are there, so I don't know why it's not appearing in FMD. 

Here's what it looks like: http://i.imgur.com/Pmrmres.png
Website: http://kissmanga.com/Manga/One-Piece

**Comment by FMDD** [comment]
Also, FMD won't support my Madoakmi account for some reason.

**Comment by StormJumper** [comment]
No problem seeing the manga in Kissmanga with the very same listing your using. What FMD version are you using?

**Comment by Purplem** [comment]
I'm having the same problem with Kissmanga on looking up any manga.  Using 9.83.0, been like this for a while now. http://puu.sh/raHbm/5383a93408.png

**Comment by StormJumper** [comment]
@Purplem I looked at your screen shot in kissmanga and have no problem. I also am usin 9.83.0 without the issue your having as well. I see them just fine. What are your connection settings, I think it has more to do with that then anything else.

**Comment by Purplem** [comment]
@StormJumper I did a fresh install without transferring some files and it seems to have fixed it, I dunno what was causing it not to work.

**Comment by StormJumper** [comment]
@Purplem That would be the most likely case bad settings.

**Comment by garybempo** [comment]
Version	:	0.9.85.0
Manga Didn't Show	: 	Daiya no A - Act II
Manga Site	:	http://kissmanga.com/Manga/Daiya-no-A-Act-II

**Comment by riderkick** [comment]
That's probably because your ip is banned. you need to open the website with your browser. You may need to answer some captcha.

**Comment by garybempo** [comment]
@riderkick thanks for replying.
I have no problem with other manga(One Piece,Naruto and etc). Just Daiya no A - Act II (in all the manga I read) is missing from the manga list, weird.
And I didn't get prompt for captcha when visiting the kissmanga.com.
I still can't find the Daiya no A - Act II in Version : 0.9.86.0 with updated manga list.
[pic ref.jpg](http://imgur.com/a/pDlFG)

**Comment by riderkick** [comment]
most pre-build manga list have been long outdated.  you have to update manually.
you can drag n drop the url to download list/favorite list to add them. or use drop box.

**Comment by garybempo** [comment]
@riderkick  thanks, the manga is appear now. [pic.jpg](http://imgur.com/a/ZKKtw)

**Comment by riderkick** [comment]
I forgot to tell you that kissmanga has sorted list. for this kind of list fmd will from first page to the last one that match with what already available in local database. So if there is any series that missing, probably that one was slipped between update. You have to do full rebuild of entire mangalist by deleting the local database and do update list manually.

**Comment by garybempo** [comment]
@riderkick thanks, the Daiya no A - Act II now is [exist](http://imgur.com/a/2ce8D) in Kissmanga list after I did what you told by deleted the old KissManga.db and Update the manga list.
But whole process took around 3 hours and a half, because of large updating list([total 11539](http://imgur.com/a/UYlha)) on Kissmanga site.
