### ISSUE TITLE
please add mangadoor.com

### ISSUE THREAD

**Issue by rs3mk** [riderkick/FMD#375]
Thanks

**Comment by rs3mk** [comment]
It's possible?. It has a lot of manga.

**Comment by riderkick** [comment]
I've seen a similar website like this, can anyone identify what engine/plugin they use?

**Comment by rs3mk** [comment]
my Manga Reader CMS:
https://codecanyon.net/item/my-manga-reader-cms/12487949

demo: 
http://getcyberworks.com/works/mangareadercms/

**Comment by kavin-90** [comment]
@riderkick I added MangaDoor please add it to `MangaList.inc, MangaList.ini`

**Comment by riderkick** [comment]
Thanks @rs3mk , @kavin-90.
I will look at it. Maybe we can merge the source code for a similar website like this.

**Comment by riderkick** [comment]
Changes here https://github.com/riderkick/FMD/commit/4e5a62aa1303ac6ea39b8be152a53a961da8e9f6
