### ISSUE TITLE
[Suggestion] BackUp Favourite List

### ISSUE THREAD

**Issue by suzakurenzan** [riderkick/FMD#383]
I had my favourite list (and download list) completely wiped out because of unknown reason, some weeks ago...
BackUp Favourite list would be nice, if we press the button, it auto saved as new txt and not overwriting the old ones
So we can recover the old one if the newer one is somehow corrupted

Example :
BackupFavourite-2016-09-19-001
BackupFavourite-2016-09-19-002
BackupFavourite-2016-09-26-001
BackupFavourite-2016-10-17-001

**Comment by StormJumper** [comment]
I created and dated each one and that is more then enough to save them. One must do their homework as well to backup important data.

**Comment by Beylers** [comment]
I support this idea, just had my whole favorite list disappear, over 100 Manga gone.

**Comment by SinfullKitten** [comment]
iv'e had my whole list disappear 3 times this week after spending hours fixing it, very upset DX and i wish it wouldn't make me work this hard.

**Comment by riderkick** [comment]
This issue have been discussed before.
If you look at the works foder, you should notice there is *.ini.run files when fmd runnning. FMD using temporary files and replace the actual files only after successfully build the temporary ini files. If even the actual files corrupted, then maybe there is another cause of problem.
Backup should be done by user. You can make a scheduled task for it

**Comment by SinfullKitten** [comment]
is there a tut on how to do this without messing anything else up

**Comment by riderkick** [comment]
Just use `cmd -C "copy favorites.ini favorites_backup.ini"`
