### ISSUE TITLE
Cant download from HeyManga "Lady Garden

### ISSUE THREAD

**Issue by huhufish** [riderkick/FMD#384]
Hi, i have trouble detecting manga "Lady Garden" from HeyManga.. it shows 0 episode in FMD while in the website, it's already "30 episode

**Comment by StormJumper** [comment]
Did you double click on the manga series to update the count? I did that and it shows up with the updated chapters. Download chapters one and reads ok.

**Comment by smoothtoast** [comment]
It won't even show up on the list for me
