### ISSUE TITLE
No Chapters for MangaSee

### ISSUE THREAD

**Issue by Wolfpup67** [riderkick/FMD#385]
When Viewing chapters for any manga on the MangaSee site in FMD the chapters are not present even though the title and everything else is. I'm using the latest version of FMD.

**Comment by StormJumper** [comment]
@Wolfpup67 , "laterst version of FMD" is which version?

**Comment by Wolfpup67** [comment]
Version 0.9.83.0 on Windows 10 64bit

**Comment by StormJumper** [comment]
ok tried MangaSee on my FMD 0.9.83.0 and it shows the title but no chapters. Could be they changed something on their site to prevent FMD from seeing the chapters. I think you need to report the problem Riddick about this.
