### ISSUE TITLE
PowerManga

### ISSUE THREAD

**Issue by sgn15** [riderkick/FMD#386]
Hi, is it possible to include Powermanga to FMD?
http://read.powermanga.org/

Thanks.

**Comment by kavin-90** [comment]
Its added but not working correctly.

**Comment by riderkick** [comment]
@kavin-90 what's not work?

**Comment by kavin-90** [comment]
@riderkick it works now. I uploaded PowerManga db on SF. 1KB file lol

**Comment by riderkick** [comment]
Yeah, I just check it. There is only 3 series in there.

**Comment by kavin-90** [comment]
they have only those series on series list page and latest updates page.
