### ISSUE TITLE
Kissmanga

### ISSUE THREAD

**Issue by Alter00** [riderkick/FMD#39]
FMD doesn't download from kissmanga, it seems it download but never end and when I try to delete data  I get this error;
![image](https://cloud.githubusercontent.com/assets/12287266/7893896/3dcc39fa-066b-11e5-808c-708fbbed3c0d.png)
Can you fix this please?
Thank you.

**Comment by MammothJerk** [comment]
from my experience kissmanga only sometimes work

so yeah it is something to look into

**Comment by Alter00** [comment]
It doesn't download, just seems like this.
![image](https://cloud.githubusercontent.com/assets/12287266/7897370/454cd348-06e2-11e5-93d1-93825a74af0f.png)

**Comment by riderkick** [comment]
What version it is?
I thought I already fix the delete method. Why the exception dialog doesn't show up. Did it produce fmd.log?
Yes sometimes kis smanga server doesn't respond. Please check with your browser. If you use proxy, put that proxy to FMD too.

**Comment by Alter00** [comment]
Current version. It didn't produce.
I checked and I do not use any proxy but it still does not download.

**Comment by riderkick** [comment]
It seems you delete the download using "delete task + data" which is indeed there is a bug(should be fixed with this commit https://github.com/riderkick/FMD/commit/096ad39a0c3cfc3108b17c99c0ee0eaee044afef).

**Comment by riderkick** [comment]
It seems ki s smanga using different image hosting for their manga. Bleach using imgur. There is also blogspot. Probably there is another image hosting too. They need special treatment.
