### ISSUE TITLE
Saving download history

### ISSUE THREAD

**Issue by bookimp** [riderkick/FMD#390]
Is there a file that is the list of my download history? Everytime I reopen FMD it has the same history has the last time I closed it and while it will download new chapters it's also re-downloading the last hundred something over and over. 

I was hoping there was a file I could copy before it closes or after to keep the history in a backup folder so it stops doing this?

**Comment by StormJumper** [comment]
What version? What site are you downloading from and what series?

**Comment by bookimp** [comment]
I'm using the current version. I've included a screen shot of what it looks like every single time I load the program (Old History) and the series that it re-downloads from each time... I admit I haven't been keeping track, it might be removing them slowly? I guess I can take new shots later and compare. (New History)

Old History:
![fmd](https://cloud.githubusercontent.com/assets/20101896/18977954/aad70032-8673-11e6-94af-75e647ec8e11.gif)

New History:
![new history 1](https://cloud.githubusercontent.com/assets/20101896/18977993/ec528bb2-8673-11e6-9d0b-a1b02184aea0.PNG)
![new history 2](https://cloud.githubusercontent.com/assets/20101896/18977996/eed4bf18-8673-11e6-8f72-9a71e61eaf6c.PNG)
