### ISSUE TITLE
Madokami URL is invalid

### ISSUE THREAD

**Issue by AsukaLangleyfag** [riderkick/FMD#395]
Topicname says everything. madokami.al is new link.

**Comment by StormJumper** [comment]
Sounds like the site is offline or doesn't exist anymore. What is the full link after http?

**Comment by Infinnitum** [comment]
I think it is https://manga.madokami.al/
      De: StormJumper <notifications@github.com>
 Para: riderkick/FMD <FMD@noreply.github.com> 
 Enviado: Sábado, 29 de octubre, 2016 17:38:07
 Asunto: Re: [riderkick/FMD] Madokami URL is invalid (#395)
   
Sounds like the site is offline or doesn't exist anymore. What is the full link after http?—

**Comment by bookimp** [comment]
Well the site works, I was just on it, but I imagine that to get it to work with FMD you'd have to have it setup on the account page as it requires login...
