### ISSUE TITLE
[Feature Request] Save 'Update Manga List' progress when clicking cancel

### ISSUE THREAD

**Issue by mznova** [riderkick/FMD#398]
Can you make it so that the progress made during the manual "update manga list" is saved once you click the "x" button? I noticed there is not a manga list archive for exhentai. Since they ban you if you load too many pages, it's also impossible to finish the manual "update manga list" task as well in one go. Clicking the "x" cancels the partial progress that's been made so this feature would be necessary to get any manga list from exhentai.

Thanks for your hard work!

**Comment by riderkick** [comment]
It will save the progress only for unsorted list. For sorted list, if we save the progress, we will not know where is the last page we have been loaded.
Don't use manga list for super huge directory like exhentai/ehentai. Just drag n drop the url to fmd from your browser. Dragging the thumbnail will do for exhentai/ehentai.
