### ISSUE TITLE
Genre in filter tab

### ISSUE THREAD

**Issue by dkartawi** [riderkick/FMD#40]
Some genres in filter tab are spelled incorrectly:
- "Echi" should be "Ecchi"
- "Historial" should be "Historical"
- "Mucical" should be "Musical" (or "Music")
- "ShoujoAi" should be "Shoujo Ai"

In older version, these genres spelled correctly

**Comment by riderkick** [comment]
I believe there is many grammatical error in English language. If you can edit fmd.en.po in folder language with Poedit and send it back to me that would be awesome. I don't have time to check it yet. In older version this string probably corrected in languages.ini. But now we use gettext, so the default language follow what initialized in design time.

**Comment by dkartawi** [comment]
I edit using text editor and change only those 4 things I mentioned
Here's the file:
https://www.mediafire.com/?t7yjec339vsa176

**Comment by riderkick** [comment]
Please do more, there will be no use if you just change a few string. I need to change it manually in design time for default language. Locating and replacing the object properties is time consuming you know. I don't feel the need to change it in meantime if it just for a few string. Or you can fork this project and make a pull request, I would gladly merge it to master branch, or just make a patch if you don't want to fork.

**Comment by MarcusGHub** [comment]
Changed some.
https://www.sendspace.com/file/2ah880

**Comment by riderkick** [comment]
It would be nice if you just make a patch against master branch. For default language(en) I need to change it manually in design time.

**Comment by MarcusGHub** [comment]
I have no idea how to do that. Hence I just uploaded it. Don't want to be a bother, but maybe you could walk through it.
