### ISSUE TITLE
Anyone seen or heard from Riderkick?

### ISSUE THREAD

**Issue by StormJumper** [riderkick/FMD#401]
Been some time since a update to the current FMD has anyone heard of any news of what is coming up FMD.

**Comment by kavin-90** [comment]
you can build own f you can't wait.

**Comment by StormJumper** [comment]
Everyone is waiting but so far no news of what is coming up tells more users either it has ended or the Project has been put of Life Support until further News is heard. Most will still use FMD but so far I haven't seen replies to my email if anything is happening. And I think most readers have more then just one "Tonari no Young" series but many they keep track of.

**Comment by kavin-90** [comment]
There are a lots series Tonari no Young Jump has like few Young Jump Series, Himouto Umaru chan S etc.

I'm building own which is not same as original FMD because i've removed few codes which cause FATAL Errors and errors to build own :smile:

**Comment by zqjpymbk** [comment]
Lack of any reply from author only proves that he's been likely silenced with a gag order as well.

**Comment by StormJumper** [comment]
I hope that isn't the case but with all the manga sites starting to break unless there is news or update the worse case that they got a cease and decease order might be what happened.

**Comment by zqjpymbk** [comment]
Anyway, I couldn't be arsed with waiting for updates on project's status, so for now I'm using domdomsoft. It supports the site I'm using for reading stuff, so there's that. As far as I'm concerned FMD is dead.

**Comment by StormJumper** [comment]
Well guess leaves trying to build it and email at the same time to find what has happened.

**Comment by StormJumper** [comment]
Tried to follow the links to build FMD but some of the sites have nothing to download to help to start.

**Comment by kavin-90** [comment]
Which site you're trying to download? so i can test that site

**Comment by StormJumper** [comment]
Just the front page where riddick gives instructions to download the libraries but when I go there I don't see them or the files to download.

**Comment by kavin-90** [comment]
Here is those packages 
[require-package.zip](https://github.com/riderkick/FMD/files/581310/require-package.zip)

**Comment by StormJumper** [comment]
I'll see what I can do with those but it says source code does this make it or where is that at? I looked but little confuse by where they are referring to the source code?

**Comment by StormJumper** [comment]
Here some news I found searching the internet....
Free Manga Downloader Discontinued - Not good news
Listed on http://alternativeto.net/software/free-manga-downloader/

**Comment by Infinnitum** [comment]
That is old news.
From that link:

"The project seems to be no longer maintained. Last version, 0.8.2b, released on March 9, 2014, and the source code can be still downloaded from the SourceForge. Working and actively maintained fork: https://alternativeto.net/software/free-manga-downloader-unofficial-build-/"
The unofficial build links to: https://github.com/riderkick/FMD



      De: StormJumper <notifications@github.com>
 Para: riderkick/FMD <FMD@noreply.github.com> 
 Enviado: Miércoles, 9 de noviembre, 2016 21:43:52
 Asunto: Re: [riderkick/FMD] Anyone seen or heard from Riderkick? (#401)
   
Here some news I found searching the internet....
Free Manga Downloader Discontinued - Not good news
Listed on http://alternativeto.net/software/free-manga-downloader/—

**Comment by kavin-90** [comment]
By editing **baseunits/ModuleList.inc** and **config/MangaList.ini**  

You need Pascal to BUILD it . Install Lazarus and FreePascal then load FMD-Source/mangadownloader/mangadownload.lpi

**Comment by StormJumper** [comment]
@Infinnitum - you got some issues with FMD take it up with Riddick.

**Comment by kavin-90** [comment]
@Infinnitum project was stopped so it went to sourceforge then sourceforge to github

**Comment by StormJumper** [comment]
Ok, I am a little lost where is FMD-Source/mangadownloader/mangadownload.lpi? Is that created after I install and run everything? Where would I go about about finding and fixing the broken manga site links?

**Comment by kavin-90** [comment]
Get FMD source from https://github.com/riderkick/FMD/releases

**Comment by StormJumper** [comment]
ok, thanks for the heads up I wasn't quite sure where to loook.

**Comment by StormJumper** [comment]
For those require packages do I just unzip and copy them to the root of lazarus folder and compile from there? The instructions there are not clear because those zip files aren't installers?

**Comment by kavin-90** [comment]
Just extract them and open package manager and use it so it will be not install in lazarus and available to use :)

**Comment by StormJumper** [comment]
So how do one go about updading the manga list to insure they match so if one updates it will get the right one or like before where they would block FMD downloads but you could to the site to read them? I know RiderKick did this but there is no instructions on this part?

**Comment by kavin-90** [comment]
in data folder upload that site.db file i think

**Comment by StormJumper** [comment]
ok, sounds like this will be more then I expected....I did find another download reader but subscribing to it you get unlimited updates. This might be my only other way should FMD stop working on sites. I might recommend this manga site list that FMD has to them to see if they can integrate it with their list.

**Comment by StormJumper** [comment]
Someone did tell me Riderkick is still around but if they are planning to come back that was still up in the air but no one has come forward to verify if this would be happening anytime in the near future here.

**Comment by kavin-90** [comment]
List down sites name i will try to make BUILD not guarantee it will work.

**Comment by StormJumper** [comment]
I think most that use FMD will know that nothing will be as before but a work in progress. Like me my programming Pascal is almost none existence after I took a look at it.

**Comment by kavin-90** [comment]
Well i'm **web developer** that is how i migrate **php to pascal** :smile:  build 2 modules . 

Webtoon one is tricky because it hide last page number in pagination that is why i'm unable to fix it until i get a way to find last chapter list pagination number.

**Comment by matoro** [comment]
Welp, mangatraders finally broke.  Guess it may be time to learn Pascal or write my own.

**Comment by kavin-90** [comment]
Mangatraders redirect to mangatraders.biz that is why it broken. Need to rebuild it.

**Comment by matoro** [comment]
@kavin-90 I was aware of the domain change, but they also released a blog post describing "Mangatraders 2.0" and the format of the site has drastically changed, so I assumed that might have broken the backend.  I'm not running on Windows so I can't get all the compilation tools but could you try a global search & replace for the mangatraders.org domain, rebuild, and upload in this thread just to see if that will work?

**Comment by kavin-90** [comment]
Whole Scrapper is need to be rebuild it will take time but they provide **download link for register users** so i'm thinking should rebuild it or leave it like that

**Comment by matoro** [comment]
Okay, so it's pretty clear that FMD was the best in its category, but I've been looking around for replacements.  Viable alternatives that I came across:
https://github.com/Hamuko/cum (python)
https://github.com/jorge-barroso/mangatux (bash)
https://github.com/jorge-barroso/baamanga (C++)

I've reached out to the author of the last two to see if they are still active, no response yet though.  Hamuko/cum and jorge-barroso/baamanga would probably be the best choices just by virtue of being cross-platform.  I know very little python but I might be able to hack together enough to contribute.  If you discover any other options post them here for posterity.

**Comment by amayra** [comment]
what is difference between pascal and Object Pascal ?

**Comment by amayra** [comment]
and can say that FMD written in Free Pascal ?

**Comment by StormJumper** [comment]
@matoro that is a understatement that FMD the best in catagory. I like you test alot of others as well beside downloading the manga series which in itself was a pain before I found FMD. If the Author comes back to update the project it would be great news but alot of others and sites are breaking now but as to still working FMD is still working which is a good thing. Most other sites I found one is paid and one is free but the free one doesn't have preview like FMD and the paid opens a separate browser for the manga but lately that site is now closed from any connections but I email them but so far have no response.

**Comment by matoro** [comment]
I am considering starting my own from scratch with the goal of keeping it lightweight and highly automated.  It would not be meant to replace FMD, but rather, provide a fraction of its functionality while being easily maintainable.  Would you (@StormJumper) or anyone else be interested in contributing?  I have been experimenting with C++ and libcurl but I can also work in Java or bash.

**Comment by kavin-90** [comment]
I know a  python one which updated weekly.

https://github.com/mikf/gallery-dl

**Comment by matoro** [comment]
That looks good, but as far as I can tell there's no subscriptions/favorites/check for new chapters functionality?  It requires you to pass a url according to the README.  It's just the downloader component, no tracking component.

Also, probably my favorite FMD feature was PDF conversion.  I have yet to see anything that can handle that.

**Comment by kavin-90** [comment]
I didn't get same Lazarus/fpc as @riderkick  so i can't build same copy as FMD but i can build older copy which does not have icons/ pdf creation etc because those are using Deprecated or invalid codes.

**Comment by StormJumper** [comment]
@matoro  and @kavin-90 , I'll have to go and find a pascal and C book and read up. It's been way way long time since I last touched programming. I knew it would be needed but didn't at the time have my brain in the right place. I'll have to go back and see how pascal and C works again this winter here because I'll have more time to review the programming to see what I can do.

**Comment by kavin-90** [comment]
Well i don't know Pascal either i just copy and paste and build module 😆

**Comment by amayra** [comment]
Borland used the name Object Pascal for the programming language in the first versions of Delphi, but later renamed it to the Delphi programming language so you learn Object Pascal or "The first version of Delphi" and there big between pascal and Object Pascal i asked you early and you ignored me

**Comment by StormJumper** [comment]
@amayra whether or not they answered shouldn't be the question - everyone is looking for a reply or answer so we shouldn't expect everything to be answered. This is a user help site asking someone to go into depth is going a bit far. I think everyone wants FMD to continue but what we should be asking ourselves in this community whom wants FMD to continue - we should start providing donations to the Author so they will continue their efforts to keep FMD ongoing. I think if we all do our part it will tell them we want the FMD project to continue. As my limited online search indicates FMD by far one of the most popular Manga Reader/Downloader that alot of users use right now from the stats I can see.

**Comment by amayra** [comment]
sorry i use "ignored" as joke i really want to help you with my limited knowledge about Object Pascal or "The first version of Delphi"

**Comment by mechjman** [comment]
I got the current version to build, but I had to comment out some sections of the code to compile, specifically in udownloadmanager.pas destroy method. I went and tried to correct mangatraders.org to .biz, but the whole structure has been changed as the paths are now different.

**Comment by kavin-90** [comment]
@mechjman mangatraders module path is MangaLife.pas

**Comment by mechjman** [comment]
I'm aware it's in mangalife.pas the issue is all the paths have changed with the site upgrade so it's not easy to do; requires nearly a rewrite

**Comment by kavin-90** [comment]
hmm, i will try to build and try and see it works or not.
