### ISSUE TITLE
Not scraping status from MangaFox

### ISSUE THREAD

**Issue by evilnight** [riderkick/FMD#403]
FMD is not scraping the status of manga causing it to not be able to detect and remove completed manga or properly add new manga to the list.

For anyone wanting to compile their own instead of waiting adding the following code to the MangaFox module appears to resolve the problem.

Add below `genres := XPathString('//div[@id="title"]/table/tbody/tr[2]/td[4]');`
```Pascal
s := XPathString('//div[@id="series_info"]/div[5]/span');
if s <> '' then
begin
  s := LowerCase(s);
  if Pos('ongoing', s) > 0 then
    status := '1'
  else if Pos('completed', s) > 0 then
    status := '0';
end;
```

**Comment by amayra** [comment]
thanks sir but can you make more easy im new to pascal-like programming languages

**Comment by amayra** [comment]
and how about add this change to your [fork ](https://github.com/evilnight/FMD)
