### ISSUE TITLE
Discontinued or Project Paused Indefinitely?

### ISSUE THREAD

**Issue by StormJumper** [riderkick/FMD#406]
I have to say for now from what I am seeing currently being as 2 months has passed without any updates would seem to indicate that the project has seen a hiatus.  I am one to say FMD was a very good project wish it would've lasted longer. I just wished the author if there was problem would inform the users to help donate for time and effort to keep the project going.

**Comment by Ianunaut** [comment]
Relax, riderkick was absent for a couple of months before. He'll probably return. If not, someone else will pick this up and fork it.

**Comment by StormJumper** [comment]
ok, that is news to me. I know these projects aren't the easiest to do or keep up but I do appreciate the Author's effort and time.

**Comment by StormJumper** [comment]
Seems like alot of sites are starting to break. Not sure about what Riderkick has said or contacted you about FDM but if things do keep breaking people will have to start looking at other sites to for updates.

**Comment by kavin-90** [comment]
I can build broken FMD which is 9.7.6 which will do few work until @riderkick not arrive :smile:

**Comment by StormJumper** [comment]
@kavin-90 that wouldn't be bad until riderkick comes back just be sure to update the manga list and sites since it seems like alot of popular and or used most seems to be having issues.

**Comment by kavin-90** [comment]
okay. I mostly use FMD for official Raw sites. (Alphaplis, Tonari no Young Jump, Sunday Web Every, Comico)

Gangan, Comic Walker, Jump+, Magaretbookstore etc which use same Reader.

i will try to make Ripper of SWF reader

**Comment by StormJumper** [comment]
@Ianunaut care you provide anymore info to your post 6 posting ago?

**Comment by Ianunaut** [comment]
I don't really have any more information, sorry. Riderkick was absent for half a year without telling anyone before at some point in 2015, so I assume his absence now might be the same. If not, I hope someone picks up the project.
