### ISSUE TITLE
Mangasee Domain Name

### ISSUE THREAD

**Issue by wildcrow** [riderkick/FMD#408]
Domain name change: 

mangasee.co to mangaseeonline.net

This is probably the cause for the "no chapters" problem.

**Comment by kavin-90** [comment]
hmm, mangasee and mangatreader looks same

**Comment by BrokenBob** [comment]
I noticed this with another downloader out there as well. Came here looking for one that works with MangaSee. So far I like what I see with FMD, just need to get MangaSee working again, it was my most used site, never any watermarks. Would very much appreciate it if you can get it to work again.

**Comment by kavin-90** [comment]
Manga Life , MangaTraders and Mangasee use same system so only domain change that is why those are broken.
