### ISSUE TITLE
Failed to create directory on specific title?

### ISSUE THREAD

**Issue by mikazuki7** [riderkick/FMD#409]
So I always got this error whenever trying to download this manga, The hero suddenly proposed to me, but . . .  on batoto. It can't make directory.

![2016-12-06 07_40_23-free manga downloader](https://cloud.githubusercontent.com/assets/8412528/20908504/03a7e96c-bb88-11e6-9021-8a0956770934.jpg)

Can someone explain why this happened? Any way to fix this? Thanks

**Comment by kavin-90** [comment]
It maybe due to invalid name i think or no disk space?
