### ISSUE TITLE
Sites to add if possible

### ISSUE THREAD

**Issue by timgorden11** [riderkick/FMD#41]
Any chance you would/could be able to add the following sites?

Lonemanga - http://lonemanga.com/ (random chapter from reader)  lonemanga.com/manga/marchen/21

LINE Webtoon - http://www.webtoons.com/en/ (random chapter from reader) http://www.webtoons.com/en/fantasy/knight-run/ep-50-pray-part-48/viewer?title_no=67&episode_no=51

Tapastic - http://tapastic.com/ (random chapter from reader) http://tapastic.com/episode/136968

thanks

**Comment by riderkick** [comment]
I can't add LINE Webtoon and Tapastic for various reason.
I will check lonemanga.

**Comment by MammothJerk** [comment]
how about adding 

https://manga.madokami.com/

under English

and

http://casanovascans.com/directory/
http://spinybackmanga.com/
http://www.webtoonsreader.com/directory/
http://imperialscans.com/archive
http://reader.vortex-scans.com/directory/
http://reader.sensescans.com/reader/list/

under English-scanlation

**Comment by riderkick** [comment]
@MammothJerk you're asking to much. There is already a lot of website supported. I believe what you're looking for is available in another website.
I would only consider it if it was unique website which the series in there not available on other website.

**Comment by MammothJerk** [comment]
ok then, how about just this one then

https://manga.madokami.com/

it's never dissapointed me with its huge variety

**Comment by riderkick** [comment]
The file can be directly downloaded on there. And it seems the series that is available in there already available on other website.
Please make a new issue if it's unrelated with OP.
