### ISSUE TITLE
Cant download from mangatown

### ISSUE THREAD

**Issue by Hexaf** [riderkick/FMD#410]
I cant download manga from mangatown. Do anyone have same issue?

**Comment by kavin-90** [comment]
They changed Image div that is why it broken.

**Comment by Hexaf** [comment]
Can you fix it? :D

**Comment by kavin-90** [comment]
I tried it but not fixed.

**Comment by amayra** [comment]
more fine for me

**Comment by Hexaf** [comment]
@Aryma what version do you use?

**Comment by hypomaniak** [comment]
Hello

I just managed to install the project environment (not so easy...)

I quickly tried to modify MangaTown code, and this seems to work:

image_url.inc:31
from 
if (Pos('<img', parse[i]) > 0) and (Pos('onerror=', parse[i]) > 0) then
to
if (Pos('<img', parse[i]) > 0) and (Pos('alt=', parse[i]) > 0) then


This may NOT be the better solution as I just managed to dive in the project code, but it gives me a result

**Comment by amayra** [comment]
can you explain to me how do you set project environment to make it compilable with Lazarus

**Comment by kavin-90** [comment]
Just install Lazarus and Require package 

https://github.com/riderkick/FMD/files/581310/require-package.zip

For Packages.
Lazarus > open package file > use no need to install

**Comment by amayra** [comment]
thanks kavin-90 can you add to change to your [fork ](https://github.com/kavin-90/FMD)

**Comment by kavin-90** [comment]
I can add changed to my fork i'm working on few japanese official one i added tonari no young jump sunday and already fixed sundaywebevery.
