### ISSUE TITLE
Mangatraders changed address

### ISSUE THREAD

**Issue by hitmanrd** [riderkick/FMD#412]
http://mangatraders.org changed to http://mangatraders.biz

**Comment by kavin-90** [comment]
Fixed Chapter List for MangaSee,MangaTrader and MangaLife but unable to fix image url so FMD pick 1 image and will return complete.

**Comment by matoro** [comment]
Posting here for when this gets fixed.

**Comment by riderkick** [comment]
@kavin-90 is this issue still relevant? Please close if not.
