### ISSUE TITLE
The future of FMD ?

### ISSUE THREAD

**Issue by amayra** [riderkick/FMD#413]
well...
Look, I was gonna go easy on you not to hurt your feelings but this look like this is the end of road 
any good alternative for FMD since no one know "Object Pascal" or dont care to fix some bug

**Comment by StormJumper** [comment]
Here's what another said...

 Ianunaut commented 13 days ago

I don't really have any more information, sorry. Riderkick was absent for half a year without telling anyone before at some point in 2015, so I assume his absence now might be the same. If not, I hope someone picks up the project.

**Comment by matoro** [comment]
I will add one more thing @amayra @StormJumper I've put a couple hundred LOC down in a few files for a simple replacement to FMD.  It's still very much a WIP and now that Christmas is coming up I won't be able to seriously crack down until January.  BUT!  When I get around to releasing it, I feel it'll have several advantages over FMD, most notably:

- Written in C++, which means blazing fast on the local side.  Pretty much all downtime will be network-related.  Also means it's completely cross-platform
- Uses libcurl for ALL network stuff, so no dependencies and everything is simple
- Highly modular, it uses a generic Extractor class which is then implemented via modules for different sites.  So anybody can write their own module in just two files
- Portable, uses a single SQLite database for keeping track of everything
- Can be run interactively or as a background daemon

Anyway when things get release-ready I will try to spread to as many former FMD users as possible.  I don't know when that will be though so keep an eye out.  Also if anyone is interested in helping out just shoot me an email.

**Comment by amayra** [comment]
@matoro i would like to help you in my free time just give your email

**Comment by matoro** [comment]
@amayra You can contact me at throwaway19587@gmail.com, it forwards to my real email.

**Comment by StormJumper** [comment]
Well when your going to get someone to test it out give me a hollar, I'll email to your gmail with my safe gmail account to get your when your ready. Just make sure it does have a preview like FMD that helps those looking and reading to know if that was the Manga they were looking for. Reading description helps but a visual also does help identify if that was what one thought it was.
