### ISSUE TITLE
Trouble loading the site Gmanga

### ISSUE THREAD

**Issue by SomeonePro** [riderkick/FMD#414]
Hello my friend
I am having a problem with the site Gmanga [AR]
As in the picture

![snip_20161211001349](https://cloud.githubusercontent.com/assets/24500203/21077113/1ad22e56-bf37-11e6-815d-e57e258efa71.png)

I hope you solve the problem
Thank You ^^

**Comment by amayra** [comment]
look like they are some change in Gmanga make FMD unable to lead it and the only way to fix this is to wait ( if ) dev to come back to fix it

**Comment by kavin-90** [comment]
It seems from picture like you were grabbing DB from fmd server which it does not exits try to update manga list

**Comment by kavin-90** [comment]
Gmanaga structure is changed so need to rebuild script.

**Comment by riderkick** [comment]
It seems entire website has changed.

**Comment by riderkick** [comment]
This website is confusing, I can't find where is the chapter list?

**Comment by kavin-90** [comment]
Same here i can't find chapter list but i know now how to find it

you can find it from reader page. click on right side of next to 2nd select box series list after click it redirect to 1st chapter of series.

Chapter Page
http://gmanga.me/mangas/futsutsuka-na-oyako-de-wa-arimasu-ga/0/SUBARASHI-CHAN
