### ISSUE TITLE
Not really an issue but....

### ISSUE THREAD

**Issue by JulioJMZ** [riderkick/FMD#416]
Is there a way for downloaded chapter's folder name to include which volume is it from? 
![screenshot 114](https://cloud.githubusercontent.com/assets/24628453/21290413/9b530d40-c476-11e6-8508-102c7a16da21.png)

**Comment by kavin-90** [comment]
Volume **TBD** means Volume no has been not set in website .

so **TBD**(To be Decide or To be Declare) is used.

**Comment by kavin-90** [comment]
Volume **TBD** means Volume number is not set in website .

so **TBD**(To be Decide or To be Declare) is used.
