### ISSUE TITLE
MangaCow isn't loading

### ISSUE THREAD

**Issue by Reyeselda95** [riderkick/FMD#418]
When trying to load favourites from mangacow it says that it doesn't work. The url changed from mangacow.co to mngcow.co and when i try to change it it says that the URL is not supported. How can we change this in order to work again?

**Comment by kavin-90** [comment]
Today it will be fixed.

**Comment by Reyeselda95** [comment]
ok, but how can i make mine work? i have already downloaded the list from the server...

**Comment by kavin-90** [comment]
It switch to WPManga so i moved it to WPManga section so i need to upload ManaCow build copy i didn't test how much it works.
