### ISSUE TITLE
Patches

### ISSUE THREAD

**Issue by kavin-90** [riderkick/FMD#419]
**Here is FMD patches Note: Its not Tested but it works on some sites which i fixed.**

**Here is My Builds of FMD**

**https://www.mediafire.com/folder/aac04rk9u95ut/FMD**

**Comment by amayra** [comment]
@kavin-90 Thank you for keeping this great project alive and updated!

**Comment by Hexaf** [comment]
@kavin-90 I am sorry to ask you this. But can you add patch log please?

**Comment by kavin-90** [comment]
@Hexaf it added in My Fork i think.

**Comment by riderkick** [comment]
Hi @kavin-90 
Thanks for your contribution.
Here is some tools that I made to help developing fmd. Using the same library as fmd, so you can expect it to give the same result as fmd. html parser, regex test and batch script to make a release. Just extract the "Release" in fmd root dir. You may need to change the path in .bat file to suit your system.

https://www.mediafire.com/folder/kcd831rr2fj1l/tools

**Comment by kavin-90** [comment]
@riderkick thanks i will check them out.

**Comment by kavin-90** [comment]
@riderkick i checked html parser don't know how it work it give me just headers in output window in xpath/css selector i got count 0.

**Comment by riderkick** [comment]
@kavin-90 that's mean there is nothing to match against your xpath/css. Try to run simple selector like `//a/@src`

**Comment by kavin-90** [comment]
i tried it show just nothing for html

![parse-html](https://cloud.githubusercontent.com/assets/15142270/21716514/e8e39862-d430-11e6-8acb-befb7621e245.png)

**Comment by kavin-90** [comment]
@riderkick i checked other site it works it seems NewType causing that only.

**Comment by riderkick** [comment]
@kavin-90 it's working fine here.
![untitled](https://cloud.githubusercontent.com/assets/4972676/21727031/3fa55b1a-d47a-11e6-9b9b-038c0bbe9f61.jpg)

**Comment by amayra** [comment]
out of curiosity any chance to make this tools open source ?

**Comment by kavin-90** [comment]
@riderkick strange i got same result which i post in image i will try it on other network to see it works or not.

**Comment by kavin-90** [comment]
@riderkick i need advice 
xpath give me data `//li[@class="OblongCard--border"]/a//h3`

`//li[@class="OblongCard--border"]/a//h3` but when i put it in module no data for  [ANames.Add(XPathString('h3',v.toNode));](url)   and show FMD error about unfinished backup

**Comment by riderkick** [comment]
Website module doesn't have access to mangalist db. So that error should be triggered outside.
I'm not locking the sqlite database, maybe there is a problem when multiple instance accessing the same db file.
