### ISSUE TITLE
can you improve this

### ISSUE THREAD

**Issue by rcarlos243** [riderkick/FMD#42]
I accidentally deleted my downloads history and I have over 200+ manga in which I read and keep track by the downloads tab.

Since the delete all completed task is fairly large and right besides the favorites tab, I accidentally pressed it and my download history is now gone >:O
http://imgur.com/fmp4SUA

can you fix it by either moving the whole thing to the bottom or somewhere else so it wont be as easy to accidentally hit.

Also can you add a new tab for favorites tab as Last Updated (with date and time and even what chapters were downloaded) so I would know if there is new chapter downloaded to it.

**Comment by riderkick** [comment]
Just enable the dialog confirmation before deleting task.

We can't get date and time of last chapter update.
