### ISSUE TITLE
Did I see what I just thought I saw?

### ISSUE THREAD

**Issue by StormJumper** [riderkick/FMD#420]
Just checked and it was updated......

**Comment by kavin-90** [comment]
Yeah, @riderkick is back and checking changes.

**Comment by StormJumper** [comment]
ok...just tried to download the latest and it said 404?

**Comment by kavin-90** [comment]
yeah because it does not exists yet just my experiment of making updater

**Comment by StormJumper** [comment]
I see...

**Comment by StormJumper** [comment]
Well downloaded the lastest and so far it works and updates without problem just that there is nothing for KireiCake and ReadComics

**Comment by kavin-90** [comment]
@StormJumper i download Star Wars latest chapter from ReadComics

**Comment by amayra** [comment]
i only remember this i when i see your post
"I Tawt I Taw a Puddy Tat! I did, I Did, I Did Tee a Puddy Tat!"
―Tweety's catchphrase

**Comment by StormJumper** [comment]
@kavin-90 if I try to do a update for ReadComics download manga list it says it couldn't find it?

**Comment by kavin-90** [comment]
@StormJumper maybe i didn't make the manga list just description page and download. I will check and let you know.
