### ISSUE TITLE
mangatraders not working even though url has been updated to mangatraders.biz

### ISSUE THREAD

**Issue by taskforce22** [riderkick/FMD#422]
Hi, I just wanted to report that mangatraders has moved from http://mangatraders.org/ to http://mangatraders.biz/.  The old site is still active but you can't get any downloads from it now.  Thanks for your time and this great and helpful program.

**Comment by kavin-90** [comment]
@taskforce22 url is already updated need to fix image url

**Comment by taskforce22** [comment]
Well, if it was in the latest version, it definitely is not working for me.  All of my favorites still show 0 chapters and I still got nothing any time I try to load manga info from there besides a generic mangatraders logo.

**Comment by kavin-90** [comment]
Mangatraders needed Login for Many Series so chapter list is empty like i said Image url is need to fix only Login will be added by @riderkick

**Comment by taskforce22** [comment]
Thanks for the update.
