### ISSUE TITLE
Not really an issue but a request

### ISSUE THREAD

**Issue by asradur** [riderkick/FMD#425]
Sorry if i'm doing this wrong, kinda new on GitHub.
I want to ask if it's possible to add a feature to transfer multiple bookmarks from one website to another.
I imported my bookmarks from DomDom wich broke down and have like 250 bookmark from kissmanga since it was the last functioning source.
Would love to have a feature that allowed me to change selected favorites from one source to another

**Comment by kevin01523** [comment]
yeah it was working a few days ago and i was using kissmanga  i hope this would be granted soon

**Comment by spamtaztik** [comment]
I also support this request. Pretty please?
