### ISSUE TITLE
KissManga - preparing download stuck on 0/1

### ISSUE THREAD

**Issue by Inareous** [riderkick/FMD#426]
Ended up only creating a folder and not downloading anything

**Comment by amayra** [comment]
thanks to cloudflare browser verification i don't think so

**Comment by Inareous** [comment]
Yeah, i narrowed down the issue by 2.

1. The cloudflare anti-bot verification / I'm Under Attack Mode is blocking FMD from interacting with the website.
I tried copying cookies from my browser however it seems that it doesn't work. Or the string to add cookies simply doesn't right.
2. reCaptcha.
I can bypass this by opening the site using my browser.

Still can't download right now, issue no 1 is bugging the hell outta me.

**Comment by kavin-90** [comment]
KissManga is working correctly i downloaded Oh! Holy Chapter 14 .

**Comment by Inareous** [comment]
@kavin-90 The problem will occur after cloudflare noticing too many request from your IP, as it will trigger IUAM (I'm Under Attack Mode).

I'm not really sure how to reproduce this on other pc.

Maybe creating huge request, then remove the verification cookies (cf_clearance) when it appears.

My problem occured after i disconnected from my internet while downloading (~50GB), thus making my session expired. The next request to access the website suddenly blocked by this.

Here is what it's looked like after blocked by IUAM

blob:https://imgur.com/060679a4-9a0f-4671-95bb-cfa2606f9e8c

**Comment by kavin-90** [comment]
@Inareous i see. cf_clearance cookie need to changed after 30 min or 1 hours or your ip change you will need new cookie because old cookie uses old ip which was changed.

**Comment by Inareous** [comment]
@kavin-90 

I tried using cloudflare-scrape (https://github.com/Anorov/cloudflare-scrape) in .py script to scrape and then print new cookies & user-agent used then manually pasting them to the advanced.ini. Unfortunately it didn't work.

I'll try waiting for a day or two before accessing KissManga again, i hope it will IUAM

**Comment by riderkick** [comment]
FMD's cloudflare scrapper should be able to request new cookies if it's expired. Currently cf cookies stored in runtime only. So if you close fmd it will not store any cookies.
If you look at `Cloudfllare.pas`, it will only scrape the new one if its meet this requirement.
- http result code >= 500
- match with xpath `//input[@name="jschl_vc"]/@value`
Maybe this one need to be updated?

**Comment by Inareous** [comment]
Hi @riderkick , sorry for the trouble.

I've found a workaround for this. That is to simply create another fresh FMD and copy the works data from old FMD.

As for the actual problem.
After sniffing and filtering http packet using wireshark, i've found that my old FMD doesn't have cf_clearance (only __cfduid) and not requesting any (even though it should!).

The scraper doesn't do anything if the cf_clearance simply isn't included in the cookie_pair ?
As the old FMD doesn't requesting any verification "GET /cdn-cgi/l/chk_jschl?jschl_vc=" (the new FMD requesting it)

For comparison : http://imgur.com/a/buKtO

I'm still not sure how to reproduce this, i guess it has something to do by forcefully make the cookies expired while keeping FMD alive. I can upload the old FMD if you want.

Anyway, i think the matter is resolved.
