### ISSUE TITLE
cannot import mangafox bookmarks from domdomsoft

### ISSUE THREAD

**Issue by kevin01523** [riderkick/FMD#427]
when i try to import my old bookmarks from domdomsoft mangafox bookmarks cannot be imported 

![image](https://cloud.githubusercontent.com/assets/8380242/21717537/8f5fb4b2-d44c-11e6-99df-dce5dca11004.png)

and if possible add goodmanga site since some of old manga translated isnt available on batoto or mangahere or mangafox

**Comment by riderkick** [comment]
mangafox domain have been changed. edit your file, find and replace all "mangafox.com" with "mangafox.me". then try to import again.

**Comment by kevin01523** [comment]
sorry for late replay busy with things yeah this solved my problem
