### ISSUE TITLE
[Request] Multiple chapters in one folder

### ISSUE THREAD

**Issue by Souravi785** [riderkick/FMD#428]
It's not an issue but I want to request an option to download all chapters in one folder like volume system. If it's not difficult. Please.

**Comment by matoro** [comment]
You should be able to do this just by setting the "Save To" locations correctly.  You can set them the same, and if you'd like EVERYTHING in the same folder, just set the custom Chapter Title string to a constant string without any variables.

**Comment by Souravi785** [comment]
Can you explain that a little?

**Comment by matoro** [comment]
When downloading a series, simply select the folder you want to save it to.  When you download the second series, select the same folder.  Does this not work?

**Comment by Souravi785** [comment]
That't not what I meant by multiple chapters in one folder. It's multiple chapters in one file. Domdomsoft had that function.

**Comment by kavin-90** [comment]
if you want something like that then we need to track Volume. 

array of that volume's chapter; then mkdir parent key then mkdir(parent key/chapter folder); so it can be done in php but to migrate it need to append volume number in front of chapter number.

then explode and send it as $args to fun of making folder may work but not sure correct approach or not.

**Comment by matoro** [comment]
Assuming you don't need to have different folders per volume, you can do this already.  Just set the chapter folder name to some string literal, like this: https://my.mixtape.moe/tcjzql.png

As long as you don't have any variables in it, all your chapters will download to the same folder.

**Comment by Souravi785** [comment]
Sorry, don't understand. I changed the names in different ways but doesn't work.

First of all let me explain what I want. 
When I download a manga chapter it goes like this....Naruto-chapter 201 and chapter 202. Two chapters in two folders inside Naruto directory.
But when I want to download like a volume system it goes like this....Naruto...........(all chapters (201-pg.01....pg20, 202-pg.01....pg21 and so on..... combine into naruto directory)

I can't seem to do this in Fmd.

**Comment by riderkick** [comment]
Just disable "auto generate chapter folder" and set your "filename" to `%CHAPTER%_%FILENAME%`.
This "save to" setting is work only on creation time. So you have to re-create your download task to apply the changes.

**Comment by Souravi785** [comment]
Thanks. It worked.
