### ISSUE TITLE
mangafox unable to download anymore??

### ISSUE THREAD

**Issue by augustinlibert** [riderkick/FMD#429]
Hi Riderkick, 

really happy to see you back. :)

I have issue of downloading from mangafox since yesterday till now, hope you can fix this and also a request, is it possible to add Volume in mangafox as well? as I can see that in mangahere but not mangafox, many thanks... :)

**Comment by kavin-90** [comment]
@augustinlibert mangafox downloading working i just downloaded Horimiya 73.

**Comment by augustinlibert** [comment]
@kavin-90 strange on my side, I got all the red cross or download incomplete. probably I will try to restart my modem and router to try again, many thanks for your reply.. :)
