### ISSUE TITLE
mangafox download not complete...

### ISSUE THREAD

**Issue by augustinlibert** [riderkick/FMD#431]
hi,

anyone facing this issue like me? I restart my modem and router just in case, and try again, problem still same, even with green tick, the manga was not download complete as well, I have no issue with mangapark.

http://i.imgur.com/sSmz0Nf.jpg

http://i.imgur.com/9n4nykY.jpg

**Comment by riderkick** [comment]
It's all pages or some page only?
You should check the particular page in your browser.
I often get this issue too when downloading from mangafox. There is often one page at the end that failed to load. Especially the last chapter.

**Comment by augustinlibert** [comment]
basically all, it only happen 2 days ago, I have check the website it has example 20 pages, but when it auto download from my favorites, it only few pages, and the software shows completed in green tick.

**Comment by murnur19** [comment]
I just downlad a bunch of complete manga from mangafox. No problem so far. Maybe there is temporary server issue. You have to check the particular page with your browser.

**Comment by murnur19** [comment]
I just download a bunch of complete mangas from mangafox. No problem so far. Maybe there is temporary server issue. You have to check those particular page with your browser.

**Comment by riderkick** [comment]
There is ip ban on mangafox. Are you sure your ip not banned?
Check all those failed task with your browser. Each page.

**Comment by augustinlibert** [comment]
I ever suspect that as well, I had off my modem and router for a moment then on again to make sure I am not using the same IP then try again but still having same issue. I have no issue with the browser so far, I can still read those manga...

**Comment by riderkick** [comment]
I think there is really temporary server issue.
As you can see here, there is a lot of `503 Service temporary unavailable`.
![untitled](https://cloud.githubusercontent.com/assets/4972676/21749143/ff0d4806-d5d2-11e6-979c-b05731ddeb42.jpg)
FYI, I'm using http://handycache.ru/ to redirect all request from fmd using http proxy. Just to see what's going on.

**Comment by riderkick** [comment]
Another thing I notice. Mangafox often respond with 503 if we send more than 2 request at the same times.
So, just be modest when leeching from mangafox.

**Comment by augustinlibert** [comment]
I will try to change the settings and see how is it then, mangafox website was having some issue recently, website down few times a day, many thanks for your prompt reply.. :)

**Comment by augustinlibert** [comment]
@murnur19 I have check the browser and it is fine, just the manga downloaded did not complete, but recently mangafox website down few times a day, it could be the issue as well I believe... thank s for your reply too... :)

**Comment by augustinlibert** [comment]
I just choose some manga and add to favorites the download shows like that [http://i.imgur.com/nnmJMba.jpg](url)

**Comment by riderkick** [comment]
That's blue chair alright.

**Comment by augustinlibert** [comment]
Sorry I did not make it clear enough, I have check all the chapters downloaded, in green tick, all folders inside only have  one page downloaded, I just took Blue Chair for example only.  :)
