### ISSUE TITLE
Issue with Negative Value in 'Retry' Variable

### ISSUE THREAD

**Issue by Inareous** [riderkick/FMD#433]
So, this is a continuation of Issue #426, i've found the method to reproduce it (Making scraper doesn't work).

That is to put negative value under "Retry" in config.ini, it will make the scraper to not work properly, the routine simply won't start.

As stated in previous issue, this cause cf_clearance to be not found in FMD and KissManga's cloudflare won't let you pass IUAM without cf_clearance.

I've yet to putting negative value on another variable, and i'm not sure how pascal interact with negative integer. I'm also wondering if there's other function broken by this.

Edit: Sorry for my engrish.

**Comment by riderkick** [comment]
Please try the latest version.

**Comment by ThePrimus** [comment]
@riderkick where can you load the latest version?

**Comment by riderkick** [comment]
IMHO, better use large number rather than infinite loop. Like 100 or so. So it can exit when there is no short solution.
