### ISSUE TITLE
No chapters for MangaTraders

### ISSUE THREAD

**Issue by ThePrimus** [riderkick/FMD#437]
Eventhough I added my user account for MangaTraders it seems like FMD can't find chapters for manga titles. I think it's because the URL for checking is wrong.

For example:
Naruto has "http://mangatraders.biz/read-online/Naruto" as its standard url (which don't exist) but for reading online it is "http://mangatraders.biz/manga/Naruto", for volume packages it is "http://mangatraders.biz/series/Naruto". If I add manuelly the "/manga/X" link then it works to load all the chapters but if I add the "/series/X" link then only a few volumes are loaded.

**Comment by matoro** [comment]
Confirming this.

**Comment by riderkick** [comment]
We gather manga list from `http://mangatraders.biz/directory/`

**Comment by ThePrimus** [comment]
The links from http://mangatraders.biz/directory/ are "/series/" and not "/read-online/". "/read-online/" does not exist on MangaTraders but on MangeSee you can find such links. So eventhough they use kind of the same system the links are different.

**Comment by matoro** [comment]
@ThePrimus , do you know if MangaSee uses the same images as MangaTraders?  IMO the only reason to use MangaTraders is for their fantastic quality--no watermarks unless it's the only version available, usually sourced directly from scanlators.  If MangaSee has the same image quality with a less infurating website scheme I see no reason not to just drop MangaTraders and refer people to MangaSee.

**Comment by ThePrimus** [comment]
@matoro unfortunally I don't know it. Maybe you can find something regarding this on the internet (or check for yourself).

**Comment by ThePrimus** [comment]
@riderkick didn't saw your edit so here is my reply: Indeed some don't have it. It seems like these manga titles don't offer chapter reading online. Atleast that's true for those which I found (like DriftingClassroom). FDM is for chapter loading so if that `/manga/` page don't exist you can't download a chapter but only volumes which FDM doesn't support. So it is not a problem, isn't it?

**Comment by matoro** [comment]
@ThePrimus It would seem that they are exact mirrors of each other, as far as my cursory inspection can tell (although it is probably MangaSee which is ripping off MangaTraders).  I tested 2 titles on the front page of both sites, Overlord and Ao no Exorcist, and the first pages of both were the exact same image, hosted on Blogspot/Google (not just the same image, but the same URL).  Additionally, the first couple pages show identical upload times for new chapters.

As such I would advocate dropping support for MangaTraders while putting a notice somewhere visible directing people to MangaSee instead.  On top of that, it would be nice to reduce the burden on MangaTraders server, since their staff are the ones doing all the hard work anyway, and Google is taking the hit for the actual image downloading.

@riderkick Thoughts?

**Comment by riderkick** [comment]
I thought they are owned by the same people?
Then leave that be. Just hoping people who have an issue with it will look at this thread.

**Comment by kavin-90** [comment]
@riderkick yeah, same people.

**Comment by riderkick** [comment]
@kavin-90 you mean to redirect mangatraders url to mangasee?

**Comment by kavin-90** [comment]
so let's drop it.

**Comment by riderkick** [comment]
Maybe I can rule out none existent series from manga list. When doing getinfo just set the status to -1 and updatethread will not save it to database.

**Comment by kavin-90** [comment]
@riderkick i didn't get why support those sites which provide Direct Download Link(DDL) of Chapter/Volumes

**Comment by ThePrimus** [comment]
@kavin-90 Why shouldn't they be supported? I thought FMD is for download automating .

**Comment by riderkick** [comment]
@kavin-90 I see your point. It was added at the time when there is no volume download on mangatraders. Basically the same like mangasee now. Since the module doesn't completely broken, and the code is shared with other website. I think we can just leave it at the moments.

**Comment by ThePrimus** [comment]
@riderkick: A possible workaround would be to make it possible to add favourites of own added URLs. So one can change the URL of a manga and add that to the favourits. Currently you can't add them to favourites

**Comment by StormJumper** [comment]
I found out unless you register for mangatraders you can't get to their site but once I did that and added the info to FMD it updated without problem. That's what I did maybe not for others but seems to work for me.

**Comment by riderkick** [comment]
@ThePrimus you can. Just load the url on manga info. once it's loaded, you can hit "add to favorites" button. Or the easiest way, just drag n drop the url to favorite list. Or enable drop box, set to "add to favorite". then drop the url in the box.

**Comment by ThePrimus** [comment]
@StormJumper I added my account to but the manga listed in manga list don't have any chapters

@riderkick didn't noticed that! That would be a manual workaround which works.

**Comment by riderkick** [comment]
@ThePrimus I don't get what you say.

**Comment by ThePrimus** [comment]
@riderkick Starting a download task for a manually added URL doesn't show up under the `download` tab eventhough its downloading.

**Comment by riderkick** [comment]
How you know its downloading if its not exist in download list?
How you add the url? via drop box?
If you set to "add to favorites", it will only add to favorites. If you set to "download all" then it will be added to download list, if there is any chapter on it.
The same with dropping the url in favorite list. It will only add to favorite.
To download all available chapter you just need to drop the url in download list.

**Comment by riderkick** [comment]
I update the mangalist, please test that.

**Comment by ThePrimus** [comment]
@riderkick I know it because I can see the files added to the download folder. I noticed that after restarting the application a started task for a manually added URL (`drag and drop to favourits`) will show up in `Downloads`.

**Comment by riderkick** [comment]
drag and drop to favorites will NOT automatically added to download list. it will NOT download anything.
you have to manually add them to download list.

**Comment by ThePrimus** [comment]
@riderkick that's not what I meant . I was talking about adding it to favourits and then start a download task.

**Comment by riderkick** [comment]
how do you start the download? from favorites, right-click>download all?
probably you filter them out. check your filter. ">>"

**Comment by riderkick** [comment]
I upload new release, please test.

**Comment by ThePrimus** [comment]
@riderkick if a manga can't be found then the "Sorry we can't..." text will displayed. That text will also be displayed as a name in the manga list if you load a manga info.

**Comment by riderkick** [comment]
I build those mangalist from fmd. So its should be the same.

**Comment by riderkick** [comment]
You have urls with "/read-online/", there is no such urls in `http://mangatraders.biz/directory/`.
I guess you just have old manga list. Those list not market blue(new).

**Comment by matoro** [comment]
It would seem download functionality is working again, but it is not retrieving the entire MangaTraders list.  572 titles show in the list, but MangaTraders has around 11000 titles available.  Now I know there are some titles which don't have chapter reading available, like oneshots, but I'm sure there were a lot more than 572 titles with it.  Additionally, if I run "update manga list", it parses through 11233 titles, but the list stays the same with 572, even if I close and reopen.  I'm not 100% sure this issue ought to be closed.

**Comment by riderkick** [comment]
@matoro, please see the commit above. after fmd check all those link, the one replied by the server with 404 or "Sorry we can't find what you're looking for" will not be saved. Those list doesn't have available chapter to be read online.

**Comment by ThePrimus** [comment]
@riderkick almost all of them have chapters available to read online. I think you still use the wrong URL to check if that page exists like my example of Naruto.

**Comment by riderkick** [comment]
@ThePrimus duh, naruto indeed exist in manga list.

**Comment by ThePrimus** [comment]
@riderkick it was an example.

**Comment by riderkick** [comment]
after doing some research its turn out all the uri in `mangatraders.biz/directory/` doesn't interchangeable with its online reading uri.  for example `http://mangatraders.biz/series/NarutoDigitalColoredComics`, its read online uri is `http://mangatraders.biz/manga/Naruto-Digital-Colored-Comics`. So we can't simply doing string replace.

So, I will just roll back to what it's before, and leave the link in mangalist with '/series/' and just doing auto redirect when read online link available.

**Comment by riderkick** [comment]
https://github.com/riderkick/FMD/commit/dc0d793cc4d7b79a299632ad32ccd8d2d03e2e7e

**Comment by ThePrimus** [comment]
@riderkick I may be wrong but it seems that all Manga `/series/` links like `NarutoDigitalColoredComics` or `ToLOVERuDarknessFullColor` are split after a capital letter and add a - to it e.g. `To-L-O-V-E-Ru-Darkness-Full-Color`.

**Comment by matoro** [comment]
Confirming @ThePrimus .  I saw the different strings for chapters vs volumes but I couldn't find a way to convert them programmatically.  Good catch looking at titles with capital letters in the name, I missed that.

So, I think the logic should be:
- Get volume link from ```/directory/```
- Convert to chapters link by adding at hyphen after each capital letter, unless there is one there already
- Probe chapters link
- If the site returns 404, skip the title: it is only available for volume download (or maybe don't skip it, but put a message somewhere indicating that, maybe with a link to the volume download)
- If not, add that link to the series database as the actual chapter link for the series

@riderkick Missing anything?

**Comment by riderkick** [comment]
The commit above will add all of them. Regardless they have read online available or not. When loading manga info, fmd will automatically detect if read online available and load the appropriate page.
Those without read online will be still saved btw. Maybe, just maybe, someday they will be available to read online.

**Comment by riderkick** [comment]
@ThePrimus , It's not that simple, we will just leave the link as it is. when loading manga info, fmd will automatically loading the appropriate page by detecting the read online button/tag.
