### ISSUE TITLE
Cookies readcomiconline

### ISSUE THREAD

**Issue by Nightwing90** [riderkick/FMD#438]
Hi,

I can download a few comics via readcomiconline. Every 5 to 10 comics, i've to delete the cookie, browse to the website, open up a comic (sometimes fill in the captcha) and then I can download some more. I have to do this everytime (5 to 10 comics). Is there something I can do about this?

**Comment by StormJumper** [comment]
Are we talking about FMD?

**Comment by riderkick** [comment]
There is nothing we can do about this. Captcha require real working browser. To much hassle for single website. I believe there is alternative website for everyone.

**Comment by kavin-90** [comment]
Google testing Invincible ReCaptcha too. Beta version of Invincible ReCaptcha is released.
