### ISSUE TITLE
Error compiling FMD

### ISSUE THREAD

**Issue by radiaku** [riderkick/FMD#44]
Hello sir,

is fmd using custom RichMemo? I barely updating my fpc but its gives me error when compiling. 

using:
Lazarus 1.5 rUnknown FPC 3.1.1 i386-win32-win32/win64
win7 ultimate

error
````
md.lpr(63,1) Error: Undefined symbol: WSRegisterCustomRichMemo 
````

thanks :)

**Comment by riderkick** [comment]
I'm using trunk version of richmemo. but there is should not be any major conflict. http://lazarus-ccr.sourceforge.net/
Is there richmemopackage on you project dependency?

**Comment by radiaku** [comment]
both yes..... but I suspected my version is an "old" revision ( I cant remember when I updating trunk ). After updating to https://svn.code.sf.net/p/lazarus-ccr/svn/components/richmemo/  (4178).

Worked like a charm... sorry for bothering :) and thank for replying
