### ISSUE TITLE
mangago

### ISSUE THREAD

**Issue by leoteesh** [riderkick/FMD#440]
Hi,
I can't seem to download from mangago. the below error message comes up. also my favourites are highlighted pinkish red. can you please advise?

![capture](https://cloud.githubusercontent.com/assets/21075197/21803766/76769f90-d723-11e6-8ab9-25bd13fc9c90.JPG)

Thanks

**Comment by joewono2011** [comment]
mangago changing URL website
www.mangago.com changed into www.mangago.me

I want to load mangago manga list from DDS to FMD, but i couldnt do it becaus URL was changed

Please help

**Comment by riderkick** [comment]
They now use cloudflare anti-ddos attack.

**Comment by joewono2011** [comment]
@riderkick there is any hope to fix it??

**Comment by purpleplushies** [comment]
also hopeful that there is a fix!
