### ISSUE TITLE
Stacking dialogs

### ISSUE THREAD

**Issue by blue-lightning** [riderkick/FMD#45]
When opening FMD, if by chance a Favorite dialog appears after the Updater dialog has showed up, the Updater dialog would hide the Favorite one and then the user is stuck because FMD requires user interaction with Favorite dialog before doing anything else.

Also, the dialogs aren't minimizable or hideable behide other windows, so it obstructs the user if they want to do other things along with updating FMD.

**Comment by riderkick** [comment]
My bad, didn't notice that. That's due to update dialog form stay on top. It should be fixed with this commit https://github.com/riderkick/FMD/commit/98d3080bc3dded32717532698af55423a54b3100
