### ISSUE TITLE
Enable logging causes system to freeze up

### ISSUE THREAD

**Issue by StormJumper** [riderkick/FMD#452]
Has the logging system been fixed? Everytime I try to check the box for "Enable Logging" my system freezes and I have to do a task manager and kill FMD process to get control back. I am using FMD 0.9.87.0 x64 version.

**Comment by riderkick** [comment]
There is no problem here. There is someone who also posts the log here, so I assume he has no problem either. Maybe permission issue?

**Comment by StormJumper** [comment]
hmm.. I wonder about that but everything else works ok. ????

**Comment by riderkick** [comment]
Permission issue or some antivirus/guard interfere.
