### ISSUE TITLE
Persistent error "Failed, try resuming this task!" in most pages

### ISSUE THREAD

**Issue by Askael89** [riderkick/FMD#453]
There is a persisting error, the program tries to download a chapter but fails, then proceeds to try to download the next chapter, but it uses the pages downloaded from the previously failed chapter to create the new .cbr file for the next chapter.
a simple solution for this would be to add the chapter number to the pages of the chapter

**Comment by StormJumper** [comment]
You want to give which site and manga example so they can test it just saying in general will give them no way to verify the problem.

**Comment by Askael89** [comment]
it is mostly with mangafox

**Comment by kavin-90** [comment]
They're having problem these days. Many times you will get 404 error when browsing site.

**Comment by StormJumper** [comment]
@kavin-90 it's a wonderful life lol.... sounds like DOS on mangafox....

**Comment by kavin-90** [comment]
@StormJumper today also they were down also their sister site mangatown lol

**Comment by riderkick** [comment]
Most of the time, if not always, mangafox reply with `503 Service temporary unavailable` if you have more than 2 connections. But that's only applied with main domain. There's no limitation to download the images, because they put the images on different domain.
