### ISSUE TITLE
Please add Goodmanga just moving from Domdom Soft Manga Downloader

### ISSUE THREAD

**Issue by molitar** [riderkick/FMD#454]
I am just moving off Mangasoft Downloader but Goodmanga is missing that I had quite a few bookmarks for.

**Comment by StormJumper** [comment]
Link so they can look into it. Doing what we can helps them.

**Comment by kavin-90** [comment]
domain is `http://www.goodmanga.net/` ?

**Comment by molitar** [comment]
Hi yes that is correct Kavin.  I like them as the try not to butcher there manga by lowering the resolution like Mangafox does.  They have quite a few manga's that other sites have but in good quality.

**Comment by kavin-90** [comment]
@molitar i added GoodManga it need touch up.

**Comment by molitar** [comment]
Awesme Kavin-90!  Thank you.  I was pleasantly suprised when I found out FMD supported importing from Manga Downloader as I have over 210+ bookmarks. Since many manga only get 1 chapter a month or two for translations I read them as released so over 210 bookmarks really does not seem that many when you think of it that way but it would of took me ages to manually add them all as I thought I was going to have to.  Thanks for this great software!

**Comment by molitar** [comment]
Kavin-90 I downloaded the latest version and compiled it but I do not see GoodManga in it at all. I downloaded the FMD-Master repository.

**Comment by kavin-90** [comment]
@molitar i just added module so you need to add it to modulelist.inc and mangalist.ini

**Comment by riderkick** [comment]
@kavin-90 do you have sf account? I want to give you permission to sf page, so you can upload the mangalist data. Just simply compress the *.db to 7z format.
https://sourceforge.net/projects/newfmd/

**Comment by kavin-90** [comment]
@riderkick I'm going to create it right away.

**Comment by riderkick** [comment]
Done. I usually use Bitvise's SSH Client. Please test if you can log in and upload some files.

![sshot-2017-01-21- 18-55-19](https://cloud.githubusercontent.com/assets/4972676/22173919/76e4d79e-e00b-11e6-80d4-08c751e9210b.jpg)
