### ISSUE TITLE
A manga available on kissmanga but not on Fmd

### ISSUE THREAD

**Issue by Souravi785** [riderkick/FMD#455]
"Enen no Shouboutai" manga is available on kissmanga but can't find it in Fmd. I tried updating the list, downloading the list from the server but still no "Enen no Shouboutai". Can you fix the problem?

**Comment by StormJumper** [comment]
link?

**Comment by Souravi785** [comment]
[http://kissmanga.com/Manga/Enen-no-Shouboutai](url)

**Comment by riderkick** [comment]
You can put that url to manga info tab.
Kissmanga has sorted list. You need to rebuild your mangalst by deleting the old one to get the fresh list.

**Comment by Souravi785** [comment]
How do I delete the old list? I deleted the list from the data folder and updated the list again. But could find the manga.

Another manga missing-[http://kissmanga.com/Manga/Gosu-The-Master](url)

**Comment by Inareous** [comment]
Hi!

You can delete KissManga.db from ~\data.

After you've done so, update the manga **but not from the server**, it will by then crawl the site and creating a new list.

**Comment by Souravi785** [comment]
It worked.Thanks.
