### ISSUE TITLE
Help! Compile error

### ISSUE THREAD

**Issue by molitar** [riderkick/FMD#456]
Took me a while to find the necessary dependencies but got all the reste working escept hi 

simplehtmltreeparser.pas(13,74) Fatal: Cannot find FLRE used by simplehtmltreeparser of package internettools.

where do I get the FLRE required and how to install it?

**Comment by Inareous** [comment]
Hi!

You can get FLRE here : https://github.com/benibela/flre/

**Comment by riderkick** [comment]
Comment out flre define, and just use Sorokin's regex which is come with fpc.
If you still want to use flre then get it here https://github.com/BeRo1985/flre

**Comment by molitar** [comment]
Thanks got it compiled but did not see the Goodmanga in the actual build only in the module.  Internettools had several components that does not work with free pascal so I had to remove the pas for them and finally got it to build properly with no errors.
