### ISSUE TITLE
Greek translation

### ISSUE THREAD

**Issue by geogeo-gr** [riderkick/FMD#460]
Greek translation to v0.9.88
[fmd_greek.zip](https://github.com/riderkick/FMD/files/723573/fmd_greek.zip)

**Comment by riderkick** [comment]
Thanks.

**Comment by geogeo-gr** [comment]
added option to open favorites at startup if check favorites checked.…
[fmd_greek.zip](https://github.com/riderkick/FMD/files/760034/fmd_greek.zip)

**Comment by riderkick** [comment]
Well, if you fork this project. You can always make a pull request, easy to merge, with a better history.
You want to do it or let me commit the changes?

There is also `lclstrconsts.po` from here:
`http://svn.freepascal.org/cgi-bin/viewvc.cgi/trunk/lcl/languages/lclstrconsts.po?view=co&revision=53737&root=lazarus`

It's for common UI like dialog etc from LCL. I don't see greek translation yet. `http://svn.freepascal.org/cgi-bin/viewvc.cgi/trunk/lcl/languages/?root=lazarus`

You can submit the file to `http://bugs.freepascal.org/`

**Comment by geogeo-gr** [comment]
Sorry for the delay but I was missing for jobs.

It is difficult for me to handle this platform, so I prefer to upload it here. Since there is no problem, of course.

As far as lclstrconsts is concerned, there is a big problem with the Greek language, similar to the corresponding QT library, leading to comic results. In Greek language, the adjectives have three generations of males, females and neutral. Words like 'new' can not be taken from a library because in Greek they are three 'New'. e.g. : 
New folder=**Νέος** φάκελος
New date=**Νέα** ημερομηνία
New file=**Νέο** αρχείο
