### ISSUE TITLE
Minor Glitch: 0.9.88.0 deselects websites

### ISSUE THREAD

**Issue by greenaar** [riderkick/FMD#461]
Following an upgrade to 0.9.88.0, all of my selected manga sites were cleared.  Account settings remained intact, but things like 'max concurrent downloads per host' were also wiped.

Not a huge deal.

Also worth noting 0.9.87.0 seemed to be missing the 7za.exe, i had to manually add it to upgrade.

**Comment by Inareous** [comment]
Config and data folder will not change because update, file 7za.exe also won't get deleted from /

Tested updating it, and it seems working as expected.

May you inquire with further detail by how you update your FMD ?

**Comment by greenaar** [comment]
I use the update button in the application.  I moved from 0.9.85.0 to .87, then to  .88 where i noticed this change.  I'm not sure how 7za.exe vanished,  I only noticed when I tried the upgrade the first time and it failed complaining about it.

As mentioned, it wasn't a huge deal -- *most* of my config settings persisted, but the list of sites and a few related settings were wiped.  If nobody else reports this as well, you can chalk it up to some issue with my configs.

**Comment by Inareous** [comment]
It is weird indeed.

7za.exe never listed as a virus so we can rule anti-virus out from this one.

As for how most of your config persisted, since almost all of settings saved in one file (config.ini), it shouldn't be possible for partial change in settings so i think only config.ini changed while accounts.db retain its data.

Are you doing some sort of rollback such as system restore / backup ?

**Comment by matoro** [comment]
This sounds to me like you configuration got deleted somehow.  If you want to be safe about this in the future, make a backup of your ```config``` and ```works``` folders.

**Comment by riderkick** [comment]
Updater will not delete your config. There is no config file in update package. Updater simply download then extract-overelwrite to existing directory.
