### ISSUE TITLE
TUMANGAONLINE does not allow me to obtain information from the mangas

### ISSUE THREAD

**Issue by hellsword** [riderkick/FMD#462]
:(  Every time I try to select a manga, the following message appears:     

![image](https://cloud.githubusercontent.com/assets/18252178/22229476/ae5b2140-e1b6-11e6-81f9-04f58e4d537a.png)

**Comment by Mariolr93** [comment]
Me too. But only with a few mangas.

**Comment by riderkick** [comment]
I don't have problem with that.
![sshot-2017-02-07- 12-35-12](https://cloud.githubusercontent.com/assets/4972676/22678035/155e9a4e-ed32-11e6-956a-70049355c366.jpg)

**Comment by kavin-90** [comment]
@riderkick screenshot show the problem. what you're getting what he is getting **url** is different that is issue.

**Comment by riderkick** [comment]
@kavin-90 can you rebuild the manga list and upload it to sf. Also, some of the missing manga list if you can.

**Comment by kavin-90** [comment]
I'm build it on Dedicated Server.

**Comment by riderkick** [comment]
Nice.

**Comment by kavin-90** [comment]
@riderkick i didn't see the data dir on SF i saw `/home/project-web/newfmd/`

**Comment by riderkick** [comment]
That's the directory for sf homepage.
It's in `/home/pfs/project/newfmd/data`
What client did you use?

![sshot-2017-02-07- 14-57-40](https://cloud.githubusercontent.com/assets/4972676/22680961/d0553138-ed45-11e6-9137-e10eea14e28d.jpg)

**Comment by kavin-90** [comment]
same as you i use now CoreFtp
