### ISSUE TITLE
PowerManga list download error

### ISSUE THREAD

**Issue by samuelporcellis** [riderkick/FMD#463]
I'm using version 0.9.88.0 and the error I get is "File not Found! Response: 404 Not Found".

**Comment by Inareous** [comment]
Right now there are no premade database for powermanga in https://sourceforge.net/projects/newfmd/files/data/

You still can update the manga manually (not from the list)

**Comment by riderkick** [comment]
If there is no prebuild mangalist and someone can build it then just send me the files. I will reupload it to mangalist repo.
Just compress the db files with 7z. And please use high/ultra compression level to save bandwidth.
