### ISSUE TITLE
Urgent Issue [mangastream]

### ISSUE THREAD

**Issue by ratbunuts** [riderkick/FMD#464]
FMD is not downloading at all today 01/23/2017. It will read all new manga's but it's failing on downloading. Is this just me? 

Update: I re-run it again and now only mangastream site is not downloading

**Comment by Tmp341** [comment]
Mangastream working here.

**Comment by riderkick** [comment]
Please elaborate

**Comment by ratbunuts** [comment]
I dont exactly know what the problem is but it seems like comcast is interfering with mangastream. And its working again now. Thanks for the reply

**Comment by riderkick** [comment]
I remove it for a reason. you can use popup menu instead. #469
