### ISSUE TITLE
Hentai2read cant update mangalist

### ISSUE THREAD

**Issue by Hexaf** [riderkick/FMD#465]
Tried to update mangalist but new manga not show up. I tried to delete the database and update mangalist from fresh it wont update.

**Comment by StormJumper** [comment]
Checked it and no problem - how did you do the update? Give steps so others can test it out.

**Comment by Hexaf** [comment]
Just usual click blue icon and update manga list.
Tried update today and it works again. Maybe my isp is the cause.
