### ISSUE TITLE
Why remove all complete gone?

### ISSUE THREAD

**Issue by KeithHanzhel** [riderkick/FMD#469]
In the latest update, the button is gone. Is there any reason you remove it?

**Comment by StormJumper** [comment]
That was gone two builds back and you just noticed it? I think they did have a update txt about it if I recall.

**Comment by KeithHanzhel** [comment]
https://github.com/riderkick/FMD/compare/0.9.87.0...0.9.88.0

In the log, he remove it in this build tho...

@riderkick 	riderkick 	hide button delete all completed task on download list toolbar 			5ea66f7

and as far as I remember, I gave issue about mangago error in build 86, so when he release build 87, the button still there...

**Comment by StormJumper** [comment]
All I do is highlight one of the completed download and pick option to clear all downloads and that gets rid of them.

**Comment by KeithHanzhel** [comment]
Yeah, I know... I just wanna know the reason like maybe it made fmd bugged or something. That button only need 1click, so for me it's more simple.

**Comment by riderkick** [comment]
I remove it because it's too wide for small scren (notebook). Since there is already a menu for it. Just 2 click away. I think it's shouldn't wasting your time that much.

**Comment by KeithHanzhel** [comment]
Well, thanks for explaining. I never use screen below 14" so I didn't know. Keep up the good work!
