### ISSUE TITLE
Tsumino Cookie

### ISSUE THREAD

**Issue by chibibi22** [riderkick/FMD#476]
so I've been following the steps on getting the cookie for tsumino but I keep getting this cookie

Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Content-Length:7
Content-Type:application/x-www-form-urlencoded; charset=UTF-8
Cookie:__cfduid=
 
ASP.NET_SessionId=
Host:www.tsumino.com
Origin:http://www.tsumino.com
Referer:http://www.tsumino.com/Read/View/27795
Save-Data:on
User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by chibibi22** [comment]
[UserAgent]
Tsumino=Mozilla/5.0 (Windows NT 6.3; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0

[Cookies]
Tsumino=ASP.NET_SessionId=

am I doing this right?

**Comment by StormJumper** [comment]
Are those steps listed on this site?

**Comment by riderkick** [comment]
You should use all the cookies, separated by `;`
```
[Cookies]
Tsumino=_cfduid=xxx; ASP.NET_SessionId=xxx
```
