### ISSUE TITLE
Kissmanga No longer working.

### ISSUE THREAD

**Issue by BadChase** [riderkick/FMD#479]
Hello guys, 

I don't know if it is just me, but a few days ago Kissmanga was working perfect. But now, when using FMD and choosing a manga from there it just says that there are 0 chapters. 

Just though you would like to know,

**Comment by Tmp341** [comment]
It is working here. Just downloaded a manga from there.

**Comment by BadChase** [comment]
Hello there. 

Okay nevermind, it didn't work, but now it does. Wow, I have no idea why. Anyway thanks.
