### ISSUE TITLE
add manga.madokami.com

### ISSUE THREAD

**Issue by MammothJerk** [riderkick/FMD#48]
> The direct link is available in there. And it seems the series that is available in there already available on other website.
> Please make a new issue if it's unrelated with OP.

here is the new issue, i just thought i should keep building on his topic since he was requesting websites to be added.

https://manga.madokami.com/

yes the link to download is in the site directly but so it is on Mangatraders, Kissmanga, and most scanlators readers.

i know there are several manga on madokami that i havent seen on any other site that is not riddled with compression artifacts, annoying/ugly watermarks, and lower resolution.

of course if its too big a job to implement madokami since the website is a bit unique then don't bother =)

**Comment by riderkick** [comment]
The main problem is I can't build the manga list. The directory is clustered with dynamic subdirectory.
I can add it but without manga list. You have to manually put the url to mangainfo.

**Comment by MammothJerk** [comment]
ah i see

thats too bad :s

**Comment by riderkick** [comment]
I can only add this directory, the others had uncertain folder deep.
```
Manga/# - F/
Manga/G - M/
Manga/N - Z/
```

**Comment by MammothJerk** [comment]
That is great
those are the most frequently used folders for me anyway =)

**Comment by riderkick** [comment]
I added this directory, refer to this commit https://github.com/riderkick/FMD/commit/2e30cb130c5a2014e795b3d3dc0bb5241ee5a1ec

    '/Manga/%23%20-%20F',
    '/Manga/G%20-%20M',
    '/Manga/N%20-%20Z',
    '/Manga/_Autouploads/AutoUploaded%20from%20Assorted%20Sources',
    '/Manga/_Autouploads/ComicWalker',
    '/Manga/Non-English/Bahasa%20Indonesia',
    '/Manga/Non-English/Brazilian%20Portuguese',
    '/Manga/Non-English/Fran%C3%A7ais',
    '/Manga/Non-English/Italian',
    '/Manga/Non-English/Spanish',
    '/Manga/_Doujinshi',
    '/Raws'
