### ISSUE TITLE
Translation for Portuguese from Brazil

### ISSUE THREAD

**Issue by Havokdan** [riderkick/FMD#481]
Links:

https://mega.nz/#!mEwgQTRI!pbUuG5tjhOu57rdB6kPANa33hQtlGb3Or9GuRMVFpiM
https://www.4shared.com/archive/RR_wwGXice/Fdm.html
https://www.mediafire.com/?b418ayb46ar4sv4

**Comment by riderkick** [comment]
Thanks.
