### ISSUE TITLE
(Contribute) Spanish Translation

### ISSUE THREAD

**Issue by Mariolr93** [riderkick/FMD#482]
I made a Spanish translation of FMD.
So, I wanna contribute with this. I hope you like it.

PS: I put a dropbox link, because github it does not let me attach the file.

https://www.dropbox.com/s/ex5js1p0m3lntrs/Spanish%20Translation.zip?dl=0

**Comment by riderkick** [comment]
Thanks. 
Yes, there is an issue when attaching `zip` file. It can attach `gz` file though. You can append another extension before attaching the file, e. g. ``file.zip.gz`
