### ISSUE TITLE
[Request] Restore two features that were removed.

### ISSUE THREAD

**Issue by A912** [riderkick/FMD#483]
1) In the downloads tab the Delete all completed tasks button is removed in the fmd_0.9.89.0_Win64 an is in only right click options. Please restore that in the top section as well.
2) On a manga that is being downloaded or completed in the download tab, when we used to double click it used to open the respective folder of the manga in download process. Now it just opens the latest file downloaded instead of the folder. Please restore this feature. which the manga filed were 

Thanks

**Comment by riderkick** [comment]
Please search related issues, it's have been discussed before.
