### ISSUE TITLE
Check for update finds update that does not exist

### ISSUE THREAD

**Issue by molitar** [riderkick/FMD#484]
I keep getting message that there is an update but it does not exist.

0.9.90.0 (16-02-2017)
[+] Added Portuguese (Brazil) translation by Havokdan
[+] Added Greek translation by geogeo_gr
[*] Fixed error when removing running download task
[*] Fixed shop drop box at startup
[*] Various changes and bug fixes
Full changes: https://github.com/riderkick/FMD/compare/0.9.89.0...0.9.90.0

**Comment by riderkick** [comment]
It seems there is a problem with sf. It's not importing from github like usual, and now they flagged my files as infected. Can you download manually from github and scan it with your antivirus?

**Comment by molitar** [comment]
Actually error I get is file not found when it attempts to start the download.  I had to download manually I am wondering if this is due to the version I am running is the x64 version.

**Comment by riderkick** [comment]
Not found is because the file wasn't ready in the sf server. Like I said, there is a problem with sf, its not imported immediately as usual. I had to import it manually to sf. Now it's should be fine.
