### ISSUE TITLE
Error Favorites list. How to fix it?

### ISSUE THREAD

**Issue by mikazuki7** [riderkick/FMD#485]
After auto-updating, suddenly my favorites list screwed up. How to fix it? I don't want to lost my 301st title to 446th.

![error fmd](https://cloud.githubusercontent.com/assets/8412528/23072424/2fefef40-f564-11e6-9c3c-5a3cbc1c67c6.jpg)

**Comment by kavin-90** [comment]
It seems your favorites list file (**favorites.ini**) got corrupt open and see what you got in that file if that file show wrong data(NULL other values) means you lost all your favorites data.

**Comment by riderkick** [comment]
The red color means it has no correct link. Your data seems corrupt.

**Comment by molitar** [comment]
wow.. I would like to see a way to backup favorites so when we have a lot of favorites we could save the backups.

**Comment by riderkick** [comment]
You can just  copy favorites.ini to other place. You can make task schedule in windows to run everyday.
I'm planning to move downloads and favorites to sqlite database, but not so soon. I've been planning since 2 years ago, don't have time to finish it yet.

**Comment by StormJumper** [comment]
Like riderkick says just copy your favorites.ini to another location that is what I do for every updates so there is always a older version from previous that was updated before the newer version was used.
