### ISSUE TITLE
Kissmanga broken

### ISSUE THREAD

**Issue by molitar** [riderkick/FMD#486]
Can not read or list the manga.   For example Love Parameter shows as 0 chapters online but there is 81 chapters that can be read.

**Comment by StormJumper** [comment]
Did you go to the site to see if there was a listing for that chapter?

**Comment by molitar** [comment]
Yes it was there at the site but the chapters showed nothing for Kissmanga in FMD.

**Comment by kavin-90** [comment]
Working fine on Latest Version I got the Chapter List.

![kissmanga](https://cloud.githubusercontent.com/assets/15142270/23155004/a7bca3c2-f836-11e6-9e2b-baa868e2626e.png)

**Comment by molitar** [comment]
Ok I relaunched it and it detected new version.  I let it update and it's working in the new version for me also.
