### ISSUE TITLE
Downloads do not finish archiving so unsure of download status

### ISSUE THREAD

**Issue by molitar** [riderkick/FMD#487]
I was trying to download 'The Gamer' on Eatmanga but I ended up with a bunch of folders that were not zipped or deleted so I was not even sure if the download finished.

example:

The Gamer 001.zip
The Gamer 002.zip
The Gamer 003 
The Gamer 004.zip
The Gamer 005
The Gamer 006
The Gamer 007
The Gamer 008.zip

it would start a new chapter download and skip the archiving process so I ended up with a mess in the folder and no idea if these folders did complete download or not.  The archive process needs to finish before starting a new folder.

**Comment by riderkick** [comment]
If you save as zip and the downloaded folder not zipped then it's not finished yet.  Some file failed to download, so its continue with next chapter in queue. The failed status should show up after the task finished. You can try to increase the retry times in connections setting.

**Comment by molitar** [comment]
I thought that too but when I looked in some of the folders it was complete.  It seems that it may lose it's place while archiving when downloading an entire manga with 50+ chapters.

**Comment by riderkick** [comment]
Like I said if you let it finish, it should show up as failed. then you can resume the task.
Or open the works.ini, there is a field `failedchapterlist`.
Or you can re add the troubled chapters, fmd will only download the missing files if chapter folder presents.
You can monitor this task and see what failed.

**Comment by molitar** [comment]
thanks for the tip on works.ini I did not know that it had a failed chapter list in it.
