### ISSUE TITLE
Urgent. FMD using a lot memory when checking for new chapters

### ISSUE THREAD

**Issue by ratbunuts** [riderkick/FMD#489]
After some recent update. I notice that FMD is using a lot of memory to run. As of today FMD is using 2.7GB of memory when it is checking for new chapters. That never happen before. Now I cant seems to run multiple software I use that usually runs along with FMD on the background.

**Comment by ZerOMegA2k5** [comment]
Same here. In my case the problem seems to be with Mangacow.

**Comment by ratbunuts** [comment]
I run FMD v0.9.88.0 from my backups and its only using the most is 130MB. So it really is on the recent update.

**Comment by ZerOMegA2k5** [comment]
Yes, I keep FMD updated and use it daily. The problem appeared after installing 0.9.92.0 update.

**Comment by Umo022** [comment]
Same here, though I run it on a Mac under Wine.  In my case though, fmd 0.9.92 is crashing during the Favorites check.  Getting debugging info from this environment is pretty hard, but my console dump might be a little helpful:

err:ole:CoUninitialize Mismatched CoUninitialize
err:ntdll:RtlpWaitForCriticalSection section 0x15fda0 "?" wait timed out in thread 01ec, blocked by 01d3, retrying (60 sec)
(Line repeats until crash.)

**Comment by SilentNN** [comment]
Just gonna chime in and say the memory leak happens for me every time I have FMD open since updating. Didn't report it last night because I hadn't tried restarting my computer.

**Comment by japzone1** [comment]
I can also confirm this issue. FMD seems to keep checking for new chapters endlessly, and slowly eating more and more RAM in the meantime. I didn't notice until programs started crashing out of nowhere. Opened up Task Manager and saw FMD using 10GB+ of RAM, which is obviously not supposed to happen.

Any easy way to downgrade in the meantime?

**Comment by riderkick** [comment]
Try the latest version.

**Comment by rs3mk** [comment]
![sin titulo 69](https://cloud.githubusercontent.com/assets/19628943/23195923/3b24f7ca-f884-11e6-98e6-3df7f0fda2c3.png)

**Comment by riderkick** [comment]
Can someone please scan the 32bit version. SF always flagged my upload with `infected: Gen:Variant.Graftor`.

By google search:
`Gen:Variant.Adware.Graftor is a specific detection used by Emsisoft Anti-Malware, F-Secure Antivirus, G-Data Antivirus and other antivirus products to indicate and detect a Potentially Unwanted Program.
A potentially unwanted application is a program that contains adware, installs toolbars or has other unclear objectives.`

It's funny because SF who usually put this kind of thing.

**Comment by japzone1** [comment]
Latest version seems to have fixed it. Chapter update check completed successfully, and FMD is sitting at 26.5MB of RAM.

**Comment by japzone1** [comment]
Also I did a malware scan like you asked and both Windows Defender and Malwarebytes said it was clean.

**Comment by kavin-90** [comment]
@riderkick that is why SF has Beware Malware posts for files and people said don't download from SF last year or maybe few years ago.

**Comment by riderkick** [comment]
I tried to download and compare the files with local files, the md5 is identical. Maybe it's false positive on their side.
