### ISSUE TITLE
Feature request, marked disable 

### ISSUE THREAD

**Issue by radiaku** [riderkick/FMD#49]
Hi, can you add feature, disable in one or more in downloads. 

Its very useful to download later but keep it in download. Sometimes connection is bitch -_-. So I can download smaller manga first and big manga later ( when connection is good )..

Thanks you :)

**Comment by riderkick** [comment]
Can't you just set it to stop. It will be skipped of course if there is active download below.
Just start/resume the task that you need to download, you can arrange the task with drag n drop or CTRL+UP/DOWN, multiple selection is supported. It's shouldn't be that hard. I usually move the larger one to the bottom.

![sshot-1](https://cloud.githubusercontent.com/assets/4972676/8026240/8c0d7bf0-0da1-11e5-95b8-fa8dd8cf3363.jpg)

**Comment by radiaku** [comment]
I didnt know that... I thought its just simple stopping... thanks you, its helped me alot :)
