### ISSUE TITLE
[Batoto] Remove Download-Limit

### ISSUE THREAD

**Issue by SDXC** [riderkick/FMD#490]
Please remove the download limit for batoto. I'm trying to move from DomDomSoft to FMD but the downloads for batoto are much too slow. With DomDomSoft I was able to run multiple downloads on batoto without getting slowed down or being blocked. It'd be nice if at least 5 files could be downloaded simultaneously :)

**Comment by rbwz** [comment]
In the tab Options>Connections, there are settings for concurrent tasks and concurrent files downloaded.

...Unless the limit is imposed by the website... (i.e. concurrent  = being blocked)...

**Comment by SDXC** [comment]
`procedure RegisterModule;
begin
  with AddModule do
  begin
    Website := modulename;
    RootURL := urlroot;
    MaxTaskLimit := 1;
    MaxConnectionLimit := 1;
    AccountSupport := True;
    SortedList := True;
    InformationAvailable := True;
    TotalDirectory := Length(dirurls);
    OnGetDirectoryPageNumber := @GetDirectoryPageNumber;
    OnGetNameAndLink := @GetNameAndLink;
    OnGetInfo := @GetInfo;
    OnGetPageNumber := @GetPageNumber;
    OnGetImageURL := @GetImageURL;
    OnLogin := @Login;
    AddOptionCheckBox(@showalllang,'ShowAllLang', @RS_ShowAllLang);
    AddOptionCheckBox(@showscangroup,'ShowScanGroup', @RS_ShowScanGroup);
end;`

This is a part of the batoto module for FMD. That's why I think it's not a site limitation and that's also why the options tab is ignored.

**Comment by riderkick** [comment]
There is advanced setting that will suppress the hard limit.
This is have been discussed before, I put that limitation with a reason. Just search the issues, I forgot the details.

**Comment by SDXC** [comment]
Well, so far the advanced options did work for me. Thank you for that hint. :)
