### ISSUE TITLE
Some Vietnamese Site can't working ?

### ISSUE THREAD

**Issue by tranhoangcore** [riderkick/FMD#491]
Dear supporter,
I have some problems on FMD about Vietnamese Manga Sites.
I can't get images, info and download chapters from:

- Truyentranhtuan.com
- Manga24h.com
- Blogtruyen.com

Can you check again ?
Regards

**Comment by kavin-90** [comment]
Truyentranhtuan.com broken
Manga24h.com redirect to Manga24h.me (seems Broken)
Blogtruyen.com works but not chapter list correctly.
