### ISSUE TITLE
download from hentai2read

### ISSUE THREAD

**Issue by kyon123** [riderkick/FMD#492]
im try download from hentai2read, how to download ongoing manga, in FMD give me blank page at  the description

**Comment by riderkick** [comment]
Please elaborate. Provide a url and screenshot if necessary.

**Comment by Squidii** [comment]
hi not sure if its the same issue but to elaborate H2R only picks up one page in each task whether its complete or not checked, i've with other manga sites and it picks up all the pages

**Comment by kavin-90** [comment]
have you try other Series if same happens to other series that means structure changed or login required

as riderkick said please provide us url or screenshot.

**Comment by Squidii** [comment]
![image](https://cloud.githubusercontent.com/assets/17956536/23337687/b8d35900-fbfe-11e6-98ab-a4763c911232.png)

tried with other Series, there doesn't seem to be an option to add an account for H2R, I've also realized that download works correctly from old task where the page numbers did pick up correctly

Example
below is an old task from three days ago that i didnt complete, when i resume it works correctly
![image](https://cloud.githubusercontent.com/assets/17956536/23337742/ee687c5c-fbff-11e6-963f-998ce66ed5cc.png)
