### ISSUE TITLE
Access violation on update

### ISSUE THREAD

**Issue by vmdude** [riderkick/FMD#495]
Hi,

Since a few weeks, auto update within app does not work for me anymore, I keep having an error 'Access violation': 

![old_updater_2017-02-28_11-28-37](https://cloud.githubusercontent.com/assets/1384259/23401793/4fb67de2-fda9-11e6-8724-f393cf2686db.png)

Even if I press OK, the program just end without being update.
Each time I have to update manually.

Is there a workaround/known issue ?
Frederic

**Comment by vmdude** [comment]
I got the exact same message running updater.exe

**Comment by riderkick** [comment]
Need more info.
Updater hasn't been touched for 7 months.
It's after downloading the update, at the middle or before starting the download?

**Comment by riderkick** [comment]
There is an issue with fmd thought, it's can't terminate most of the threads when closing the entire program. I'm still working on it.
Try to terminate all the threads before launching the updater. I mean stop all downloads, favorites check, and all other threads.

**Comment by riderkick** [comment]
What version did you use? (32/64)
Try running the updater manually from cmd:
`updater.exe -x -r 3 -a "https://sourceforge.net/projects/newfmd/files/0.9.94.0/fmd_0.9.94.0.7z/download" -l "fmd.exe"`

Other thing is, the updater can't write the file to disk, try to run the cmd with admin priviledges or set compability of updater.exe with admin.

**Comment by vmdude** [comment]
I tried to run updater.exe even i there is no process running, with the same result.

Command line also give the same result

![powershell_2017-02-28_15-54-36](https://cloud.githubusercontent.com/assets/1384259/23410134/84506cbe-fdce-11e6-81f9-c5bc62209c3e.png)

**Comment by riderkick** [comment]
Strange, what version of your updater.exe? Properties > Details tabs.

**Comment by vmdude** [comment]
Here it is:

![explorer_2017-02-28_16-13-07](https://cloud.githubusercontent.com/assets/1384259/23410843/d4ddeefc-fdd0-11e6-9146-2a3e3e23edc2.png)

**Comment by riderkick** [comment]
Can you launch the updater.exe ?
Does it show the window?

**Comment by vmdude** [comment]
If I start the updater.exe, it displays the window, even in elevated mode

**Comment by vmdude** [comment]
I've got the error as soon as I start the upgrade process, or that I start updater.exe

**Comment by riderkick** [comment]
Please try this one, remove the .txt part. Just replace your replace file.
[updater.exe.txt](https://github.com/riderkick/FMD/files/807378/updater.exe.txt)

**Comment by vmdude** [comment]
This one start successfully, but it's stuck on this page:

![2017-02-28_17-03-25](https://cloud.githubusercontent.com/assets/1384259/23413060/e12ce940-fdd7-11e6-9612-568f9eff3018.png)

**Comment by vmdude** [comment]
Yep it updated successfully, thx a lot.
Can I keep this updater.exe version ? It will not be overwritten by future update ?

**Comment by riderkick** [comment]
Try this, remove .txt part. Both file must be in the same folder.
[updater.dbg.txt](https://github.com/riderkick/FMD/files/807434/updater.dbg.txt)
[updater.exe.txt](https://github.com/riderkick/FMD/files/807435/updater.exe.txt)

**Comment by vmdude** [comment]
It works as well with these files.

**Comment by riderkick** [comment]
It will. But future version should include the fixed updater.
You can update to current latest version and replace the updater with the fixed one, then it should be fine for the future updates.
