### ISSUE TITLE
Kissmanga downloads fail. Chapters are named incorrectly.

### ISSUE THREAD

**Issue by molitar** [riderkick/FMD#496]
These downloads keep failing to download for some reason on Kissmanga. If I go to web they are there but these ones tend to fail a lot.

http://i.imgur.com/oXQbjeJ.png

Just wanted to add that other manga's work perfectly fine with Kissmanga.  Not sure why some work good and others do not. 

Ok looking in the folder the chapter is trying to download as...

Sweet Guy Chapter 072!%~

There is no !%~ after the chapter name so this seems to be a bug in downloads for Kissmanga.

**Comment by BadChase** [comment]
I get the same issue after the update yesterday. Even with the new today it is still the same.
I also get it from GoodManga and Kissmanga. But can download other series. 

But for those that doesn't work it gets created a folder with the ending of !%~ just as above, and then fails to download. 

If you want to know which series, then please tell me.

**Comment by kavin-90** [comment]
verified i got not complete chapter list i gonna build list from ?id= because that only needed to view chapter.

**Comment by Tmp341** [comment]
I've compiled two pictures here: first one is for kissmanga. It's working without a problem. 2nd one is the options i have. Check it if yours are different. I'm not trying to say these all are right.,

[ss](https://cloud.githubusercontent.com/assets/1683388/23475757/977d8974-fec9-11e6-9e62-a18cfd083003.jpg)

**Comment by molitar** [comment]
Thanks new release has fixed the issue.. working good now so looks like you can close this as a resolved ticket!  Thanks again!

**Comment by riderkick** [comment]
I can't open kissmanga. My country block it. And most of free vpn or proxy is banned by kissmanga. Anyone have working proxy?

**Comment by riderkick** [comment]
`!%~` is separator used by works.ini. There is a bug when converting it to db, I forgot to parse it first.
fixed by commit https://github.com/riderkick/FMD/commit/bcbe2e5264d3d70783f83d38fc90cb68b179048b

**Comment by kavin-90** [comment]
@riderkick above my code for fixing chapter list because it OP's series i checked latest version give me less than 10 chapters where on website it greater than 70. so i changed foreach query.

2nd i saw you use <title> why not use original div which contain series title so i changed in my kissmanga to it. 2nd i use replace string to remove series title from chapter name.

**Comment by riderkick** [comment]
@kavin-90 I can't open kissmanga, so I can't test it.

**Comment by kavin-90** [comment]
@riderkick you can search google for freevpn

**Comment by riderkick** [comment]
@kavin-90 I did, but most vpn is blocked by kissmanga/cloudflare.

**Comment by riderkick** [comment]
@kavin-90, you can commit the changes if you sure about that.
There is an option to remove the series name from chapters. That's what it is for. Some people still wanted to include the series name on the chapters, for example when they store all series in one folder. There is an argument about this, I forgot where. So just leave the chapter title as it is. People still can use the "remove series name from chapters" if they wanted to.

**Comment by riderkick** [comment]
@kavin-90 , I just remembered, I use `title` because, in series with `@` character, the `a` text will contain a javascript that supposes to be replaced with `@` character.

**Comment by riderkick** [comment]
@kavin-90 
Please check `http://kissmanga.com/Manga/Idolm-ster-Dearly-Stars-Innocent-Blue`
You will see what I'm talking about.

**Comment by kavin-90** [comment]
yeah that is Cloudflare fault

**Comment by riderkick** [comment]
> @riderkick above my code for fixing chapter list because it OP's series i checked latest version give me less than 10 chapters where on website it greater than 70. so i changed foreach query.

@kavin-90 which one is that?

**Comment by riderkick** [comment]
No. I mean which series has less than 10 chapters?

**Comment by kavin-90** [comment]
Sweet Guy

**Comment by riderkick** [comment]
It looks fine.

![sshot-2017-03-02- 23-00-59](https://cloud.githubusercontent.com/assets/4972676/23512585/14028260-ff9c-11e6-8ec0-58c7567ed523.jpg)

**Comment by kavin-90** [comment]
Yeah, now it show full list strange.

**Comment by riderkick** [comment]
No changes required then.
Can you check https://github.com/riderkick/FMD/issues/500?

**Comment by kavin-90** [comment]
How i don't know. I build Modules from copy and paste lol
