### ISSUE TITLE
Fmd not updating

### ISSUE THREAD

**Issue by leoteesh** [riderkick/FMD#498]
Hi 
I am trying to update to the most recent version but i am getting error message each time.

"File not found - error 404 not found"

![Uploading Fmd error.JPG…]()

Can you please help?
Many thanks

![Uploading Fmd error.JPG…]()

**Comment by molitar** [comment]
Files need to updated before they are updated on the web.  This has happened a few times so we have to wait for the update to be uploaded.

**Comment by riderkick** [comment]
Whole amazon s3 is down last night.
https://www.lowendtalk.com/discussion/107226/amazon-s3-down
It should be fine now.
