### ISSUE TITLE
madokami downloads failed

### ISSUE THREAD

**Issue by MammothJerk** [riderkick/FMD#50]
![](http://puu.sh/ij2Js/b436aa311a.png)
appears that some downloads don't work while some do.
i don't have much knowledge in this area but it might be because some of the images and PNG while others are JPG?
this is how it looks like in one of the destination folders
![](http://puu.sh/ij3dd/0183a455e8.png)
all of these folder are EMPTY

the chapters above 56 in the above picture do seem to download like normal until the failed error occurs
these chapters managed to download successfully
![](http://puu.sh/ij3i3/bb41b23816.png)

on the chapters that just show up as empty folders it seems like the transfer rate is very low 
![](http://puu.sh/ij3nK/76dea60cf0.png)
and in this instance it shows that the progress is 0/930 when in actuality the DL only contains 186 pages

**Comment by riderkick** [comment]
FMD will check the header of file to determine true file extensions.
It can be problem with parsing the json data or simply temporary server error.

**Comment by riderkick** [comment]
Fixed in 0.9.16.2, maybe.
