### ISSUE TITLE
possibility of feature which you can select/skip image to download?

### ISSUE THREAD

**Issue by otakuakiba** [riderkick/FMD#504]
say, is it possible to make a feature which you can select or skip image(s) to download ?
i know that would mean there has to be a pause between parsing the chapter and download images.
Its just, you know how there are galleries at g.e/exhentai that get updates here and there, now and then.
to be precise, i'm talking about korean-h-weebtoon shit that get updates regularly and you cant just download the new content from them, and a feature such as that would be a great help, since now you cant download them from raws.yomanga which got shut down already.

and while i'm at it. apparently **mangasee/mangalife** change their domain to **.us**, for now its  not such a problem since you can just change them to old domain on your own if you paste the link from browser, and  get redirect.

the last one, and i know i am being a dick with asking too much. but having more sites where hosts non-resized, non-compressed and non-watermarked images is always a good thing, and if it doesn't bother you, i hope you can add **manganel** to the list.

sorry for my engrish and thanks in advance.

**Comment by riderkick** [comment]
You can use save to without compress/pdf, just use "none".
So, the next time you add the same series, it will look at the existing folder, and only download the file that doesn't exist in the folder.

**Comment by riderkick** [comment]
Declined.
