### ISSUE TITLE
My work download missing

### ISSUE THREAD

**Issue by Hexaf** [riderkick/FMD#505]
I am using version 0.9.95 and 0.9.96 64 bit. When I close fmd and reopen it my recent work missing.

**Comment by riderkick** [comment]
Maybe related to #500
Try the latest version.

**Comment by Hexaf** [comment]
I try use 0.9.97 the bug still there

**Comment by NhKPaNdA** [comment]
And we are back for part 2.  Seems most of the issues from #500 was fixed. I tried some things out and the issues I found were: 1. Anything added automatically from your favorites into your downloads is not saved when FMD is closed and re-opened, though if a new download is added by manually searching for an individual manga update in your favorites, the state is saved when closed. 2. If something that was stopped in your downloads and resumed but sits in the queue, it returns to a stopped state when you close and re-open FMD.

**Comment by riderkick** [comment]
Can you look at the `fmd.log`, I put exception log if add/update, delete or commit failed. Maybe there is some information in there.

**Comment by Hexaf** [comment]
Well, if i check enable log and apply my fmd crash

**Comment by NhKPaNdA** [comment]
Doesn't look like there is. This is the last log session:

=== Log Session Started at 3/3/2017 10:37:53 by Free Manga Downloader ===
10:37:53:631 INFO: "Free Manga Downloader" started with [PID:8384] [HANDLE:4294967295]
10:37:53:695 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 0.9.97.0
               Product Version   : Win32 Debug
               Host Machine      : Windows 10
               Target CPU_OS     : i386_Win32
               FPC Version       : 3.1.1
               LCL Version       : 1.7
               Path              : D:\[Free Manga Downloader]\fmd.exe
               Process ID        : 8384
               MainThread ID     : 5368
10:52:58:932 INFO: TMainForm.FormClose
10:53:00:960 INFO: TMainForm.CloseNow, terminating downloads threads
10:53:01:067 INFO: TMainForm.CloseNow, downlads threads terminated
10:53:01:095 INFO: TMainForm.CloseNow, disabling all timer
10:53:01:156 INFO: TMainForm.CloseNow, backup downloads
10:53:01:186 INFO: TMainForm.CloseNow, backup favorites
10:53:01:337 INFO: TMainForm.CloseNow, backup all data to file
10:53:01:381 INFO: TMainForm.CloseNow, closing other forms
10:53:01:395 INFO: TMainForm.CloseNow, stop ipc server
10:53:01:416 INFO: TMainForm.FormDestroy, freeing all objects
10:53:01:844 INFO: "Free Manga Downloader" exit normally [PID:8384] [HANDLE:4294967295]

In that session my favorites were checked and new updates were added to download and none of them were there when I re-opened FMD.

**Comment by Hexaf** [comment]
I have same case with @NhKPaNdA

**Comment by riderkick** [comment]
@Hexaf check your permission/antivirus. Try with new installation.

@NhKPaNdA I just tried with auto download favorite and close it, it was there when I open it. Care to post your favorites.db and downloads.db?

**Comment by NhKPaNdA** [comment]
[works.zip](https://github.com/riderkick/FMD/files/816292/works.zip)

Here you go. The favorites_before.db is before the new chapter check.

**Comment by Hexaf** [comment]
=== Log Session Started at 3/3/2017 16:30:35 by Free Manga Downloader ===
16:30:35:382 INFO: "Free Manga Downloader" started with [PID:7424] [HANDLE:18446744073709551615]
16:30:35:382 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 0.9.97.0
               Product Version   : Win64 Debug
               Host Machine      : Windows 7 64-bit
               Target CPU_OS     : x86_64_Win64
               FPC Version       : 3.1.1
               LCL Version       : 1.7
               Path              : E:\fmd\fmd.exe
               Process ID        : 7424
               MainThread ID     : 7384
16:34:10:612 INFO: TMainForm.FormClose
16:34:11:459 INFO: TMainForm.CloseNow, terminating check favorites threads
16:34:11:755 INFO: TMainForm.CloseNow, check favorites threads terminated
16:34:11:755 INFO: TMainForm.CloseNow, disabling all timer
16:34:11:755 INFO: TMainForm.CloseNow, backup downloads
16:34:11:755 INFO: TMainForm.CloseNow, backup favorites
16:34:11:982 INFO: TMainForm.CloseNow, backup all data to file
16:34:11:984 INFO: TMainForm.CloseNow, closing other forms
16:34:11:985 INFO: TMainForm.CloseNow, stop ipc server
16:34:11:992 INFO: TMainForm.FormDestroy, freeing all objects
16:34:13:411 INFO: "Free Manga Downloader" exit normally [PID:7424] [HANDLE:18446744073709551615]

**Comment by riderkick** [comment]
It's saved alright here. Download automatically added after favorites check,
After reopen:
![sshot-2017-03-03- 17-38-52](https://cloud.githubusercontent.com/assets/4972676/23545943/7267e2c2-0038-11e7-8717-fd2ea5101475.jpg)

**Comment by Hexaf** [comment]
I think I found out. Try to delete all the task from old fmd. I try this and download some manga and voila no missing again.

**Comment by Hexaf** [comment]
But sadly I cant retrieve the manga update from favorite so I need to check it manually :(

**Comment by NhKPaNdA** [comment]
I deleted my downloads.db and had FMD recheck for new manga updates. The downloads saved properly and were there when i re-opened FMD. I assume it was from the download tasks from before the .97 update that was breaking them.

**Comment by NhKPaNdA** [comment]
=== Log Session Started at 3/3/2017 12:14:28 by Free Manga Downloader ===
12:14:28:242 INFO: "Free Manga Downloader" started with [PID:5936] [HANDLE:4294967295]
12:14:28:263 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 0.9.97.0
               Product Version   : Win32 Debug
               Host Machine      : Windows 10
               Target CPU_OS     : i386_Win32
               FPC Version       : 3.1.1
               LCL Version       : 1.7
               Path              : D:\[Free Manga Downloader]\fmd.exe
               Process ID        : 5936
               MainThread ID     : 7288
12:15:10:654 INFO: addedlink=/comic/_/comics/sekitou-elegy-r869
12:15:19:452 INFO: addedlink=/comic/_/comics/sekitou-elegy-r869
12:15:37:809 INFO: addedlink=http://bato.to/comic/_/comics/kampfer-r835
12:15:53:207 INFO: addedlink=http://eatmanga.com/Manga-Scan/Fairy-Tail/
12:16:03:920 INFO: addedlink=http://eatmanga.com/Manga-Scan/Fuuka/
12:16:19:462 INFO: addedlink=http://eatmanga.com/Manga-Scan/Nanatsu-No-Taizai/
12:16:34:307 INFO: addedlink=http://eatmanga.com/Manga-Scan/Onepunch-Man/
12:16:49:690 INFO: addedlink=http://kissmanga.com/Manga/The-God-of-High-School
12:17:35:202 INFO: TMainForm.FormClose
12:17:36:357 INFO: TMainForm.CloseNow, terminating downloads threads
12:17:36:780 INFO: TMainForm.CloseNow, downlads threads terminated
12:17:36:801 INFO: TMainForm.CloseNow, disabling all timer
12:17:36:922 INFO: TMainForm.CloseNow, backup downloads
12:17:36:959 INFO: TMainForm.CloseNow, backup favorites
12:17:37:088 INFO: TMainForm.CloseNow, backup all data to file
12:17:37:141 INFO: TMainForm.CloseNow, closing other forms
12:17:37:162 INFO: TMainForm.CloseNow, stop ipc server
12:17:37:191 INFO: TMainForm.FormDestroy, freeing all objects
12:17:37:588 INFO: "Free Manga Downloader" exit normally [PID:5936] [HANDLE:4294967295]

This is the session where I deleted my downloads.db and added all my previous tasks manually and had auto favorites check add new updates to the downloads. This is the picture of what my downloads were after I re-opened FMD.

![fmd after](https://cloud.githubusercontent.com/assets/15315466/23547500/0b536ccc-000c-11e7-9b11-5baa28ac9a10.jpg)

**Comment by riderkick** [comment]
View manga info from the different method?
The roots URL should be truncated. I will check it again.

**Comment by kevin01523** [comment]
https://www.datafilehost.com/d/f18c1587 can you look at mine too anything added then stopped doesnt get saved on downloads and my tasks since february until today didnt get saved or disappeared  after i updated to latest from 0.9.92.0 i do suggest a backup and import feature  of all tasks and favorites rather than backuping manually. like what domdom did before

**Comment by NhKPaNdA** [comment]
[favorites.zip](https://github.com/riderkick/FMD/files/818569/favorites.zip)

So I was trying to narrow down what could be causing the problem. I deleted my downloads.db and had the auto check run through my favorites. Once al the new chapters were added, i closed FMD and re-opened it to see if everything stayed, which they did. I then let them all download and finish and after closing and re-opening FMD half of them were completed (until Konjiki no word Master) while the other half was still waiting in the queue and even 2 of the downloads (The Gamer & The God of Highschool) failed to download even though they downloaded perfectly fine before. After they finished again I closed and re-opened FMD and they were all in the same state as when I closed. I then did the auto check on my favorites again for the same chapters that were already done and after they were added I closed and re-opened FMD to see that none of the re-added chapters saved.

**Comment by riderkick** [comment]
Please try this, remove .txt part. Compiled for win32, so you have to use the right dlls.
[bin.7z.txt](https://github.com/riderkick/FMD/files/818689/bin.7z.txt)

**Comment by kevin01523** [comment]
ok for now manually added links tasks gets saved even when using old  downloads.db and etc i'm originally using 64 bit version. downloaded the  32 bit binaries and dll to use the 32 bit version ill test it a bit if it still fails to save some tasks etc

**Comment by NhKPaNdA** [comment]
I've tried it out and I think it's working now. I added new mangas and let my favorites do their update check and everything is still there after closing and re-opening FMD.
