### ISSUE TITLE
Any way to speed up List Updates for ExHentai?

### ISSUE THREAD

**Issue by GlassedSilver** [riderkick/FMD#506]
Hey, so far I've added most of the places I want to be able to download from and once everything is set and running I'll put this neat little tool to the test and hopefully scrape the mangas half-automated without having to check each site individually from the browser.

One thing though:

I cannot pull a pre-made list from the server ("Download manga list from server") for ExHentai and fetching it all by myself ("Update manga list") takes REALLY long for ExHentai.
It's slower for any site to start from zero as I have noticed, however, I'm talking one scraped item per second slow here...

Currently it's sitting at 136/12518 (this isn't my first attempt, so it's still in the hundreds now), but there must be a way to get started faster, no?

Maybe someone of the other users can send me their list to start me off? (I do not have "Don't load manga information when updating lists" ticked, mind you. I will need and appreciate the filters!)

I have added my account to the list and its status is showing as "OK".
I also added the igneous cookie from my Chrome browser as well, didn't help.
Even tried setting the user agent for ExHentai in FMD as Chrome - no good!

Any help would be appreciated!

**Comment by riderkick** [comment]
Can't you just search the contents you wanted on the web, and just drag n drop the link(usually the thumbnails also contains the link) to fmd's downloads list. H sites like this usually updated every day, so there's a lot of changes every day, It will be tiresome to keep up with that. They usually also has better/faster search/filter features.

**Comment by GlassedSilver** [comment]
Oh, I'm perfectly fine to let it sit there for the initial list and take a while, it's just that I wondered why there isn't a readymade list like for all other sites as the updates after that seem to be a lot speedier.

As for faster and better filters on the sites themselves:

probably, but right now I prefer the convenience for discovery, if I'm looking for something specific and wouldn't find it I'd still go out and do more thorough searching by hand. :)

**Comment by riderkick** [comment]
ExHentai has so many items, It will take too long. Besides, there is a ban. You can't get complete list with one attempt.
I just check their website. Their filter features is quite good and fast.
