### ISSUE TITLE
[Requests] 3 Requests to Ask

### ISSUE THREAD

**Issue by Tmp341** [riderkick/FMD#510]
1. Can you add [Mangazuki](https://mangazuki.co)? It seems they are YoManga's successors. (According to comments on website.)

2. I have 107 favorites and i think i'll add others in the future. I like "check favorites on startup" because it makes this a lot easier. Anyway, is there a way to add "disable" to autocheck some of them? I want to keep my all favorites, but i also don't want Fmd checks all of them. I hope i expressed my opinion clearly.

3. I was looking at [Manga-Tr](http://manga-tr.com/) and it seems your list is a bit out of date. Tried using "update this list" but nothing happened.

Thank you in advance.

**Comment by kavin-90** [comment]
Mangazuki will be support soon. i gonna work on it and yomanga was my domain .

Mangazuki changed now before few days ago it looks different.

**Comment by Tmp341** [comment]
Thank you for this, but i have a disabled disable option:
![ss](https://cloud.githubusercontent.com/assets/1683388/23625484/603e1cae-02ba-11e7-9828-0bcf5a990247.jpg)

**Comment by riderkick** [comment]
Restart your fmd, due to the new column in the database, the database needs to be rebuild.
It should be works automatically before restoring the data. Maybe something goes wrong. I will check the codes.
