### ISSUE TITLE
Cannot favorite title with quotes in name

### ISSUE THREAD

**Issue by DaJay42** [riderkick/FMD#511]
Attempting to favorite a manga with quotes in the title results in a database error on close.

Example manga with issue: [Isekai de "Kuro no Iyashi Te" tte Yobarete Imasu](http://kissmanga.com/Manga/Isekai-de-Kuro-no-Iyashi-Te-tte-Yobarete-Imasu)

Resulting error in the log:
EXCEPTION: TFavoritesDB.Add failed!
               ESQLDatabaseError - TSQLite3ConnectionH : near "Kuro": syntax error
                 $000000010036A21F
                 $0000000100368191
                 $000000010036872A
                 $0000000100368BA7
                 $000000010036CD4A
                 $000000010036CB94
                 $000000010047D794  Add,  line 66 of ../baseunits/FavoritesDB.pas
                 $00000001003FE448  Backup,  line 985 of ../baseunits/uFavoritesManager.pas
                 $0000000100045D8A  CloseNow,  line 1349 of forms/frmMain.pas
                 $0000000100045060  FormClose,  line 1269 of forms/frmMain.pas
                 $00000001000218DA
                 $00000001000246A0
                 $00000001000248D4
                 $00000001000102C6
                 $0000000100152ED9
                 $0000000100148FCF
                 $0000000100022A53

**Comment by kavin-90** [comment]
@riderkick  Need to escape double quote for it i think string replace will work then on favorite list strip slashes will be needed because title will return Ore ga Ojou-sama \"Shomen Sample\" like string.
