### ISSUE TITLE
Can't Update

### ISSUE THREAD

**Issue by furafurari** [riderkick/FMD#512]
Hi, I have an issue when I'm updating FMD to the latest version. Whenever I used the new updater, it gives an error message like this:

https://s8.postimg.org/gddbkh2wl/errorr.png

And I clicked ok every time, but nothing happens. What to do?

**Comment by riderkick** [comment]
Update manually by download the latest version in Releases section.
Just extract to current working installation, and overwrite all files.
Read #495
