### ISSUE TITLE
Manga List

### ISSUE THREAD

**Issue by ratbunuts** [riderkick/FMD#514]
Hello, Where do we get source for the new manga website that's been newly added like https://mangazuki.co/? Its not included on the newest update

**Comment by kavin-90** [comment]
It was incomplete so that is why its not added in new updates.

Manga list,Chapter download complected but not chapter list because it use pagination for it.

**Comment by ratbunuts** [comment]
Thanks for the reply kavin-90. Ill wait patiently then.
