### ISSUE TITLE
Fmd Update  File not found

### ISSUE THREAD

**Issue by Beylers** [riderkick/FMD#516]
The new update is not linked correctly, it's at https://github.com/riderkick/FMD/releases/download/0.99.0/fmd_0.9.99.0_Win64.7z

instead of the bump https://github.com/riderkick/FMD/releases/download/0.9.99.0/fmd_0.9.99.0_Win64.7z

**Comment by riderkick** [comment]
Wrong release tag. 🤕
Fixed.
