### ISSUE TITLE
Websites failing to download list from server

### ISSUE THREAD

**Issue by molitar** [riderkick/FMD#518]
Ok first I tried to just download from site itself after deleting list to get nice clean lists. The only one that worked out of all I tried was Batoto and about 3 or 4 others.  So I than used option to download from server and I kept getting errors from these sites.

Ex-Hentai
FunManga
GoodManga
HentaiChanRU
HentaiRead
Jaiminisbox
KivManga
MangaBackup

At this point I just gave up on having a clean Database that works and just deleted the new data folder and put back the old one.  The server list are broken and useless and it will not download direct from the sites the list first.

**Comment by riderkick** [comment]
There is no prebuild data for that websites.
Just drag the urls to download list.
https://sourceforge.net/projects/newfmd/files/data/
