### ISSUE TITLE
[Batoto] FMD not downloading 

### ISSUE THREAD

**Issue by ratbunuts** [riderkick/FMD#519]
Is it just me that after fmd done preparing, it wont start downloading.

**Comment by matoro** [comment]
Sorry, going to need a lot more information than that.  Site, series, chapter, log file, etc...

**Comment by ratbunuts** [comment]
site: batoto, manga: Darwins Game: Chapter 37; Hanstu x Trash, chap 106

**Comment by ratbunuts** [comment]
It seems like only the Batoto site is not downloading

**Comment by Purplem** [comment]
Nothing from Batoto is downloading for me either.

**Comment by Ianunaut** [comment]
I'm still running 0.9.91 and Batoto just downloaded for me. Must be something about the 0.9.100 update.

**Comment by Purplem** [comment]
Could this be the reason why it's not working? Can't view anything with this setting but if I change it, I can view it fine. http://puu.sh/uABLy/80ae2a4883.png

**Comment by cetwiw** [comment]
@Purplem I've got no problem downloading from batoto today,
but maybe this app choose that server instead of another one.

**Comment by riderkick** [comment]
It is working fine here. And I'm quite surprised, batoto is much faster now.
I'm gonna remove the batot limit then.

**Comment by riderkick** [comment]
@Purplem that seems the case. The default one(auto) is `img.bato.to`.

**Comment by riderkick** [comment]
I will add the option to select the server.

**Comment by riderkick** [comment]
https://github.com/riderkick/FMD/commit/f2bea66050e6397511ae9528f77ae1cb52a7d761
Host is hard-coded, so if they change the domain, we need to change the code.
