### ISSUE TITLE
Request, Can you add this manga site

### ISSUE THREAD

**Issue by radiaku** [riderkick/FMD#52]
hello riderkick

can you add mangacap.com, raw of the content on this sites just plainly amazing... 

Example:
http://www.mangacap.com/Fury/ (66 chapter), in other sites ( only 15 chapter )
http://www.mangacap.com/Combat_Continent/, ( 144 chapter ), in other sites ( only 82)

And I thought manga, readmanga.today is taking from here for the raws

but its has limitation,  using dns cloudflare... If I accessing too much, its will pop out captcha. and sometimes if I revisiting after long break, its showing captcha.( using browser FIREFOX without clearing cookies )

If its okay and no bothering you. Can you add mangacap.com please... :)

**Comment by riderkick** [comment]
If I'm not wrong I've seen very similar layout with manga,cap that already supported in fmd. Maybe we can use the same script. It's much better than writing redundant script.

**Comment by rajlaksh** [comment]
they're WP-Manga based it works for all WP-Manga sites.

**Comment by radiaku** [comment]
Okay... yes the layout is familiar. But how about limitation dns cloudflare @riderkick ?

**Comment by riderkick** [comment]
If they use cookies, then we simply request without cookies. It's will be not wise if they limit by the ip.

**Comment by radiaku** [comment]
Okay thanks you. Can I ask something oot. how to learning freepascal without documentation & sample ( free pascal has poor documentation and less example ). I having nightmare starting it, until now. What do you suggest for me? where do I starting it?

**Comment by riderkick** [comment]
You can read delphi tutorial.
If you have fundamental background of programming, it should not so hard to learn new languages.

**Comment by radiaku** [comment]
okay thanks for clue.

**Comment by riderkick** [comment]
If I notice that earlier, I would not wasting so much time to write the same script over and over again. 😢
Do their page viewer also the same?

**Comment by radiaku** [comment]
I dont know if they same. but image html like this one.. 
<img class="manga-page" style="max-width:940px" src="http://www.mangacap.com/wp-content/manga/4334/69/01.jpg" alt="Fury - Chapter 17 - 1"/>

manga2u gone, mangacow.co changing their code ( as i remember ), goes same for senmanga :)
