### ISSUE TITLE
[suggestion] Keep 'Favorites list' colors after scan

### ISSUE THREAD

**Issue by CodeKatta** [riderkick/FMD#520]
During the scan for new chapters the entries in the favorites list are assigned a color according to their status. However, after the scan finishes the colors are removed.

So would it be possible to add an option to leave the color coding on even after the scan finished?

ありがとうございます

**Comment by riderkick** [comment]
Those color reflect the actual status of favorites and its thread, just like color in download list.
It's possible to keep the status but we have to remove the feautures to be able to check indivual favorite. And I against it.
Declined.
