### ISSUE TITLE
Error during Program Execution

### ISSUE THREAD

**Issue by furafurari** [riderkick/FMD#521]
Hi! So I had downloaded the new FMD and replaced all in my FMD folder (in hopes that my setting will not be resetted), but after I clicked the .exe and even run it as administrator, all I got is this error:

https://s3.postimg.org/5yk0kxqur/eeerror.png

The details:

Unhandled exception!
Application       : Free Manga Downloader
Version           : 0.9.99.0
Product Version   : Win32 Debug
Host Machine      : Windows 8.1 64-bit
Target CPU_OS     : i386_Win32
FPC Version       : 3.1.1
LCL Version       : 1.7
Path              : E:\Programs\Free Manga Downloader\fmd.exe
Process ID        : 2372
MainThread ID     : 2600
Thread ID         : 2600
Time              : 09/03/2017 07:36:59.728
Exception Class   : EDatabaseError
Message           : SQL statement not set
  $006E8D16
  $006E2BFE
  $006E2D5C
  $006E77DE
  $006EA9CB
  $006E76FB
  $006D83D6  ConvertToDB,  line 1691 of ../baseunits/uDownloadsManager.pas
  $006D852C  Restore,  line 1703 of ../baseunits/uDownloadsManager.pas
  $00460F9E  FormCreate,  line 1119 of forms/frmMain.pas
  $0041D88D
  $0041C287
  $0042174E
  $00427142
  $0040355A  $main,  line 85 of md.lpr

Any help would be appreciated, thanks!

**Comment by riderkick** [comment]
Duplicate #517
