### ISSUE TITLE
Mangasee domain and title format hasn't fixed yet

### ISSUE THREAD

**Issue by cetwiw** [riderkick/FMD#522]
Hi, thank you for this awesome free app for downloading Manga.
I made an account for this little issue, maybe you didn't notice it for a few latest releases.
I usually downloading manga from Mangasee. And now they have changed their domain to http://mangaseeonline.us/
and please update the format title links like the following screenshot:
![screenshot 21](https://cloud.githubusercontent.com/assets/26290014/23734986/63041e6e-04b5-11e7-8721-09bcbdfe2846.jpg)

thanks in advance

**Comment by riderkick** [comment]
It's working fine event after the domain changed, at least until the old domain expired.
You have old an manga list, try to rebuild the manga list from scratch.
The one in sf is really old, I will rebuild the fresh one if I have time.

**Comment by cetwiw** [comment]
Ah I see that's why I always got that error, right after I remove the mangasee data file and try update manga list for mangasee from scratch (it took me for about 3hrs that's why I never did it before :) ), now it works again flawlessly lol thank you gan
