### ISSUE TITLE
Readmangatoday and Batoto not downloading

### ISSUE THREAD

**Issue by ratbunuts** [riderkick/FMD#527]
Readmanga and Batoto not downloading. Batoto will prepare but will download like 1 to 2 pages then its gonna fail to download. Readmanga doesnt prepare or download at all. oh and FMD will have the terminate  dialogue box for error message.

**Comment by ratbunuts** [comment]
For Readmanga site. Im downloading prison school chap 244 and its not downloading

**Comment by liohunter** [comment]
I'm having the same issue with Batoto, it might have something to with their server. Would it be possible to add an option to choose which image server you want to use like on the website?

**Comment by riderkick** [comment]
Batoto server option have been added, just wait for updates. #519

**Comment by ratbunuts** [comment]
Thanks riderkick for the update. Batoto is working fine now. ReadmangaToday is all left that's not downloading.
