### ISSUE TITLE
Please let us change how filenames work.

### ISSUE THREAD

**Issue by formigao** [riderkick/FMD#528]
% FILENAME% must be customizable.
Sometimes I do not want my image files to start 001.

Here's an example: some sites like to put a few extra pages before manga chapters and when i download it i have  page 001 that is Advertising.

u usually delete it but now the manga looks like its missing a page.

would be REALLY AMAZING if we could make the filenames start with 000 or maybe even -002 -001.

so we could adjust for every website.

thanks !

**Comment by formigao** [comment]
Even better can you make the FMD ignore some pages when downloading ?

this way we can avoid those pages and dont need to delete than manually.

**Comment by riderkick** [comment]
You should tell us what website it is. Series and chapter so we can investigate.  Maybe we can rule out that page.

**Comment by formigao** [comment]
Thanks for the reply riderkick.

here's the website in question: http://unionmangas.net/

this is a chapter that have those pages.

http://unionmangas.net/leitor/One_Piece/858

thanks again for the attention.
