### ISSUE TITLE
[mangago] The program does not download anything

### ISSUE THREAD

**Issue by reiko23426** [riderkick/FMD#529]
As I said, the program does not update does not download any of the manga from mangago to mangafox even mangapark  pls hlp T=T

**Comment by kavin-90** [comment]
download latest copy from [release section](https://github.com/riderkick/FMD/releases) and try.again

**Comment by reiko23426** [comment]
Version I have is the last thing

**Comment by kavin-90** [comment]
MangaFox/Manga Park is working for me are you sure you're getting nothing from them?

**Comment by reiko23426** [comment]
-____-        I've turned off the protection and seemed to start download but mangago Still  not working

**Comment by kavin-90** [comment]
MangaGo Has download error i got same error. it seems they changed reader so need to verify and fix it.

**Comment by riderkick** [comment]
@kavin-90 that's not json. Just scan line by line.

**Comment by kavin-90** [comment]
@riderkick it change for each chapter on mangago and it as 2 images src 1st is google and 2nd is backup if google failed.

**Comment by riderkick** [comment]
I got something like this,
1set:
'iweb6.mangapicgallery.com'
2set:
`img_6.rocaca.net`
And both redirected to `iweb6.mangapicgallery.com`.
So both actually point to the same source.
I pick the second set because its using the same domain.

**Comment by leoteesh** [comment]
mangafox is not working for me :(

**Comment by riderkick** [comment]
Please test and close if ok.

**Comment by reiko23426** [comment]
How long should you wait the new update ^^ 
 and I tried (mangago, fixed image src.) but it dont work --_--

**Comment by joewono2011** [comment]
doesnt work in mangago >.<

**Comment by reiko23426** [comment]
pls fix mangago T_T
