### ISSUE TITLE
0.9.16.6 (64bit) Batoto Manga Cover Doesn't Show Anymore.

### ISSUE THREAD

**Issue by ChronoSX007** [riderkick/FMD#53]
Screenshot: http://puu.sh/ioaig/5d5f8c3ced.png

**Comment by MammothJerk** [comment]
I've noticed this problem aswell

**Comment by riderkick** [comment]
Working fine here. Batoto notoriously known with their server issue.
http://i.minus.com/iwPLHe3ck4ESJ.jpg
