### ISSUE TITLE
Kissmanga not working

### ISSUE THREAD

**Issue by Souravi785** [riderkick/FMD#531]
Kissmanga stopped working suddenly. No matter how many times I try to download from kissmanga and every manga I tried says, failed, try resuming this task! And the same happens even if I try resuming it over and over again. Can you solve this issue please?

**Comment by riderkick** [comment]
Its working fine here.
Read #497, #509

**Comment by Souravi785** [comment]
kissmanga is available in my country and i could reach the site with my ip. And i always download from kissmanga on fmd. The problem started recently.

Edit:Somehow the problem fixed by itself.
