### ISSUE TITLE
Mangafox - failure to download

### ISSUE THREAD

**Issue by leoteesh** [riderkick/FMD#532]
Hi,
Mangafox does not seem to work. i get a failure each time and every time i try to resume this download, the same thing happens.
Appreciate you looking into this.
Many thanks

**Comment by StormJumper** [comment]
Could be they changed their scripts again-guess they might have to update the script again.

**Comment by riderkick** [comment]
Its working fine here.
Tell us which series and chapter.

**Comment by leoteesh** [comment]
For example http://mangafox.me/manga/1_3_romantica/ chapter 1 is coming up as failure
http://mangafox.me/manga/1_1/ is also coming up as failure

Thank you

**Comment by riderkick** [comment]
It's working fine.
Some series/chapter is marked as licensed on certain region/country. Maybe your country is one of those.
That's mean those series is already available as hard copy in your region.
![sshot-2017-03-16- 20-22-22](https://cloud.githubusercontent.com/assets/4972676/23995841/40f08412-0a86-11e7-8e92-d0309e47ec63.jpg)
