### ISSUE TITLE
Raws Websites are not working

### ISSUE THREAD

**Issue by hlaxkar** [riderkick/FMD#534]
None of the raw websites are working i am unable to download list form servers.

**Comment by kavin-90** [comment]
if that failed you should have used update this manga list which will fetch websites manga list

**Comment by hlaxkar** [comment]
thanx it did the trick but is is slow and takes much time.what about fixing the error ? 
Error image
![untitled](https://cloud.githubusercontent.com/assets/26454395/24034439/5c611446-0b17-11e7-9d91-45e9f9885633.png)

**Comment by kavin-90** [comment]
same method will work. it seems that site does not have data files on server so manual update that site manga list via update this manga list
