### ISSUE TITLE
Mangafox not all pages downloaded

### ISSUE THREAD

**Issue by Lost1221** [riderkick/FMD#540]
The only request i have is if you can add option when downloading to see how many pages have each chapter and when you download whole manga to show you how many pages you should have.
I Downloaded 52 mangas and almost half is not downloaded completely.
Thank you
Beside this this is the best program i ever had :)

**Comment by danielbintar** [comment]
and there is also manga at mangafox that cant be downloaded at all.
https://s.kaskus.id/images/2017/03/11/2791051_20170311062024.png

**Comment by Lost1221** [comment]
It could be fantastic if you can in favorites next to "Save To'' put  "All Pages" and "Completed Manga" (that the manga is finished by author)

**Comment by StormJumper** [comment]
@danielbintar your page contains errors so if you want them to see the problem you need to fix your uploading problem first.

**Comment by Lost1221** [comment]
If i download to many at once for example 4 its not downloading all pages I had to download one by one.
