### ISSUE TITLE
Batoto spanish

### ISSUE THREAD

**Issue by Youshuu** [riderkick/FMD#541]
Can you add an option to download manga from Batoto in spanish and not only english?
Thanks and great job!

**Comment by Tmp341** [comment]
Yeah. This would be a good option. You should be able download multilanguage, if supported by site.

**Comment by rs3mk** [comment]
![sin titulo 186](https://cloud.githubusercontent.com/assets/19628943/24247957/7910aa1a-0f9b-11e7-8e95-0e4f37ce2347.png)

**Comment by riderkick** [comment]
Options>Website>Options>Batoto>Show all language
