### ISSUE TITLE
Requests of new features

### ISSUE THREAD

**Issue by molitar** [riderkick/FMD#542]
1. I would like to be able to just go to next manga after viewing each one in a summary type.  I like to filter all new manga with some keywords but than I have to manually click on each one to view it.  Can we get a next button and be able to just view the summary like DomDomSoft Manga Downloader did?  Maybe add a next button just under the manga summary to go to the next one in the text list.

2. I would also like to be able to save custom filter settings.

3. feature I would like to see is to be able to right click a failed download and have it find a manga on another site so I can download and favorite site when one goes down.  Like all the Kiss Manga that do not work right now I have to manually find a new site for each and every one.

4. Have save filters that can work by web site groups.  I like to be able to search for new manga that focus on Fantasy or Ecchi but way current filter works it also locates manga's on hentai sites.  I can not filter out the hentai sites unless I uncheck them and restart. 

5. There is some sites that are having download problems where the last page fails to download so it thinks it is not complete. I will manually stop the download where it's stuck and zip up the chapter than go download starting after that chapter.  I would like to be able to mark the chapters as already downloaded manually.

Currently I think I am going to have to have two installed copies of FMD so I can have one just on hentai/doujin sites and one that is not so I can find the new translated manga's that will be good to read.

**Comment by molitar** [comment]
bump

**Comment by Tmp341** [comment]
Riderkick probably abandoned project and kmvi is busy sometimes irl it seems.
