### ISSUE TITLE
How do I use the website cookie feature?

### ISSUE THREAD

**Issue by molitar** [riderkick/FMD#546]
How can I use the website cookie feature?  I can add a website but I see just an empty value field that needs to be filled in.  Where or how do you get that value?

**Comment by riderkick** [comment]
How you decide to use custom cookies then? Where you get the cookies?

**Comment by molitar** [comment]
I use Firefox as my browser.  I can view cookies with cookie viewer but not sure how to use it with FMD as I am not sure which part of the cookie to use there is like 8 different sections for the entire cookie as seperate files.

**Comment by riderkick** [comment]
Depend on what you want to use, cookies just some info for server to identify the client with some session data to calculate things. For login usually it's `session_id` or something like that.

**Comment by molitar** [comment]
Ok thanks..

**Comment by riderkick** [comment]
You can add all them if not sure, separated by `;`
