### ISSUE TITLE
Improve check for new chapters

### ISSUE THREAD

**Issue by anshbansal** [riderkick/FMD#55]
Hi

Would you consider improving the check for new chapters part? 
Like making it possible to check for new chapter for one Favorited item? And perhaps a progress bar for individual chapters. On slow internet it seems that it is completely stuck. No idea about what is happening.

**Comment by riderkick** [comment]
What do you mean by progress bar? When its stuck, it just waiting the reply from server, that's it, nothing more.

**Comment by anshbansal** [comment]
Then maybe add a timeout. A progress bar can show how much time has passed till the timeout. 
Or if downloads are happening then add the KBs that will be downloaded, if possible. That can also give a progress bar.

Maybe two progress bars? One for timeout and other for the size of file.

Checking for new chapter for one Favorited should be clear. Right?

**Comment by riderkick** [comment]
There is no file to be downloaded, it just a webpage. And sometimes it's multiple pages need to be loaded.
Synchronizing every connection to main thread will just disrupt the main thread process and possibly the other thread that also wanted to synchronize to main thread. It will be easy if its single threaded.
I will not add such feature, it's not worth the hassle. I still accept the patch though. Feel free to send a patch or pull request, with audit of course. Just be careful with other threads that tied with favoritemanager like downloadmanager, also be wise when synchronizing to main thread, check other threads that might be also need main thread (dialog, update, etc).

I will just add global connection timeout to connection settings.

**Comment by anshbansal** [comment]
Then how about showing the logs. Like many software have a "Show details" button. On clicking on them the logging is shown. That at least shows that something is happening.

**Comment by riderkick** [comment]
When stuck there is nothing happened, it's just simply waiting.

**Comment by anshbansal** [comment]
Ok

**Comment by riderkick** [comment]
check/stop favorite per item added in latest commit. 
Refer to https://github.com/riderkick/FMD/commit/58eb27ac7309e299562f17bef076295d42509276 https://github.com/riderkick/FMD/commit/3598bd147d4feb3ec9cf645b8f6f0cb13b999cd0
