### ISSUE TITLE
"No Image" is downloaded from hentai2read

### ISSUE THREAD

**Issue by hlaxkar** [riderkick/FMD#551]
Some series are working but many of the manga in "Hentai2Read" are downloading these images.and the number of these are same as pages in chapter
![001](https://cloud.githubusercontent.com/assets/26454395/24292801/d82f6fbc-10b4-11e7-9a36-181a03c47518.png)

**Comment by hlaxkar** [comment]
Whatever......

**Comment by Hexaf** [comment]
well you need to recheck on the website as well. Sometime on the website has no image
