### ISSUE TITLE
Kissmanga still not working

### ISSUE THREAD

**Issue by RainerZA** [riderkick/FMD#557]
I am on version 0.9.108.0 and am trying to download kissxsis 107 and still get the failed message. I have deleted the previous task and tried to start a new one. It still does not work.
This is the output for the log file.

=== Log Session Started at 2017/03/27 08:34:50 by Free Manga Downloader ===
08:34:50:346 INFO: "Free Manga Downloader" started with [PID:5392] [HANDLE:4294967295]
08:34:50:348 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 0.9.108.0
               Product Version   : Win32 Debug
               Host Machine      : Windows 10 64-bit
               Target CPU_OS     : i386_Win32
               FPC Version       : 3.1.1
               LCL Version       : 1.7
               Path              : B:\Download\fmd_0.9.85.0\fmd.exe
               Process ID        : 5392
               MainThread ID     : 9252
08:35:09:686 WARNING: TTaskThread, checkforfinish failed=1/1 "KissXSis" > "KissXSis - KissXSis Kiss 107"

**Comment by Tmp341** [comment]
Yeah. It seems every manga has different key and iv. For KissXSis, (key) "72nnasdasd9asdn123nasdbasd612basd"
(iv) "a5e8e2e9c2721be0a84ad660c472c1f3"

**Comment by kavin-90** [comment]
that is why we added custom key settings so user will add them and download chapters without any problem

Website -> options there add your key and download chapter.

**Comment by RainerZA** [comment]
Thanks that got it working. Do we have to do this manually for each manga?

**Comment by riderkick** [comment]
The latest version had key and iv detection. If it's fail then you probably got different kind of code. Save the complete webpage of the l reader website and post here.

**Comment by danielbintar** [comment]
A few hours ago it works fine.
But now I can't even see the the manga detail, chapter, etc. The web works

**Comment by kevin01523** [comment]
working earlier but not working now

**Comment by Tmp341** [comment]
Is there a possibility of "kissmanga staff was here" situation?

**Comment by Tmp341** [comment]
> 23:53:42:286 TTaskThread, checkforfinish failed=1/1 "Unbalance x Unbalance" > "Unbalance x Unbalance 065-072 Read Online"


[Kissmanga.zip.txt](https://github.com/riderkick/FMD/files/880372/Kissmanga.zip.txt)

A web page with it's files. Key chamges sometimes, it seems.
