### ISSUE TITLE
[REQUEST] Temp files stored somewhere else

### ISSUE THREAD

**Issue by marstaik** [riderkick/FMD#558]
Hey, I use the .cbz format for downloading from every site I use.

I would like to request a feature to be able to specify a different temp directory for in-progress downloads if possible, as this would really be nice for google drive, onedrive, and dropbox users so that it does not constantly upload all the images, then delete them over and over again. This sometimes causes slow syncing and other annoyances to occur.

**Comment by StormJumper** [comment]
I don't think google drive or onedrive or dropbox would like copyright materials on their site or get into take down notice from manga companies. So be careful what you wish for.

**Comment by marstaik** [comment]
I use it for personal reasons syncing between two of my pc's, nothing to do
with putting them online for people to download.

**Comment by riderkick** [comment]
You should not store the fast working dir in the first place.
We don't store/keep track every files we working on. That will require a lot of changes.
Declined.
