### ISSUE TITLE
Exception during deleting download from queue

### ISSUE THREAD

**Issue by anshbansal** [riderkick/FMD#56]
![untitled](https://cloud.githubusercontent.com/assets/4127841/8155375/4b927466-1361-11e5-8dea-00166f4153f4.png)

I imported information from an older version of FMD. It added all manga in downloads completely. I delted one of them and got the above error.  Happened only once. I am using it on Windows 7 64-bit machine.

**Comment by anshbansal** [comment]
It happened again. I had imported the config from 0.3.3b version of FMD.

**Comment by riderkick** [comment]
https://github.com/riderkick/FMD/commit/2d34c3afef991a0ab84acde8a1ef8ee37e3bf1cb

**Comment by anshbansal** [comment]
This is not happening anymore.
