### ISSUE TITLE
Wondering when YoManga Download issue will be fixed

### ISSUE THREAD

**Issue by Wolfpup67** [riderkick/FMD#563]
YoManga is still failing the DL chapters for any of the manga listen there.

Here is the section of the log file:
=== Log Session Started at 3/30/2017 8:20:18 by Free Manga Downloader ===
08:20:18:166 INFO: "Free Manga Downloader" started with [PID:13676] [HANDLE:18446744073709551615]
08:20:18:167 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 0.9.109.0
               Product Version   : Win64 Debug
               Host Machine      : Windows 10 64-bit
               Target CPU_OS     : x86_64_Win64
               FPC Version       : 3.1.1
               LCL Version       : 1.7
               Path              : D:\fmd\fmd.exe
               Process ID        : 13676
               MainThread ID     : 7668
08:30:23:208 WARNING: TTaskThread, checkforfinish failed=13/13 "Erotic Sensuality & Perception" > "[YoManga]_0001_Chapter 0001"
08:30:49:629 WARNING: TTaskThread, checkforfinish failed=20/20 "Erotic Sensuality & Perception" > "[YoManga]_0002_Chapter 0002"
08:31:07:246 WARNING: TTaskThread, checkforfinish failed=15/15 "Erotic Sensuality & Perception" > "[YoManga]_0003_Chapter 0003"
08:31:23:264 WARNING: TTaskThread, checkforfinish failed=14/14 "Erotic Sensuality & Perception" > "[YoManga]_0004_Chapter 0004"
08:31:38:079 WARNING: TTaskThread, checkforfinish failed=13/13 "Erotic Sensuality & Perception" > "[YoManga]_0005_Chapter 0005"
08:31:55:299 WARNING: TTaskThread, checkforfinish failed=13/13 "Erotic Sensuality & Perception" > "[YoManga]_0006_Chapter 0006"
08:32:12:117 WARNING: TTaskThread, checkforfinish failed=15/15 "Erotic Sensuality & Perception" > "[YoManga]_0007_Chapter 0007"
08:32:28:534 WARNING: TTaskThread, checkforfinish failed=13/13 "Erotic Sensuality & Perception" > "[YoManga]_0008_Chapter 0008"
08:32:45:755 WARNING: TTaskThread, checkforfinish failed=12/12 "Erotic Sensuality & Perception" > "[YoManga]_0009_Chapter 0009"
08:33:11:402 WARNING: TTaskThread, checkforfinish failed=19/19 "Erotic Sensuality & Perception" > "[YoManga]_0010_Chapter 0010"
08:33:23:869 WARNING: TTaskThread, checkforfinish failed=13/13 "Naughty Girl" > "[YoManga]_0001_Chapter 0001"
08:33:30:275 WARNING: TTaskThread, checkforfinish failed=5/5 "Naughty Girl" > "[YoManga]_0002_Chapter 0002"
08:33:39:486 WARNING: TTaskThread, checkforfinish failed=7/7 "Naughty Girl" > "[YoManga]_0003_Chapter 0003"
08:33:47:496 WARNING: TTaskThread, checkforfinish failed=6/6 "Naughty Girl" > "[YoManga]_0004_Chapter 0004"
08:33:55:506 WARNING: TTaskThread, checkforfinish failed=6/6 "Naughty Girl" > "[YoManga]_0005_Chapter 0005"
08:34:04:317 WARNING: TTaskThread, checkforfinish failed=7/7 "Naughty Girl" > "[YoManga]_0006_Chapter 0006"
08:34:13:128 WARNING: TTaskThread, checkforfinish failed=6/6 "Naughty Girl" > "[YoManga]_0007_Chapter 0007"
08:34:21:539 WARNING: TTaskThread, checkforfinish failed=7/7 "Naughty Girl" > "[YoManga]_0008_Chapter 0008"
08:34:28:744 WARNING: TTaskThread, checkforfinish failed=5/5 "Naughty Girl" > "[YoManga]_0009_Chapter 0009"
08:34:35:952 WARNING: TTaskThread, checkforfinish failed=6/6 "Naughty Girl" > "[YoManga]_0010_Chapter 0010"

This has been going on for quite a few months.

**Comment by comicult** [comment]
i think this is more because yomanga is dead
some of their crew moving to mangazuki. check them out

**Comment by Tmp341** [comment]
I think YoManga split apart.

**Comment by kavin-90** [comment]
What i see is chapter is download complete but it return failed try resume this task

**Comment by riderkick** [comment]
Yomanga is dead. Do I have to remove it?
