### ISSUE TITLE
he***2read slowness issue

### ISSUE THREAD

**Issue by Max1475369** [riderkick/FMD#564]
I just notified that this page has dropped the speed from few MB/s down to 10 > 105 kb/s at most. At the end, even if the download job finished the files seem to be corrupted. Well, just FYI :)

**Comment by Hexaf** [comment]
Well it's works fine to me. What do you mean corrupted? It's no image? If yes, it is because the server problem. And you need to report to them.

**Comment by Max1475369** [comment]
Yea, the speed dropped after the job started. Images downloaded after all. However, file corrupted. Just wonder if they do anything to block download software like this one.

**Comment by Max1475369** [comment]
Yea, it seems the servers having an issue as when I'm using software. No issue then.
