### ISSUE TITLE
[Issue] Mangatraders Empty Chapter

### ISSUE THREAD

**Issue by TehBotolSosro** [riderkick/FMD#566]
seem mangatraders changed their chapter list, using FMD 0.9.109.0 result in empty chapter for all the manga, without chapter number there is no possible way to download it,

terima kasih thank you

**Comment by TehBotolSosro** [comment]
batoto is also empty chapter, mangastream is working though

**Comment by StormJumper** [comment]
Sounds like they changed their scripts again to prevent downloads. @TehBotolSosro you want to report this if this continues still to the developers to look into it.

**Comment by kavin-90** [comment]
are you sure MangaTraders you got empty chapters did you check it on website too?

MangaTrader need login for some series so they got empty chapters

**Comment by TehBotolSosro** [comment]
turn out it need the login or they will return empty, thanks for the reminder kavin-90
