### ISSUE TITLE
[Issue] Kissmanga failed download

### ISSUE THREAD

**Issue by Aoiripper** [riderkick/FMD#568]
failed to download every manga in kissmanga
I used Version 0.9.109.0

**Comment by Fliiv** [comment]
Think it's hitting KissManga's DDOS protection.  When I pull something up the "Manga Info" tab, the title shows up as the same "Please wait 5 seconds..." message I sometimes get from the website.  Not sure what triggers this.  Might just when they're busy, might be after a certain amount of activity from your IP address.

**Comment by Tmp341** [comment]
I've changed Kissmanga "key" from options, now it downloads. Fmd doesn't get it automatically i think.

**Comment by Fliiv** [comment]
Every FMD update since March 23rd has been addressing KissManga issues.  To help track down the issue, what key did you plug in that worked?

**Comment by Tmp341** [comment]
I was using a key starting with "7" then it stopped working. Now using this: 
> mshsdf832nsdbash20asdm
and it isn't working either, says "0" chapters and has "#ffddcc" color on them.

Edit: Opened kissmanga, pasted get the same key above, pasted it. Now it sees my favorites. I dunno what happened.

**Comment by Fliiv** [comment]
That's the same key I have, and mine's working again at the moment.  I think that rules out a configuration issue and is more evidence of trouble with KissManga's DDOS protection.  Thanks for the information.

**Comment by Aoiripper** [comment]
I have change the key to "72nnasdasd9asdn123nasdbasd612basd", and it's working now.

**Comment by Fliiv** [comment]
Currently not working.  Tried with both keys, same response: I either get just the title or "Please wait 5 seconds..." in the "Manga Info" tab.  Next time it starts working again I'll try the other key.

**Comment by Fliiv** [comment]
Confirmed: When it's working for me, it works with either key.

**Comment by Leguron** [comment]
Thanks for the help Aoiripper. The key worked. Strangely
 "For key type 'chko'.
For iv type 'CryptoJS.enc.Hex.stringify(iv)'
Copy the result without quote."

Doesn't give me anything anymore on kissmanga.

**Comment by Tmp341** [comment]
>  Leguron commented 2 days ago
> 
> Thanks for the help Aoiripper. The key worked. Strangely
> "For key type 'chko'.
> For iv type 'CryptoJS.enc.Hex.stringify(iv)'
> Copy the result without quote."
> 
> Doesn't give me anything anymore on kissmanga.

I got a minute ago, the following key: "nsfd732nsdnds823nsdf"

**Comment by spamtaztik** [comment]
Um, hello there. Yesterday night I was able to open kissmanga using FDM, download new chapters, check favorites, basically everything. But suddenly when I tried to check favorites today, it's showing 0 chapters, and the manga info page is blank. I've tried these keys: nsfd732nsdnds823nsdf and 72nnasdasd9asdn123nasdbasd612basd, but both failed. I was able to open kissmanga through browser just fine.

Any idea why?

**Comment by kavin-90** [comment]
Kissmanga keys always changing so try run this

`"For key type 'chko'.` and add that key into fmd and try again

**Comment by spamtaztik** [comment]
Why, that blows. Why won't they just let us download in peace without visiting their site and depriving them of their advertising inc - Oh.

Well, jokes aside, how do I do that? I've tried visiting kissmanga.com using chrome, opened dev tools (ctrl shift I, right?), and typed chko in the console tab, but it gave me "chko is not defined". Sorry, not a coder here...

**Comment by spamtaztik** [comment]
Aahhh, got it... Apparently I have to run the chko command AFTER actually opening a manga image page.

Aaand, apparently I have to close FMD and re-open it again for the key and init string to work, because just clicking "apply" then rechecking new chapters for the favorites from kissmanga does nothing. 

Seriously, need a FAQ page for these uncommon features... :(

Thanks

**Comment by Fliiv** [comment]
Ah. If KissManga is cycling keys and you have to restart FMD to change keys that explains my experience. It would only work when my current key cycled back in, then the other keys I tried didn't change anything since I didn't restart. I confirmed that restarting with a different key changed it from not working to working for me too.
