### ISSUE TITLE
mangago.me has trouble downloading files with an ' in the title

### ISSUE THREAD

**Issue by purpleplushies** [riderkick/FMD#570]
like the title says, on mangago.me it appears that any title with an apostrophe ['] in the title will fail to download.  this might not actually be an issue but on my entire list of things i have attempted to download the only common factor seems to be that ones with the apostrophe don't download and the ones without seem to work fine.  also not sure if its only on mangago.me or if it is an issue on other sites as well

**Comment by kaori8** [comment]
Any manga title i click from "MangaGo" no information comes and can't download either, it just says "one more step". No manga from mangago can't be downloaded

**Comment by kavin-90** [comment]
MangaGo Use Clodflare UAM mode like Kissmanga uses going to see how it use without CF before and how it use CF on Description page
