### ISSUE TITLE
[ISSUE] Where's hitomi.la?

### ISSUE THREAD

**Issue by Ratentaisou** [riderkick/FMD#571]
As you can see from the title, im trying to download a h-manga. But somehow hitomi.la doesn't exist in my manga sites. All there's Fakku,H2R,Pururin, and PervEden.

But somehow i find other issues that said hitomi.la does exist....
Is it removed or am i just an idiot?

**Comment by Fliiv** [comment]
In case you didn't know, you have to choose which sites appear in the drop-down: "Options" tab -> "Websites" tab -> a second "Websites" tab under that -> "H-Sites" category.  If it's not there, then there's a bug.

**Comment by StormJumper** [comment]
@Ratentaisou what version are you using and did you unzip it correctly and didn't overwrite the new mangalist? If you did that you will not see updated manga sites.
