### ISSUE TITLE
Mangazuki descending chapter

### ISSUE THREAD

**Issue by Hexaf** [riderkick/FMD#572]
I found descending all manga on mangazuki have descending chapter. Maybe it can make update system have issue. Can you make it ascending?

**Comment by StormJumper** [comment]
What version of FMD are you using?

**Comment by kavin-90** [comment]
right click on chapter list click on descending order.

![descending](https://cloud.githubusercontent.com/assets/15142270/25183039/123216d6-2534-11e7-9674-bc309b598a0b.png)
