### ISSUE TITLE
MangaGo- Can't download any manga+No manga information

### ISSUE THREAD

**Issue by kaori8** [riderkick/FMD#573]
A few days after the release of this new version manga go manga list has been like this. No matter which manga title i click can't download any manga or see the information and it says "one more step"
![untitled](https://cloud.githubusercontent.com/assets/27344538/25038869/a51aba68-2122-11e7-90ed-7235bc83c05f.png)

**Comment by kavin-90** [comment]
checking

**Comment by StormJumper** [comment]
@kaori8 , it does help if you give the version your using to help the developers to know where to start looking.

**Comment by kaori8** [comment]
kavin-90, can you please tell me which version are using? should i uninstall and then download and install the whole program again?if it is not too much trouble can you send me your fmd version via gmail? here is my gmaild id: kaorimiyaznono8@gmail.com

**Comment by kaori8** [comment]
StormJumper, i am totally new here..i just updated the new version 109 and then after a few days it happened. How can i send it to the developers? is there a contact email address here..if you could tell me about it it would be really helpful..thanks..

**Comment by kavin-90** [comment]
I'm using latest version to check the issues.

Version	:	0.9.109.0

i don't any problem with MangaGo other than ' series names

**Comment by kaori8** [comment]
kavin-90, i downloaded fmd 0.9.109.0 version again from this website released page and installed it but still the same problem..

**Comment by kaori8** [comment]
The only sites working are mangafox,mangahere and manga reader. Kissmanga, Batoto, Eat Manga, MangaInn just titles no chapters and no information. Manga traders similar to Manga go whenever i click any manga title it becomes "N/A" like manga go becomes "one more step"

**Comment by kavin-90** [comment]
hmm, does manga list show any series list?

your OS version 32 bit or 64 bit? because i use 64 bit work so if i give you 64 version not sure it gonna work for you or not

**Comment by kaori8** [comment]
yap..it shows series list just like the screen shot i posted in the issue..my OS is 64 bit and i also installed 64 bit version

**Comment by kavin-90** [comment]
okay, i'm uploading it here it for you try that version 

http://www.mediafire.com/file/qzry3zc87l1k4ri/fmd.rar

**Comment by kaori8** [comment]
Thanks..i installed the version u uploaded but again same thing only manga fox, mangahere, manga reader work..manga go and other websites still the same..

**Comment by kaori8** [comment]
![1](https://cloud.githubusercontent.com/assets/27344538/25211484/34adbef4-25a7-11e7-964d-678660be0711.png)
![2](https://cloud.githubusercontent.com/assets/27344538/25211485/34b5c2fc-25a7-11e7-8f50-d00037cdfbb1.png)
![3](https://cloud.githubusercontent.com/assets/27344538/25211487/34b848ce-25a7-11e7-8bb3-0499531e9bb7.png)
![4](https://cloud.githubusercontent.com/assets/27344538/25211486/34b83c9e-25a7-11e7-865a-c7347b7a9858.png)

**Comment by kaori8** [comment]
I really don't understand why is it happening..i also tried the older version 0.9.108 but the same thing happens..if manga fox, manga here and manga reader can work then what's happening with other websites...while uninstalling a version i delete all of them manually too..i am very confused..i am using windows 7 ultimate and OS is 64-bit.

**Comment by kavin-90** [comment]
Its the same OS as i use..

What i can tell you even my build version give me the same thing 😞

those sites work in browser? also try disable temporary Anti-virus software or add FMD into Ignore it

**Comment by kaori8** [comment]
yap..they work in browser..i can read any manga online with these websites..my anti virus software is kasperesky and yeah..i put FMD ignore it..

**Comment by kaori8** [comment]
yap..these sites work perfectly from browser...i can read any manga online like that..and in my anti-virus program kasperesky FMD is in "ignore it" setting too..the manga list is there but when i click on the title nothing comes its like it can't establish a connection with the main website..and shows error like just the title or n/a or one more step..is it related to something like domain or IP address..my web connection is through Singapore and IPv4..
