### ISSUE TITLE
Kissmanga issue - fix-able?

### ISSUE THREAD

**Issue by spamtaztik** [riderkick/FMD#580]
Hullo devs,

Do you guys know how often the kissmanga key changes? Is it changed on an interval or totally random?

And do you guys see the issue to be fixable in the future, or are we stuck with having to get a new key whenever it's changed? If it's not fixable, I might have to move my favorites to another site(s)...

Any insights?

And as always, thanks for the great app!

**Comment by kavin-90** [comment]
Auto key retrieval system is falling so you have to keep add it manual

**Comment by spamtaztik** [comment]
So, at the moment it's a no, yeah? <sigh>
Alright then, thanks.
