### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by abhi98** [riderkick/FMD#59]
Can you please try to add this http://www.mh160.com/ website ? Its in different language but It would be great if you can add it.Thank You For all the Hard work :)

**Comment by rajlaksh** [comment]
Oh Chinese Scanlation sites :+1:  
:smiley:

**Comment by abhishekanime98** [comment]
Yeah but I think its going to be really hard or not possible to add this site in FMD because its in different language.

**Comment by rajlaksh** [comment]
It will be easy because it use all images on 1 pages.

**Comment by riderkick** [comment]
I'm planning to change the current websites script mechanism. Every website has its own unit so it can store its own private data like cookies(for login etc), active task count etc, But it required to rewrite all the scripts, and I don't have time to do that. I'm trying to design how it can work with old scripts.
So, all new websites request will be pending.

**Comment by abhi98** [comment]
Thanks riderkick

**Comment by riderkick** [comment]
Does it run on some reader engine like WPManga? So it can be used for other website too.
IIRC, I've seen website that are similar to this, with the same layout etc. 😕
I lost in translation, I can't investigate further. 😵

**Comment by abhi98** [comment]
I think this site doesn't have a reader engine.

**Comment by abhi98** [comment]
Please try to add the site of FMD thanks :)

**Comment by abhi98** [comment]
can you check if it is possible to add this site http://www.chuixue.com instead of the other one ?

**Comment by riderkick** [comment]
Currently I have a problem with character encoding. I've trying to convert to gb2313, gbk etc without success, the char still in "?".

**Comment by riderkick** [comment]
Hi, where is the chapter list, I can't find it. Is it removed or there is somewhere else?
http://www.mh160.com/kanmanhua/94/

**Comment by abhi98** [comment]
Try this links

http://www.mh160.com/kanmanhua/23827/ 

http://www.mh160.com/kanmanhua/22384/

http://www.mh160.com/kanmanhua/21840/
