### ISSUE TITLE
 help...can't download list, can't add account bato.to

### ISSUE THREAD

**Issue by potanx** [riderkick/FMD#590]
i have problem, every time i try to download list or download update new version always failed
i add bato.to account it checking and never change even after i sleep and when i try to close normally it can't, i must force end from task manager.
this happen since the frst time i use FMD, it's version 0.9.86 i use the 64 version.7z i extract and open the fmd.exe now i use the latest still the same.
my os windows 7 ultimate 64 i use simple dnscrypt too. what should i do so i can download new version from the program or list work and succes add accoun?
i try to use not the 64 version, without simple dnscrypt, run as administrator it still fail 500 and only checking
no firewall in my os, i delete the windows firewall and no 3rdparty firewall

thanks

**Comment by StormJumper** [comment]
Did you log into the site bato.to to find out if this was a site issue or not?

**Comment by potanx** [comment]
i can login in the web bato.to

**Comment by StormJumper** [comment]
Did you double check to see if the info you entered into FMD matches?

**Comment by potanx** [comment]
yes i double check it, here now there is new version i need to download it manually it can't do auto update from the aplication, alll my favourite gone T_T
