### ISSUE TITLE
Neoproject Scanlation does not work

### ISSUE THREAD

**Issue by Mariolr93** [riderkick/FMD#591]
Neoproject Scanlation does not work, this scanlation had 2 pages... But it seems that http://npscan.scans-es.com/slide/ is down. Also some manga projects in this page were not updated or FMD could not load them.
The other page is this http://npscan.mangaea.net/slide/

![sin titulo](https://cloud.githubusercontent.com/assets/19262204/26023977/0b5f069e-3785-11e7-9848-f9c8b39d9061.jpg)

**Comment by kavin-90** [comment]
It seems they changed domain so domain has been updated.
