### ISSUE TITLE
downloading/updating lists extremely slow

### ISSUE THREAD

**Issue by sgn15** [riderkick/FMD#592]
Hi, I downloaded a new 0.9.110.0 and I am currently downloading lists and I just want to ask how fast/slow is the updating/downloading lists supposed to be? 

After downloading the lists (zip files), some of them failed. I tried the "update all lists at once" and it's extremely slow (more than 2 hours for a site and it's still not finished).

Do I need to tinker something within the settings for this to fasten the updating speed? or is this normal?

Please help. Thanks.

Edit:

I noticed the connection settings. Does it affect the updating speed? What are the optimal values for those 4 connection settings?

**Comment by StormJumper** [comment]
What sites are you using? Which one is the problem? I have the 0.9.110.0 and with my favorites I have no problems when doing a update manga list.
