### ISSUE TITLE
HeyManga problem!!! still not solved!!!

### ISSUE THREAD

**Issue by sadeghp88** [riderkick/FMD#595]
Version :0.9.110.0

Site : Heymanga
Issue : Only first page of every chapter is downloading for any manga.

**Comment by riderkick** [comment]
First page downloaded just fine.

![sshot-2017-05-24- 14-54-51](https://cloud.githubusercontent.com/assets/4972676/26390499/6347c3fe-4091-11e7-932e-c64406b8aa0d.jpg)
