### ISSUE TITLE
KissManga Added reCAPTCHA Test

### ISSUE THREAD

**Issue by marstaik** [riderkick/FMD#596]
Just letting you know that KissManga has now added a reCAPTCHA test (the one where you click "I'm not a robot").

You can open it up on a browser and pass the test, taking the cookies, idtz and __unam, and grab a few hundred pages before you have to do it again.

Might be worthwhile to have it detect a captcha page and open up a prompt for the user to click on?

**Comment by kavin-90** [comment]
Nope there is no reCAPTCHA test.

that reCAPTCHA test is given to you by cloudflare because Cloudflare think your ip is malicious ip

**Comment by marstaik** [comment]
There is definitely a Google reCAPTCHA test, it appears when you go to read a chapter, not when you enter the site.

See screenshot for details.
http://f.staik.net/f/uy.png

**Comment by kavin-90** [comment]
I checked i didn't get it that Google reCAPTCHA test maybe kissmanga added your ip into bad ip list

**Comment by Tmp341** [comment]
Nope, not here (Turkey) either.

**Comment by ronny1982** [comment]
KissManga has a captcha test. It is triggered when there are to many page requests per minute from the same IP.

**Comment by abhi98** [comment]
Is there a way to restart the download after the reCAPTCHA test?
