### ISSUE TITLE
Application crash/hard shutdown wipes favorites.

### ISSUE THREAD

**Issue by greenaar** [riderkick/FMD#598]
I've had this happen a few times now, and only just figured out why.

FMD's open, and windows updates finish, the system reboots.  I start FMD up.. and it's empty. No favorites.  Manga lists are empty (no hosts to select).

Looking in the FMD folder, files are missing. (Specifically the ones that control chapters downloaded, favorites, and manga lists.

Restore from backup, start the app... all is well. Shutdown the app properly, all is still good.

Restart the computer with the app open (which i assume is performing the equivalent of an application crash)... files are gone.

Don't know if there's anything you can do about this -- maybe offer a 'keep backup copies' option?

**Comment by Tmp341** [comment]
Open Options/Misc/Log/ and choose "Enable Logging", then post your log here.

**Comment by greenaar** [comment]
I apparently had logging enabled.  Seen below, the windows shutdown, and a run immediately after (I'd lost favorites by this point).  Looking, it looks like there's a whole write-to-disk process that wasn't getting honored here, and the application exits before properly closing.

15:33:40:666 INFO: "Free Manga Downloader" started with [PID:11176] [HANDLE:18446744073709551615]
15:33:40:681 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 0.9.110.0
               Product Version   : Win64 Debug
               Host Machine      : Windows 10 64-bit
               Target CPU_OS     : x86_64_Win64
               FPC Version       : 3.1.1
               LCL Version       : 1.9.0.0
               Path              : D:\My Documents\FMD\fmd.exe
               Process ID        : 11176
               MainThread ID     : 11164
15:02:00:159 INFO: TMainForm.FormClose
15:02:01:728 INFO: TMainForm.FormClose aborted!
=== Log Session Started at 5/20/2017 14:55:57 by Free Manga Downloader ===
14:55:57:398 INFO: "Free Manga Downloader" started with [PID:6404] [HANDLE:18446744073709551615]
14:55:57:398 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 0.9.110.0
               Product Version   : Win64 Debug
               Host Machine      : Windows 10 64-bit
               Target CPU_OS     : x86_64_Win64
               FPC Version       : 3.1.1
               LCL Version       : 1.9.0.0
               Path              : D:\My Documents\FMD\fmd.exe
               Process ID        : 6404
               MainThread ID     : 1028
14:57:13:067 INFO: TMainForm.FormClose
14:57:14:551 INFO: TMainForm.CloseNow, disabling all timer
14:57:14:552 INFO: TMainForm.CloseNow, backup downloads
14:57:14:553 INFO: TMainForm.CloseNow, backup favorites
14:57:14:554 INFO: TMainForm.CloseNow, backup all data to file
14:57:14:564 INFO: TMainForm.CloseNow, closing other forms
14:57:14:565 INFO: TMainForm.CloseNow, stop ipc server
14:57:14:573 INFO: TMainForm.FormDestroy, freeing all objects
14:57:14:874 INFO: "Free Manga Downloader" exit normally [PID:6404] [HANDLE:18446744073709551615]

**Comment by StormJumper** [comment]
@greenaar The claims that "Windows update finish, the system reboots" is stretch without a Windows error log showing the caused the problem. I have Windows 10x64 and when I update and reboot-I don't loose my favorites. I think you have other task running that is causing FMD problems. Did you verify your A/V isn't blocking the updates.

**Comment by greenaar** [comment]
I have verified that, yes.  Now, i haven't tried hard killing the FMD process, which might also prove/disprove this.

The only thing I'm somewhat confident about is that a hard exit doesn't do some kind of on-exit writes, and the lack of that seems to cause a problem on next load.

I can adapt to it, but I wanted to make sure you knew.
