### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Benjigx** [riderkick/FMD#6]
Its add this two sites in the program? http://centraldemangas.org/ 
http://mangasproject.xpg.uol.com.br/Home

Language: Portuguese

**Comment by riderkick** [comment]
http://centraldemangas.org/ already supported.
http://mangasproject.xpg.uol.com.br/ dropped because website changes, and I get lost while navigating their website. It always redirected to http://www.aliancaproject.com.br and nothing in there.
