### ISSUE TITLE
Download List not being maintained between computer shutdowns

### ISSUE THREAD

**Issue by anshbansal** [riderkick/FMD#60]
Hi

I had many things in queue in the download list. I shutdown my computer and then I restarted.Now my downloads list is empty. This has happened 2-3 times. At first I thought I was not paying attention but it is definitely happening.

**Comment by anshbansal** [comment]
I checked the works folder and noticed that the works file still had all of the details. But they were not being shown in the downloads list.

**Comment by anshbansal** [comment]
A question. Why is downloaded list being maintained in both downloadedlist as well as favoourites?

**Comment by anshbansal** [comment]
I changed works.ini to another name and started checking through the tasks one by one. In the past few days I had noticed that some chapters had missing pages. Cross-referencing with the tasks present I am finding that these are the missing pages in the chapters.

There is some form of data corruption going on here.

**Comment by anshbansal** [comment]
I stopped and the task vanished from the download list. I can still resume all and download works but nothing is shown in the download lists.

The works.ini file is like below. I removed the details.

[general]
NumberOfTasks=1

[task0]
Website=xxxx
Link=/manga/xxxx/
Title=xxxx
SaveTo=D:\Manga\Mangass\xxxx\
Status=Stopped (94/215)
Progress=7/30
DateTime=42179.9172214583
ChapterLinks=
TaskStatus=STATUS_STOP
ChapterPtr=93
NumberOfPages=30
CurrentPage=30

**Comment by riderkick** [comment]
check your download filter ">>"

**Comment by anshbansal** [comment]
Has not happened again so it might have the filters.
