### ISSUE TITLE
Cannot get manga list from Raw sites

### ISSUE THREAD

**Issue by fmdmf** [riderkick/FMD#606]
Hi. Firstly, thanks for all of the hard work on FMD.

I've noticed that in the latest build (and the previous one), that trying to download manga lists from some Raw sites results in a 404 error. The two I was looking at are:

- Raw SenManga
- Tonarinoyoungjump

**Comment by StormJumper** [comment]
@fmdmf did you try to go to the site directly to see if the problem was really from fmd? 404 means sites is unreachable did you check to see if the site was changed or offline first?

**Comment by fmdmf** [comment]
@StormJumper  Yeah, both sites were working well each time I tried.

**Comment by kavin-90** [comment]
@fmdmf i will fix tonari no young jump with comico

**Comment by fmdmf** [comment]
@kavin-90 Thank you!

**Comment by fmdmf** [comment]
@kavin-90 Will you be doing Raw Sen Manga as well?

**Comment by kavin-90** [comment]
@fmdmf tonari no young jump manga list fetcher does not exists so you got 404 error is right

FMD has no problem with downloading chapter from Raw SenManga and tonari no young jump

**Comment by fmdmf** [comment]
@kavin-90 What do you mean? How do we download chapters without first getting the manga list?

**Comment by riderkick** [comment]
https://github.com/riderkick/FMD/issues/146

**Comment by fmdmf** [comment]
@riderkick Thank you!

**Comment by fmdmf** [comment]
I've just tried this method with both RawSenManga and Tonari. It seems it works fine for RawSen, but with Tonari it only grabs up to chapter 99. Does it not support 3 digit numbered chapters?

**Comment by fmdmf** [comment]
Issue is still present with Tonari no Young Jump. Is there a workaround?

**Comment by kavin-90** [comment]
can you please give sample url?

**Comment by fmdmf** [comment]
@kavin-90 Sure. For example with this series: http://www.tonarinoyj.jp/manga/onepanman/

FMD seems to only read up to chapter 99.

**Comment by kmvi** [comment]
Fixed
c2f378c913b7431ab7c060f9dde47939d048df4e
b4feda3f224f2d162f16f574829ee4e986dc0c18
