### ISSUE TITLE
Please add leitor.net

### ISSUE THREAD

**Issue by formigao** [riderkick/FMD#607]

**Comment by kmvi** [comment]
this site no longer exists

**Comment by formigao** [comment]
@kmvi the site changed name to : https://leitor.net/

**Comment by kmvi** [comment]
Site support was added recently #993. But did they changed domain again? Or is the site just not working?

**Comment by formigao** [comment]
@kmvi site is still working. i think they block access from outside brazil.

but its working just fine here. maybe you need to use a proxy to accesss it
