### ISSUE TITLE
Option to change current chapter in favourites

### ISSUE THREAD

**Issue by anshbansal** [riderkick/FMD#61]
In older versions there was an option to change the current chapter in the favorites list. That is missing.  That is very much needed because of bugs causing my download list to become empty.

**Comment by riderkick** [comment]
Current chapter automatically updated when checking favorites, there is nothing in the code that using this field, just for information only.

**Comment by anshbansal** [comment]
I mean the current chapter that I have downloaded so far. The code should be using that information for checking what to download.

What if a download fails? Or some other error? Or what if I delete and want to change chapters back?
