### ISSUE TITLE
[ISSUE] EatManga All Links Broken

### ISSUE THREAD

**Issue by J2486G** [riderkick/FMD#610]
I am on the latest release, 0.9.113.0, but EatManga still does not work at all and has not since it changed its URL to eatmanga.me.  I can still access the website fine through multiple browsers at eatmanga.me, but the program still lists all links as eatmanga.com and shows only a blank when accessing manga info after double clicking a link under EatManga (see below) despite updating the list.  Thank you for the excellent program, and I hope this will be able to be resolved.

![image](https://user-images.githubusercontent.com/25311381/26945830-c538ce6a-4c52-11e7-9328-cfd9b9aa0d27.png)

**Comment by StormJumper** [comment]
Did you go to the site directly as well from the web to see if the site is offline or changed links?

**Comment by J2486G** [comment]
As I mentioned in my original post, I can access EatManga from any browser I try, but it has been broken on FMD since its url changed to eatmanga.me from eatmanga.com.  I have added an image of what the site looks like for me in chrome.


![image](https://user-images.githubusercontent.com/25311381/26989583-4547a998-4d19-11e7-8538-67cee8a55b9b.png)
