### ISSUE TITLE
Delete all completed tasks deleting everything in downloads list

### ISSUE THREAD

**Issue by anshbansal** [riderkick/FMD#62]
I used the option "Delete all completed tasks" and all my download tasks were deleted. Whether they be completed or only stopped/paused.

**Comment by riderkick** [comment]
Working fine here, check your download filter
![sshot-1](https://cloud.githubusercontent.com/assets/4972676/8365772/1a5c1604-1bc2-11e5-8d1b-7a105a89b562.jpg)

**Comment by riderkick** [comment]
related with https://github.com/riderkick/FMD/issues/60
