### ISSUE TITLE
[Feature Suggestion] Additional option for manga name

### ISSUE THREAD

**Issue by subnighter** [riderkick/FMD#620]
Currently, for manga names probably are obtained from "og:description". I would suggest also adding manga name from URL. For example, in case of  [https://myreadingmanga.info/kokomi-oh-hero-eng/](https://myreadingmanga.info/kokomi-oh-hero-eng/), in first tab there would be "Oh My Hero!", and in second - "kokomi oh hero eng". The process of obtaining of the second name would be:
1) getting the manga URL "https://myreadingmanga.info/kokomi-oh-hero-eng/",
2) removing the website URL (and possibly ending "/") "kokomi-oh-hero-eng", and
3) replacing strange characters (underscores, hyphens) "kokomi oh hero eng".
Something similar could be accomplished by using "og:title" as well: "[Kokomi] Oh My Hero! (c.1) [Eng] - MyReadingManga".
There are manga where the first variant would make more sense, and there are manga where the second variant would be more easily searchable.

**Comment by riderkick** [comment]
https://github.com/riderkick/FMD/blob/master/baseunits/modules/MyReadingManga.pas#L58-L61

The first variant is the right one. Any other information which is not part of the title should go to tags.

**Comment by subnighter** [comment]
Thanks for reply. More or less (with emphasis on less) I can guess what those lines do but could you explain them (for example, line 61 - if all previous attempts fail, then the title will be ...)?
I would really love to see the language information already in the list without need to click "View manga infos"

**Comment by riderkick** [comment]
Empty (N/A).
This is title, it should be cleared.
Searching on the web directly would be more efficient. Especially for website that contain mostly one shot series. And just drag n drop the url(s) (dragging the thumbnail usually will do) to the download list or drop box.

**Comment by subnighter** [comment]
Thanks, seems like it will be easier.
