### ISSUE TITLE
[Error] File not found when clicking "Download manga list from server"

### ISSUE THREAD

**Issue by subnighter** [riderkick/FMD#621]
MyReadingManga has this. How can I fix it?

**Comment by riderkick** [comment]
There is no prebuild manga list for that website.
You can't fix until someone upload it. Just build yourself, "Update manga list".
Or just use drag n drop the url(s) to download list.

https://sourceforge.net/projects/newfmd/files/data/

**Comment by subnighter** [comment]
Thanks for reply. Was wondering whether that would cause not to download  some part of list for manga on the website. Due to your comment I think that it is not a case.
