### ISSUE TITLE
[Error]I cant download from ReadManga.Today ??

### ISSUE THREAD

**Issue by AiEsper** [riderkick/FMD#622]
There are nothing in chapter list
Is that bug , feature or RMT doing?
![This](https://user-images.githubusercontent.com/27928013/27212910-96d0384c-528d-11e7-8300-89e1d527401f.png)

**Comment by riderkick** [comment]
Seems like they remove many chapters from various series.
Only those in "Hot" has the chapters.

![sshot-2017-06-17- 01-33-52](https://user-images.githubusercontent.com/4972676/27237905-6a8db0c8-52fd-11e7-8af9-594095f8e8dc.jpg)
