### ISSUE TITLE
Shogakukan's tameshiyo.me chapter preview site

### ISSUE THREAD

**Issue by anonsubmitter** [riderkick/FMD#623]
Could you add Shogakukan's Shogakukan's tameshiyo.me chapter preview site?
Sample pages: https://www.google.com/#q=site:shogakukan.tameshiyo.me

**Comment by riderkick** [comment]
Try this, just drag n drop the url(s) to download list.

Compiled for win32. Get the rest of file from the release package.
[fmd.7z.txt](https://github.com/riderkick/FMD/files/1082557/fmd.7z.txt)
