### ISSUE TITLE
Error tmo in "Check for new chapter", when many favorites mangas

### ISSUE THREAD

**Issue by rs3mk** [riderkick/FMD#626]
Error in TMO (tumangaonline.com) when reviewing new chapters when there are many mangas in favorites.
![check](https://user-images.githubusercontent.com/19628943/27259677-3f0cc06a-53de-11e7-8c3e-8c4dc9c16d37.png)

Thanks.

**Comment by StormJumper** [comment]
Does the manga show up if you go to the website to read them?

**Comment by rs3mk** [comment]
yes, working: https://www.tumangaonline.com/biblioteca/mangas/11821/What-Does-The-Fox-Say

When you make many requests in a short time, TMO blocks you.

**Comment by rs3mk** [comment]
check https://www.youtube.com/watch?v=HpfmG4EQjSo
