### ISSUE TITLE
Kissmanga not downloading

### ISSUE THREAD

**Issue by angelo93** [riderkick/FMD#629]
Hi, 
I seem to have a problem when downloading from kiss manga. All of my updates keep failing. If possible could you look into this? Thanks for all your hard work!

Cheers!

**Comment by StormJumper** [comment]
Have you tried to go to kissmanga to see if the site didn't change their script or url?

**Comment by angelo93** [comment]
The url seems to be unchanged. I don't actually know how to check the script.

**Comment by Tmp341** [comment]
Chek this:

1. Open kissmanga.com -> Open a manga chapter's first page.
2. Right click -> inspect element -> choose "console"
3. Type "chko" and hit enter. Copy and paste what has returned from that code to a blank text file. For example "mshsdf832nsdbash20asdm". 
4. Now type "CryptoJS.enc.Hex.stringify(iv)" and hit enter. Copy and paste what has returned from that code to a blank text file. For example "a5e8e2e9c2721be0a84ad660c472c1f3"
5. Open FMD -> Go to "Settings -> Websites -> Options" tab. Paste those codes to "Key" and Initialization Vector".
6. Save.
7. Restart FMD.
8. Check again.

**Comment by corpse69** [comment]
i dont quite follow  ether its not working for me or im using wrong browsers aswell

**Comment by riderkick** [comment]
I figured out the anti-bot can be bypassed with google dcp(data saver).
Please test it.
[fmd.7z.txt](https://github.com/riderkick/FMD/files/1166698/fmd.7z.txt)
