### ISSUE TITLE
Russian localization for the FMD

### ISSUE THREAD

**Issue by TokcDK** [riderkick/FMD#631]
Hi.
I like this tool. It is very convenient for using with many sites. 
Thank you for your work on it.

I want to contribute with added localization. I have russian localization files of fmd.ru_RU \ updater.ru_RU. Tested them in two weeks. How can I add them? Just upload to this post?

ps
And second question. Where can I upload databases for couple manga sites which was created with update manga list function?

**Comment by riderkick** [comment]
Yes, just upload here. Or you can fork this project and edit/add the files. Then make a pull request.

You can upload the database here too. Compress with 7zip.
Or if you want to maintain the database,create a sourceforge account. Message me, and I will give you permission. Then you can easily modify the databases directly with sftp.
https://sourceforge.net/projects/newfmd/files/data/

**Comment by TokcDK** [comment]
Thanks. Made pull request for localization.

Here is SF account: https://sourceforge.net/u/tokcdk/profile

**Comment by riderkick** [comment]
Done.
