### ISSUE TITLE
Delete task + data deleted the whole manga folder

### ISSUE THREAD

**Issue by anshbansal** [riderkick/FMD#64]
Is it supposed to delete the whoel folder containing the particular manga? I mean not only the mangas which were downloaded as part of the task but the whole damn folder containing the particular manga and all of its sub folders.

If yes, then is there a way to hide this option. I don't see why I would want to do us this option ever again.

**Comment by riderkick** [comment]
It seems so, I didn't touching this part yet, I'll try to look at this later.

**Comment by riderkick** [comment]
https://github.com/riderkick/FMD/commit/cf5d875b4db6ef1ad1fdaefadc40b796f7c797a4
