### ISSUE TITLE
Myreadingmanga.info gets the info of the manga but not downloads anything.

### ISSUE THREAD

**Issue by Reyeselda95** [riderkick/FMD#640]
i was trying to download some chapters from there but when i click downoad it puts like the chapter only have one page and don't downloads anything. Can anyone fix it? Thanks :)

**Comment by riderkick** [comment]
Download just fine.
GIve me an example.

**Comment by Reyeselda95** [comment]
https://myreadingmanga.info/wasukoro-whats-wrong-with-stripping-the-bastard-raw/
https://myreadingmanga.info/hibakichi-kisaragi-yuki-hcf-mayo-naka-shokushu-persona-4-dj-jp/
https://myreadingmanga.info/draw-two-dragon-rush-2-jp/
https://myreadingmanga.info/tiger-bunny-dj-%e8%a7%a6%e6%89%8bx%e3%83%90%e3%83%bc%e3%83%8a%e3%83%93%e3%83%bc%e3%82%a2%e3%83%b3%e3%82%bd%e3%83%ad%e3%82%b8%e3%83%bcslippery-eng/
https://myreadingmanga.info/tora-shutsubotsu-chuui-zelo-lee-brave-lover-2-eng/
Any of these are downloading. Some of this page work, some others don't and i don't know why, cuz i can see the manga info when i type the url. Here are two screenshots.
![captura2](https://user-images.githubusercontent.com/22152673/27592711-5f0b9200-5b55-11e7-993e-7e1e3122c780.PNG)

When i mark to download and click download it happens this:

![captura](https://user-images.githubusercontent.com/22152673/27592589-24303460-5b55-11e7-9fb2-05027fbc6335.PNG)

**Comment by nurikod** [comment]
the problem is in the site 
i thy 2 programs and all the time its downloading only haft of the pictures 2,4,6,8,10....
if someone know a way to undo it olz tell
