### ISSUE TITLE
MangaSee downloads failing

### ISSUE THREAD

**Issue by WaitWhat4355** [riderkick/FMD#641]
Downloads appear to be failing on MangaSee specifically, and the addresses in FMD are the correct ones for the site.

**Comment by BrokenBob** [comment]
I also have seen this. Using 0.9.118.0. This is what it says in the log: 

09:10:08:981 TTaskThread, checkforfinish failed=1/1 "Boku no Hero Academia" > "No. 001"
09:10:13:467 TTaskThread, checkforfinish failed=1/1 "ReLIFE" > "Chapter 185"
etc.

And says the same for all titles from MangaSee.
