### ISSUE TITLE
fix mangasee.co / mangaseeonline.us pls. 

### ISSUE THREAD

**Issue by rydroned** [riderkick/FMD#647]
cant auto download from favorite and it keeps getting 0 images or files

**Comment by psdaf** [comment]
Yeah, i'm trying to download Naruto (i couldn't find other page with good manga quality) but it fails.  I really want to download from Mangasee.  Help!

**Comment by Anvirol** [comment]
Yeah it's a shame. Mangasee seems to have higher quality releases than other sites.

**Comment by BrokenBob** [comment]
It is fixed technically, but you have to build it yourself. Although that said I would love to see riderkick do up a new release as the one I built will download fine but I can't check for new ones. So I have to use the release one to check for new chapters then start the download, which will fail, then close it and swap out the exe for the one I built and then start it up and I can resume the downloads.

**Comment by psdaf** [comment]
Build it myself? Didn't know that, i'm new to this, can you explain how to do it? Anyways i'll look around and see if i can do it myself. Well time to screw up things!

**Comment by berserkingyadis** [comment]
Has this issue been resolved?

**Comment by Anvirol** [comment]
@berserkingyadis yes
