### ISSUE TITLE
German Translation - interested?

### ISSUE THREAD

**Issue by Novellis** [riderkick/FMD#653]
Oi!

First, I like your project. It's a nice alternative to DomDomSoft Manga Downloader which is pretty dead. However, I saw that different languages are already available. To support the project at least somehow, I could provide you with a german translation, if you like.
Plus, I found one "mistake" in your fmd.en: 
"Fan based work inpspired by official manga/anime."
Did you mean "inspired"?

I couldn't find any other way to contact you, so forgive me, that I post here.

See ya,

**Comment by riderkick** [comment]
Just make a pull request.

**Comment by Novellis** [comment]
I have never done a pull request before. I guess it's easier for me to depose it here.

[fmd.de.zip](https://github.com/riderkick/FMD/files/1163927/fmd.de.zip)
