### ISSUE TITLE
[ASK] Can it auto-update from the software itself?

### ISSUE THREAD

**Issue by p1nkyy** [riderkick/FMD#66]
All this time, I have always download the 7z file, replace the FMD in my PC, and replacing the config folder. Can this software actually update within itself? Thanks!

**Comment by anshbansal** [comment]
There is an option to check updates in Options.

**Comment by p1nkyy** [comment]
Doesn't really do anything when I press on it.

**Comment by riderkick** [comment]
Options>check for new version. It will check the new version at startup, also if you set favorites check timer, it will also check the new version alongside favorites checking. 
There is no feedback when there is no new version, so it looks like there is nothing happened. Sorry I'm too lazy to add message dialog for no updates, and no one complain about it too, I may add it if you want.
Try to check for new version from previous version, it will show the new version with the changelog

**Comment by p1nkyy** [comment]
The thing is, I know I'm using an outdated version. The version in Github here is already 0.9.17.1 while mine is still 0.9.7.1. I'm using the 64 bit version, taken from your Mediafire folder.

**Comment by riderkick** [comment]
Update method is disabled prior migrating to giithub. So the ones from my mediafire folder can't do automatic update.

**Comment by p1nkyy** [comment]
Ah I see. OK, thanks for explaining!
