### ISSUE TITLE
naming issue

### ISSUE THREAD

**Issue by fajarq96** [riderkick/FMD#660]
there no problem with download but folder name always changed to "One more step"
here the pic
https://puu.sh/wIHyh/ca2948aee9.png
https://puu.sh/wII0w/2e0566d562.png

**Comment by StormJumper** [comment]
Full screen - cropping isn't going to help them see what is happening. Unedited screen shot will do more to inform them what is going on to know what else to do.

**Comment by fajarq96** [comment]
already fixed somehow, don't know the reason though.
maybe its from my connection
