### ISSUE TITLE
Chapter says downloaded even if not all page downloaded

### ISSUE THREAD

**Issue by anshbansal** [riderkick/FMD#67]
Has happened with me multiple times. Download gets completed but actually only page of the chapter was downloaded.

**Comment by anshbansal** [comment]
Sometimes even when not a single page as downloaded the download was complete.

**Comment by riderkick** [comment]
In works.ini does NumberOfPages>1 ?
It hard to reproduce when the problem.

**Comment by riderkick** [comment]
this commit should fix your issue https://github.com/riderkick/FMD/commit/29e77860e9afe75f6c0d90140875f1946bba3fca
