### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by nFteddy** [riderkick/FMD#670]
I've finally managed to get all the dependencies installed however when I am attempting to build FMD I keep getting this error:

simplehtmltreeparser.pas(13,74) Fatal: Cannot find FLRE used by simplehtmltreeparser of package internettools.

I am not sure how to remove the dependency on FLRE or how to install it properly... Any guidance would be greatly appreciated.

**Comment by riderkick** [comment]
https://github.com/riderkick/FMD/issues/456

**Comment by nFteddy** [comment]
Sorry, maybe to clarify it is an issue with the build when it hits Compile Package internettools. How do I comment out the FLRE from the simplehtmltreeparser.pas?

**Comment by riderkick** [comment]
Just undefine flre in `internettoolsconfig.inc` and define Sorokin's. Toggle comment `Ctrl + /`.
