### ISSUE TITLE
downloading manga shokugeki no soma and one piece frequently failed

### ISSUE THREAD

**Issue by namaasliku** [riderkick/FMD#671]
i have these issue for a while already, i first experience it from several build ago (i don't really remember the exact build) and it still persist until now. i only have problem downloading those series and never have problem downloading other series. i tried downloading it from mangainn, mangahere, batoto, eatmanga.  sometimes it could work after fmd update but the problem will happen again the next time i tried to download. i tried to open the website with browser and it work fine

![image](https://user-images.githubusercontent.com/20202134/28365888-f46146e2-6cbc-11e7-87e9-0b8a6da9fa1b.png)

**Comment by Fieryhellz** [comment]
Mangatown seems the most reliable for me, give it a go.

**Comment by traitorAIZEN** [comment]
I used to have this problem not just with shokugeki and one piece.
I lowered the "Number of Downloaded files per task..." to 6 and then i never had this problem again in any site use.

**Comment by namaasliku** [comment]
> Mangatown seems the most reliable for me, give it a go.


it helps, seems like it was site related problem maybe, thanks!

> I used to have this problem not just with shokugeki and one piece.
I lowered the "Number of Downloaded files per task..." to 6 and then i never had this problem again in any site use.

it is always 1 in my setting, i don't think i can lower it more than this
