### ISSUE TITLE
Relative path

### ISSUE THREAD

**Issue by 1aam2am1** [riderkick/FMD#672]
Cold you add please relative path to download folder (manga favorites download folder path)?
I would like to have FMD on my pendrive, but each computer assigns a different drive letter to me. And I must keep FMD in one computer.

**Comment by riderkick** [comment]
Please test. 
Test all function from downloads, favorites, open folder, open with etc.
Test with `..\` too.
Close if Ok.

Compiled for win32.
[fmd.7z.txt](https://github.com/riderkick/FMD/files/1175938/fmd.7z.txt)

**Comment by 1aam2am1** [comment]
Everything works fine.
Thanks.
