### ISSUE TITLE
Just updated to 119, still have issues with downloading from Kissmanga

### ISSUE THREAD

**Issue by Katylar** [riderkick/FMD#674]
Hi! Is there anyway to get assistance regarding this issue? It seems to be isolated to Kissmanga, as I have no issues with downloading anything from Batoto, or Mangastream, etc.

Basically, it started about a week ago. I tried downloading some new chapters, and I kept getting errors when I try to download. The download would work (i.e. the progress bar would change color, I'd get a transfer-rate), but after a few second (i.e. after the manga has been downloaded), I'd get an error.

When I checked the log, I always get the same issue:

![image](https://user-images.githubusercontent.com/12586726/28459873-e95ff1b8-6e41-11e7-87eb-0bfc17ba2e31.png)

I've already tried deleting my old FMD instance, and unzipped a completely new one in a different folder, and when I tried to download anything from Kiss—same issue. So unless there's an issue with my registry or something, I don't know why this is happening.

I can view Kissmanga info just fine, and can read online. So it's not a firewall issue, either.

**Comment by echoPN** [comment]
I have the same Problem...
and I try download it with another App, it's say I got blocked by Cloudflare though I still can open Kissmanga on Browser without problem...

**Comment by Tmp341** [comment]
@echoPN [Check](https://github.com/riderkick/FMD/wiki/FAQ#cannot-download-from-kissmanga) this.

**Comment by echoPN** [comment]
Ohh...
It's work...
Thanks...
