### ISSUE TITLE
Double clicking on column header behavior changed

### ISSUE THREAD

**Issue by SilentNN** [riderkick/FMD#676]
To see the most recently downloaded chapters at the top of my downloads list, I was quickly clicking on the "Added" column header to resort my downloads list. Now when I multi-click a column header, it sorts once for the first click then opens a chapter for the next double click. Moving the mouse between my first and second click avoids the issue, but is inconvenient.

If a feature to automatically have new downloads added to the top of the list or to sort it automatically after downloads are added, I would appreciate it too.

**Comment by kmvi** [comment]
Fixed 9473f98a96b33c1fecb79493387c8099dc008ae6
