### ISSUE TITLE
Mangafox watermark

### ISSUE THREAD

**Issue by traitorAIZEN** [riderkick/FMD#680]
I would like to inform you that some pages downloaded from Mangafox still retain their watermarks eventhough I've checked the "Remove watermark" in the options.
I've also noticed that it only happens for pages with this specific watermark:

![0000](https://user-images.githubusercontent.com/30373315/28492573-80b9446e-6f38-11e7-9341-ab3c94f7939c.jpg)

I hope this info helps you solve the issue.
Thanks.

**Comment by riderkick** [comment]
You should tell the exact page/image so we can investigate.

**Comment by traitorAIZEN** [comment]
-http://mangafox.me/manga/gate_jietai_kare_no_chi_nite_kaku_tatakeri/vTBD/c059/11.html
-http://mangafox.me/manga/gate_jietai_kare_no_chi_nite_kaku_tatakeri/vTBD/c059/15.html
-http://mangafox.me/manga/gate_jietai_kare_no_chi_nite_kaku_tatakeri/vTBD/c059/22.html
-http://mangafox.me/manga/gate_jietai_kare_no_chi_nite_kaku_tatakeri/vTBD/c059/23.html
-http://mangafox.me/manga/gate_jietai_kare_no_chi_nite_kaku_tatakeri/vTBD/c059/24.html
-http://mangafox.me/manga/gate_jietai_kare_no_chi_nite_kaku_tatakeri/vTBD/c059/27.html
-http://mangafox.me/manga/gate_jietai_kare_no_chi_nite_kaku_tatakeri/vTBD/c059/38.html
