### ISSUE TITLE
Mangogo -some manga not downloading

### ISSUE THREAD

**Issue by leoteesh** [riderkick/FMD#682]
Hi 

Over the last few days, some mangas are failing to download. I kept trying over the last few days but still the same outcome - any chance you can help me on this?
![image](https://user-images.githubusercontent.com/21075197/28497898-f2db6bde-6f89-11e7-9134-addd6134cb92.png)

Many thanks

**Comment by subnighter** [comment]
How does it look when you try to access the updated chapter from web browser (for example, some pages are not loading, there are redirects, etc)?

**Comment by leoteesh** [comment]
the chapters work fine on the website

**Comment by riderkick** [comment]
Please test with various series, old and new release. I'm not sure if the new reader page is also applied to old series or not.
[fmd.7z.txt](https://github.com/riderkick/FMD/files/1168113/fmd.7z.txt)

**Comment by subnighter** [comment]
What are we supposed to do with it? After removing ".txt" part of file name, the archive contains only fmd.exe.

**Comment by leoteesh** [comment]
hi, sorry is this ok now?

**Comment by riderkick** [comment]
Just get the rest of the file from the release package. It is compiled for win32.

**Comment by subnighter** [comment]
Oh, so that's why nothing happened when pasted to fmd folder and double-clicked fmd.exe (using 64-bit Windows).

**Comment by riderkick** [comment]
You need the right dll, can't be mixed. Just overwrite all in your fmd folder with win32 release package. You can overwrite them again with 64bit build later. All config file is the same.

**Comment by leoteesh** [comment]
Sorry, I am not too sure how do i do this?

**Comment by subnighter** [comment]
leoteesh:
If you have 32-bit FMD it's easy - remove ".txt" part of file name of attachment, unzip it, and replace old fmd.exe with the new one.
riderkick:
Indeed, not all manga use the new reader page. One of them is , for example, [this](http://www.mangago.me/read-manga/how_much_i_like_you/)

**Comment by leoteesh** [comment]
Sorry for so many questions
Feeling really silly and a bit confused. Really have no idea how to do this. I am not even sure as to where to start.
i am using win64.

**Comment by subnighter** [comment]
leoteesh:
Below is what I did:
1. Moved the files of root folder (but not folders )of 64-bit FMD to some other place;
2. Downloaded [the latest release](https://github.com/riderkick/FMD/releases/download/0.9.119.0/fmd_0.9.119.0.7z) from [here](https://github.com/riderkick/FMD/releases) and unzipped;
3. Pasted the files but not folders
![image](https://user-images.githubusercontent.com/29464178/28558203-7ecda32e-7119-11e7-8cfa-35cdb5a22309.png)
to the place where 64-bit FMD was installed;
3a. Renamed fmd.exe to fmd_old.exe (optional step, I'll tell you later why it's beneficial);
4. Downloaded fmd.7z.txt from this tread;
5. Renamed fmd.7z.txt to fmd.7z;
6. Extracted fmd.exe from fmd.7z;.
7. Pasted fmd.exe to the place where 64-bit FMD was installed;
8. Double-clicked fmd.exe and clicked resume to failed downloads.
And now why I suggest to have also previous version of fmd.exe. Manggo isn't consistent - for some manga they are using old reader, and for some - the new. fmd_old.exe knows how to deal with the old one, fmd.exe - with the new one. But neither know how to download from both. So switching between fmd.exe versions is required when either one fails to download.
But it's possible to have an algorithm dealing with both cases:
1. Detect which reader site it is: I naively assume verification whether the website name contains "mangago" should suffice.
2. The result of versification is true then use the old mangago code.
3. The result of versification is true then use the new mangago code.

**Comment by leoteesh** [comment]
Thanks so much for your detailed explanations. i am not finding the fmd7z.txt
is it the 7za.exe?
thanks

**Comment by subnighter** [comment]
That file is [here](https://github.com/riderkick/FMD/issues/682#issuecomment-317255047).

**Comment by leoteesh** [comment]
Thanks. i tried it but my antivirus is not letting me open the file and the below comes up
![image](https://user-images.githubusercontent.com/21075197/28590851-90c9622c-717b-11e7-9cd2-8633e1bf7208.png)

**Comment by riderkick** [comment]
Your antivirus block that path. You can't create a file with that path anymore. Add  the fmd folder to your antivirus exclusion list. Antivirus gotten aggressive this day, furthermore after all of that ransomware spike.

**Comment by spamtaztik** [comment]
New fmd.exe works. Thanks a bunch!

**Comment by subnighter** [comment]
Not fully fixed yet - there are manga which fail to download (because they use old reader). Just realized that full fix would require few but deep changes instead of my previous naive approach. Sloppily remembering what i learned about Borland Pascal really long time ago, the fix would look like:
In line 15 insert 
old_site: boolean; //a variable what shows which reader version is
And now it looks complicated.  When starting a download, there should be a check which reader version is used on server for downloadable chapter.
And then in GetPageNumber it would be used.
But the most interesting would be looking what do
`XPathString('//script[contains(.,"imgsrcs")]/substring-before(substring-after(substring-before(.,"imgsrcs"),"= ''"),"''")', Document);
XPathString('//script[contains(.,"imgsrcs")]/replace(substring-before(substring-after(.,"("),")"),"''","")', Document);`
return in both cases (old and new readers).
For now I'll have to switch between 119 and 120 versions.

**Comment by leoteesh** [comment]
When I opened the fmd.exe, it came off as empty. All favourites and history disappeared

**Comment by spamtaztik** [comment]
@leoteesh Did you move the new exe to overwrite the original fmd.exe in your fmd folder?

**Comment by riderkick** [comment]
Give the example URL for both old and new reader. So I can investigate. The series and chapters.

**Comment by riderkick** [comment]
Give the example URL for both old and new reader. So I can investigate. The series and chapters.

**Comment by riderkick** [comment]
Give the example URL for both old and new reader. So I can investigate. The series and chapters.

**Comment by subnighter** [comment]
I believe the readers are per-series basis. The manga using old reader were hard to find.
New reader:
http://www.mangago.me/read-manga/kono_oto_tomare/
http://www.mangago.me/read-manga/yugami_kun_ni_wa_tomodachi_ga_inai/
http://www.mangago.me/read-manga/doukyonin_wa_hiza_tokidoki_atama_no_ue/
Old reader:
http://www.mangago.me/read-manga/hitorijime_my_hero/ - specifically tested chapter 5.5 of this manga. Version 119 could download but 120 couldn't.
http://www.mangago.me/read-manga/cello_mellow/
http://www.mangago.me/read-manga/teddy_bear_no_wakarekata/
http://www.mangago.me/read-manga/like_a_hero/

**Comment by riderkick** [comment]
Try this.
[fmd.7z.txt](https://github.com/riderkick/FMD/files/1177965/fmd.7z.txt)

**Comment by subnighter** [comment]
Thanks, seem to work with both readers.

**Comment by leoteesh** [comment]
I tried changing to the new fmd.7z.txt, it comes up blank again. i did overwrite the old fmd
![image](https://user-images.githubusercontent.com/21075197/28656874-358a4864-729c-11e7-9d17-97fd2688f17b.png)
![image](https://user-images.githubusercontent.com/21075197/28656887-466602e0-729c-11e7-8555-d6ce0776c78d.png)

**Comment by subnighter** [comment]
leoteesh, did you download 32-bit version?

**Comment by riderkick** [comment]
That's compiled for win32.  downloads, favorites etc using sqlite db. you need the right sqlite dll. also the openssl dll. the rest doesn't matter.

**Comment by leoteesh** [comment]
Ah. No I am using the 64 bit version. If I download the 32bit won't I lose all my history and favourites?

**Comment by riderkick** [comment]
No. All user data is portable, you can switch between 32bit and 64bit anytime.

**Comment by leoteesh** [comment]
How would you do that? Just copy the files over?
If I don't do this - would it update automatically through fmd? As updates, I usually just do that from the fmd
