### ISSUE TITLE
Another (?) mangago issue

### ISSUE THREAD

**Issue by spamtaztik** [riderkick/FMD#684]
After updating to 119, all my downloads from MangaGo will always get the "Failed, try resuming this task" error. Retrying or downloading manually from the "manga info" page also gave me that error. Any idea why? 

BTW, the first error msg was on July 20th, and I'm using Win7, if that helps in any way.

Thanks!

**Comment by riderkick** [comment]
https://github.com/riderkick/FMD/issues/682
