### ISSUE TITLE
Since 0.9.120.0 he no longer save as cbz

### ISSUE THREAD

**Issue by nille02** [riderkick/FMD#687]
Since the 0.9.120.0 Update he no longer save files as cbz. He Download the images and delete them without creating the cbz archive. There are no errors in the log.

**Comment by riderkick** [comment]
Look at the source.  https://github.com/riderkick/FMD/blob/master/baseunits/uPacker.pas#L151-L158
It will check for compressed file before cleaning the images.
So it success to write the compressed file but your system (maybe antivirus) remove them afterward.
Try to exclude the fmd folder. Or try to temporary disable your antivirus to see if they are the culprit.

**Comment by nille02** [comment]
There is no AV tool that can go in the way.  But i find the created files now. They are in the root folder and only named after the comic/manga.

Each Favorite has it own Subdirectory where the cbz files are placed and where he download the images. but then he create the cbz files based on the comic/manga name and save it in the directory before the manga/comic folder.  

eg. instead of save "Issue #27.cbz" in the Rick and Morty Folder, he name the File "Rick and Morty.cbz" and save it one level higher where all manga/comic folders are present.

**Comment by nille02** [comment]
![screenshot 2017-07-27 13 02 54](https://user-images.githubusercontent.com/4272018/28667527-287c12f8-72cc-11e7-8d8a-ed091aefe718.png)

This are the Save to Settings that worked until now without a problem. 

The Default Path there is not my main directory. Its set for each Comic/manga manual to E:\%Username%\Bilder\Manga\Manga Downloader\<Comic or Manga Name>

**Comment by nille02** [comment]
A workaround would be to check the "Auto generate chapter folder option". Its Possible that he name the Archive like the Folder?

**Comment by liohunter** [comment]
I'm having the exact same issue since the new update, the images get saved in root as the folder name.

**Comment by riderkick** [comment]
Give me your downloads.db

**Comment by nille02** [comment]
[works.zip](https://github.com/riderkick/FMD/files/1182301/works.zip)

Thats the Database from my Testsetup.

**Comment by riderkick** [comment]
If you look at this commit this commit https://github.com/riderkick/FMD/commit/e7ecb4c542443cb0d099e2100ed0b8bdc3e7bfc0
There is not much changed actually.
Do the option `Auto generate chapter folder` enabled in your settings?

**Comment by riderkick** [comment]
Without chapter folder, the compressed file will be following where it stored.
This behavior is the same since forever.

With Auto generate chapter folder enabled.
`downloads\series name\chapter name\downloaded file.jpg`
The compressed file will be:
`downloads\series name\chapter name.cbz`

Without Auto generate chapter folder enabled.
`downloads\series name\downloaded file.jpg`
The compressed file will be:
`downloads\series name.cbz`

**Comment by nille02** [comment]
Its now different. In the past version it was like this. series name is not generated from fmd its in my case the folder to the comic/manga in favorites

Without Auto generate chapter folder enabled.
`downloads\series name\downloaded file.jpg`
The compressed file will be:
`downloads\series name\chapter.cbz`

and now its 

Without Auto generate chapter folder enabled.
`downloads\series name\downloaded file.jpg`
The compressed file will be:
`downloads\series name.cbz`

**Comment by riderkick** [comment]
The problem without auto generate chapter folder is because of the filename is the same for all chapter, 001.jpg, 002.jpg etc. There is a chance the files will be overwritten by other chapter, especially if the chapter failed to complete. Except if you changes the custom filename by adding the chapter name.

**Comment by nille02** [comment]
i know the problem, i had it sometimes in the past. and i don't have a problem with enable the auto generation. my concern is thats maybe a bug that he create the cbz file based on the foldername and not use the actual chapter name like before. 
With the cbz file name like the foldername is also a problem that he overwrite it every time.

**Comment by riderkick** [comment]
Please test.
[fmd.7z.txt](https://github.com/riderkick/FMD/files/1182431/fmd.7z.txt)

**Comment by nille02** [comment]
It works. Thank you.
