### ISSUE TITLE
Failed creating directory

### ISSUE THREAD

**Issue by Souravi785** [riderkick/FMD#688]
when i try to download "saikin kono sekai wa watashi dake no mono ni nari mashita" the download fails immediately and says failed to create directory. What should i do?

p.s-this manga download fails in every site i tried in fmd.

It worked fine when i changed manga folder name. But why did it fail. I don't think the character name exceeded 200 characters. Could u please look into this?

**Comment by riderkick** [comment]
Post your downloads.db and config.ini

**Comment by Souravi785** [comment]
[downloads.zip](https://github.com/riderkick/FMD/files/1184887/downloads.zip)
[config.ini.zip](https://github.com/riderkick/FMD/files/1184888/config.ini.zip)

**Comment by riderkick** [comment]
Your downloads.db is empty. I ask about the failed task.

**Comment by Souravi785** [comment]
[downloads.zip](https://github.com/riderkick/FMD/files/1185281/downloads.zip)
[config.zip](https://github.com/riderkick/FMD/files/1185283/config.zip)
[config.ini.zip](https://github.com/riderkick/FMD/files/1185286/config.ini.zip)
[downloadedchapters.zip](https://github.com/riderkick/FMD/files/1185285/downloadedchapters.zip)

I dunno if these are right. But I uploaded the files i found when trying to downloading chapters.
