### ISSUE TITLE
Update window shows that I have old version

### ISSUE THREAD

**Issue by Splendorius** [riderkick/FMD#69]
Not program breaking bug, but very annoying (especially if you have automatic updates on)

![update bug](https://cloud.githubusercontent.com/assets/13199942/8521987/c3d3bd66-23e9-11e5-8bb3-44b51e22c4b1.jpg)

**Comment by riderkick** [comment]
Probably you really had the old one. Version number in updates dialog come from the actual file information, while the one in about tab is come from static file readme.rtf.

READ THE CHANGELOG! 
There is bug before 0.9.16.1 that make updater can't overwrite the current executable file.
You need to manually download the zip file and overwrite your existing folder.
