### ISSUE TITLE
Japscan downloads not working

### ISSUE THREAD

**Issue by Paperlegend** [riderkick/FMD#694]
Hello, I have tried to download mangas from Japscan (french) but every download fails for some reasons, is it only happening to me or is it a common problem? It would be appreciated if it was fixed, I really want to download mangas in my native language but none of them works... 

the error is ''Failed!, Try resuming this task!'' I'm using the latest version.

Thanks in advance!
![japscanfail](https://user-images.githubusercontent.com/30707551/28948572-89fbd366-7884-11e7-9ca8-2bbe00877965.png)

**Comment by riderkick** [comment]
It's working fine here. Post your downloads.db.

**Comment by Paperlegend** [comment]
it won't let me upload it, it says We don't support that file type

**Comment by riderkick** [comment]
zip your file, rename it and add .txt at the end. `downloads.zip.txt`

**Comment by Paperlegend** [comment]
[downloads.zip.txt.zip](https://github.com/riderkick/FMD/files/1236750/downloads.zip.txt.zip)

Thank you, here it is

**Comment by riderkick** [comment]
I'm asking for `download.db` not the db-journal. I need to reproduce your issue.

**Comment by Paperlegend** [comment]
Sorry I chose the wrong one, I'm not used to this. Here, this should be the right one now

[downloads.txt.zip](https://github.com/riderkick/FMD/files/1237178/downloads.txt.zip)

**Comment by riderkick** [comment]
Your downloads.db is empty.

**Comment by Paperlegend** [comment]
[downloads.txt.zip](https://github.com/riderkick/FMD/files/1240399/downloads.txt.zip)

I don't know why it's empty, here's another one, I have downloaded a bunch of chapters (they have all failed tho, obviously) so it might be different now
