### ISSUE TITLE
heymanga.me new releases failing to download

### ISSUE THREAD

**Issue by Anvirol** [riderkick/FMD#696]
New releases seem to pass the "Preparing" step, but failing to download images.

I noticed that new releases have images at: (there might be other addresses as well)
i4.heymanga.me

While older releases seem to be using:
i1.heymanga.me

**Comment by riderkick** [comment]
That depend on the server. There is no special case on heymanga module to change the address. Every series, every chapter has different domain for image address I suppose.

**Comment by Anvirol** [comment]
As far as I can tell most of the series now use i4.heymanga.me server. 
I hope you can build some kind of fix. I guess I'll have to use their website for now :)

They got a lot of stuff translated that appears nowhere else.

**Comment by riderkick** [comment]
I just check it, there is no alternative address from the web. All my downloads works fine.

**Comment by Meliodas-Sama** [comment]
First of all, thank you for your hard work FMD developers:
 ⦁	riderkick
 ⦁	kavin-90

I'm having the same issue, I can download old manga chapters, but I can't download the new ones 
(pretty sure after  05-Aug-2017).
Here's an example:
Manga Title: Tomo-chan wa Onnanoko!.
Link: [https://www.heymanga.me/manga/Tomochan_wa_Onnanoko](url).
I can download the chapters from 1->598, but can't download chapters from 599->607 (Latest).

And about the servers:
The first image from the chapter 1 (Image link):
[https://i1.heymanga.me/655664414913698495989245861.jpg](url)
The first image from the chapter 597 (Image link):
[https://i1.heymanga.me/1763136794609787928994257464.jpg](url)
Same server (or whatever) i1.

The first image from the chapter 599 (Image link):
[https://i4.heymanga.me/13530269431028149523852164852.jpg](url)
The first image from the chapter 607 (Image link):
[https://i4.heymanga.me/20551908541425153170314428910.jpg](url)
Same server (or whatever) i4.

And thank you for your hard work.

**Comment by riderkick** [comment]
Please try and close if ok.

[fmd_win32.7z.txt](https://github.com/riderkick/FMD/files/1229867/fmd_win32.7z.txt)

**Comment by Anvirol** [comment]
Showing status 0 when updating series.
Also broke 2 other sites gameofscanlation.moe and mangazuki.co

I had to download latest sqlite3 Windows binaries to get this version to run

**Comment by Meliodas-Sama** [comment]
Thank you for the fixing, works fine for me.
@Anvirol you need to use the FMD 32-bit:
https://github.com/riderkick/FMD/releases/download/0.9.124.0/fmd_0.9.124.0.7z

**Comment by Anvirol** [comment]
@riderkick thanks it's fixed 👍
