### ISSUE TITLE
KissManga DLs Down

### ISSUE THREAD

**Issue by Recursiivio** [riderkick/FMD#697]
Website is up but downloads failing in the same fashion as ~2 weeks ago.

**Comment by kevin01523** [comment]
i can download fine check the decryption keys needed

**Comment by Recursiivio** [comment]
I know about the keys, it doesn't work here.

**Comment by riderkick** [comment]
Usually the problem is because your ip is flagged as spammer/bot. This is the case when you using shared ip like vpn, proxy or public isp.  This is cloudflare thing that we don't have any auto fix at the moment.
