### ISSUE TITLE
so what now

### ISSUE THREAD

**Issue by MammothJerk** [riderkick/FMD#7]
i'm not the best with github stuff, the layout is very confusing for me.

i used to download the updates from https://www.mediafire.com/folder/3ccy2c7g36hp3/Fmd for win64

i just copied the fiels in the rar over to my fmd folder and ran it from there, what do i do now? and how does the updater.exe work now with the url and filename?

love the program btw

**Comment by rhoen91** [comment]
Not Cholif/riderkick but, just click on the "releases" link on the FMD github page and download them from there. Once you've downloaded the latest versions you can now update from the program itself from the "about" tab(only the 32-bit versions for now).

**Comment by riderkick** [comment]
You can update to win64 since 0.9.8.1. Look at this commit https://github.com/riderkick/FMD/commit/31719776dfd9e78e1277c221b36f047aed57ae0d
