### ISSUE TITLE
Reader request

### ISSUE THREAD

**Issue by Tenome** [riderkick/FMD#70]
Can you add support for these generic online readers, if you haven't already? A lot of scanlation sites use them, but they hide their DDLs behind numerous adfly links that don't work half the time.

For example,

http://reader.shoujosense.com/read/usemono_yado/en/1/2/page/2

**Comment by rajlaksh** [comment]
FoolzSlide is already Supported.

**Comment by Tenome** [comment]
I didn't see it under English or English-scanlation. What checkbox should I look for?

**Comment by riderkick** [comment]
Hi @rajlaksh do you know what plugins used by m a n g a p a n d a and m a n g a r e a d e r . net ?

**Comment by rajlaksh** [comment]
Manga Panda is mangareader.net site.

I can grab any image from mangareader.net :smile:
