### ISSUE TITLE
MangaGo: List Updating and Manga Title

### ISSUE THREAD

**Issue by Meliodas-Sama** [riderkick/FMD#707]
First of all, thank you for your hard work FMD developers:
⦁	riderkick
⦁	kavin-90

1. I've tried to build MangaGo List from scratch, the result was 220 mangas only, then I downloaded the list from the server it worked-out but when updating the last one it didn't add any mangas to the list, so it didn't update.

2. when I load a manga from the server List (MangaGo List) the word "manga" is added to the last of the manga title, also all the mangas from the one I built from scratch have the word, could you please remove it.

And thank you for the MangaFox fixing yesterday in FMD 0.9.124.0.

**Comment by riderkick** [comment]
Mangago list seems to be limited to 5 page only. Thus, we can't fetch more data. Even though the page number is correct.
http://www.mangago.me/list/directory/all/6/

**Comment by Meliodas-Sama** [comment]
Thanks for the explanation.
