### ISSUE TITLE
How To Add New Site ?

### ISSUE THREAD

**Issue by shikitemeikato** [riderkick/FMD#709]
if me .. i'm must build with source code for add another site ? or just request to @riderkick

**Comment by matoro** [comment]
@shikitemeikato The code for adding a new site is in the baseunits/modules folder.  Just take a look at any of those .pas files as a template for adding a new site.

**Comment by shikitemeikato** [comment]
Thanks for reply @matoro

**Comment by matoro** [comment]
@shikitemeikato You will want to make a data folder in baseunits/includes.  Update config/mangalist.ini, baseunits/uData.pas, baseunits/uDownloadsManager.pas, and baseunits/uBaseUnit.pas.  Basically anywhere which has the list of sites hardcoded in.  Then build and you should be good to go.

**Comment by riderkick** [comment]
No, don't do that. That's the old modules. I'm trying to get rid of them. Look at baseunits/modules/. Add them to websitemodules.inc to initialize them automatically.

**Comment by shikitemeikato** [comment]
Alright , ..Thank you for your attention XD
