### ISSUE TITLE
Heymanga issue

### ISSUE THREAD

**Issue by H4nZ83** [riderkick/FMD#710]
hello, are there any heymanga.me issue ??
is this issue known yet ??

because when i try to download brawling go it resulted this on log

08:48:02:548 TTaskThread, checkforfinish failed=17/17 "Brawling Go" > "/manga/Brawling_Go/93/"
https://i1.heymanga.me/1371537031499342127569822425.jpg
https://i1.heymanga.me/2273354781709567431598993112.jpg
https://i1.heymanga.me/212313448915055644971834090115.jpg
https://i1.heymanga.me/5663052019225899481257993877.jpg
https://i1.heymanga.me/34779005211152769301782349647.jpg
https://i1.heymanga.me/16380343775352749321713426847.jpg
https://i1.heymanga.me/11660074811675774697224913226.jpg
https://i1.heymanga.me/153314417811728010351296128169.jpg
https://i1.heymanga.me/134695311714204186981307051651.jpg
https://i1.heymanga.me/134336918920543805492130372065.jpg
https://i1.heymanga.me/12425804851971706931501507081.jpg
https://i1.heymanga.me/121107385818577016721119357783.jpg
https://i1.heymanga.me/84170547810421738052050154627.jpg
https://i1.heymanga.me/99337881411678220431556445440.jpg
https://i1.heymanga.me/3189791721216995530977264685.jpg
https://i1.heymanga.me/161975519370252898263088805.jpg
https://i1.heymanga.me/136100694610689644161736644001.jpg

and then when i check the address via web browser it comes to not found.
but when i try to open the manga title on the website it comes out, but with a age warning

**Comment by H4nZ83** [comment]
the age 18+ check link comes with this
https://www.heymanga.me/adult.php?adult=1
if dont want to show the check anymore.

**Comment by riderkick** [comment]
https://github.com/riderkick/FMD/issues/696
