### ISSUE TITLE
List index (134) out of bounds

### ISSUE THREAD

**Issue by amayra** [riderkick/FMD#711]
this happened after new update and give this log : 
```
Program exception!
Application       : Free Manga Downloader
Version           : 0.9.124.0
Product Version   : Win64 Debug
Host Machine      : Windows 10 64-bit
FPC Version       : 3.0.2
LCL Version       : 1.9.0.0
WidgetSet         : Win32/Win64
Target CPU-OS     : x86_64-Win64
Build Time        : 2017/08/16 04:03:29
Path              : D:\Compressed\fmd\fmd.exe
Process ID        : 8828
MainThread ID     : 8172
Thread ID         : 4364
Time              : 20/08/2017 09:50:45.989
Sender Class      : TTaskThread
Exception Class   : EStringListError
Message           : List index (134) out of bounds
  $000000010004F4BF
  $000000010005010D
  $0000000100003606
  $0000000100014CF7
  $00007FF9E0452774
  $00007FF9E07B0D51
```

**Comment by riderkick** [comment]
There is not much information about that.
Kindly write the step to reproduce the issue. I need to be able to reproduce your issue to locate the problem.

**Comment by Twoearle** [comment]
I've got a similar error

```
Program exception!
Application       : Free Manga Downloader
Version           : 0.9.124.0
Product Version   : Win32 Debug
Host Machine      : Windows 10 64-bit
FPC Version       : 3.0.2
LCL Version       : 1.9.0.0
WidgetSet         : Win32/Win64
Target CPU-OS     : i386-Win32
Build Time        : 2017/08/16 04:04:30
Path              : C:\Free Manga Downloader\fmd.exe
Process ID        : 6816
MainThread ID     : 1120
Thread ID         : 6520
Time              : 20-08-2017 15:44:22.325
Sender Class      : TTaskThread
Exception Class   : EStringListError
Message           : List index (2) out of bounds
  $00442213
  $00442B95
  $0041292E
  $74E262C4
  $77710F69
  $77710F34
```

This happens right after the program finishes checking the favorites list, and begins download of new chapters (if there's any available)

> Do you have the correct fmd.db?
How can one check this?

**Comment by riderkick** [comment]
Just use the one provided from the release package. To make sure, extract manually from the release package(*.7z), in case the automatic update can't replace that file.
If the debug file correct. It should show some information where the error occured. Like this one.
![sshot-2017-08-21- 03-01-20](https://user-images.githubusercontent.com/4972676/29497585-32e05b82-861d-11e7-9787-410e8b398258.jpg)

From the information above, its occurred in download process. I suspect it was from the old modules which is using include files. Include files sometime doesn't give the correct debug symbol.

Just provide the information about your download. website, series and chapter.

**Comment by Twoearle** [comment]
Seems to be working fine now. Worst case scenario, ill backup the "works" folder and reinstall.
