### ISSUE TITLE
FMD Downloads tab

### ISSUE THREAD

**Issue by Meliodas-Sama** [riderkick/FMD#714]
First of all, thank you for your hard work FMD developers:
⦁	riderkick
⦁	kavin-90

1) I can't change the tasks sort method anymore (by name, Added, Website.......).
2) If there are no tasks and I choose (merge completed tasks) from drop list it gives an error:
List index (-1) out of bounds.

**Comment by riderkick** [comment]
Task sort work as expected.

**Comment by Meliodas-Sama** [comment]
Thanks for the fixing @riderkick.

About the task sort, after I saw your comment I tried different situations, it worked in some of them it appears that I can't change the tasks sort method if:
1. There are no tasks.
2. There is only one task.

And thank you for your hard work.

**Comment by riderkick** [comment]
That behaviour always been like that since forever. No sort performed when count < 2.

**Comment by Meliodas-Sama** [comment]
Thanks for the explanation, and for the change.
