### ISSUE TITLE
Exception Errors when using Update all list at once.

### ISSUE THREAD

**Issue by molitar** [riderkick/FMD#718]
I pasted the last part of the log when I tried running it.. get all sorts of form errors.

15:55:25:001 EXCEPTION: EStringListError - List index (0) out of bounds

  Website : Madokami
  CS      : CS_DIRECTORY_PAGE

                 $000000010004F5AF
                 $00000001002FBE40 line 499 of ../baseunits/WebsiteModules.pas
                 $0000000100300A49 line 962 of ../baseunits/uData.pas
                 $000000010037ACE1 line 164 of ../baseunits/uUpdateThread.pas
                 $00000001000501FD
                 $0000000100003606
                 $0000000100014C97
                 $00000000776159CD
                 $000000007774A561
=== Log Session Started at 8/26/2017 15:55:34 by Free Manga Downloader ===
15:55:34:670 INFO: "Free Manga Downloader" started with [PID:12232] [HANDLE:18446744073709551615]
15:55:34:671 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 0.9.125.0
               Product Version   : Win64 Debug
               Host Machine      : Windows 7 64-bit
               FPC Version       : 3.0.2
               LCL Version       : 1.9.0.0
               WidgetSet         : Win32/Win64
               Target CPU-OS     : x86_64-Win64
               Build Time        : 2017/08/23 03:38:30
               Path              : C:\DOS\fmd\fmd.exe
               Process ID        : 12232
               MainThread ID     : 9452
15:57:29:627 EXCEPTION: EStringListError - List index (0) out of bounds

  Website : Madokami
  CS      : CS_DIRECTORY_PAGE

                 $000000010004F5AF
                 $00000001002FBE40 line 499 of ../baseunits/WebsiteModules.pas
                 $0000000100300A49 line 962 of ../baseunits/uData.pas
                 $000000010037ACE1 line 164 of ../baseunits/uUpdateThread.pas
                 $00000001000501FD
                 $0000000100003606
                 $0000000100014C97
                 $00000000776159CD
                 $000000007774A561
15:57:40:621 EXCEPTION: EStringListError - List index (0) out of bounds

  Website : Madokami
  CS      : CS_DIRECTORY_PAGE

                 $000000010004F5AF
                 $00000001002FBE40 line 499 of ../baseunits/WebsiteModules.pas
                 $0000000100300A49 line 962 of ../baseunits/uData.pas
                 $000000010037ACE1 line 164 of ../baseunits/uUpdateThread.pas
                 $00000001000501FD
                 $0000000100003606
                 $0000000100014C97
                 $00000000776159CD
                 $000000007774A561
15:57:42:621 EXCEPTION: EStringListError - List index (0) out of bounds

  Website : Madokami
  CS      : CS_DIRECTORY_PAGE

                 $000000010004F5AF
                 $00000001002FBE40 line 499 of ../baseunits/WebsiteModules.pas
                 $0000000100300A49 line 962 of ../baseunits/uData.pas
                 $000000010037ACE1 line 164 of ../baseunits/uUpdateThread.pas
                 $00000001000501FD
                 $0000000100003606
                 $0000000100014C97
                 $00000000776159CD
                 $000000007774A561
15:57:45:122 EXCEPTION: EStringListError - List index (0) out of bounds

  Website : Madokami
  CS      : CS_DIRECTORY_PAGE

                 $000000010004F5AF
                 $00000001002FBE40 line 499 of ../baseunits/WebsiteModules.pas
                 $0000000100300A49 line 962 of ../baseunits/uData.pas
                 $000000010037ACE1 line 164 of ../baseunits/uUpdateThread.pas
                 $00000001000501FD
                 $0000000100003606
                 $0000000100014C97
                 $00000000776159CD
                 $000000007774A561
15:57:46:622 EXCEPTION: EStringListError - List index (0) out of bounds

  Website : Madokami
  CS      : CS_DIRECTORY_PAGE

                 $000000010004F5AF
                 $00000001002FBE40 line 499 of ../baseunits/WebsiteModules.pas
                 $0000000100300A49 line 962 of ../baseunits/uData.pas
                 $000000010037ACE1 line 164 of ../baseunits/uUpdateThread.pas
                 $00000001000501FD
                 $0000000100003606
                 $0000000100014C97
                 $00000000776159CD
                 $000000007774A561
15:57:47:621 EXCEPTION: EStringListError - List index (0) out of bounds

  Website : Madokami
  CS      : CS_DIRECTORY_PAGE

                 $000000010004F5AF
                 $00000001002FBE40 line 499 of ../baseunits/WebsiteModules.pas
                 $0000000100300A49 line 962 of ../baseunits/uData.pas
                 $000000010037ACE1 line 164 of ../baseunits/uUpdateThread.pas
                 $00000001000501FD
                 $0000000100003606
                 $0000000100014C97
                 $00000000776159CD
                 $000000007774A561
15:57:48:622 EXCEPTION: EStringListError - List index (0) out of bounds

  Website : Madokami
  CS      : CS_DIRECTORY_PAGE

                 $000000010004F5AF
                 $00000001002FBE40 line 499 of ../baseunits/WebsiteModules.pas
                 $0000000100300A49 line 962 of ../baseunits/uData.pas
                 $000000010037ACE1 line 164 of ../baseunits/uUpdateThread.pas
                 $00000001000501FD
                 $0000000100003606
                 $0000000100014C97
                 $00000000776159CD
                 $000000007774A561
15:57:49:622 EXCEPTION: EStringListError - List index (0) out of bounds

  Website : Madokami
  CS      : CS_DIRECTORY_PAGE

                 $000000010004F5AF
                 $00000001002FBE40 line 499 of ../baseunits/WebsiteModules.pas
                 $0000000100300A49 line 962 of ../baseunits/uData.pas
                 $000000010037ACE1 line 164 of ../baseunits/uUpdateThread.pas
                 $00000001000501FD
                 $0000000100003606
                 $0000000100014C97
                 $00000000776159CD
                 $000000007774A561
15:57:50:623 EXCEPTION: EStringListError - List index (0) out of bounds

  Website : Madokami
  CS      : CS_DIRECTORY_PAGE

                 $000000010004F5AF
                 $00000001002FBE40 line 499 of ../baseunits/WebsiteModules.pas
                 $0000000100300A49 line 962 of ../baseunits/uData.pas
                 $000000010037ACE1 line 164 of ../baseunits/uUpdateThread.pas
                 $00000001000501FD
                 $0000000100003606
                 $0000000100014C97
                 $00000000776159CD
                 $000000007774A561
15:57:51:621 EXCEPTION: EStringListError - List index (0) out of bounds

  Website : Madokami
  CS      : CS_DIRECTORY_PAGE

                 $000000010004F5AF
                 $00000001002FBE40 line 499 of ../baseunits/WebsiteModules.pas
                 $0000000100300A49 line 962 of ../baseunits/uData.pas
                 $000000010037ACE1 line 164 of ../baseunits/uUpdateThread.pas
                 $00000001000501FD
                 $0000000100003606
                 $0000000100014C97
                 $00000000776159CD
                 $000000007774A561
15:57:52:624 EXCEPTION: EStringListError - List index (0) out of bounds

  Website : Madokami
  CS      : CS_DIRECTORY_PAGE

                 $000000010004F5AF
                 $00000001002FBE40 line 499 of ../baseunits/WebsiteModules.pas
                 $0000000100300A49 line 962 of ../baseunits/uData.pas
                 $000000010037ACE1 line 164 of ../baseunits/uUpdateThread.pas
                 $00000001000501FD
                 $0000000100003606
                 $0000000100014C97
                 $00000000776159CD
                 $000000007774A561
15:57:53:622 EXCEPTION: EStringListError - List index (0) out of bounds

  Website : Madokami
  CS      : CS_DIRECTORY_PAGE

                 $000000010004F5AF
                 $00000001002FBE40 line 499 of ../baseunits/WebsiteModules.pas
                 $0000000100300A49 line 962 of ../baseunits/uData.pas
                 $000000010037ACE1 line 164 of ../baseunits/uUpdateThread.pas
                 $00000001000501FD
                 $0000000100003606
                 $0000000100014C97
                 $00000000776159CD
                 $000000007774A561
15:57:58:629 EXCEPTION: EStringListError - List index (0) out of bounds

  Website : Madokami
  CS      : CS_DIRECTORY_PAGE

                 $000000010004F5AF
                 $00000001002FBE40 line 499 of ../baseunits/WebsiteModules.pas
                 $0000000100300A49 line 962 of ../baseunits/uData.pas
                 $000000010037ACE1 line 164 of ../baseunits/uUpdateThread.pas
                 $00000001000501FD
                 $0000000100003606
                 $0000000100014C97
                 $00000000776159CD
                 $000000007774A561
15:58:04:122 EXCEPTION: EStringListError - List index (0) out of bounds

  Website : Madokami
  CS      : CS_DIRECTORY_PAGE

                 $000000010004F5AF
                 $00000001002FBE40 line 499 of ../baseunits/WebsiteModules.pas
                 $0000000100300A49 line 962 of ../baseunits/uData.pas
                 $000000010037ACE1 line 164 of ../baseunits/uUpdateThread.pas
                 $00000001000501FD
                 $0000000100003606
                 $0000000100014C97
                 $00000000776159CD
                 $000000007774A561
15:58:05:121 EXCEPTION: EStringListError - List index (0) out of bounds

  Website : Madokami
  CS      : CS_DIRECTORY_PAGE

                 $000000010004F5AF
                 $00000001002FBE40 line 499 of ../baseunits/WebsiteModules.pas
                 $0000000100300A49 line 962 of ../baseunits/uData.pas
                 $000000010037ACE1 line 164 of ../baseunits/uUpdateThread.pas
                 $00000001000501FD
                 $0000000100003606
                 $0000000100014C97
                 $00000000776159CD
                 $000000007774A561
15:58:06:122 EXCEPTION: EStringListError - List index (0) out of bounds

  Website : Madokami
  CS      : CS_DIRECTORY_PAGE

                 $000000010004F5AF
                 $00000001002FBE40 line 499 of ../baseunits/WebsiteModules.pas
                 $0000000100300A49 line 962 of ../baseunits/uData.pas
                 $000000010037ACE1 line 164 of ../baseunits/uUpdateThread.pas
                 $00000001000501FD
                 $0000000100003606
                 $0000000100014C97
                 $00000000776159CD
                 $000000007774A561
15:58:07:120 EXCEPTION: EStringListError - List index (0) out of bounds

  Website : Madokami
  CS      : CS_DIRECTORY_PAGE

                 $000000010004F5AF
                 $00000001002FBE40 line 499 of ../baseunits/WebsiteModules.pas
                 $0000000100300A49 line 962 of ../baseunits/uData.pas
                 $000000010037ACE1 line 164 of ../baseunits/uUpdateThread.pas
                 $00000001000501FD
                 $0000000100003606
                 $0000000100014C97
                 $00000000776159CD
                 $000000007774A561
15:58:08:625 EXCEPTION: EStringListError - List index (0) out of bounds

  Website : Madokami
  CS      : CS_DIRECTORY_PAGE

                 $000000010004F5AF
                 $00000001002FBE40 line 499 of ../baseunits/WebsiteModules.pas
                 $0000000100300A49 line 962 of ../baseunits/uData.pas
                 $000000010037ACE1 line 164 of ../baseunits/uUpdateThread.pas
                 $00000001000501FD
                 $0000000100003606
                 $0000000100014C97
                 $00000000776159CD
                 $000000007774A561
=== Log Session Started at 8/26/2017 15:58:13 by Free Manga Downloader ===
15:58:13:633 INFO: "Free Manga Downloader" started with [PID:8300] [HANDLE:18446744073709551615]
15:58:13:633 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 0.9.125.0
               Product Version   : Win64 Debug
               Host Machine      : Windows 7 64-bit
               FPC Version       : 3.0.2
               LCL Version       : 1.9.0.0
               WidgetSet         : Win32/Win64
               Target CPU-OS     : x86_64-Win64
               Build Time        : 2017/08/23 03:38:30
               Path              : C:\DOS\fmd\fmd.exe
               Process ID        : 8300
               MainThread ID     : 10996

**Comment by riderkick** [comment]
This is madokami specific. Does it also show an error if you only update madokami?]

**Comment by molitar** [comment]
Yep I got the error.  Figured out need account to keep it from crashing.  So may want to build a safety check that if site with no account than don't attempt to download the list.
