### ISSUE TITLE
MangaStream downloads not loading

### ISSUE THREAD

**Issue by Alkasul** [riderkick/FMD#720]
After the last update I couldn't download anything from MS, there are no problems with the site whatsoever and there isn't any error too, I'm not using VPN or anything like that, it's just not loading.
![image](https://user-images.githubusercontent.com/31385630/29749835-b8e3f106-8b3d-11e7-8491-fe9cf95a105d.png)

**Comment by wildcrow** [comment]
Yeah, the mangastream online reader seems to be working, and I had the same problem like 2 patches ago too, worked again and then yesterday the same problem.

**Comment by imblad3** [comment]
Got same issue with mangastream download. Can't download after latest update.

**Comment by ZerOMegA2k5** [comment]
Same problem here after the last update. 
After that I tried the old version 0.9.112.0 and that one is working just fine.

**Comment by nsnasa21** [comment]
I'm having this problem as well.

**Comment by Lun4m** [comment]
I have the same problem with MangaEden. Downloads still work with version 0.9.124.0.
