### ISSUE TITLE
mangareader.net offline

### ISSUE THREAD

**Issue by nille02** [riderkick/FMD#73]
FDM claims that mangareader.net is offline. The Website works normal in the webbrowser. The Check for new chapters stuck if he come to one of the mangas from this site.

**Comment by riderkick** [comment]
It's working fine here.

**Comment by nille02** [comment]
Not for me. The Website works normal. 

![mr](https://cloud.githubusercontent.com/assets/4272018/8755291/15b99748-2cca-11e5-8e0d-cbd0803372c7.PNG)

**Comment by riderkick** [comment]
Rebuild your list from scratch then, or change those link manually. Those *.dat file actually is just plain text file, just locate the link and replace it, just be carefull with separator "!%~".
Note that fmd can work without manga list. Just paste the link to the URL box, after loaded, you can download or add it to the favorites.
