### ISSUE TITLE
List index (-1) out of bounds

### ISSUE THREAD

**Issue by ORelio** [riderkick/FMD#74]
Hello,
First of all thanks for maintaining FMD which is really a convenient tool!
Today I upgraded to 0.9.18.2_Win64 on my Windows 7 computer.
After unzip and lauch, the app directly crashes with the following exception:

````
Unhandled exception!
Application       : Free Manga Downloader
Version           : 0.9.18.2
Product Version   : Win64 Debug
FPC Version       : 3.1.1
LCL Version       : 1.5
Target CPU_OS     : x86_64_Win64
Host Machine      : Windows 7 64-bit
Path              : C:\Users\ORelio\Desktop\fmd_0.9.18.2_Win64\fmd.exe
Proccess Id       : 2528
Thread Id         : 3084
Time              : 16/07/2015 18:53:07
Ignored Exception : EImagingError,ERegExpr
Exception Class   : EStringListError
Message           : List index (-1) out of bounds
Exception Address : $00000001000638F1
  $0000000100060F50
  $0000000100059E5F
  $000000010003FD3D
  $0000000100020213
  $000000010001E741
  $0000000100024CA0
  $000000010002C28B
  $0000000100003362
  $00000001000033A6
  $0000000100018403
  $0000000100018F06
  $0000000076D259CD
  $0000000076F5B981
````

The GUI does not even appears. After trying some older releases, seems like the issue was introduced in `0.9.12.1`. So release `0.9.12.0_Win64` and older work properly, while `0.9.12.1_Win64` and later will crash on startup :/

Thanks in advance for your help and keep up the good work :)

**Comment by riderkick** [comment]
I suspect it was due to broken data in your config file, or in download/favorite list.
If you don'r mind, please send me your config.ini, works.ini and favorites.ini.
Btw, you can try to make fresh copy of fmd, it may works.

**Comment by ORelio** [comment]
Thanks for your reply! But unless FMD is creating some files outside its installation directory, it was a fresh install directly unzipped from its 7z archive so with its default configuration files...

After more testing I discovered that FMD works properly when placed in my `D:\` drive but not on my desktop. I think this is because my actual Windows username contains some french non-ASCII characters like these: `éèêàâôùûüç` (sorry I changed it in the report above, thinking it would be totally unrelated), causing the application path to contain a non-ASCII character, causing the crash.

After digging a bit with commits between `0.9.12.0` and `0.9.12.1`, I think it's caused by translation files. When FMD looks for translation files, non-ASCII characters in the path will cause FMD not to find any translation files, so the list representing translation files is empty. Then, when FMD tries to save the language (see commit 50baca15f0ec4bf87b24eda763e0b958e536d2b5), there is a crash because the list is empty. After checking out `0.9.12.0` more thoroughly, there is no crash but the dropdown menu in app settings for selecting a language is... empty! Also, when deleting the `languages` folder, the app crashes with the same exact error: `List index (-1) out of bounds` while it works when the folder is present :)

So, I'm not familiar with Pascal but after digging further, I'd say that the [CollectLanguagesFiles](https://github.com/riderkick/FMD/blob/28885bebac81658d149052363bdcea337673c5ca/baseunits/utranslation.pas#L688) procedure would need a fix, because `latin1` paths are not properly handled, since paths are interpreted as `UTF-8` and the `UTF-8` representation of characters with accents is not the same as in `latin1` :)

Thanks in advance. Note that this fix absolutely is not urgent since one can have FMD working simply by installing it in a directory without special `latin1` characters in its path, but maybe some more explicit error messages when no language files are found or invalid characters are detected would help meanwhile?

**Comment by riderkick** [comment]
Well, that's strange, even though we already use utf8 stuff.
But there is indeed a bug if there is range check error.
The hard part is your log doesn't have enough information to localize the problem. It's always been hard to pull enough debug information with fpc, especially those unhandled exception.

**Comment by ORelio** [comment]
No worries, I know that error reporting is not that easy since I'm working on my own projects and sometimes issues are hard to track down. To explain further the current issue: a conversion is needed between `latin1` and `UTF-8`, as illustrated by the table below.

![letter-spagetti](https://cloud.githubusercontent.com/assets/1128206/8752905/b35cd252-2cb7-11e5-9e81-a9d1253d4bd3.png)

The above example shows `latin1` characters (Char) and their corresponding multibyte representation as `UTF-8`, read as if it was `latin1` (X-Trans): if you try to interpret `é` (`UTF-8`-encoded) as `latin1` you would incorrectly get `Ã©` instead of the intended character. The same way, if you try to interpret the `latin1` character `é` as `UTF-8` you would get `0x233`, which is an unreadable character.

It seems like the library FMD is using ([Lazarus](http://wiki.lazarus.freepascal.org/fileutil)?) assumes `UTF-8` input from the Windows operating system when calling its `UTF-8` functions eg `DirectoryExistsUTF8`, which I think is not always true because in occidental editions of the operating system, Windows may return directory info as `Latin1 (ISO-8859-1)`, and so only `ASCII` characters, which are encoded the same way between `latin1` and `UTF-8`, will be properly interpreted. This would explain the current issue.

Encoding problems can often get very annoying to fix that's why I was saying it's not urgent ^^

**Comment by riderkick** [comment]
Conversion is correctly done in fpc, note that GetCurrentDirUT8, DirectoryExistUTF8 always works unless the string is loss in translation, e.g. when assign the value of UnicodeString/UTF8string to String. Maybe I need to explicitly declare the variable as UTF8String. I'll try to set UTF8 in RTL first.

Those exception message seems causing by simply empty combobox. Maybe there is somewhere in code that can't accept Count = 0/ItemIndex = -1. I'll look at it later.

**Comment by ORelio** [comment]
Woah, thanks and congrats for the swift fixes! :)

**Comment by ORelio** [comment]
Just tested `0.9.19.1` release and the bug is gone indeed. Thanks!
