### ISSUE TITLE
Tumangaonline don't load

### ISSUE THREAD

**Issue by Youshuu** [riderkick/FMD#740]
Tumangaonline don't load Manga Info nor download, just create empty folders, since yesterday. They publish on their facebook that they make some maintenance yesterday so I don't know is that maintenance mess with something that FMD use to download from them.

**Comment by rs3mk** [comment]
yes, not work!

**Comment by TheDoom95** [comment]
does not work, I read that the page code became stronger. Please fix that error in the next update.

**Comment by horacio881** [comment]
Same problem. Please fix it, it is the most complete site in spanish.

**Comment by syleniaa** [comment]
I have the same problem, please fix it

**Comment by OscarCid** [comment]
same problem, waiting the fix.

**Comment by rs3mk** [comment]
HDoujin Downloader working!

https://dl.dropboxusercontent.com/s/xdvx6g43xh5dai1/changelog.txt

**Comment by kavin-90** [comment]
it is not working because of they change whole site to JS

**Comment by m80enemy** [comment]
is there a way to fix this? hdoujin is not working anymore but i like fmd better

**Comment by kavin-90** [comment]
soon™

**Comment by kmvi** [comment]
Fixed in [latest release](https://github.com/riderkick/FMD/releases/tag/0.9.133.0), please check
