### ISSUE TITLE
Updating manga list don't get some titles. 

### ISSUE THREAD

**Issue by formigao** [riderkick/FMD#742]
Hi im having problem to update http://unionmangas.net/

some mangas keep missing from FMD like :

http://unionmangas.net/manga/magi-sinbad-no-bouken
http://unionmangas.net/manga/magi-the-labyrinth-of-magic

you can read normally on web but if you searchg for magi at FMD you found nothing.

**Comment by kmvi** [comment]
Manga list db updated on server
