### ISSUE TITLE
Long folder names

### ISSUE THREAD

**Issue by subnighter** [riderkick/FMD#748]
When downloading some manga, for example, [this](http://www.mangago.me/read-manga/isekai_de_skill_wo_kaitai_shitara_cheat_na_yome_ga_zoushoku_shimashita_gainen_kousa_no_structure/) one, the chapter number doesn't appear in the name of the folder for the chapter and new chapters don't get downloaded.
The suggestion is to either somehow to scrape chapter number from original string(for example, "Tantei Gakuen Q 001 Vol 01" => "001 Vol 01", maybe find the first occurrence of digit and change folder name into substring of initial string beginning with that digit), or to remove characters from the beginning instead from the end.

**Comment by Delenai** [comment]
There is and option under the "Save to" tab
"Remove manga name from chapter"

**Comment by subnighter** [comment]
Thanks, that fixed it.
