### ISSUE TITLE
JaiminisBox (Smokin' Parade) Unavailable For Download!, Why?

### ISSUE THREAD

**Issue by JLChamberlain** [riderkick/FMD#751]
So Smokin' Parade by JaiminisBox is one of the manga I have in my favourites but for a while now it hasn't been able to do updates for this series and just appears red even though the program has no issues with other series done by JaiminisBox. Why is this occuring & how can it be fixed?

**Comment by Tmp341** [comment]
> Sorry we aren't updating this as much, we're working on a better system so please bear with us! 
says Jon aimini's Box website. System change might affected it.
