### ISSUE TITLE
Tumangaonline

### ISSUE THREAD

**Issue by OldMartin** [riderkick/FMD#758]
Tumangaonline its not working and some other spanish manga sites but when i use english like manga fox everything its fine

**Comment by GATOQSECOMIO** [comment]
same problem

**Comment by kavin-90** [comment]
need to rewrite script for Tumangaonline

**Comment by kmvi** [comment]
Fixed in [latest release](https://github.com/riderkick/FMD/releases/tag/0.9.133.0), please check

**Comment by GATOQSECOMIO** [comment]
TumangaOnline works perfect (0.9.133.0)
thanks for update! @kmvi
