### ISSUE TITLE
Validate if the total filename length is less than 259

### ISSUE THREAD

**Issue by Nandaka** [riderkick/FMD#76]
As answered in here: http://stackoverflow.com/a/265782

I think you need to validate the saved filename length to 259 characters for Windows OS

I've encountered an issue with this manga: http://bato.to/comic/_/comics/infinite-stratos-infinite-stratos-book-direct-from-the-warehouse-artbook-r10886 
with chapter folder name set to ```%MANGA% %CHAPTER%```

tested with version 0.9.18.2

**Comment by riderkick** [comment]
Did you ever read the source?
There is a function CorrectPathSys(const Path: String): String; in uBaseUnit.pas
We use that function to validate path in downloadmanager.
