### ISSUE TITLE
Mangago update list doesn't work.

### ISSUE THREAD

**Issue by kaori8** [riderkick/FMD#768]
No matter how many times i click on the update list or restart or reinstall it doesn't. Just show that looking for titles but no new manga is added to the list. It has been like that for the last few months. I am using version 0.9.126.0
![untitled 2](https://user-images.githubusercontent.com/27344538/32135459-6f9c47d6-bc21-11e7-803c-41d4ef7c7c29.png)

**Comment by kavin-90** [comment]
1st it will check all pages and then start reading series info pages
