### ISSUE TITLE
[Solved] Need help setting up Batoto.

### ISSUE THREAD

**Issue by taigalover** [riderkick/FMD#770]
I know the advanced.ini file looks like this:

[UserAgent]
Batoto=Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0

[Cookies]
Batoto=member_id=; pass_hash=; rteStatus=rte; session_id=

But i dont know what the rteStatus is and what to put in it.
I know the memeber_id is something like this:1231244
And the pass_hash is something like this:123121323423545954958985
But also i dont know what the session_id looks like, because i get 2 session id when i open mozzila.

could really use some help in this

**Comment by taigalover** [comment]
Oh, i got it.

I had to login from inside FMD too, my bad.

**Comment by StormJumper** [comment]
You should change the title to "Solved" that would help redundant posting helps.

**Comment by taigalover** [comment]
Sorry, changed it.
