### ISSUE TITLE
MagaHere downloads failing.

### ISSUE THREAD

**Issue by Wolfpup67** [riderkick/FMD#775]
MangaHere has added an extra page to the chapters named featured and it is now causing the downloads to fail.
Here is an example link: http://www.mangahere.co/manga/world_s_end_harem/c031.2/featured.html
This extra page is nothing but an advertisement page.

**Comment by Genome17** [comment]
I give tips for now, while we wait for the updates
to resolve the error, you can try copying an image from your data or whatever and name it as the last page in the manga chapter's folder. ex: if previous page 001.jpg so you name the image 002.jpg

sorry for my bad english
![screenshot 92](https://user-images.githubusercontent.com/33371180/32404951-c06536aa-c19e-11e7-9253-bda659e9d3b1.png)
![screenshot 93](https://user-images.githubusercontent.com/33371180/32404952-c4003bc0-c19e-11e7-86e6-0f955dabb111.png)

**Comment by Wolfpup67** [comment]
The problem is that Manga Here has added an extra page to the chapters. 
For example if a chapter has 19 pages Manga here has it with 20 pages with 1-19 being the images while the last page dose not have any images but instead has items advertised on it.

**Comment by StormJumper** [comment]
Also seems like they are now blocking FMD downloads as well. I tried to update recently and it say "failed" on all updates and could be related to the extra page causing the fail download because the ads don't download.

**Comment by Genome17** [comment]
wait for update for easy, for now use my tips on above
![screenshot 96](https://user-images.githubusercontent.com/33371180/32470613-50d5f05e-c39c-11e7-9c2a-3ce9044a8d84.png)

**Comment by StormJumper** [comment]
That's easier said then done. Did you consider user of FMD have more then just one Manga series they download to read? You should consider that before thinking it's something that easy to do.

**Comment by kavin-90** [comment]
I checked source code and as people says fmd tries to download that last page (featured page) that is causing it so so 

`          PageNumber := XPath('(//span[@class="right"]/select)[1]/option').Count - 1; `

that code will solve it

**Comment by ralvarador** [comment]
Thanks for the new release.
The issue was fixed for Mangafox, but not for MangaTown.

**Comment by kmvi** [comment]
Fixed for mangatown d3c3a60
