### ISSUE TITLE
Cannot complete the task from mangatown

### ISSUE THREAD

**Issue by Hexaf** [riderkick/FMD#778]
My FMD cannot complete the task, it always check the chapter. I check the folder download and FMD download all pages, but FMD doesnt turn it to cbz.

**Comment by namaasliku** [comment]
i think it have the same issue with mangahere in issue   #775
someone there posted a trick to make the task completed by adding a picture then redownload, i just tried it and it worked

**Comment by Hexaf** [comment]
Alright, that trick works. Thanks

**Comment by codeduph** [comment]
I'm also having the same issue with "mangatown" can't complete the download.
