### ISSUE TITLE
Has anyone heard from riderkick or kaven90?

### ISSUE THREAD

**Issue by StormJumper** [riderkick/FMD#781]
It seems like this is another hiatus from previous again? I do hope we hear back from them about the project here and it it will continue on.

**Comment by Tmp341** [comment]
[riderkick](https://github.com/riderkick?tab=overview&from=2017-10-01&to=2017-10-31&utf8=%E2%9C%93)
It seems he hasn't made a move since august, but today he made 2 commits.

[kavin-90](https://github.com/kavin-90?tab=overview&from=2017-09-01&to=2017-09-30&utf8=%E2%9C%93)
Other than this, i don't if he writes comments around "Issues".

**Comment by StormJumper** [comment]
Same here this project I like from all others I tried I have one other paid that I keep in reserve that I use as well so hopefully this doesn't go the demise of domdomsoft of which I think was a very good manga downloader reader.

**Comment by kavin-90** [comment]
I'm busy in php programming.

**Comment by StormJumper** [comment]
@kavin-90, good to hear back because sites are some how changing the script or have setups to block FMD from getting manga downloads.

**Comment by StormJumper** [comment]
But back to my related question is there any updates on when FMD will be update since MangaHere uses ads at end of their manga to stop FMD from properly downloading the manga now?

**Comment by StormJumper** [comment]
@kavin-90 do you know if there is a time frame when FMD might get a update to the issues mentioned on the FMD forum?

**Comment by kavin-90** [comment]
hmm

First I'm trying to build FMD and getting error because of fp version change 😢 

after that i will think about time when new update will be released

**Comment by StormJumper** [comment]
@kavin-90 ok good to hear but sounds like I came late and people are having issue with kissmanga now.
