### ISSUE TITLE
Support for mangarock.com

### ISSUE THREAD

**Issue by crse** [riderkick/FMD#786]

**Comment by Liriel-666** [comment]
i would prefer that too

**Comment by Beylers** [comment]
please add this site

**Comment by kmvi** [comment]
Mangarock uses webp as image format. @riderkick, is it worth it to include webp decoder to the project? I couldn't find any implementations of webp decoder in Pascal so I wrote a simple one using [Google libwebp](https://github.com/webmproject/libwebp): kmvi/FMD@ccfed1a. It reads webp to TMemBitmap, which can be saved to png. But it's required to add libwebp.dll into the distro.

**Comment by kmvi** [comment]
Compiled libwebp 0.6.1: https://gist.github.com/kmvi/8e4fe1eca44d5a174512fc5f32da2970

**Comment by riderkick** [comment]
Yes, you can. You should make the library name global variable. We may change that at runtime.
