### ISSUE TITLE
Batoto don't show anything

### ISSUE THREAD

**Issue by KeithHanzhel** [riderkick/FMD#791]
I can open batoto in browser, but no chapter list in FMD. Mangahere and Mangastream works fine.
It's just me and my net connection?

**Comment by Tmp341** [comment]
Have you tried entering your batoto username and password?

**Comment by KeithHanzhel** [comment]
I found that my office's network is the problem.  It's blocked by cloudflare and need to enter the captcha before I can access batoto. But it worked fine before 0.9.127

**Comment by StormJumper** [comment]
Have you tried to enter batoto from the web to first to find out where the problem is coming from?

**Comment by KeithHanzhel** [comment]
"It's blocked by cloudflare and need to enter the captcha before I can access batoto." But now it's already return to normal again. Dunno what's happen though....

**Comment by kmvi** [comment]
Batoto is closed
