### ISSUE TITLE
Add new Scanlation sites and fix existing ones. See post details

### ISSUE THREAD

**Issue by Leguron** [riderkick/FMD#792]
Mangazuki changed their site layout and the fmd is not working anymore.
- [x] https://mangazuki.co/ 

I'd also like to be able to download the raws from Mangazuki. 
- [x] https://raws.mangazuki.co/

There is also a new interesting scanlation website called Psychoplay. From the looks of it it's running the same website Mangazuki used to have so adding it should be easy if you use the code from Mangazuki for it.

- [x] https://psychoplay.co/

The last website I'd like to see added is Manwha. 

- [ ] https://manhwa.co/

**Comment by Anvirol** [comment]
Thanks a lot of the added sites. Can we get the last one too? :)
https://manhwa.co/
