### ISSUE TITLE
Bato.to Cannot Get Manga Info (0.9.127.0 64bit)

### ISSUE THREAD

**Issue by ChronoVlad** [riderkick/FMD#796]
They seem to have updated their site or something because it was working fine earlier today also they seem to have some kind of script implemented that automatically bans IP addresses that uses automated programs such as FMD how do i prevent that?

**Comment by nille02** [comment]
Same on my Side, maybe its because of the DDoS Protection from Cloudflare.

**Comment by forvy** [comment]
Apparently, it was their update? Since I used 0.9.126.0 same result.

**Comment by Tmp341** [comment]
It is ok on browser but when tried to open on fmd, it says there is a problem with my connection. Even though i can fully access to internet and other sites via fmd.

**Comment by SDXC** [comment]
bato is actually being DDoS'ed right now, so they had to put on cloudflare.
https://twitter.com/BatotoStatus/status/935113583960064000

**Comment by nille02** [comment]
i guess this can be closed now, the DDoS is over and fmd is working again.
