### ISSUE TITLE
H2R - Update Manga List not working.

### ISSUE THREAD

**Issue by GitSaur** [riderkick/FMD#799]
I was wondering if you could fix the Update Manga List for Hentai2Read.com.

It hasn't been working for quite some time but since you've pushed an update recently, can it be updated?

Great app btw, even the paid ones can't be compared to this one. Thanks!

**Comment by Tmp341** [comment]
It is updated over here. I forced "update list" on my end, it worked.

**Comment by GitSaur** [comment]
You sure you're getting everything? Check the site itself and check if the last added title is in FMD. 

I've been trying it on my PC and laptop (redownloaded as well) and they both don't fetch the newest chapters. Like it'll progress bars moves a bit and complete faster than expected but none of the new ones are there. My list has 13,632 titles but there's a lot more than that on the site now.

**Comment by kmvi** [comment]
Manga list has been updated on server, also see explanation [here](https://github.com/riderkick/FMD/issues/910#issuecomment-364736122)
