### ISSUE TITLE
bug, oversight, or me being bad at stuff.

### ISSUE THREAD

**Issue by MammothJerk** [riderkick/FMD#8]
![Image](http://puu.sh/hlF5z/3d6ee726b6.png)

when right clicking downloaded manga and then clicking open... even with a reader set up in the options > general > external program it doesn't do anything

C:\Program Files\Honeyview\Honeyview.exe "%PATH%%FCHAPTER%"

that is the correct path for the reader, correct? it works when clicking open... from the favorites tab.

would save a lot of trouble if just right clicking the downloaded manga and selecting open to read said downloaded chapter was possible =)

**Comment by riderkick** [comment]
Please use this:
C:\Program Files\Honeyview\Honeyview.exe  "%PATH%\%FCHAPTER%"

**Comment by MammothJerk** [comment]
that didnt change anything =(

using open... on favorites works the same as before aswell

**Comment by riderkick** [comment]
"Open" on favorites using the same method with download list. Do you mean "Open" on favorites work but not on download list?
I'm using portable honeyview and it's work. FMD will look for the first file inside %PATH% to fill %FCHAPTER%.

I'll try to add %FDCHAPTER% for fist downloaded chapter if possible.

**Comment by MammothJerk** [comment]
Open... DOES NOT work on downloads
Open... DOES work on favorites

it seems the external program only updates after restartingthe application so i did some more tests
with
C:\Program Files\Honeyview\Honeyview.exe "%PATH%\%FCHAPTER%"
NEITHER works

C:\Program Files\Honeyview\Honeyview.exe "%PATH%%FCHAPTER%"
ONLY favorites work

C:\Program Files\Honeyview\Honeyview.exe "%PATH%/%FCHAPTER%"
ONLY favorites work

Downloads tab doesnt seem to work at all with either of these

**Comment by riderkick** [comment]
Oh yeah. There is a bug. Should be fixed with this commit https://github.com/riderkick/FMD/commit/dec4025090ef8b0f69fcc36d5c147fbb3b495d42

**Comment by riderkick** [comment]
I change the value for %FCHAPTER% with first downloaded chapter if it exists. Otherwise it will looking for the first file/folder in download directory. Refer to this commit https://github.com/riderkick/FMD/commit/6a6d71840fa4f6b63923446a211df8aa3da8f16d
