### ISSUE TITLE
[Request] Batoto favorites "import"

### ISSUE THREAD

**Issue by MammothJerk** [riderkick/FMD#80]
Is it possible to somehow import all of my bato.to favorites into fmd?

at https://bato.to/myfollows it shows the latest 10 or so releases from manga that you follow. if you scroll down there is a list from #-Z of all of your favorites with their name and their page hyperlinked.

![](http://puu.sh/jeF5N/730da498cb.png)

from my basic experience it seems that a script could do this but i have no idea how to create such a thing

again, thanks for the great application =)

**Comment by riderkick** [comment]
You can try to add to favorites using drop box, `Options>View>Show Drop Box` and `Mode>Add to favorites`.
And drop the link to this box that show up.
But unfortunately, currently we only support single link.
I'll try get the HTML source to parse the links.

**Comment by MammothJerk** [comment]
i have about 950 favorites on batoto so i would reather not add them one by one :D

**Comment by riderkick** [comment]
With the latest version you can select all of them on your browser and drag it to drop box, it will load all of them.

**Comment by MammothJerk** [comment]
on firefox I cannot add even one URL now, it just shows the circle with a line through when hovering the url over the box.

in chrome i can still add one by one but i cannot do many. when i focus many it still shows that it works but none of the manga show up in the favorites.

I'm not sure if i'm doing this right?

should i left click and drag over the links and then drag the focused links to the drop box? am i supposed to download the links somehow?

i made a quick webm showing the problem since im very bad at explaining
![](http://puu.sh/jgnIy/1454d7e226.webm]

**Comment by riderkick** [comment]
It will not immediately appear on favorites, we need to load this page first and check the current chapters as starting point, just like how you add to favorites via manga list. There will be loading status on status bar.

**Comment by riderkick** [comment]
There is bug on drop box, which lead to range check error. Does it not appear on you?
I just fix it.

**Comment by riderkick** [comment]
It should be look like this.
http://i.minus.com/iMT8ANOBZg7Oe.gif
Yes, ba to to is slow here.

**Comment by MammothJerk** [comment]
It now works on firefox, great :+1: 

multiple links now works on firefox but does NOT work on chrome


the default "Save to" location on favorited manga using drop box is the default download path even if the "Auto generate folder based on manga's name" box is checked. 
When downloading it does create it's own folder even though the "Save to" says E:\Manga\ (in my case). would be nice if it indicated its own folder even in the "Save to" as it does when adding favorites normally.

again thanks for the great work =)

**Comment by riderkick** [comment]
That sound like a bug.

**Comment by MammothJerk** [comment]
![](http://puu.sh/ji6VW/8d373fc46e.png)
![](http://puu.sh/ji6X8/82c7b2fcf7.png)
