### ISSUE TITLE
Problem with Batoto, Mangasee, Jaimini's Box.

### ISSUE THREAD

**Issue by nsnasa21** [riderkick/FMD#800]
Can't load manga from these sites. Turns up empty.

**Comment by wuhugm** [comment]
Jamini's Box gives error 666 for downloaded manga

It replaces all images downloaded with error page against crawlers

**Comment by nsnasa21** [comment]
![001](https://user-images.githubusercontent.com/28336158/33805736-c81a0e10-dde7-11e7-8d34-fa443afdf288.jpg)

**Comment by kmvi** [comment]
Fixed in 0.9.130.0 release
