### ISSUE TITLE
Issue with old favorites

### ISSUE THREAD

**Issue by 1aam2am1** [riderkick/FMD#802]
Old favorites when moved to database. Have problem with:
- websitelink
- link

This causes problem that when we click on favorites and "view manga info" we see manga as if is in favorites. But if we search this manga and then click. Then it isn't in our favorites.
Example (error in database):
mangafoxhttp://mangafox.me/manga/... insted of mangafox/manga/...
http://mangafox.me/manga/... insted of /manga/...

The same problem exist in downloadedchapters.db file to.

Solution:
UPDATE downloadedchapters SET websitelink = REPLACE(websitelink, 'http://mangafox.me', '') WHERE websitelink LIKE '%http://mangafox.me%';

UPDATE favorites SET websitelink = REPLACE(websitelink, 'http://mangafox.me', '') WHERE websitelink LIKE '%http://mangafox.me%';

UPDATE favorites SET link = REPLACE(link, 'http://mangafox.me', '') WHERE link LIKE '%http://mangafox.me%';

UPDATE downloads SET link = REPLACE(link, 'http://mangafox.me', '') WHERE link LIKE '%http://mangafox.me%';

**Comment by Leguron** [comment]
Is that the solution for the creators of fmd or is that something the users are supposed to do? I don't know where I as a user can make these changes.

**Comment by 1aam2am1** [comment]
To users:

I did this changes on:
https://sqliteonline.com/
site. When opened proper DB.

To creators this should be done once to each DB. Because this is error in import of old favorites.

PS. I only use mangafox.me therefore I don't know, if similar error exist for another website.
And this should also be done to other records, witch changing the sql query.
