### ISSUE TITLE
Volume number not being added to filename

### ISSUE THREAD

**Issue by Xilhion** [riderkick/FMD#804]
Hi,
First of all, big thanks for the awesome work. Everything works great except for one small thing:
I'd like to have the volume number of the chapter on the filename but although i've played a lot with the settings, i can't seem to have it working. 

Here are the settings i currently set that looks ok to me : 
![2017-12-04 11_01_38-fmd](https://user-images.githubusercontent.com/1412543/33547467-6fb8884e-d8e4-11e7-9078-6d8a24a74e0c.png)

But here is the naming that this generate (chapter on 4 digit and no volume number) : 
![2017-12-04 11_13_34-win16 - teamviewer](https://user-images.githubusercontent.com/1412543/33547516-976aa142-d8e4-11e7-9a34-be7cb788ef40.png)

Is there something i'm doing/expecting wrong ?

**Comment by Suddow** [comment]
Volume numbers aren't tracked, you'd have to add them manually.  Numbering refers to the index number in FMD.
