### ISSUE TITLE
Anyone have a problem with Tumangaonline?

### ISSUE THREAD

**Issue by Juanitocancino** [riderkick/FMD#806]
I checked the source in the program says that have X chapters, but when charges the manga info dont show anything and marks that the manga have 0 chapters

**Comment by kavin-90** [comment]
they changed whole site to javascript that is why it is show no info

**Comment by kmvi** [comment]
Fixed in [latest release](https://github.com/riderkick/FMD/releases/tag/0.9.133.0), please check
