### ISSUE TITLE
0 Bytes Batoto Downloads

### ISSUE THREAD

**Issue by wuhugm** [riderkick/FMD#808]
Chapters downloaded resulted in 0 or 1 Bytes files

The number of pages is correct but all just blank image files

**Comment by muto4013** [comment]
seems no update or fix is necessary, batoto is closing down

**Comment by Tmp341** [comment]
Batoto's other staff backing up mangas, probably batotov2 or something might show up.

**Comment by muto4013** [comment]
yep, but that would be a NEW site, which would need some new parsing. 

Maybe also interesting in this matter; batoto has switched again to cloudflare anti-ddos protection, so FMD will have some problems to see batoto content.

**Comment by wuhugm** [comment]
Aww shucks...
