### ISSUE TITLE
Anyone have a problem with mangazuki?

### ISSUE THREAD

**Issue by xavi0ur** [riderkick/FMD#810]
hi. i tried to open mangazuki, but FMD not showing anything. 
maybe because mangazuki change the site?
i tried to enter the new address of mangazuki but still not showing anything.

thanks

**Comment by Hexaf** [comment]
because mangazuki change the address. When FMD want to catch mangalist the address from FMD is "https://mangazuki.co/series/Brawling-Go" but the actual from mangazuki is "https://mangazuki.co/manga/brawling-go"

**Comment by ralvarador** [comment]
Also, it has changed their webpage desing and disappear a lot of series from their webpage... before they change their domain - if you put a mangazuki URL, the FMD wasn't able to read the information of the series (the manga information tab appear emtpy)
