### ISSUE TITLE
MangaHere down??

### ISSUE THREAD

**Issue by StormJumper** [riderkick/FMD#812]
Does anyone else know if this site if down or what happened to it?

**Comment by LeahDizon** [comment]
can't access it from browser? or with FMD? i can access it from browser but can't from FMD, maybe because it changed from mangahere.co to mangahere.cc

**Comment by ralvarador** [comment]
Well... today when I tried to add any mangahere(.cc) URL to FMD receive error message; but then mofiying it yo .co, the FDM still was capable to read and download manga series / chapters... but don't know how much time it still will work.
