### ISSUE TITLE
Download error - Mangago

### ISSUE THREAD

**Issue by leoteesh** [riderkick/FMD#813]
Hi
There are some mangas which are not downloading from Mangago. they are working properly on  the website. Is there any chance you can look into? Many thanks
![image](https://user-images.githubusercontent.com/21075197/34295492-8d26e61c-e705-11e7-8dbc-8be1bd271002.png)

**Comment by Tmp341** [comment]
Same here. Here is a little info:

Typed mangago on browser, a cloudflare page welcomed me. Then I've tried opening one of my mangas. Opened last uploaded page. Then something funny happened. It opened on a seperate tab and url contains "mnggo.net/article/tobacco-agreements,xxxx.html".

**Comment by SakuraDeplume** [comment]
same! tho this problem has been going on for months already but i just kinda ignored it n there are other sites i could use until more site were starting to have similar issues. 

so i hoped mangago could be fixed soon. Thanks

**Comment by madorenji** [comment]
oh my god, same here.. this happened before but it was fixed after i updated my mangago list and it's at it again but still not working normal.. this just started yesterday, I've been updating mangago server on the list multiple times, restarting PC etc ;; _ ;;
i even cleaned my completed list (hoping it helps lol) but nothing.
tho i tried downloading random manga on mangago list and they worked fine but to my bookmarked mangas that supposedly ready to download updates is not working and keep on failing to download the data(and all of them are working on the mangago site, not deleted or missed the chapters).. and i think i already had the latest version. Please Help us, masters!
![image](https://user-images.githubusercontent.com/34802355/34323640-fa12a322-e88d-11e7-90ac-2c8139fdb259.png)

**Comment by jmira965** [comment]
Hi guys,
Recently, mangago.me may have gone through some changes regarding security. So, I found that the only those mangas or a chapter that has been added in 2017 are not being downloaded. I found two instances, where in same manga the chapters that were added in till 2016 are downloaded, but those added in 2017 are not downloaded. It could be due to some manhwa issues this month. Its possible they did something, which doesnt let the app access the chapters added in 2017. Can someone else confirm this, too? Try downloading manga which have older mangas.

**Comment by SakuraDeplume** [comment]
oh you're right i tried downloading a 2011 manga n it works just fine

**Comment by madorenji** [comment]
you are right, i download a 2015 manga and did work but the 2017 manga just
fails again...

**Comment by leoteesh** [comment]
yes, got the same issue

**Comment by jmira965** [comment]
For me, I had download my last manga that was added in 2017 on 20th of this month, without an issue. that means something may have changed after that date. Also, I once tried to open the site with vpn on,(US ip address), it the site didn't open. There may have been some security changes in mangogo.me if anyone was in the site around 5th or 6th of the month you may know, it has to do with manhwas from a certain site. 
Also, for some people who have issues with opening manga and being redirected to a random site, you have to sign in to read the manga without being redirected.

**Comment by leoteesh** [comment]
hi - sorry could you please advise if this is sorted?
many thanks

**Comment by jmira965** [comment]
Same here.

**Comment by madorenji** [comment]
this shouldn't be closed until this is solved...

**Comment by ralvarador** [comment]
Hey... check that they made some changes in the code (closed); build it yourself or wait 'till "they do us the favor" and share the release / commit

**Comment by jmira965** [comment]
Thank a lot for fixing it in search a short notice!
 Although no possible at the moment, I would definitely try to support you through donation, I did see something like "Support the developer" somewhere, but, I cant find it now, I would be grateful, if anyone can tell me how.
