### ISSUE TITLE
Kissmanga partially broken?

### ISSUE THREAD

**Issue by Leguron** [riderkick/FMD#815]
Whenever I download a whole series from kissmanga it's downloading everything but skipping some chapter.

Restarting it a lot is getting you some additional chapters downloaded but there are still some that can be read on the website but that can't be downloaded.

**Comment by feelingwalnut** [comment]
try using the "read online" button in the manga info page to confirm that it is not an issue with the manga site itself.
recently i had to notify a site that several chapters online were non functional, they corrected the error and then the download worked fine.

**Comment by Suddow** [comment]
I am also having issues with KM, but the download won't even start.  It just cycles each chapter and 'fails' immediately.  Here's a paste from the log:  https://pastebin.com/53aaUH0s

I've tried updating the key and IV, still didn't make a difference.  It was working just 2 days ago.
