### ISSUE TITLE
Remove websites that stopped existing. See list below.

### ISSUE THREAD

**Issue by Leguron** [riderkick/FMD#817]
AnimeA
EatManga
EyeOnManga
HeyManga
KivManga
Madokami
MangaCool
MangaIce
MangaLife
MangaSpy
MangaStreamTo
UnixManga
ReadComics
MeinManga
Comic-XXX

**Comment by muto4013** [comment]
as a workaround you could edit the file mangalist.ini in fmd\config

**Comment by Meliodas-Sama** [comment]
I don't know about the rest but Madokami is working and it's not down.

**Comment by kmvi** [comment]
--> #891
