### ISSUE TITLE
Can't update to latest version

### ISSUE THREAD

**Issue by alvarexoz** [riderkick/FMD#818]
Hello, riderkick. I have reinstalling FMD from earlier version (0.8.2b), but i can't get through up to date latest version. Do you have latest version of this application? Please, help me

**Comment by alvarexoz** [comment]
![stuck fmd](https://user-images.githubusercontent.com/17180171/34452107-88534c6e-ed6a-11e7-9d4b-0ece0ffbf666.PNG)
Get stuck and never updating

**Comment by zackad** [comment]
the latest version can be found here
https://github.com/riderkick/FMD/releases

just download the latest release and extract.
