### ISSUE TITLE
Need info about recent project status

### ISSUE THREAD

**Issue by Tmp341** [riderkick/FMD#819]
Hello. I've started using this after Domdomsoft was dead. This project was (and still is) indeed a life saver. I was using online reading scripts but not all those websites contains what i'm looking for. So, i gotta check Site A for manga X and site B for manga Y etc. But like domdomsoft, fmd came to my rescue. After a couple of clicks, i can read them offline. I can even send them to my phone, read there without considering internet. Because of how i like this app, I even started translating for my local language.

But starting from a couple of months ago, @riderkick, @kavin-90 and other contributors began slowly working on it. Now there are dozens of websites changed and they haven't been corrected.

I think project managers are having real life issues and this project's status going for "discontinued".

Don't get me wrong but all those users need an explanation about what is going on and what isn't. Either we have to start looking for other apps or sit on where we are and wait.

I hope you understand these words aren't criticism. They're just curiosity.

Regards.

**Comment by subnighter** [comment]
Poking around this website might help to see what's going on with this project. See, for example, [commits](https://github.com/riderkick/FMD/commits/master). Another thing is that manga site owners might be trying to break automatization of downloads.

**Comment by Tmp341** [comment]
@subnighter I know that page but I was asking for a statement, thats all.
