### ISSUE TITLE
NineMangaDe downloads allways the same picture

### ISSUE THREAD

**Issue by morula** [riderkick/FMD#821]
NineMangaDE (-> OnePiece) downloads allways the same picture.

![003](https://user-images.githubusercontent.com/7601076/34489848-12ae5492-efde-11e7-94dc-87da2e04f503.jpg)

**Comment by Tmp341** [comment]
Doing that to all mangas. After i finished downloading, i've checked their site again. Opened via history, and i saw this pic again. But when i searched another manga, opened it properly.

I couldn't be able to track which website is using fmd for downloading these, but ninemanga is using :

https://img.wiemanga.com/comics/pic/45/301/193649/Band8Kapitel61501_0.jpg

**Comment by elwallyhdez** [comment]
NineMangaES. always the same picture
![001](https://user-images.githubusercontent.com/11392845/34586941-2ddfe324-f174-11e7-8368-a84d2d9c804c.jpg)
