### ISSUE TITLE
[Request] H-Sites Database Files

### ISSUE THREAD

**Issue by shikitemeikato** [riderkick/FMD#822]
If anyone Having Database Files Completed Updated Like
HentaiCafe
HitomiLa
Tsumino
Nhentai Or
e-Hentai 

Can u Share The Files ? Upload then to MEGA or GoogleDrive or anywebhosting  ... Please 
Thanks For Help

**Comment by renzocroas** [comment]
can request add on "Kissdoujin.com"?

**Comment by Tmp341** [comment]
I think all those datas on server should be updated.
