### ISSUE TITLE
MangaFox changes

### ISSUE THREAD

**Issue by CodeKatta** [riderkick/FMD#823]
It seems there has been a major change with MangaFox, i.e. the URL changed from 'mangafox.la' to 'mangafox.fun' and the website has a new design. Apparently they also switched from underscores '_' to hyphens '-' on the new site (.../manga/manga_name -> .../manga/manga-name).

The old site (.la) still exists but is no longer updated.

**Comment by greenaar** [comment]
I'd wondered what was going on, that's the second domain migration in the last month :\

**Comment by riderkick** [comment]
mangafox.la is still updating. I think mangafox.fun is entirely different website. It's similar to mangatown/mangacap?

**Comment by kmvi** [comment]
It's identical to https://mangahub.io/

**Comment by H4nZ83** [comment]
now the fanfox.net was not mangafox itself, it just open mangazone.com

**Comment by H4nZ83** [comment]
ups sorry, i just noticed that the default chrome browser redirect it to mangazone.com when i opened fanfox.net
but when i'm using proxy it would open the fanfox.net..
sorry for the miss information i give earlier
