### ISSUE TITLE
Mangago Downloads error again? 

### ISSUE THREAD

**Issue by Sakurahime08** [riderkick/FMD#824]
Hope you can fix! Thanks!

**Comment by Tmp341** [comment]
Failed here so i checked. It redirected me to a new website:
Tried: 
www.mangago.me/read-manga/kekkon_yubiwa_monogatari/mf/c034/pg-1/

Redirected:
http://www.fashionlib.net/article/wet-hair-instructions-for-use,1684.html

Tried opening that manga with browsing through website, and got this:
http://www.fashionlib.net/article/fall-winter-2017-2018-trends-short-cuts,91.html

Trying to block manga readers/downloaders? Or am i hacked?

**Comment by Sakurahime08** [comment]
It's usually like this when you're not signed in to the website. Maybe authorization should be added?

**Comment by leoteesh** [comment]
Having the same problem as well :(

**Comment by joewono2011** [comment]
i was signed in
but i was redirected as well >.<

maybe sign in  or not are not main problem in this case

Sorry for my bad english

**Comment by yuuno43** [comment]
Also having similar/same issues.

**Comment by leoteesh** [comment]
anyone else having trouble accessing mango website? i have no idea what to do..help anyone?
![image](https://user-images.githubusercontent.com/21075197/34792495-16d8aac8-f640-11e7-81cb-817c55cb2464.png)

**Comment by ronny1982** [comment]
MangaGo is banning all IPs that made requests to the chapter pages that does not met certain criteria. Since FMD does not met the criteria your IP will be banned as soon as you try to access a chapter from MangaGo. For the time being do not access MangaGo to prevent your IP from being banned.

If i have to guess what this criteria might be that gets you banned, i would suspect a HTTP header (e.g. host, referer, ...) that gets fooled by the redirect, but haven't investigated to much yet.

**Comment by leoteesh** [comment]
Thanks for the clarification. this is so disappointing. any reasons why they are doing this and how idea on how to rectify this? sorry i really don't know what to do! thanks again

**Comment by madorenji** [comment]
after the update version 0.9.129.0, mangago works perfect again (gladly, i had 50+ manga updated) but after a day i can't download chpters from mangago again ;; _ ;; 
thank you so much for working hard fixing every issues, i hope you can solve this again. I'll patiently wait~

**Comment by ronny1982** [comment]
I found another clue: Maybe the URL `http://<REDIRECTED-HOST>/ywz.ico` must be called before each request to prevent your IP from being banned...

`
<iframe id="cristree" style="width:1px;height:1px;overflow:hidden;" frameborder="no" src="/ywz.ico"></iframe>
<script>
	setInterval( function() {
		document.getElementById( "cristree" ).src = "/ywz.ico";
	}, 6000 );
</script>
`

**Comment by Sakurahime08** [comment]
Will your IP get banned from just checking your bookmarks?

**Comment by alexandriatale** [comment]
What does it mean by "Maybe the URL http://<REDIRECTED-HOST>/ywz.ico must be called before each request"? I tried to open the URL site but it redirect me to google..

**Comment by Anvirol** [comment]
Downloads are working for me, but looks like the site is scrambling some of the pages: 
![image](https://user-images.githubusercontent.com/3955313/35003023-2f155a2e-faf4-11e7-8da4-5bd363b40af7.png)

**Comment by ronny1982** [comment]
Which manga(s)/chapter(s) are using this obfuscation?

**Comment by leoteesh** [comment]
nothing is working for me. Error messages comes up and if i use FMD, my ip gets banned from mangago

**Comment by madorenji** [comment]
same with me
![002](https://user-images.githubusercontent.com/34802355/35028576-bfb857d2-fb91-11e7-8a3b-536d4bf26079.jpg)

**Comment by alexandriatale** [comment]
same with me. this is ookami-heika no hanayome manga chapter 60. some pages are scrambled like this, some are normal.
![005](https://user-images.githubusercontent.com/33077478/35043187-3b55c1a0-fbbe-11e7-9d99-23f79af23631.jpg)

**Comment by Tmp341** [comment]
How is this possible, technically?

**Comment by ronny1982** [comment]
The scrambled image is just a bait, the real image urls are encrypted now with javascript. The encryption script is obfuscated, but still easy to understand ;)

I wonder when they will render the image on a canvas...

**Comment by alexandriatale** [comment]
Btw, now I cannot download from mangago again. But I didn't get banned because I still can open the website and read online..

**Comment by leoteesh** [comment]
yes, same for me. my ip address didn't get banned! but no download

**Comment by ronny1982** [comment]
FMD uses hardcoded decryption key and iv, but the mangago javascript has dynamic generated encryption key and iv which change regulary
=> not working anymore

**Comment by Tmp341** [comment]
Same here.

**Comment by leoteesh** [comment]
Sorry, was there any luck regarding this?

**Comment by Sakurahime08** [comment]
any news?

**Comment by Tmp341** [comment]
Nope. Still no luck. Even vpn wouldn't be able to solve it.

**Comment by riderkick** [comment]
Does it still fail with recent changes? [fmd-win32.7z.txt](https://github.com/riderkick/FMD/files/1697608/fmd-win32.7z.txt)

**Comment by alexandriatale** [comment]
still cannot download on 0.9.132.0 ver

**Comment by Tmp341** [comment]
@riderkick Got lua53.dll error with yours, even tried with w32 files. But i can run released w32 version on w64.

![ss](https://user-images.githubusercontent.com/1683388/35848051-a83f42ae-0b2d-11e8-90c0-331bda8fb4ec.jpg)

Warning is in Turkish, says something like: Code running can't continue because lua53.dll couldn't be found. Reinstalling app might be able to solve problem.

**Comment by jmira965** [comment]
Mangago has even blocked screenshoting or even ability to save individual image. Chapter pages are undetectable by any browser extension, but u can detect everything else. For example, image to pdf, where the extension detects the images and converts them to a single pdf file, but the latest updated chapters cannot be saved that way anymore.That goes for anything posted in feb 2018.

**Comment by kmvi** [comment]
@Tmp341 https://github.com/riderkick/FMD/files/1696157/luadll.7z.txt

**Comment by Tmp341** [comment]
@kmvi Used 32bit lua53 and it worked. And tested a Mangago manga, finished download. Checked manga and looks like everything ok. But why fmd runs through a command window? Because i'm running it on w64?

**Comment by riderkick** [comment]
@Tmp341 That's a developer build. compiled with stdout and heaptrc active. Sometimes I attach those build for testing purpose only.

**Comment by alexandriatale** [comment]
I tried to open using the one you've uploaded here but I got this error.. I copied my current sqlite3.dll but it doesn't work.. what to do? btw, I'm using 32bit lua53.dll

![fmd error](https://user-images.githubusercontent.com/33077478/35922380-05ebada2-0c50-11e8-8b44-07eb4be4b491.png)

**Comment by alexandriatale** [comment]
Also, I was about to update my current fmd but I got error message like this. What happened?

![fmd error](https://user-images.githubusercontent.com/33077478/35922717-d88abbae-0c50-11e8-9d09-88a0f9e5843e.jpg)
