### ISSUE TITLE
Can not load SQLite client library "...". Check your installation

### ISSUE THREAD

**Issue by Erramyne** [riderkick/FMD#825]
Ran into this issue quite some time ago, thought it would go away with reboots/redownloading FMD but it doesn't. I think I had this issue before formatting my laptop too so it's probably not related my config, I haven't always had this error though.
Every time I reboot the laptop, I get this error:
https://i.imgur.com/FGUhnO4.png
Clicking Terminate closes the program, opening it again doesn't produce any errors.
Also, I have FMD on Task Scheduler to open at "log on of any user" with highest privileges. Reopening FMD as administrator doesn't produce the error either, so I don't think "with highest privileges" is the cause.

The error on the image as text:
> 
> Unhandled exception!
> Application       : Free Manga Downloader
> Version           : 0.9.129.0
> Product Version   : Win64 Debug
> Host Machine      : Windows 10 64-bit
> FPC Version       : 3.0.4
> LCL Version       : 1.9.0.0
> WidgetSet         : Win32/Win64
> Target CPU-OS     : x86_64-Win64
> Build Time        : 2018/01/02 04:57:45
> Path              : D:\Tech\Desktop\Software\Portable\FMD\fmd.exe
> Process ID        : 7276
> MainThread ID     : 7280
> Thread ID         : 7280
> Time              : 07-01-2018 03:08:43.813
> Exception Class   : EInOutError
> Message           : Can not load SQLite client library "C:\Windows\system32\sqlite3.dll". Check your installation.
>   $00000001000392CE
>   $0000000100346A39
>   $0000000100360D6B
>   $0000000100361D67
>   $000000010034C80F
>   $0000000100348EBF
>   $000000010034E695
>   $000000010034EC21
>   $000000010035231B
>   $0000000100352F7F
>   $0000000100353350
>   $000000010034E57C
>   $0000000100355109
>   $0000000100458C8A line 106 of ../baseunits/DownloadsDB.pas
>   $000000010033C24C line 1594 of ../baseunits/uDownloadsManager.pas
>   $00000001000709B6 line 1104 of forms/frmMain.pas
>   $0000000100020D91

**Comment by 0xh3LL0** [comment]
thats odd, sqlite3.dll should be available on FMD directory, and FMD should load it from there instead, since i'm using win xp, and there is no sqlite3.dll on my system32, and FMD run just fine...
how about copy the sqlite3.dll from FMD directory to system32 manually?
let us know if that works...

**Comment by Erramyne** [comment]
Copying sqlite3.dll from the FMD directory to system32 manually did fix it, I'm not sure why it wasn't there on the first place though? I've never touched the Windows folder as a whole. Thanks a lot!

**Comment by Erramyne** [comment]
Never-mind, I still ran into some other issues. I thought that it was running as administrator that might've caused everything so I disabled the FMD task scheduler entry, rebooted and ran FMD again as administrator manually and I didn't have any problems. So yeah, I think there's something about task scheduler that triggers the problem I'm not sure what it is so I'll just put a shortcut in the startup folder instead of an entry in task scheduler. Thanks a lot regardless.

**Comment by ralvarador** [comment]
Today I got this error but when launching the FDM trhough a "Customized Windows Toolbar".
Launching FDM.exe trhough the Toolbar raise the error.
Then creating a "Windows Shortcut" of the FDM.exe (which store the full-path of the EXE in the field "Start in"), and launching the app with the Shortcut - works, even executing it "As Administrator".

Looks like a "PATH" Environment issue... try launching not the .EXE but the .LNK in the "Task Scheduler Entry"

![image](https://user-images.githubusercontent.com/30580377/35047008-aa056054-fb66-11e7-9906-b98c4c74d160.png)

**Comment by riderkick** [comment]
This is because you have incorrect bitness of sqlite dll. If you make a shortcut of fmd without the correct "Star in" directory, then the system will assume it to start from system32 which may contains sqlite dll from different installations of apps with different bitness.
