### ISSUE TITLE
Transferring Bookmarks/Favorites to other manga sites

### ISSUE THREAD

**Issue by wuhugm** [riderkick/FMD#826]
As you guys know, Bato.to is closing down

Now, all my Bookmarks/Favorites is for Bato.to

There are a thousand mangas in there

It's impossible to manually re-bookmark each one of them to other sites

Is it possible just to have the entire list change their manga site?

Or
Since Domdom has this feature
Can't we export the favorites into Domdom (In FMD we can only import from Domdom, it seems?)
Change manga sites
Then re-import back to FMD?

Man... Bato.to's end is the worst news of 2018

**Comment by spamtaztik** [comment]
I second this. While I don't use Bato.to much, the absence of this feature from FMD had forced me to re-bookmark my mangas from the sites that have died in the past. Any way of adding this to FMD?

**Comment by wuhugm** [comment]
^Indeed

Hoping for Bato.to v2 but slim chance...

**Comment by R-Jimenez** [comment]
Would likewise love to see this. I don't care if the progress/downloaded status of the chapters is lost, I just won't muster the willpower to move the ~900 series I have bookmarked on bato.to.

Would be nice to see something similar to what DomDom has, as mentioned above.

**Comment by Tmp341** [comment]
I'm supporting this too. Because sometimes a site changes something, so all i have is "failed" error.

**Comment by Beylers** [comment]
Would also love to have this feature

**Comment by muto4013** [comment]
a quick workaround:
if you know which sites has your mangas you could export the bookmark into csv or text via sqlite command line, edit the file in an texteditor and reimport / recreate the database file with the modified file

**Comment by wuhugm** [comment]
@muto4013 Please teach us how to do that in detailed instructions bro! Thanks!

**Comment by Tmp341** [comment]
@muto4013 But we have to enter other site's manga link too. I've checked and there were 5 rows (actually 9 of them but 4 doesn't need to change), 42 lines (my 42 mangas on batoto). That means i have 210 things to change.

**Comment by muto4013** [comment]
ok, from memory, don't kill me if i miss a step :) Here the most simple version for windows, should work also in other OS: save your fmd\works folder to another location (safety), download the sqlite tools from sqlite.org, extract to fmd\works. In the next steps omit the quotation marks: start cmd in works, execute "sqlite3 favorites.db" now type in sqlite shell " .output new.sql" ".dump" ".exit" (there is a point in front of the commands). Now open the new.sql file in an editor and replace "batoto" with the new mangasite name. The names are found in config\mangalist.ini in case you didn't know what to type. BTW: The side MUST be active and have your preferred mangas.  Safe the sql file, delete the favorites.db and execute the following: "sqlite3 -init new.sql favorites.db "" " Empty string "" is needed for sqlite3 to quit automatically.
If you start FMD all Batoto entrys should be replaced with your new link.
This procedure is not foul proof, e.g if the manga doesn't exist in the new site, you get some errors.
hope this helps a little bit until a better solution.

**Comment by muto4013** [comment]
@Tmp341 : sorry, i didn't understand your post, could you please rephrase ? 
Because in the database there are only 2 columns to change, websitelink and website.
if you meant your 42 batoto mangas are on several different sites, well that's a little bit more complicated.

**Comment by wuhugm** [comment]
@muto4013 Gonna try it after sleep, thanks bro! 
Any suggestion which site to transfer to for now?
Mangahere probably has all what bato.to had, but the quality is kinda...

**Comment by Tmp341** [comment]
@muto4013 Here is what i'm saying:
I've opened it with a database editor.
![SS](https://user-images.githubusercontent.com/1683388/34874116-d022f7c2-f7a8-11e7-8ac7-70ae51d2b9ad.jpg)


We have to change "websitelink", from "batoto/comic/_/comics/black-kanojo-r18922" to "kissmanga/xxx/yyy/zzz". Am i wrong? Then i have to change others like that. If i change those one by one, that makes 210.

**Comment by muto4013** [comment]
@Tmp341  Big thanks, i discovered a real big mistake in my approach. I did the replace with mangasee and mangabackup it was working fine but i didn't notice the difference in other sites like kissmanga and others since i normally don't use them.
example: in "link" the entry for mangasee would be "/manga/kuro-no-souzou-shoukanshi-tenseisha-no-hangyaku" like in batoto but in goodmanga it would be "/18520/kuro-no-souzou-shoukanshi-tenseisha-no-hangyaku" Also downloadedchapterlist differs extreme 

I didn't notice earlier so sorry to all : **MY SOLUTION DOESN''T WORK**

I will try find a better solution but don't know yet if a simple approach would be possible :(

**Comment by Tmp341** [comment]
Actually there are two solutions.

1. You have to change everything manually. If you're crazy enough, you can do it but i don't know anything about how that "downloadedchapter" changes.

2. An automated process needed. Either it checks your manga site datas, compare them, then changes them inside your favorites database. Or it checks those manga sites online, confirms mangas then changes your old ones with the new ones. Both of them in this 2nd solution needs an expert.

So, both solutions are bad for normal FMD users.

**Comment by muto4013** [comment]
started few hours ago with something like solution 2.   The change of the local data is simple, this part is nearly done but i am stuck with downloadchapter, seems you need to get this info online.  
Will scrub through the fmd source and look how this part was done. Unfortunately it will take some time, i am not so familiar with pascal so don't expect a proper solution soon.

**Comment by wuhugm** [comment]
@muto4013 No downloaded chapter record is hard but we can live it. In Domdom times, I used the bookmark transfer feature quite often and I don't know how Domdom did it but it kept the downloaded chapter record, well mostly, some downloads 5-10 latest chapters instead of only the latest one, and very little download from beginning.

**Comment by Tmp341** [comment]
@muto4013 If fmd recreates those entries later, i can live without it. I mean i don't wanna see an error.

**Comment by wuhugm** [comment]
No solution yet? I haven't been reading manga for more than a week and began to show withdrawal symptoms

**Comment by ralvarador** [comment]
BTW: bato.to has set active the option to export your "Following" list.

I already used a SQL Query against the .db files using the DB Browser for SQLite to recreate the URLs list and add them to another Software. (https://portableapps.com/apps/development/sqlite_database_browser_portable).

The main problem comes from the fact that - Not Always The Webpages Use The Same Name Conventioning to create the URLs, neither the Names of the Mangas.

So, create a SQL Query which let you export the FMD Bato.to's URL list to a CSV/TXT, then use a Search & Replace tool to transform them to a Mangafox, Mangahere, Mangatown URL form... isn't so suitable (possible but not suitable).
![imagen](https://user-images.githubusercontent.com/30580377/34972460-b9d47e92-fa4f-11e7-9936-6da4ae84d878.png)

![imagen](https://user-images.githubusercontent.com/30580377/34972462-bf7b38d6-fa4f-11e7-863d-f6f24f8d0afb.png)

**Comment by muto4013** [comment]
sorry folks, i had a small accident, am in hospital now, don't  know when i can continue,operation scheduled for friday, then some rehab.

@ralvarador : you can get the link from the masterlist table in [name].db (folder: \data), [name] would be website in favorites. websitelink entry in favorites would be a merge with entrys website and link.
still no solution for downloadedchapterlist.

sorry about the confusing style, too much painkillers :(

**Comment by riderkick** [comment]
https://github.com/riderkick/FMD/commit/7738999a228be9528a009ee6c3ec7d22cd25a59d

**Comment by wuhugm** [comment]
^Umm, what do I do with this?

**Comment by Tmp341** [comment]
You gotta wait for a new release.

**Comment by riderkick** [comment]
https://github.com/riderkick/FMD/commit/865941d491c40aadc93a495a7d59c5ade665a363

**Comment by riderkick** [comment]
Please test and close if OK.

**Comment by riderkick** [comment]
[fmd.7z.txt](https://github.com/riderkick/FMD/files/1648657/fmd.7z.txt)

**Comment by wuhugm** [comment]
@riderkick Oh boy! It worked! I transferred to Manga Eden and it worked. Gonna try more before closing this thread. Thanks Kamenrider!

**Comment by Tmp341** [comment]
I got error, even that file is there:

> Can not load SQLite client library "D:\Program Files\Portable\Fmd\sqlite3.dll

**Comment by wuhugm** [comment]
Update of my tries

Loaded 873 Batoto favorites

207 Invalids
666 Valids / Successful transfers

**666!!!** That number boi~ Am I the devil lol~

Nice ratio
Gonna figure out why 207 mangas failed
Probably different names

**Comment by riderkick** [comment]
@Tmp341 you have different bitness of sqlite3.dll. That one compiled with target i386-win32.

**Comment by wuhugm** [comment]
I think I've made a huge mistake

I transferred all my Batoto mangas to MangaEden (coz it has the largest database excluding hentai)

But it turns out many mangas there are port from Mangafox

So that horrendous watermark is there

God damn it

**Comment by asradur** [comment]
Can someone describe it to me step by step how to change my bookmarks?

**Comment by wuhugm** [comment]
^Get the file riderkick upload, delete the .txt from the filename, extract, replace the exe of FMD, start the program, go to favorites, right click any manga there, there should be new option of transfer bookmark

**Comment by wuhugm** [comment]
Guys, where is the best website to transfer to?

Ninemanga replaces images with anti-bot image
Mangaeden has mangafox watermark

Is there any healthy site remaining?

**Comment by asradur** [comment]
I would recommend readmanga.today
Is there any way to make the transfer work on win64?

**Comment by ralvarador** [comment]
@asradur, in the meanwhile a new release/build is released, you could:
- download the  X86 version
- decompress the archive.
- Download the file that @riderkick shared (https://github.com/riderkick/FMD/files/1648657/fmd.7z.txt)
   - when downloading the file, you should "remove" the ".txt" file extension to get the rigth-file extension (7z.)
   - Decompress the 7z file to the folder where you decompress the X86 FMD; overwrite the fmd.exe
- Then go to your X64 FMD, copy the config files / folders and paste them in your X86 FMD (Folders: Config, Data, Works, downloads).

Execute the X86 FMD.exe... it should show the same configuration from your X64.

**Comment by wuhugm** [comment]
!Update!

This feature is now included in the latest release of FMD 0.9.130.0
For those who applied the fix mentioned before,
You need to replace the exe with one from before the fix (FMD 0.9.129.0),
If not your update will fail
If you lost your exe, get one from the FMD releases on this site

**Comment by leoteesh** [comment]
hi, my update updated automatically. sorry but i am a bit confused on how to transfer the favorites to other websites.

**Comment by alexandriatale** [comment]
Does it copy my list or remove it? Do I still have my original list? I mean, I want to copy my list from mangago to mangahere, because I cannot download from mangago lately. But I didn't want my mangago list to be removed. Maybe copy them onto mangahere website?

**Comment by Tmp341** [comment]
![SS](https://user-images.githubusercontent.com/1683388/35320788-16b85ce4-00f6-11e8-9ae0-1a1906904de9.gif)

If checked manga has red mark, you gotta try another site or look for your manga manually. 
This one contains one manga transfer, but you can do a couple of more. I've tried 42 mangas and almost 30 of them was succesful.

**Comment by wuhugm** [comment]
@leoteesh That solution is only for those who overwrite their exe with riderkick's, everyone else can update normally and follow Tmp341's example above to transfer

@alexandriatale Your mangago's favorite will be replace to whatever site you transfer the favorites to. For safety, might be better to archive your entire FMD folder somewhere before attempting the transfers

**Comment by leoteesh** [comment]
Thanks- i have tried for one example but it not working - from batoto to readmanga. have also tried different sites. not sure if i doing this correctly
![image](https://user-images.githubusercontent.com/21075197/35353222-670a32ec-013e-11e8-808e-be989507aaf8.png)

**Comment by Tmp341** [comment]
That means 2 things:

1. That manga isn't there. Other than readmanga, try mangago, mangasee etc. You might find it.
2. That manga is there with a different name. If you really wanna use readmanga, search it manually. For example, it might be "mitsuyokon - tsukumogami no yomegoryou" or something like that.

And i've checked, readmanga doesn't have that manga.

**Comment by leoteesh** [comment]
thank you will check
