### ISSUE TITLE
Batoto is closing - cannot access downloads anymore?

### ISSUE THREAD

**Issue by Sakurahime08** [riderkick/FMD#830]
Is there a way to be able to download before it finally shuts down? I can't seem to download from the site. thanks!

**Comment by ralvarador** [comment]
Supposedly - nope, but not until 18th January; the issue is that they had activated de Cloudflare and it wasn't implemented here for bato.to

**Comment by ronny1982** [comment]
You can use HakuNeko until Batoto goes offline, but be prepared for very slow and failed downloads due to the cloudflare protection...
