### ISSUE TITLE
How to Build FMD?

### ISSUE THREAD

**Issue by rajlaksh** [riderkick/FMD#84]
I hate __Sourceforge__ for VIRUS.  Because it add Malicious code with package :cry:  :sob: 

My OS Windows 7 x64
Lazarus
Free Pascal Compiler v2.6.4  which one to pick?
RichMemo
Virtual TreeView
Synapse.
Vampyre Imaging Library.

Where to get it no __Sourceforge__ Please.

**Comment by riderkick** [comment]
I don't know what you're talking about no sourceforge.
Just try to compile the source with lazarus 1.4

**Comment by rajlaksh** [comment]
lazarus is on Sourceforge so i can't trust all those package.
