### ISSUE TITLE
Build this FMD

### ISSUE THREAD

**Issue by BambooKids** [riderkick/FMD#840]
Can anyone help me to build this version now, and send me download link?
I can't wait riderkick to build it. 
Thanks

**Comment by Tmp341** [comment]
Check [This](https://github.com/riderkick/FMD/blob/master/readme.txt) link.

**Comment by BambooKids** [comment]
I always failed to build it. Can you build it for me and send me a link download?
I don't understand about code and programming... Thanks

**Comment by Tmp341** [comment]
Building needs a lot of app installation, i don't install an app just for using once. Sorry. But, someone else might do it for you.
