### ISSUE TITLE
Ability to mass switch download sites from one to another for favorites. 

### ISSUE THREAD

**Issue by bennettn** [riderkick/FMD#843]
Is there an ability to switch all your favorites from one manga site, (For example batoto) to another one. I know not all series will have the same name on another site and some sites won't have some titles. Is the only option doing it manually? This is not the best option when favorites get into the hundreds and thousands. If this functionality is already in the program, I would appreciate some help in finding it. If not, I think this feature is quite necessary now that the end of the world is here for batoto.

**Comment by joewono2011** [comment]
Ir seems fmd doesnt have this feature
dds have this feature

I do it manually, one by one

**Comment by Tmp341** [comment]
We've expressed our wish about something like that in here : #826
