### ISSUE TITLE
Add mangadex.com

### ISSUE THREAD

**Issue by Thrieze** [riderkick/FMD#845]
https://mangadex.com/ Is a new site by Doki, trying to do the new batoto thing. So this may be early but something to look into.

**Comment by R-Jimenez** [comment]
Seconded. Seems like the community is starting to push behind it (for now).

**Comment by nille02** [comment]
Would love it, too.

**Comment by wildcrow** [comment]
Yeah, seems like they will be at the very least the source for new scanlations, not sure about the previous Bato.to content tho, anyway i hope to see this one on the manga list too.

Regards.
