### ISSUE TITLE
not finding new chapters

### ISSUE THREAD

**Issue by christer9** [riderkick/FMD#850]
it search and search but not finding any, is it only me or?

**Comment by Thrieze** [comment]
Yea I noticed the same actually, if you click manga info you can see there is a new chapter there but it doesnt get picked up by the check for updates.

**Comment by Tmp341** [comment]
You get that error anyone specific, or all together?

**Comment by Thrieze** [comment]
I don't get an error per se. It just never finds anything.

**Comment by christer9** [comment]
all of them, but as Therieze sad  it finds them but you need to manually download from favorites

**Comment by Tmp341** [comment]
Have you tried this?

- Backup "works\favorites.db" and "data"
- Delete everything, then install fmd again.
- Restore your "works\favorites.db" and "data"

**Comment by christer9** [comment]
did not work

**Comment by H4nZ83** [comment]
okay i've experienced this issues too, have you checked the web directly by using the link on the description?
if you have checked the link via browser and it show some chapter then the FMD db was broken, 
but if you checked the link and there was no chapter there, means that manga has been licensed in your country and no further update from that site.

**Comment by christer9** [comment]
it finds all chapter and i can download if i click on it in fav then choose chapters manually but it just dont download anything automatic as i did before

**Comment by christer9** [comment]
todays update that i just recived fixed  the problem     you guys are the best
