### ISSUE TITLE
Search in All Manga Sites

### ISSUE THREAD

**Issue by wuhugm** [riderkick/FMD#853]
Somehow this filter doesn't do what it says

Let's say for example this manga Nectar of Dharani/Shinju no Nectar
I searched for Nectar with Search in All Manga Sites and so few results

I know for sure that there are more in other sites, like mangafox and mangahere (Already in my lists too)
But they are not included in the search result

Why?

**Comment by riderkick** [comment]
sqlite by default only allow 10 attached databases. you can try cyqlite dll which increase this limit to 64. just google.

**Comment by wuhugm** [comment]
^I should replace sqlite3.dll with cyqlite.dll ?

**Comment by wuhugm** [comment]
Error : Can not load SQLite client library :(

**Comment by riderkick** [comment]
You have to use the right dll bitness for your installation.
I will include my compiled sqlite3.dll with 125 attached limit for next release.
