### ISSUE TITLE
[Feature Request] Have comments on Manga Sites like DomDomSoft had

### ISSUE THREAD

**Issue by bmix** [riderkick/FMD#858]
*DomDomSoft Manga Downloader* had some comments on the type and quality of the sites it had integrated. For people, like me, who only download then and when, and therefore are not well known of the Scanlation/Hosting scene, it would be a welcome addition to be able to judge the quality of the sites in advance.

**Comment by Tmp341** [comment]
There might be a rating system for each site. Or warning system, like "This site has a watermark" or "This site allows only one manga download, then scrambles all pages" etc. 
For commenting, user signup system needed, or else you might see spamming.

**Comment by bmix** [comment]
I wasn't thinking about social commenting or user-rating. I thought about some hardcoded wisdom like *DomDomSoft MangaDownloader* had. Here is the example:

![domdom](https://user-images.githubusercontent.com/310157/35307390-de680216-00a2-11e8-9b71-99233c3f7afb.jpg)

It would tell you what is noteworthy about a site.

**Comment by Tmp341** [comment]
@bmix Ah, that might be good feature.

**Comment by riderkick** [comment]
Is there anyone who want to reviews all of those website?
We can change the mangalist.ini structure to something like
```
[English]
KissManga=<details>
```

**Comment by bmix** [comment]
I think the most interesting aspect would be the quality of scans. This is what I am constantly asking myself, before I download a comic. Do I get the 44MB archive with the medium quality scans or the 160MB (preferred) archive with the HQ? This should be info, we could easily collect here, under this issue.

**Comment by riderkick** [comment]
Moved to #891
