### ISSUE TITLE
[Request] Let Users Create Scrapers

### ISSUE THREAD

**Issue by bmix** [riderkick/FMD#861]
Seeing, that more than a half of issues relate to requests to update old or add new sites, it may be interesting to see, whether there could be a generic way to use any site and have the users define the patterns (the xpaths, mostly) to scrape for.

**Comment by Tmp341** [comment]
@bmix Agree. Updating sometimes needs a lot of time. For example, some large sites like Hitomi.la shows 15k updates, and i've stopped it after 15 minutes (even it only found 500 hentai) though.

**Comment by bmix** [comment]
Not sure whether we are on the same track. I meant to have the site-scraper code itself being user-definable, not the comics, that have been updated on a site.

**Comment by Tmp341** [comment]
Oh. I got it now.

**Comment by riderkick** [comment]
The direction I would like to go is to use Lua or PascalScript. But there is a lot of thing need to be done. I don't have time for it yet.

**Comment by bmix** [comment]
Nobody knows PascalScript ;-) Lua is also not the most popular with users. Is FMD Windows-only or is it multi-platform? If Windows-only I rather would recommend the ActiveScript host (making FMD a COM+ object, but don't quote me on that, since I am not very well educated on the application host side of things), because that would mean, that [any of these languages](https://en.wikipedia.org/wiki/Active_Scripting) could be used by the user. The chapter [Active Host Engines](http://www.mvps.org/scripting/languages/) under www.mvps.org/scripting/languages shows some more.

But wouldn't it be much easier to just form the logic behind the XPath evaluation into a dialog and let the user define those XPaths? I guess, there must be a common pattern to these sites?! This would not require any app-scripting at all.

**Comment by riderkick** [comment]
Moved to #909
