### ISSUE TITLE
tumangaonline dejo de funcionar 

### ISSUE THREAD

**Issue by Alexcr86** [riderkick/FMD#863]
tumangaonline dejo de funcionar hace tiempo, ya no se puede ver la información del manga y no busca nuevas actualizaciones en favoritos

**Comment by byhacktutos** [comment]
el usuario Alexcr86 esta en lo cierto actualmente ni cargando la base de datos y selecionando cualquier manga manualmente se puede ver ni descargar nada cuando bajas la base de datos y le das click a algun manga si acaso carga la info y no la imagen ni la lista de capitulos es mas al lado en la base de datos donde dice el numero de capitulos automaticamente se pone en (0) como si no ubiera ningun capitulo disponible

**Comment by rs3mk** [comment]
close ticket, works now.

**Comment by GATOQSECOMIO** [comment]
@Alexcr86 @byhacktutos actualmente en la v0.9.133.0 está resuelto, prueba a "actualizar lista de manga" para bajarlos individualmente o "descargar la lista de manga desde el servidor" para actualizar TMO desde un zip.
