### ISSUE TITLE
Feature to show new manga released on all sites!

### ISSUE THREAD

**Issue by molitar** [riderkick/FMD#864]
Dom manga downloader could filter new manga's only on all sites and just simply hit next > next > next to get a summary of each one.. Was easy to find new manga I want to follow. 

Can we get something like that for FMD?

**Comment by riderkick** [comment]
There is `Search only new manga` checkbox in mangalist filter options.

**Comment by molitar** [comment]
Riderkick I am meaning more like Domdom.. You could click next and read the summary of the next new manga.  It's very difficult with FMD.. you have to double click each one wait for manga info to load. than repeat.  I want to be able to quickly press next.. see summary and go to the next one. I used that feature to find new manga's I wanted to read.

**Comment by riderkick** [comment]
There is a hint of summary if you hover on mangalist item for a few seconds.

**Comment by molitar** [comment]
Yes but can we get a next button so when filtering for new manga can actually just hit next and it go to the next manga?  Currently it's a lot of clicking to go through each and every manga to load the manga info box. 

To find new manga I may want to read.. filter by new for all manga sites with the chosen filters.. than I have over 100+ to check out.. double click wait to load.. read entire summary as well as see artwork on cover > move down to next one in list > repeat.. that is a lot of needless clicking and scrolling. If there was a next button just hit next > read summary > press next again.

**Comment by riderkick** [comment]
Just moving your mouse up/down a bit is much easier then click a button.
