### ISSUE TITLE
New user, downloads just not working

### ISSUE THREAD

**Issue by Blake81** [riderkick/FMD#869]
Just got FMD after I found out that my old DomDomSoft no longer worked, but for some reason, I just cannot DL anything.

When I download something, it creates folders for each chapter, and that's it. No images are ever DLd. I tried various different sites as I thought it could be an error with MangaFox, but still nothing.

It doesn't even give me a specific error message; it just says ''DLs failed, try resuming'', which I've done again and again and still nothing.

Anyone has any idea of what this may be? Or has experienced a similar issue?

**Comment by Tmp341** [comment]
Mangafox bans some ISPs or IPs. or countries. I can't download from there, not just download, i can't open it from browser, it gives 404 error.

Try using others, like mangago, mangasee etc.

**Comment by Blake81** [comment]
Well, I'm on the USA, so I don't think it's the country.

Also, tried MangaHere and MangaGo with the same results.

**Comment by Tmp341** [comment]
Do you have log?

**Comment by Blake81** [comment]
Maybe I do, where can I find that?

**Comment by kmvi** [comment]
@Blake81 Options -> Misc -> Log -> Enable logging. Also please tell which version you're using (About tab)

**Comment by Blake81** [comment]
=== Log Session Started at 1/25/2018 22:52:40 by Free Manga Downloader ===
22:52:40:052 INFO: "Free Manga Downloader" started with [PID:7820] [HANDLE:4294967295]
22:52:40:053 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 0.9.130.0
               Product Version   : Win32 Debug
               Host Machine      : Windows 7 64-bit
               FPC Version       : 3.0.4
               LCL Version       : 1.9.0.0
               WidgetSet         : Win32/Win64
               Target CPU-OS     : i386-Win32
               Build Time        : 2018/01/23 16:36:12
               Path              : C:\Free Manga Downloader\fmd.exe
               Process ID        : 7820
               MainThread ID     : 8028
22:52:47:362 WARNING: TTaskThread, checkforfinish failed=1/1 "Boku no Hero Academia" > "/manga/boku_no_hero_academia/c166/"
W
22:52:47:364 WARNING: TTaskThread, download failed. "Boku no Hero Academia" "Boku no Hero Academia 166" "/manga/boku_no_hero_academia/c166/"
22:52:47:364 WARNING: TTaskThread, download failed. "Boku no Hero Academia" "Boku no Hero Academia 166" "/manga/boku_no_hero_academia/c166/"

**Comment by Blake81** [comment]
There ya go. Those are DLing from different sources as well.

**Comment by kmvi** [comment]
Mangafox
> The series Boku no Hero Academia is not available in Manga Fox. 

Mangahere
> The series Boku no Hero Academia has been licensed, it is not available in MangaHere.

Try to use for example mangasee, mangalife, kissmanga.

**Comment by Blake81** [comment]
Gotcha, will try there.

**Comment by Blake81** [comment]
Btw, got this exception when I enabled Kissmanga on the Website list:

Program exception!
Application       : Free Manga Downloader
Version           : 0.9.130.0
Product Version   : Win32 Debug
Host Machine      : Windows 7 64-bit
FPC Version       : 3.0.4
LCL Version       : 1.9.0.0
WidgetSet         : Win32/Win64
Target CPU-OS     : i386-Win32
Build Time        : 2018/01/23 16:36:12
Path              : C:\Free Manga Downloader\fmd.exe
Process ID        : 2916
MainThread ID     : 2912
Thread ID         : 2912
Time              : 25/01/2018 23:10:24.354
Sender Class      : TMainForm
Exception Class   : EAccessViolation
Message           : Access violation
  $00751B02  APPLYBASICCOLORTOVT,  line 223 of ./forms/frmCustomColor.pas
  $00751E58  APPLY,  line 280 of ./forms/frmCustomColor.pas
  $0046C37B  TMAINFORM__APPLYOPTIONS,  line 5118 of ./forms/frmMain.pas
  $00467B34  TMAINFORM__BTOPTIONAPPLYCLICK,  line 4295 of ./forms/frmMain.pas
  $0052013D
  $00516FB2
  $00593654
  $00501B92
  $005020EB
  $005C3D3D
  $756062FA
  $75606D3A
  $7560966E
  $756096D5
  $71C445A1
  $71C44603
  $71C4448D
