### ISSUE TITLE
[Request] Select all text in URL field on "Manga Info" - "Info" tab

### ISSUE THREAD

**Issue by SDXC** [riderkick/FMD#873]
When I paste a link into the "Input URL here" field (Tab "Manga Info", Subtab "Info") and after that I want to put another link into it, I have to CTRL+A or mouse select the URL.

I'd like to have a small feature that either autoselects the URL when clicking in the textbox or at least when I doubleclick. I hope you know what I mean and maybe you also missed this already at some point.

**Comment by riderkick** [comment]
"Paste and go" will replace all text.

**Comment by SDXC** [comment]
Oh, didn't know there was a custom context menu. Is it possible to assign a key shortcut for this function? For example CTRL+SHIFT+V ?
