### ISSUE TITLE
FMD error after recent update

### ISSUE THREAD

**Issue by H4nZ83** [riderkick/FMD#878]
Hello, i got this error after i'm updating to recent version of fmd

and then i got this error

Unhandled exception!
Application       : Free Manga Downloader
Version           : 0.9.131.0
Product Version   : Win32 Debug
Host Machine      : Windows XP
FPC Version       : 3.0.4
LCL Version       : 1.9.0.0
WidgetSet         : Win32/Win64
Target CPU-OS     : i386-Win32
Build Time        : 2018/01/27 02:26:03
Path              : H:\g\Downloader\fmd\fmd.exe
Process ID        : 2180
MainThread ID     : 5656
Thread ID         : 5656
Time              : 27/01/2018 08:53:41.379
Exception Class   : EInOutError
Message           : Can not load WebP codec library "H:\g\Downloader\fmd\libwebp.dll". Check your installation.
  $00438F0E  INITWEBPMODULE,  line 56 of F:/GitRepo/Freepascal/FMD/baseunits/webp.pas
  $0046162E  TMAINFORM__LOADABOUT,  line 2128 of ./forms/frmMain.pas
  $0045DA18  TMAINFORM__FORMCREATE,  line 1096 of ./forms/frmMain.pas
  $0041B77D
  $0041A194
  $0041F5FF
  $00425382
  $0040355C  main,  line 96 of md.lpr

**Comment by kmvi** [comment]
I've rebuilt libwebp with `_WIN32_WINNT=0x0501` macro set. Replace libwebp.dll in your installation with x86\libwebp.dll from [this zip](https://gist.github.com/kmvi/8e4fe1eca44d5a174512fc5f32da2970/raw/f6e875885e7a19b11e410f73c205e65f083ff765/libwebp.zip). please tell whether it works.

**Comment by riderkick** [comment]
Google provide precompiled libwebp binary here https://storage.googleapis.com/downloads.webmproject.org/releases/webp/index.html

**Comment by kmvi** [comment]
@riderkick it seems there are only libs for static linking

**Comment by azrael12tmp** [comment]
@kmvi your link is working fine for me, i have a x86 with xp as well
@riderkick maybe your link is working but i was unable to find the library, maybe it must be compiled or something

**Comment by riderkick** [comment]
Ops. IIRC I used to install a setup file from webm release. It does add libwebp-x.dll to system32.  I don't know where it is now.

**Comment by riderkick** [comment]
Compile with gcc without png,jpeg,tiff,gif,wic. @kmvi we only need decompress function, right?
[libwebp.7z.txt](https://github.com/riderkick/FMD/files/1670820/libwebp.7z.txt)

**Comment by kmvi** [comment]
@riderkick yes. just tested your dll on xp vm, it works.

**Comment by riderkick** [comment]
@kmvi, some converted file is to large for png. While the source is only 300kb it produce 3,4mb png file.
Consider to add save as jpeg option. And use `SaveImageStreamToFile` in baseunit to preserve last-modified time. Just replace `DownloadThread.FHTTP.Document`.
Or add webp detection in `SaveImageStreamToFile` to automatically convert webp stream. That way we don't need to deal with webp anymore in the future. Also add global option to convert webp to png/jpeg.

**Comment by H4nZ83** [comment]
yeah, its working.
thanks for your dll file, its working like magic, no error messages.
the problem was on the libwebp.dll file that not supported on xp machine

**Comment by H4nZ83** [comment]
okay, which version should i use? the last one or the first one ?
because with the first one it solved the bug.
thanks anyway for your help @riderkick, @kmvi

**Comment by riderkick** [comment]
Whichever works. They are basically the same.

**Comment by H4nZ83** [comment]
thx..
