### ISSUE TITLE
Since version 0.9.19.0+ there is a weird green border on every window of the application

### ISSUE THREAD

**Issue by terabyte-gc** [riderkick/FMD#88]
As per title, since that version I see that green border around any window/popup and when I try to download a manga nothing gets actually saved in the folder. I went back to 0.9.18.2 which is the latest version working for me.

**Comment by riderkick** [comment]
Those green border probably your antivirus doing, safe mode/sandbox. Usually if you enabled safe mode/sandbox, and you trying to launch new executable file, it will temporary run the executable file in safe mode/sandbox while the antivirus scan this file. After finish scanning usually it will relaunch the executable file in normal mode. You can check your antivirus settings.

**Comment by terabyte-gc** [comment]
I use avast antivirus, but I do have Comodo Firewall. I'll look into that, thanks.

Not sure why it only has issues on newer versions thought, I do remember allowing them as safe applications.

**Comment by terabyte-gc** [comment]
Okay, it was indeed the firewall. I had added it as a safe file when the rule popup appeared but for some reason it didn't save it properly. I manually added it and it worked.
