### ISSUE TITLE
FMD cannot get manga info

### ISSUE THREAD

**Issue by carljbai** [riderkick/FMD#89]
FMD will not retrieve manga info since the update to 0.9.21.1 . All releases I tested with (0.9.21.1, 0.9.21.0, 0.9.18.1) all encounter the same error. Since this has appeared I have rebooted, allowed access through windows firewall, disabled my antivirus, and attempted several clean installs of the software. an identical download sunk through OneDrive has been tested on two separate computers but failing on the original computer. Does FMD store any data outside of a Fresh install that could be responsible?

Attached is 2 screenshots of the error message I am receiving taken in two separate instances of FMD in two different install locations accessing two different manga from 2 separate sites.

![2](https://cloud.githubusercontent.com/assets/7985170/9148612/72b2f746-3d50-11e5-8875-49e2c00f7a6f.jpg)
![1](https://cloud.githubusercontent.com/assets/7985170/9148613/72b49380-3d50-11e5-921f-e9228fa019aa.jpg)

**Comment by riderkick** [comment]
FMD doesn't store to any other folder, it's only store to current folder you run FMD from.
Can you open the corresponding title in your browser?

**Comment by carljbai** [comment]
Yes I can open the titles in my browser. However when looking at the logs for my network adapter FMD never gets requests access during the times I try to open manga info. It is possible that something blocking FMD requests on my end was the cause of the problem from the start.

**Comment by riderkick** [comment]
Probably, check your firewall. Some antivirus also come with firewall, you may need to check your antivirus as well.

**Comment by carljbai** [comment]
I resolved the error. Avast antivirus was suppressing file and network access despite me disabling the real time shield. I had to shut off all real time protection then manually add an exemption for FMD before it would allow the traffic through. As of now I submitted FMD to Avast so hopefully future versions will not block it.
