### ISSUE TITLE
0.9.21.1 Error

### ISSUE THREAD

**Issue by greenaar** [riderkick/FMD#90]
Crash on trying to automatically download after checking favorites, 100% of the time.

**Comment by greenaar** [comment]
Please note, 0.9.20.0 does not crash, under identical conditions.  Rolled back to that version as a short term workaround.

**Comment by blue-lightning** [comment]
Me too. Dumping log:
```
Program exception!
Application       : Free Manga Downloader
Version           : 0.9.21.1
Product Version   : Win64 Debug
FPC Version       : 3.1.1
LCL Version       : 1.5
Target CPU_OS     : x86_64_Win64
Host Machine      : Windows 64-bit
Path              : E:\Setups\Free Manga Downloader\fmd.exe
Proccess Id       : 2028
Thread Id         : 2860
Time              : 2015-08-08 10:54:37
Ignored Exception : EImagingError,ERegExpr
Sender Class      : TFavoriteManager
Exception Class   : EAccessViolation
Message           : Access violation
Exception Address : $000000010049E0B2
  $000000010049C1C5 line 281 of ../baseunits/uFavoritesManager.pas
  $00000001000653F6
  $000000010006581A
  $0000000100286134
  $00000001002876EC
  $00007FF9DA28250D
  $00007FF9DA282367
  $00000001002884F2
  $000000010002A200
  $000000010002A691
  $0000000100088336
  $000000010002A629
  $00000001000033C5 line 62 of md.lpr
  $00000001000033F6 line 64 of md.lpr
  $0000000100018693
  $0000000100019196
```

**Comment by ajsha** [comment]
Same here

Program exception!
Application       : Free Manga Downloader
Version           : 0.9.21.1
Product Version   : Win32 Debug
FPC Version       : 3.1.1
LCL Version       : 1.5
Target CPU_OS     : i386_Win32
Host Machine      : Windows 7
Path              : G:\Tools\Internet\Free Manga Downloader\fmd\fmd.exe
Proccess Id       : 4980
Thread Id         : 712
Time              : 8/08/2015 16:24:21
Ignored Exception : EImagingError,ERegExpr
Sender Class      : TFavoriteManager
Exception Class   : EAccessViolation
Message           : Access violation
Exception Address : $007B95A8
  $007B7CBB TFAVORITETASK__SYNCSHOWRESULT, line 281 of F:/GitRepo/Freepascal/FMD/baseunits/uFavoritesManager.pas
  $004529FC
  $0060E6C6
  $0060FC4B
  $7557C4E7
  $7557C5E7
  $7557CC19
  $7557CC70
  $0061078E
  $00422896
  $0046FC0A

**Comment by ajsha** [comment]
reverting to 0.9.20.0 resolved the issue (0.9.21.0 didnt work either)

**Comment by nigredo-tori** [comment]
Same here:

Program exception!
Application       : Free Manga Downloader
Version           : 0.9.21.1
Product Version   : Win64 Debug
FPC Version       : 3.1.1
LCL Version       : 1.5
Target CPU_OS     : x86_64_Win64
Host Machine      : Windows 64-bit
Path              : D:\Program Files (x86)\Free Manga Downloader\fmd.exe
Proccess Id       : 8384
Thread Id         : 6844
Time              : 8/8/2015 11:06:53
Ignored Exception : EImagingError,ERegExpr
Sender Class      : TFavoriteManager
Exception Class   : EAccessViolation
Message           : Access violation
Exception Address : $000000010049E0B2
  $000000010049C1C5 line 281 of ../baseunits/uFavoritesManager.pas
  $00000001000653F6
  $000000010006581A
  $0000000100286134
  $00000001002876EC
  $00007FFF59E400DC
  $00007FFF59E3FC07
  $00000001002884F2
  $000000010002A200
  $000000010002A691
  $0000000100088336
  $000000010002A629
  $00000001000033C5 line 62 of md.lpr
  $00000001000033F6 line 64 of md.lpr
  $0000000100018693
  $0000000100019196

**Comment by riderkick** [comment]
It seems option "Automatic download after finish checking" doesn't stored properly either.
