### ISSUE TITLE
FMD downloaded files didn't update modified date

### ISSUE THREAD

**Issue by forvy** [riderkick/FMD#904]
Hi, I just updated into windows10 last week because my wiindows7 keep getting issues. Problem is on windows7 last modified date was updated when FMD download files, yet on windows 10 last modified date wasn't updated.
As you can see on images below:
(FMD download)
![image](https://user-images.githubusercontent.com/17746819/35762181-00aa75e4-08d6-11e8-9c9d-7e4c17567d77.png)

(Explorer-after reopen and refresh multiple times)
![image](https://user-images.githubusercontent.com/17746819/35762190-20a5911c-08d6-11e8-8a15-322bff6553fb.png)

Any idea how to fix this issue? Other than opening respective manga folder one by one to update modified date. Thanks

**Comment by riderkick** [comment]
Please elaborate more.
FMD only change files last modified date if it's available on server header response `last-modified`.
Try to run with admin privileges.

**Comment by forvy** [comment]
For example: 
If I had One Piece folder on download directory with the last date modified 1/31/2018 15:07
then I download a new chapter at 2/3/2018 11:16  it would be changed into 2/3/2018 11:16 for the One Piece folder.  
But as you can on the picture, unless I access the new chapter which I download using FMD the Manga folder modified date wasn't updated (Goblin Slayer and One Piece could be observed from the picture).

Idk if it was by updating OS (from win7 to 10) or latest update which made it this way since my friend said in last few update FMD modified date also act up on his laptop.

I will try to run FMD as admin as soon as I get the chance when there is new Manga update.

**Comment by nille02** [comment]
I guess this is more a Windows issue on your site. I looked in my Download Folder and the Date modified Colum in the Explorer changes with each new update. 

If i search on the Internet, there are many with a similar problem to yours.

**Comment by forvy** [comment]
Any suggestion how to solve it?

**Comment by forvy** [comment]
Issue resolved. It was permission matter apparently. 
![untitled](https://user-images.githubusercontent.com/17746819/36058385-c03166a8-0e61-11e8-9fab-1c42be5682c4.png)
