### ISSUE TITLE
Sites that fail to download directory from server

### ISSUE THREAD

**Issue by molitar** [riderkick/FMD#908]
List of sites that I am unable to download from server.

MangaIce - now moved to MangaDeep so needs URL correction
MangaSpy - same as MangaDeep seems they have merged
MyMangaMe - unable to find is it gone?

**Comment by Tmp341** [comment]
Check #891

**Comment by kmvi** [comment]
Mangadeep db was uploaded to server.  It seems MyMangaMe no longer exists.
