### ISSUE TITLE
Kissmanga missing mangas

### ISSUE THREAD

**Issue by Tmp341** [riderkick/FMD#910]
I've come across something like this, but i don't remember on which site, because i thought it was some kind of update list problem. I didn't think it was urgent, it is still not though, but when i tried to find this manga, i couldn't find it through fmd, but it was on kissmanga. Here is a screenshot:

[ss](https://user-images.githubusercontent.com/1683388/35856085-f010c90a-0b45-11e8-9a83-d997c7340e68.jpg)

I've tried both it's English and Chinese name, but couldn't be able to find it.

**Comment by kmvi** [comment]
@riderkick could you please comment [this part](https://github.com/riderkick/FMD/blob/master/baseunits/uUpdateThread.pas#L166)? I don't understand why thread should terminate after first `GetNamesAndLink` call (if `SortedList = true`). Kissmanga has 266 pages of newest titles.

**Comment by riderkick** [comment]
@kmvi Some website has sorted list of manga directory, ordered by addition time. We stop at that page when fetching new manga list. So we don't waste resources.

**Comment by kmvi** [comment]
Kissmanga has that list, but it uses pagination. Update thread processes only the first page and then terminates. Should we remove `SortedList := True` from kissmanga module?

**Comment by riderkick** [comment]
@kmvi removing `sortedlist := true` will causing kissmanga to load all page. And that will take time just to get a few item. Usually if some mangas missing in update process, its causing by temporary internet issue. So, some thread got broken data, but other thread keep filling new data to database. The way to fix this is to remove the database and rebuild the list from scratch.
IIRC setting the fixed directory page number in `websites > options > advance > update list` will ignore sortedlist.

**Comment by kmvi** [comment]
@Tmp341 I've updated kissmanga db on server, please check

**Comment by Tmp341** [comment]
Ok, they are listed now. Thank you.
[sss](https://user-images.githubusercontent.com/1683388/35912344-61150888-0c0d-11e8-8979-9348acfab597.jpg)

For information, are you going to update it once in a while and we will get through server, or we can update it through manual site update?

**Comment by kmvi** [comment]
Manual update works somehow strange, I'll continue to research this issue

**Comment by Tmp341** [comment]
Manual update is strange, yeah. I couldn't get almost 30 percent of the list.

**Comment by kmvi** [comment]
@Tmp341 I'll try to explain. Some sites (Kissmanga, hentai2read among them) provide a list of titles in the last added order. This gives an advantage: we can check only the first few pages of the directory, until we find the title which is already in the FMD DB. When such a title is found, there is no sense to view the remaining pages, they are all already in the DB. It's in the perfect world. But sometimes the titles order is violated and the title, which was added many years ago, for some reason appears on the first pages of the directory (maybe it was deleted and added back). Obviously this breaks the update process. A workaround is to set `websites > options > advance > update list > directory page number` parameter. For now Kissmanga directory has 267 pages. If this parameter is set, it forces to read all 267 pages of the directory. This feature will be available in the next release.

**Comment by Tmp341** [comment]
Do you know what parameter HitomiLa has? My list is outdated and when i try to update, it shows 40k titles. Maybe it doesn't show me exact number.

**Comment by kmvi** [comment]
Yes, it also uses the list in last added order.

**Comment by riderkick** [comment]
For large list of manga like that of hentai/adult site. Usually they have single chapter. So you never really need a database for all the list. Just drag n drop the link(s) to download list area. Databases only useful if you need to transfer between websites. Thus you need working databases.
I personally never really use the databases. I search on the website directly. Socialize on respected forum to get my interest. FMD doesn't intended to browse new mangas, etc. It's not manga libraries. Mainly its for downloading.

**Comment by Tmp341** [comment]
> Just drag n drop the link(s) to download list area/drop box window.
When i try to update a hentai site, they always have a lot of numbers. I wasn't aware of that "drag n drop" thing. Thank you.

**Comment by riderkick** [comment]
@Tmp341 drag n drop have been added a long times ago. Drop box window is very useful for hentai site. Usually you can drag n drop the thumbnails, multiple link is supported. Firefox has a feature to select multiple row with `Ctrl`. You can use that to drop it to fmd.

@kmvi can you please update the screenshots in sf page. They're very old. Put the drop box feature on the first order. So people know such thing exist.
