### ISSUE TITLE
Can't update to 0.9.133.0

### ISSUE THREAD

**Issue by wuhugm** [riderkick/FMD#912]
After clicking update

It displays the progress bar for few seconds then gives the error "file not found" then it fails

https://i.imgur.com/OlkmdrN.png

As shown in above link

**Comment by subnighter** [comment]
Same here. Additional info that using the 64-bit version.

**Comment by Tmp341** [comment]
Probably an error caused a take back the release.

**Comment by rs3mk** [comment]
not work :/
