### ISSUE TITLE
MangaPanda returning 0 chapters after newest update

### ISSUE THREAD

**Issue by tomatosoupcan** [riderkick/FMD#914]
See the images below, having MP issues since the most recent update, but I am able to browse to the site with no issues in Chrome and the likes.

![image](https://user-images.githubusercontent.com/11912393/35925936-390fee1c-0be4-11e8-8c5f-9f7b5a4dfb97.png)
![image](https://user-images.githubusercontent.com/11912393/35926007-6157cd22-0be4-11e8-92b7-d3dbf031e841.png)

**Comment by kmvi** [comment]
Fixed 9e4d6fa14fb831bde53141981b13071782c9ca3f
