### ISSUE TITLE
mangago scramble pictures

### ISSUE THREAD

**Issue by sadeghp88** [riderkick/FMD#916]
hello
the mangas which are downloaded from mangago are still scrambled!!!
please fix this. its such a bummer :(

![026](https://user-images.githubusercontent.com/28827241/35937212-c36c76e0-0c5a-11e8-835b-8c4367ad0479.jpg)

**Comment by subnighter** [comment]
It would be better to provide examples of pages where it happens. One of such cases is http://www.mangago.me/read-manga/the_young_master_and_the_maid/. In chapter 29 pages 2, 5, 6, 7, 11, 13, 14, 15, 16, 17, 18, 19, and 22 are scrambled.

**Comment by leoteesh** [comment]
same here 
whole chapters
![image](https://user-images.githubusercontent.com/21075197/35941460-3341585c-0c4a-11e8-9ef0-7d9572431ca1.png)

![image](https://user-images.githubusercontent.com/21075197/35941315-bc5e1946-0c49-11e8-838b-75ade7d1e70d.png)
![image](https://user-images.githubusercontent.com/21075197/35941430-12fc5538-0c4a-11e8-85ac-3093cfbae44d.png)

**Comment by leoteesh** [comment]
also getting error messages
![image](https://user-images.githubusercontent.com/21075197/35942690-5f2913ca-0c4e-11e8-82fb-b4dffe32ca5c.png)

![image](https://user-images.githubusercontent.com/21075197/35942727-7ed80550-0c4e-11e8-9120-6ab683981179.png)

**Comment by joewono2011** [comment]
Same here

**Comment by kmvi** [comment]
they again changed the scrambling algorithm + added several tricks. it's impossible to win: whatever we do, any change breaks our module

**Comment by riderkick** [comment]
They may monitor this project and change their project accordingly. The same cat and mouse games with rawsenmanga back then.

**Comment by Tmp341** [comment]
Because this is an open project, they can see source code, so they can change their code according to project's change.

**Comment by Sakurahime08** [comment]
And here I thought everything was fixed when i saw the update. T_T Thanks for all the effort! (But I do hope you guys find a solution!)

**Comment by jmira965** [comment]
I got an error while downloading from manga. "Access Violation"

**Comment by kmvi** [comment]
please check this fix (32-bit)
[fmd.7z.txt](https://github.com/riderkick/FMD/files/1707893/fmd.7z.txt)

**Comment by subnighter** [comment]
Thanks, in my example no longer is scrambled.

**Comment by leoteesh** [comment]
For me it is still scramble (after the update)
![image](https://user-images.githubusercontent.com/21075197/35994034-10035d96-0d07-11e8-85d4-69a817dc39e8.png)
![image](https://user-images.githubusercontent.com/21075197/35994053-1f9e1e80-0d07-11e8-86dc-a605dcc7707d.png)

also getting errors in downloading 
![image](https://user-images.githubusercontent.com/21075197/35994082-36c6b1a8-0d07-11e8-8dd6-3c80a312e883.png)

**Comment by kmvi** [comment]
@leoteesh the updated version (134) doesn't contain fix, check this file [fmd.7z.txt](https://github.com/riderkick/FMD/files/1707893/fmd.7z.txt) (32-bit only).

**Comment by leoteesh** [comment]
Thanks. Sorry I am not too sure how to use it so that I don't lose my favourites?

**Comment by Tmp341** [comment]
@leoteesh It is just an executable file. If you don't delete your favorites.db file manually, you won't lose it.

**Comment by leoteesh** [comment]
i am getting this message when i open it
![image](https://user-images.githubusercontent.com/21075197/36051608-99e8d654-0de2-11e8-8aab-f0f5f4bc389d.png)

**Comment by subnighter** [comment]
I think the information how to switch 32-bit version to 64-bi one, and reverse should be added to the FAQ. Should be similar to:
1. Download the latest release for the target CPU you want to switch. It should be found [here](https://github.com/riderkick/FMD/releases/latest). 64-bit version can be easily recognized due to the presence of Win64.7z in the name of the archive; the 32-bit is the other 7z file.
2. Unzip the file.
3. Replace the files but not folders of your previous installation with the recently un-archived file.
Now you successfully changed version without losing favorites.

4. (rarely used) Rename the fmd.exe to, for example, fmd_old.exe, and paste the file you were asked to test. That way if you do happen to like the behavior of the previous version better, you will be able to undo it easily.

**Comment by Sakurahime08** [comment]
Images are still scrambled in the latest update but are random. Usually the first chapters downloaded are fixed then it gets scrambled in the later task downloads for the same series. Then back again when downloading for a new series.

**Comment by Tmp341** [comment]
@leoteesh Try this, paste it inside fmd folder.
[https://github.com/riderkick/FMD/files/1696157/luadll.7z.txt](https://github.com/riderkick/FMD/files/1696157/luadll.7z.txt)

**Comment by leoteesh** [comment]
did what you suggested but still saying it is missing- which is weird because it is there
![image](https://user-images.githubusercontent.com/21075197/36061537-8271e08a-0e53-11e8-891e-7158c4d81b3d.png)

**Comment by Sakurahime08** [comment]
so was this fixed?
