### ISSUE TITLE
Error messages 

### ISSUE THREAD

**Issue by leoteesh** [riderkick/FMD#917]
I am getting error messages and also fmd is closing by itself
![image](https://user-images.githubusercontent.com/21075197/35942690-5f2913ca-0c4e-11e8-82fb-b4dffe32ca5c.png)

![image](https://user-images.githubusercontent.com/21075197/35942727-7ed80550-0c4e-11e8-9120-6ab683981179.png)

![image](https://user-images.githubusercontent.com/21075197/35943173-2340caa4-0c50-11e8-9bab-69d21e059266.png)

**Comment by riderkick** [comment]
Where is the details info?

**Comment by Tmp341** [comment]
I'm seeing 2 mangago name. Saying "unknown picture format", they've probably it because you broke their "worth better than gold" website codes.

**Comment by subnighter** [comment]
`Program exception!
Application       : Free Manga Downloader
Version           : 0.9.133.0
Product Version   : Win64 Debug
Host Machine      : Windows 10 64-bit
FPC Version       : 3.0.4
LCL Version       : 1.9.0.0
WidgetSet         : Win32/Win64
Target CPU-OS     : x86_64-Win64
Build Time        : 2018/02/07 19:58:54
Path              : C:\Users\User\Downloads\fmd_0.9.89.0_Win64\fmd.exe
Process ID        : 9496
MainThread ID     : 4912
Thread ID         : 5376
Time              : 08.02.2018 16:49:40.107
Sender Class      : TDownloadThread
Exception Class   : EAccessViolation
Message           : Access violation
  In TDownloadThread.Execute
  Flag        : CS_GETPAGENUMBER
  Website     : MangaGo
  Title       : Ordinary Men
  Chapterlink : /read-manga/ordinary_men/uu/ordinary_men-chapter-21
  Chaptername : Ch.021

  $000000010000BDAA
  $000000010025255C
  $0000000100560F10 line 235 of ../baseunits/modules/MangaGo.pas
  $0000000100330FD7 line 600 of ../baseunits/WebsiteModules.pas
  $0000000100359F55 line 468 of ../baseunits/uDownloadsManager.pas
  $0000000100359C00 line 360 of ../baseunits/uDownloadsManager.pas
  $0000000100053D1D
  $0000000100003A16
  $00000001000150C7
  $00007FFA202E1FE4
  $00007FFA22BEEFB1`

**Comment by alexandriatale** [comment]
I also get this error message after updating into 0.9.134.0 version. Yesterday it still worked perfectly

![fmd error](https://user-images.githubusercontent.com/33077478/35979980-2ea21eee-0d1c-11e8-99af-ab0bfc256c47.jpg)

**Comment by kmvi** [comment]
please check this fix (32-bit)
[fmd.7z.txt](https://github.com/riderkick/FMD/files/1707893/fmd.7z.txt)

**Comment by subnighter** [comment]
Thanks, is successfully downloading.

**Comment by alexandriatale** [comment]
it works! thank you very much!
