### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by Tmp341** [riderkick/FMD#918]
I've already translated Turkish language in [#913](https://github.com/riderkick/FMD/pull/913/files?diff=unified#diff-78ba7087ab414fa2a7cdc433caf02b0bR762) but seems unchanged:

![ssss](https://user-images.githubusercontent.com/1683388/35957492-e53bc1ca-0cac-11e8-9de7-29f752ce117b.jpg)

![sssss](https://user-images.githubusercontent.com/1683388/35957628-a3fd6bf4-0cad-11e8-9c6e-dfe8f8427409.jpg)

**Comment by kmvi** [comment]
Your PR has been merged after 133 release, so updated translation will be available only in next release

**Comment by Tmp341** [comment]
Ah thank you. I've miscalculated time changes.

**Comment by Tmp341** [comment]
Wait, it seems included:

https://github.com/riderkick/FMD/compare/0.9.133.0...master

**Comment by kmvi** [comment]
![untitled](https://user-images.githubusercontent.com/6571513/35958502-2040987c-0cb2-11e8-9645-f2292cc9160b.png)

**Comment by Tmp341** [comment]
Ok. Got it now.
