### ISSUE TITLE
download files per task > 1 not working

### ISSUE THREAD

**Issue by bugbug4** [riderkick/FMD#921]
download files per task > 1 not working since 0.9.133 & 134, with 1 file per task and one task download it works but takes  ~4 minutes for 20 pages chapter. older version settings with 32/32 worked and were fast.
ps: are there somewehere old binaries?

**Comment by Tmp341** [comment]
You can download old versions from here:
[Releases](https://github.com/riderkick/FMD/releases)

**Comment by riderkick** [comment]
What not works. It is error or what? Please elaborate. Website, series, chapter, etc.

**Comment by bugbug4** [comment]
with all sites (example: mangafox, mangahere). only a few but at least one page is downloaded then it says failed. with resume one page more is downloaded etc. downgraded version and everything works again

**Comment by bugbug4** [comment]
also tested 135 still the same. 
The progressbar jumps around: for example 1/18 -> 17/8 -> 1/18 -> 17/18 -> etc for a few times and then only page 1 is in the folder. If i set it to download only one file at the time it does the following: download a few kB -> wait 1-3seconds -> download a few kB -> wait 1-3seconds etc. takes forever but at the end everithing is there.

**Comment by riderkick** [comment]
You're not saying anything about your website. Many download problem is depend on the website.
