### ISSUE TITLE
mangastream downloads all duplicates

### ISSUE THREAD

**Issue by mooglestiltzkin** [riderkick/FMD#922]
I noticed that mangastream would download duplicates of the same image. making it basically unusable :/

Problem just occurred with Version	: 0.9.134.0

the version before that mangastream just simply did not work. The version even before that worked though.

**Comment by imblad3** [comment]
+1 same issue, just updated with newest version 0.9.134.0
download a manga from mangastream, all pages i.e. 18 pages all of it is first page.
and asked to download all favorite manga from mangastream

**Comment by riderkick** [comment]
Please test and close if ok.
Download raw file https://github.com/riderkick/FMD/blob/master/lua/modules/MangaStream.lua
And replace the one in your installation `lua\modules\*`.

**Comment by mooglestiltzkin** [comment]
tested, the MangaStream.lua update seems to have done the trick 👍
