### ISSUE TITLE
Failure to update on WINE

### ISSUE THREAD

**Issue by birdmanravo** [riderkick/FMD#923]
Attempting to update FMD on WINE causes an error claiming 7za.exe can not be found. 
You can duplicate this error by running fmd.exe through WINE while the terminal is not navigating to FMD's home folder.
Navigating to FMD's home folder and running fmd.exe through WINE will alleviate the issue but this means  having to manually navigate a terminal to start FMD every time it needs to update.

**Comment by matoro** [comment]
@birdmanravo 

You could just put it in a wrapper script, which is what I do.

```
#!/bin/bash
cd /path/to/fmd/folder
wine fmd.exe "$@"
```

put this in `fmd.sh` and place it wherever you want, or invoke it from a `.desktop` file if you want it as a graphical app in your DE.
