### ISSUE TITLE
Mangastream - No Chapters?

### ISSUE THREAD

**Issue by Clydefrosch22** [riderkick/FMD#931]
Seems like something broke with the last update (at least the last update I applied). 
In the favorite list, it shows all manga from mangastream as having 0 chapters. Trying to load manga info gives an error message "Cannot get manga info. Please check internet connection"

Already replaced the lua as instructed in https://github.com/riderkick/FMD/issues/922

**Comment by riderkick** [comment]
It's working fine. Some manga are removed, so 0 chapters.

**Comment by Clydefrosch22** [comment]
Do you mean FMR removed those manga? Because they sure as hell aren't removed from the mangastream website.
Literally not a single manga from Mangastream is accessible.

**Comment by Tmp341** [comment]
Which version you're using?

**Comment by Clydefrosch22** [comment]
The one that released yesterday
Version	:	0.9.135.0

Shokugeki leads to the same error message for me.

**Comment by Tmp341** [comment]
Can you connect mangastream via browser?

**Comment by Clydefrosch22** [comment]
yes, very much so.  https://readms.net/ is working perfectly.
and I was still able to get updates through FMD a week ago. it just stopped working when I applied an update I had ignored for a few days around thursday

**Comment by Tmp341** [comment]
Try fresh install:

Remove everything except "data", "works" folders and "config\accounts.db" file. Download fmd 0.9.135.0 from here and extract again.

**Comment by Clydefrosch22** [comment]
Done, but didn't change anything

Mangastream does work again using the 131 version.
I noticed that the website displayed in the manga info screen for the old version is http://mangastream.com/manga/shaman_king_zero while for the new one its just 
/manga/shaman_king_zero
could that have something to do with it?

**Comment by Clydefrosch22** [comment]
I just wanted to say that, on another machine with a fresh install, mangastream still doesn't find any chapters under the newest version...

**Comment by Tmp341** [comment]
![ssss](https://user-images.githubusercontent.com/1683388/36719908-6e419d5a-1bb7-11e8-8811-b2f10c12b775.jpg)

It is working. And downloaded latest chapter now. I would say you should check your advanced setting, but you're saying you already did fresh install.

**Comment by Clydefrosch22** [comment]
After several installs I had it working on the latest 150 version with all my old settings and download progress and whatnot, even though it asked me to download every chapter of every mangastream manga in my favorites, as if I had never downloaded any of them before (and only the mangastream mangas).
But at a later start, it was right back to 0 chapters, being unable to load manga info and the wrong link. And it was gone from the website selection entirely too.
I have no idea what the heck is going on so i went back to 132 again

**Comment by riderkick** [comment]
Mangastream using external lua script. Are you sure it's listed in your website options? How many modules activated in your fmd?
`About > Modules: x`
It seems like modules doesn't loaded with your machine.

**Comment by Clydefrosch22** [comment]
It was selectable, albeit not in the website tab as on 132, but in a different, new one thats not there on 132 it seems. 
Unfortunately, I didn't check if it was still there when it disappeared from the website dropdown menu in the Manga Info tab.
I couldn't say about the number of modules either, but on 150 it did want to update a load of .lua files after the first startup, among them one for mangastream, if those were module files? I let it do that and restart.

I guess I'll give it another go tomorrow. If modules not loading right is the issue, what could cause that?

**Comment by riderkick** [comment]
If you enable the log. There will be a log about loading the modules. If successful it will log "Loaded modules from x: x". With the latest version, there is should be 209 modules loaded.
