### ISSUE TITLE
help with custom genre

### ISSUE THREAD

**Issue by shogunreaper** [riderkick/FMD#936]
I'm trying to search for the custom genre "Korean Comic" on hentai2read.com but nothing shows up.

i can search for random things like "touhou dj." and "7442nd" and get results but not with korean comic, why is that?

**Comment by Tmp341** [comment]
You should check, which filter used for Korean comics. 

Edit: They are not filtered with tag, they are using [KOREAN] inside title.

**Comment by shogunreaper** [comment]
it says Korean Comic right down under the Category spot?

**Comment by Tmp341** [comment]
Nope. Titles contain [Korean], instead of a tag.

**Comment by shogunreaper** [comment]
its right there on the page heres a picture.

https://i.imgur.com/Tavon51.png

**Comment by Tmp341** [comment]
Have you manualy updated h2r list? I got one as i said, but my list isn't up to date.

**Comment by shogunreaper** [comment]
yeah i downloaded the zip from the server.

**Comment by Tmp341** [comment]
Nope, do this one:

![ssss](https://user-images.githubusercontent.com/1683388/36063282-cfef16c4-0e8b-11e8-9bff-b80492f8fad6.jpg)

**Comment by shogunreaper** [comment]
i did that too.

**Comment by riderkick** [comment]
Filter works if the genres is correct. Some website doesn't have genres, or genres is within the title. So filter have to be adjusted depending on the condition.

**Comment by riderkick** [comment]
Filter work if the genres is correct. Some website doesn't have genres, or genres is within the title. So filter have to be adjusted depending on the condition.

**Comment by shogunreaper** [comment]
what do you mean don't have genres?

look at the image i posted they are right on the page.

**Comment by riderkick** [comment]
Not on the website. But in the fmd databases. Filter is doing filtering on the local databases not directly on the website. We are not integrated to any website. We basically just a website scrapper. We load the page and store the data locally.

**Comment by shogunreaper** [comment]
so why isn't it in the database?

**Comment by riderkick** [comment]
Probably because you don't have an up to date databases.

**Comment by shogunreaper** [comment]
yeah i do, i downloaded from the server and did the "update manga list"

**Comment by riderkick** [comment]
Most databases in the server hasn't been updated for a long time.
Sometimes, the data on the website is changed and doesn't match anymore with our databases. Especially genres with probably getting updated over time. You need to build your database from scratch by deleting the local db file. Then do `Update list`.

**Comment by riderkick** [comment]
Ok. I tested h2r. Search "a world that I rule". Before open the manga info. Hover in the result to show the hint. You can see there is no korean tag. But if you open the manga info, the data will be fetched from the website. And it does getting updated with new tag/genres. If you filter with "korean" in the genre field, it will show above title.
So, the conclusion is our databases isn't up to date anymore.

**Comment by shogunreaper** [comment]
i deleted the db and re-downloaded and was able to get more results.

old db was 4406kb vs new one at 7220kb.

why did i have to delete it to get new stuff though? Why did updating the old one not work?

**Comment by riderkick** [comment]
Update list only add the new titles. Not updating entire records.

**Comment by Tmp341** [comment]
@riderkick When we update a list via manual update, is it like yours on servers? I mean, "Mangago.db" can be considered as decent database and shared?

You can make a new repo and we can share our databases via PR. Then you or someone assosiated can upload them on SF.

**Comment by riderkick** [comment]
@Tmp341 Binary is not suitable for git or most version control system. And we need a server with direct link. SF is good until now. They support ftp which is very handy. Anyone who want to maintain the databases can mention me. I can give them access to sf page if they're serious. I even give them access as admin. So they can add another user or do something with that project page. But maybe not now. SF still not fully restored right now, I can't open admin page.
