### ISSUE TITLE
Feature Request : Save Manga file as JPG

### ISSUE THREAD

**Issue by H4nZ83** [riderkick/FMD#939]
Request to save the downloaded manga as JPG, because if the website provided PNG then the download size comes to > 30 mb, but as JPEG it only < 10 mb

the issues occured when updating the libwebp.dll
before that update all pages was saved as JPEG

**Comment by riderkick** [comment]
WebP codes doesn't interfere with png file. png NEVER saved as jpeg even before the integration of libwebp.
