### ISSUE TITLE
Mangadex IP ban warning to FMD users on main page

### ISSUE THREAD

**Issue by Tomoko23** [riderkick/FMD#940]
"Update (10-Feb) Notice: Using Free Manga Downloader to download images may result in your IP being banned because of the abnormal number of hits to the site, due to the way they have implemented their method of image downloading."
https://mangadex.com/
i there a way to be able to download and prevent IP ban? I'm disabling all mangadex favorites for now :'(

**Comment by Tmp341** [comment]
Vpn is the first solution comes to my mind.

**Comment by riderkick** [comment]
They may detect the number of concurrent connections from certain ip. Or by number of request per-time. Some users may abuse it with too much thread per task.
Try to limit mangadex thread to 1 in website advanced options.

**Comment by kmvi** [comment]
> due to the way they have implemented their method of image downloading
well, and which way is right then?

**Comment by Tomoko23** [comment]
@riderkick  thank you for the quick reply. I will do what you suggested and will also use the "use proxy" option, once I figure out how to use it lol

**Comment by ralvarador** [comment]
I used to use only 1 file / task.
With a "Time between the downloads" of files/projects, could that reduce the "load" that their servers?
In the code I read that you user User-Agent-Strings to mimicying the behaviour of a web-browser requesting a webpage (mangadex in this case), what could be the difference? A web browser does some request at the same time, didn't it?

**Comment by Tmp341** [comment]
Maybe, in addition to "number of threads", adding "kb/s" limitation would be good. Like torrent clients.

**Comment by karehaqt** [comment]
That explains why I'm getting the notice that my IP address has been banned.  Guess it's time to start using my VPN from my seedbox provider.

**Comment by DelKatey** [comment]
Not staff of MangaDex, but it's not them who's doing the banning, it's CloudFlare.

**Comment by molitar** [comment]
Thanks for the tip about the setting for a single website.

**Comment by Tomoko23** [comment]
@Tmp341 that's a cool idea, although you could also do it yourself right now with [NetLimiter](https://www.netlimiter.com/products/nl4)

**Comment by Tmp341** [comment]
@Tomoko23 That is good suggestion, but i probably won't us it other than FMD, it is not necessary for me. But if it is possible, adding a feature like this to FMD would be nice though.

@DelKatey He was using 150? That is just for one person. Do the math. I understand Mangadex too, this is an expensive operation, but other than banning, i think they should force us "kb/s" and "1 or 2 thread" usage somehow.

**Comment by DelKatey** [comment]
@Tmp341 The site owner, as I understand it, is working through a long backlog of features. As such, I doubt he had time to think that much about it, or just prioritized other more highly desired features by the community over that. The site is still pretty new, after all.

**Comment by riderkick** [comment]
@kmvi , there is  `MaxSendBandwidth, MaxRecvBandwidth, MaxBandwidth` in `THTTPSend.Sock`. Can you test it. Limit bandwidth should be divided equally (rounded) by number of threads. You can change it in `httpsendthread` unit. Make global variable for default `DefaultMaxRecvBandwdth`. And set the default on `THTTPSendThread.Create`.

**Comment by aria8** [comment]
now can download from mangadex without banned or not?

**Comment by Tmp341** [comment]
@aria8 For safety, download from somewhere else, until further notice or update.

**Comment by kmvi** [comment]
@riderkick something like this? kmvi/FMD@1f057203 The bandwidth limitation works fine.

**Comment by misteranonimous** [comment]
MangaDex admin here. Are you hitting every page of a chapter via its URL? Because that's why it's registering all the hits. What you should be doing is going to page 1 of a chapter, parse the javascript on the page to check all the filenames of the images in that chapter, and then go to the image directly, without also loading page 2,3,4, etc

**Comment by riderkick** [comment]
@kmvi if that's works fine, you can add the limit in `Options > Connections`.

**Comment by riderkick** [comment]
@misteranonimous, yes we do that https://github.com/riderkick/FMD/blob/master/baseunits/modules/Mangadex.pas#L90-L96

```
{$IFDEF WIN32}
  MAX_TASKLIMIT = 16;
  MAX_CONNECTIONPERHOSTLIMIT = 64;
  {$ENDIF}
  {$IFDEF WIN64}
  MAX_TASKLIMIT = 64;
  MAX_CONNECTIONPERHOSTLIMIT = 256;
  {$ENDIF} 

I think someone abusing this settings.
Check new chapters will read this settings and spawn that much of request at the same time.
Firefox has max 6 concurrent connections per server CMIIW.

**Comment by karehaqt** [comment]
@misteranonimous How do we get ourselves unbanned as I didn't know there was a limit, using a VPN for the moment.

**Comment by misteranonimous** [comment]
@karehaqt Send an email to holo@doki.co with your IP address and explain what happened.

**Comment by karehaqt** [comment]
@misteranonimous Email sent, many thanks :)

**Comment by kmvi** [comment]
@riderkick I was wrong, bandwidth limitation works correctly only with http. If https is used, the real speed is much lower than the set limit.
https://github.com/kmvi/FMD/tree/bandwidth

**Comment by riderkick** [comment]
Depends on the encryption algorithm, ssl stream may contains padding.

**Comment by riderkick** [comment]
Download speed in fmd is reading HR_ReadCount in hook OnStatus event. So, it's the decoded ssl packets.
You can push that changes to main repo.

**Comment by kmvi** [comment]
![untitled](https://user-images.githubusercontent.com/6571513/36086315-aa8214e8-0fdc-11e8-8b0c-0b8288872bce.png)
