### ISSUE TITLE
Just to report that the Automatic Update to 0.9.136 X86 has failed - then manually updated (y)

### ISSUE THREAD

**Issue by ralvarador** [riderkick/FMD#945]
but manually updated - NP!
The update say that couldn't find the 7za... but It's in the folder...
OS - Windows 10 X68
FMD in use: 0.9.135.0 - x86 version
![image](https://user-images.githubusercontent.com/30580377/36077335-8a489b16-0f37-11e8-9f55-fe0ee55ee65a.png)

**Comment by molitar** [comment]
Had the same problem.

**Comment by leoteesh** [comment]
had the same problem
![image](https://user-images.githubusercontent.com/21075197/36078489-e0030f50-0f6e-11e8-93de-da627a294481.png)

**Comment by rs3mk** [comment]
same

**Comment by Leguron** [comment]
When I want to update manually what do I need to do?

**Comment by ralvarador** [comment]
Just download the file available in the "FMD release post" according with the "architecture" that you use (X86 or X64), and then decompress it over the "FMD folder"... overwrite on prompt!

As usual, make a backup of the FMD config folders (Config, Data, Works) - just in case... the FMD Distribution come without the DATA / WORKS folders - so supposedly that folders and the config files stored in them will not be affected by the overwriting, as the CONFIG folder which have two files that should not affect your current configuration...
WELL - AT LEAST, IT'S WHAT I DO / DID.

**Comment by leoteesh** [comment]
hi, still having the same problem.

**Comment by Tmp341** [comment]
@leoteesh [https://github.com/riderkick/FMD/releases](https://github.com/riderkick/FMD/releases)

**Comment by H4nZ83** [comment]
the recent update still not solving the problem

**Comment by riderkick** [comment]
0.9.137.0 that fix it. So, it's will be in effect to update to the later version after 0.9.137.0.
Update from 0.9.136.0 to 0.9.137.0 is failed because 0.9.136.0 still contains the bug of course. 🤦‍♂️

**Comment by leoteesh** [comment]
getting this pop up when i restart fmd
![image](https://user-images.githubusercontent.com/21075197/36137377-da09d768-108c-11e8-9424-c722dc3691bb.png)
do you know what it means?

**Comment by riderkick** [comment]
@leoteesh . Now fmd can use lua script to add more website support without the need to download the whole program. User can just check the modules update in "Options > Website > Modules".
Those dialog is just a warning if the update gonna overwrite any local modification. Just in case user modify the local script, so they can backup the data first. You can suppress this warning in the same page. Additionally new modules require the whole program restart. There is also an option for auto restart at the same page.
