### ISSUE TITLE
Can't update FMD program via auto-update

### ISSUE THREAD

**Issue by Zeny0** [riderkick/FMD#952]
Hello,
Each time I try to update FMD from 0.9.135.0 I get an error that say : "Can't extract file because 7za.exe not found!"
But when I look in my fmd folder 7za.exe is here, and there seems to be no interference from my antivirus so I don't know what is the problem here...

**Comment by matoro** [comment]
https://github.com/riderkick/FMD/issues/932

**Comment by Scharhrot** [comment]
same problem here with me

**Comment by riderkick** [comment]
I thought I wrote it clear in changelog.
