### ISSUE TITLE
MangaGo New Link Encryption

### ISSUE THREAD

**Issue by ronny1982** [riderkick/FMD#953]
MangaGo added a new link encryption, since it seems rotating based on the time here are the scritps containing the selfmade `md5_jj(...)` encryption...

[chapter.601.js.txt](https://github.com/riderkick/FMD/files/1717810/chapter.601.js.txt)
[crypto.601.js.txt](https://github.com/riderkick/FMD/files/1717811/crypto.601.js.txt)

**Comment by Tmp341** [comment]
They are fighting like they own them. I would understand if we were talking about Crunchyroll here.

**Comment by riderkick** [comment]
Are they also own the translations?
I know many websites also rip each other. But they don't want to be ripped.

**Comment by kmvi** [comment]
descrambling  also broken

**Comment by nille02** [comment]
> I know many websites also rip each other. But they don't want to be ripped.
Like all "Scanlation Projects"
