### ISSUE TITLE
v 0.9.137.0 still save to png

### ISSUE THREAD

**Issue by H4nZ83** [riderkick/FMD#956]
on recent update the file that was on png not converted to jpg, still on png files, and it takes a lot of space

**Comment by riderkick** [comment]
There is no png to jpeg conversion in 0.9.137.0.

**Comment by H4nZ83** [comment]
if i want to use png to jpg conversion then using old version ?

**Comment by riderkick** [comment]
There is never been any png to jpeg conversion before.
