### ISSUE TITLE
webp conversion to jpeg/png

### ISSUE THREAD

**Issue by H4nZ83** [riderkick/FMD#958]
when will the conversion of webp to jpeg/png will available again ?

**Comment by riderkick** [comment]
webp to png/jpeg is available since 0.9.135.0

**Comment by H4nZ83** [comment]
but earlier you said that on 0.9.137.0 webp to png/jpeg was not available

**Comment by riderkick** [comment]
When I ever said that?

**Comment by H4nZ83** [comment]
on #956

**Comment by riderkick** [comment]
I said 
>There is never been any png to jpeg conversion before.
