### ISSUE TITLE
can not download manga from kissmanga

### ISSUE THREAD

**Issue by Scharhrot** [riderkick/FMD#960]
everytime i downloaded from kissmanga the folder is empty and there is an error
i tried to download manga berserk and all the folder is empty, what is wrong with kissmanga ?

**Comment by zqjpymbk** [comment]
For a site that steals others' work, they're remarkably protective of their stolen content. Most likely altered site yet another time to stop people from ripping chapters.

**Comment by kmvi** [comment]
Try to disable "Use Google DCP" checkbox (Option -> Websites -> Options tab)

**Comment by Tmp341** [comment]
@zqjpymbk Most of them are like that.

**Comment by Scharhrot** [comment]
@zqjpymbk i tried mangareader and the volume of berserk manga is not arranged correctly start from volume 9 so i tried kissanime

**Comment by Scharhrot** [comment]
@Tmp341 it works, thnx bro ^_^
