### ISSUE TITLE
Updating is not Updating?

### ISSUE THREAD

**Issue by wuhugm** [riderkick/FMD#961]
FMD underwent automatic update from 0.9.137.0 to 0.9.138.0
When the update finished (no error)
FMD is still at 0.9.137.0 and asking for update again
Repeated 3 times and still the same

**Comment by Tmp341** [comment]
I've downloaded it manually.

**Comment by wuhugm** [comment]
@Tmp341 Man, stop saying that, that's not a solution at all

**Comment by Tmp341** [comment]
@wuhugm a couple of days ago @riderkick said that we should manual update it, if updater couldn't be able to (other than 404 error). Sometimes updater can't overwrite on files. That's why i'm saying that.

**Comment by wuhugm** [comment]
@Tmp341 I know, but I've seen you telling people to manually update so many times
That's just makeshift solution. 
In the changelog for 0.9.137.0, it said it corrected the updating problem, but apparently it hasn't

**Comment by Tmp341** [comment]
Try running "updater" via admin rights, as stated, updater can't overwrite on some dlls. As for "404" error, unless @kmvi or @riderkick uploads them on server, we gotta wait. I got 404 error, that's why i've updated manually. I'm a fmd translator and irl student, i gotta test them when i can get my hands on them, when i have time.

**Comment by H4nZ83** [comment]
i think the issues lies on the ability of FMD to close itself and it takes a long time whether you activate the close to tray or minimize to tray option or not..
the FMD.exe itself still running after i clicked close button for a while. 
it took a time to really terminate the FMD thread on the task manager if you choose to exit FMD

**Comment by riderkick** [comment]
I just check it. Updater is working fine. What fixed is typo of 7za.exe. Updater basically just download the packed and extract it to current directory. Thus overwriting all the files. But sometimes, system may lock the file, or fmd.exe doesn't terminated as expected. So, we can't overwrite that file. We need to close that instance first. If it hang, then force close with task manager is the last resort.
