### ISSUE TITLE
Possible to auto stop and restart downloads if they stop for to long?

### ISSUE THREAD

**Issue by karehaqt** [riderkick/FMD#962]
At the moment I have an issue where for some reason, my downloads will just stop and won't restart until I manually stop and start them.  I have reduced the retry time down to 1 second and set it to 100 retries but this doesn't seem to make a difference.  Would it be possible to add a timeout option whereby if downloads have stopped for x amount of minutes, the program stops and restarts the downloads automatically, hope that makes sense?

I have tried creating a brand new install of the program but it still does it regardless.

**Comment by riderkick** [comment]
That's what connection timeout for. Lower the timeout and increase the retry times or failed task retry times.
