### ISSUE TITLE
the websites list missing

### ISSUE THREAD

**Issue by H4nZ83** [riderkick/FMD#963]
the websites list from advanced tab in websites option gone missing

**Comment by H4nZ83** [comment]
the version was 0.9.138.0

**Comment by Tmp341** [comment]
You mean this: 

![sss](https://user-images.githubusercontent.com/1683388/36148016-85bec88c-10cb-11e8-9c03-d6f79b927831.jpg)

It is right there. Backup your "data", "works", "lua" folders and "config\accounts.db" file. Delete everything, download from here again and overwrite it.

**Comment by H4nZ83** [comment]
yes, but when you add a webiste then the list was empty
on every tab inside the advanced tab
when you select add then the list comes empty..

**Comment by H4nZ83** [comment]
i've tried your solution again, and its not working 
still got empty websites list

**Comment by Tmp341** [comment]
Ah, found what you were talking about. You can't add website from dropdown menu, as it is empty.

Yeah. It is empty.
![ssss](https://user-images.githubusercontent.com/1683388/36149161-c83fe7fa-10cf-11e8-9c5d-05b8b14eadfc.jpg)

**Comment by H4nZ83** [comment]
the list was there, the scroll box was full of list, but when i click an item it shows nothing on the add menu
and the list was empty

**Comment by H4nZ83** [comment]
yeah you got the issues.. thanks
