### ISSUE TITLE
Can't filter using "Search in all manga sites"

### ISSUE THREAD

**Issue by vothphong2001** [riderkick/FMD#97]
Filter Option "Search in all manga sites" does not work. Can you fix it?
Error after update from 9.18.2 to 9.21.8
Thanks

**Comment by riderkick** [comment]
describe what doesn't work, what you input and what you expect

**Comment by vothphong2001** [comment]
Filter Option  (Filter artist or author)
- Uncheck "Search in all manga sites": Filter current Sites
- Checked "Search in all manga sites": Not filter at all
Thanks

**Comment by riderkick** [comment]
describe what you input and what you expect, if you don't input anything of course it doesn't filter anything.

**Comment by vothphong2001** [comment]
Error on large Database file
Example: E-Hentai, NHentai
Just filter, remove filter, filter and it stop working
