### ISSUE TITLE
download manga list from server was error

### ISSUE THREAD

**Issue by H4nZ83** [riderkick/FMD#972]
when i open the sites of some new sites that recently added and there was a notification to download the manga list, after download and extract it, cames with empty ones.
i checked the downloaded file was only 1 kb

**Comment by Tmp341** [comment]
Can you open that site manually? For example, hentai2read. If you can't try with a vpn.

**Comment by Tmp341** [comment]
Some sites aren't uploaded to server i think. They give 404 error, if you are having that.

**Comment by riderkick** [comment]
SF server is still down.

**Comment by H4nZ83** [comment]
yes it got 404 response..

**Comment by alexandriatale** [comment]
I also tried to download manga list and got this error notice

![window](https://user-images.githubusercontent.com/33077478/36261542-416fcb36-1297-11e8-93b2-2dceac53e6a6.jpg)

**Comment by Tmp341** [comment]
Database files are located on SF. And it was down yesterday.

**Comment by kmvi** [comment]
Moved to #1021
