### ISSUE TITLE
Updater broken with .138 and will not update!

### ISSUE THREAD

**Issue by molitar** [riderkick/FMD#974]
I got the message for module update to .139 and it is still at .138.  Now getting message to update to .140 and it's still at .138.  It will not update at all!  It keeps saying needs to update than fails to update!

Oh and it keeps asking the stupid question do I want to delete finished tasks. How many times do I need to answer that. That new feature is junk as it just keeps asking.

**Comment by riderkick** [comment]
It's working fine here.
You can disable that feature in options.

**Comment by riderkick** [comment]
Edit: 
SF server maybe down in some area.
I can't even push a commits to SF git.

**Comment by Leguron** [comment]
Update is working for me now.

**Comment by riderkick** [comment]
I move the update url to GH for now. SF still down. Maybe until February 15.
