### ISSUE TITLE
.138 updater grabs focus!

### ISSUE THREAD

**Issue by molitar** [riderkick/FMD#975]
Stop the updater from grabbing focus I could not work on anything else while the update window kept popping up saying update server list from each and every site!

Second major bug I extracted to a brand new folder and did a server download and there is no chapters!  No manga just empty file list!  Totally broken.

**Comment by riderkick** [comment]
Then don't use the updater.
SF server is down in many area. We store databases and update packets in SF. Just wait for a few hours.

**Comment by Tmp341** [comment]
@riderkick, Is making updater silent difficult? Making it auto download, then wait for fmd to terminated. Like firefox. Then, it starts updating at system tray with a "fmd is now updating" balloon tip. It should be user defined of course. It can try updating until successufly finished.

**Comment by riderkick** [comment]
@Tmp341 not really. I just not touching it for a long times since its just work. I do plan to get rid of the updater since a long time. Maybe I'll do it later.

**Comment by Leguron** [comment]
Update is working for me now.
