### ISSUE TITLE
Update all list at once impossibly slow

### ISSUE THREAD

**Issue by molitar** [riderkick/FMD#977]
(Still version .138 as unable to update at this time still even though it says there is a .140)

Ok I downloaded all the lists from server that I was able to.  I have all the English sites, Translation sites, and most of the H-sites but Exhentai, HentaiRU, and Yaoi.

I started the process and 4+ hours later it was still only about a fourth done with Hitomila.  This would take days just to do the update. Another problem I noticed I use to be able to download more than one at a time so if I needed to check a manga on a specific site I could still download the list for that one but now no longer able to do this.

So that I could check the manga I need to download and just to make sure it's not having problems I canceled the task and restarted to download all lists again and it is stuck on Doujin Moe looking for new titles with progress...

Updating list 7/82 [T:50 53/100] Looking for new titles 1/1    (has not moved from here for at least 5 minutes it is stuck)

**Comment by molitar** [comment]
I have tried to download .140 manually and it has not helped.. for now going back to .137 until major update bugs are fixed.

**Comment by Tmp341** [comment]
H-site manual updates are way too slow and if your isp blocks it, it is impossible. I was downloading hitomi.la via vpn, fmd showed i have 1.5k new titles. I gotta close pc at that time. When i opened fmd 2 days later, fmd showed me i have 4k new titles. I said "like hell i'll update that" and stopped.

**Comment by molitar** [comment]
Yeah but never had that problem with .137.  Still using it at this time and it's still working fine.

**Comment by riderkick** [comment]
>[T:50 53/100] 
50 threads is too much. You kill the server.
For h sites, don't use mangalist. Just drag n drop the link(s).
Maybe I need to remove this h sites from website selection.

**Comment by molitar** [comment]
That was only to see if it was number making a difference as I had setting on 6.  Did not make any difference.  So 1 thread, 4, threads, 6 threads, 20 threads and mass quick test of 50 threads.. No difference.. so maybe threads are not actually working or something. 

But .137 with my default settings of 6 threads was able to pull the list in under an hour.. no where near 4+ hours and still not completed.   I'll try the latest .140 in separate folder and test.

**Comment by Tmp341** [comment]
Threads option doesn't make any difference for you, but server.
