### ISSUE TITLE
Can anyone explain this error from the log file?

### ISSUE THREAD

**Issue by karehaqt** [riderkick/FMD#980]
Downloading from Mangafox and wondering if it's something that can be fixed

04:02:19:976 TTaskThread, checkforfinish failed=2/9 "Himouto! Umaru-chan" >"/manga/himouto_umaru_chan/c157/"WW

04:02:19:976 TTaskThread, download failed. "Himouto! Umaru-chan" "Himouto! Umaru-chan 157 Umaru and Treasure Box" "/manga/himouto_umaru_chan/c157/"

**Comment by Tmp341** [comment]
Either mangafox changed something or you can't access their website.

**Comment by riderkick** [comment]
Mangafox can't be accessed from asia region? It's always redirected to mangazoneapp.

**Comment by Tmp341** [comment]
Well, i get 404 page here in Turkey.

**Comment by karehaqt** [comment]
@riderkick That's weird as I live in the UK, as does my Internet connection.

**Comment by riderkick** [comment]
I think mangafox gotten hit hard in Asia. Most mangas already published in Asia. Maybe the publisher threaten them. The reason of those licensed mangas message in some region. Their revenue may have been hit a big times. So, they need to keep legit.

**Comment by karehaqt** [comment]
I'm surprised Mangafox care given that they're based in China, and Chinese companies don't give a crap about IP and copyright.

**Comment by riderkick** [comment]
The one who paid them. The advertising company probably from outside of China. So they have to oblige.

**Comment by karehaqt** [comment]
Seems like it's getting harder to hoard manga as all the sites just want you to read on site and not download.

**Comment by riderkick** [comment]
Of course. Download with app doesn't load the ads, doesn't even load the website traffic counter. They need us to load the ads and click it even by mistake. That's why many of them publish their own app, so they can control the ads. It just all about money.

**Comment by karehaqt** [comment]
I'm just glad that a lot of the series I read are getting official releases now so I can buy them, but it's still nice to be able to read the newer chapters way in advance.  What we need is a manga Netflix 😁
