### ISSUE TITLE
update failed

### ISSUE THREAD

**Issue by alexandriatale** [riderkick/FMD#982]
While I tried to update, it said 7za.exe not found. But it's there! Anyone know what's wrong? Thank you!

![updater](https://user-images.githubusercontent.com/33077478/36245822-8f24da0c-125f-11e8-8bee-b16cc5524c23.jpg)

![window](https://user-images.githubusercontent.com/33077478/36245948-08d87034-1260-11e8-8351-07d41772071a.jpg)

**Comment by Tmp341** [comment]
There was an error with FMD codes, updater couldn't be able to extract files from archive. I think it was fixed around v0.9.136.0.

**Comment by alexandriatale** [comment]
ohh, so I manual download version 136, then update again to ver 141?

**Comment by MilesWilford** [comment]
How do we actually fix this issue, as a user?  FMD cannot update so I cannot update to receive the fix -- is there a manual update?

**Comment by riderkick** [comment]
It is clearly stated in changelog. When new update available, it will show a changelog.
https://github.com/riderkick/FMD/releases
https://sourceforge.net/projects/newfmd/files/
