### ISSUE TITLE
Mangadex banning again

### ISSUE THREAD

**Issue by karehaqt** [riderkick/FMD#983]
Even with the change in FMD limiting connections to 4 when using Mangadex my IP has been banned again :(  I'm guessing they just don't want people downloading and just reading on the site.  I've switched my downloads over to other sites now and I'll just read Mangadex via 4G on my iPad.

**Comment by 7h3Cub3** [comment]
why not using 1 connection ? so that you don't get banned again.

**Comment by karehaqt** [comment]
That's the thing I did have it set to 1 in the interface, and with FMS having a hardcoded setting of a max of 4 for the site anyway I thought I would be fine, but alas no 😥.  

I don't feel like I should be asking to be unbanned for a second time due to this as I feel guilty.

**Comment by riderkick** [comment]
Probably not only due to number of concurrent connections. But also quantity of request per time basis (per minute, per hour). You probably doing a long simultaneous download.

**Comment by karehaqt** [comment]
I'll see how I fair using Tachiyomi on my phone on 4G, I have a 100GB monthly data plan so I might as well put that to use.

**Comment by karehaqt** [comment]
Decided to just move my downloads elsewhere and ask for an unban just to use the site for reading only.  The new Batato seems to work fine, plus with more and more scanalator sites being added I'll use them to.
