### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by leoteesh** [riderkick/FMD#986]
Hi,

is anyone else having error to update fmd?
![image](https://user-images.githubusercontent.com/21075197/36296858-5748d34e-12e7-11e8-9af2-0ac7e17aa5e2.png)

**Comment by Tmp341** [comment]
Yep. Even github source gives that error. I wonder why?

**Comment by riderkick** [comment]
My upload to gh keep failed. Using gh api to make a release. Now there is a bunch of broken release I need to remove one by one. 🤦‍♂️

**Comment by Tmp341** [comment]
Is sf still down?
