### ISSUE TITLE
Rewrite modules with lua script

### ISSUE THREAD

**Issue by riderkick** [riderkick/FMD#993]
- [x] Dynasty-Scans http://dynasty-scans.com
- [x] NHentai http://nhentai.net
- [x] MangaTown http://www.mangatown.com
- [x] AnimExtremist http://www.animextremist.com
- [x] AnimeStory http://www.anime-story.com --> http://www.mymanga.io (MyMangaIo)
- [x] MangasPROJECT http://mangaproject.xpg.uol.com.br --> https://leitor.net (Leitor)
- [x] ~ScanManga http://www.scan-manga.com~
- [x] MangaKu http://mangaku.web.id
- [x] ~~MangaREADER_POR http://www.mangareader.com.br~~
- [x] ~~MangaHost http://br.mangahost.com~~

**Comment by kmvi** [comment]
Which modules should I take? So that we don't rewrite the same thing.

**Comment by formigao** [comment]
i can help a little : https://mangahost.cc/ is the new site and maybe they block access outside from of brazil.

MangasPROJECT  changed name to https://leitor.net/

i can accesss both fine here from brazil.

**Comment by riderkick** [comment]
@kmvi you can go from the bottom. I'm will go from the top.

@formigao, we welcome every pull request.

**Comment by kmvi** [comment]
I'm stuck with leitor.net json parsing. 

mymanga.io sends an invalid html, which must be corrected first. Also, searching the catalog returns only 300 results, and I don't know how to get the rest. kmvi/FMD@48b72b61e6ab238e9ca59469cf70407b6a69f185

**Comment by kmvi** [comment]
leitor.net manga directory has undetermined number of pages. It's the same as mentioned [here](https://github.com/riderkick/FMD/issues/909#issuecomment-365844635). I do not yet see a way to solve this problem

**Comment by riderkick** [comment]
Maybe we need to publish that updatelist object after all. But. I don't see any other use except that currentdirectorypagenumber.
Actually you can just go to load next page with `while true do`. And use http.terminated to break the loop. It just doesn't show the progress ui.
