### ISSUE TITLE
error when downloading

### ISSUE THREAD

**Issue by H4nZ83** [riderkick/FMD#996]
what happened ?

Program exception!
Application       : Free Manga Downloader
Version           : 0.9.143.0
Product Version   : Win32 Debug
Host Machine      : Windows XP
FPC Version       : 3.0.4
LCL Version       : 1.8.0.6
WidgetSet         : Win32/Win64
Target CPU-OS     : i386-Win32
Build Time        : 2018/02/17 05:57:45
Path              : H:\g\Downloader\fmd\fmd.exe
Process ID        : 3908
MainThread ID     : 6472
Thread ID         : 5936
Time              : 17/02/2018 08:50:37.281
Sender Class      : TTaskThread
Exception Class   : EInOutError
Message           : Access denied
  In TTaskThread.Execute
  Flag        : CS_DOWNLOAD
  Website     : MangaFox
  Title       : Hunter X Hunter
  Chapterlink : /manga/hunter_x_hunter/vTBD/c374/
  Chaptername : Hunter X Hunter 374

  $00472A67
  $00471D24
  $00472387
  $005DB728  CHECKFORFINISH,  line 827 of F:/GitRepo/Freepascal/FMD/baseunits/uDownloadsManager.pas
  $005DAD3E  TTASKTHREAD__EXECUTE,  line 1016 of F:/GitRepo/Freepascal/FMD/baseunits/uDownloadsManager.pas
  $004441A5
  $00412E0E
  $7C80B729

**Comment by H4nZ83** [comment]
are there any problem if i'm in the middle of updating manga list ?

**Comment by riderkick** [comment]
https://github.com/riderkick/FMD/commit/72c88970231af7704c27a21cbb37deae3a59793f
