### ISSUE TITLE
Hoe to add other manga pages?

### ISSUE THREAD

**Issue by Qizmo** [riderkick/FMD#997]
Hi, I'm new to this program and is currently loading manga from mangahere.

However some of the manga can only be loaded a few pages only even after loading for days. Like Nagasarete Airantou, which I got all chapters but some of them only load like 5-8 pages from around 30 pages, and it wouldn't load further. So I try going to the mangahere web to check on the manga that got problem and notice that the manga can't be open from the browser too.

I now reading online from mangatown and don't seems to have such problem and notice that in your "changelog.txt" you have  "[*] MangaTown, exclude ads page" on line 143. 

How do I add mangatown to my manga pages list? I currently only have 4 pages MangaFow, MangaHere, MangaInn and MangaReader.

**Comment by riderkick** [comment]
Options > Website.
But you don't have to check them, if you don't use the manga list. You can drag n drop the url(s) to your download/favorite list or drop box.
All website support is loaded. Input the url in manga info tab will automatically detect if such url is supported.

**Comment by Qizmo** [comment]
Thank you very much riderkick. Too bad seems like mangatown is not in the list. -_-'

**Comment by riderkick** [comment]
Oh I forgot. MangaTown is not available right now. https://github.com/riderkick/FMD/issues/993
It will be available again shortly. You can check module update in `Options > Website > Modules`.

**Comment by Qizmo** [comment]
Ahhh!!! Ok. Thank you very much 👯‍♂️ 
I will wait for it then :D

By the way I got another question please. In the "options", "websites". I found the link for ChampionScans.
However after I tick and apply it. Then try loading manga list from server. It kept saying
"Failed to finish"
ChampionScans: 404 not found"

Does this mean ChampionScans list in the "Website" an error?

**Comment by riderkick** [comment]
SF server is down since Feb 13. They major server migration or something like that. https://twitter.com/sfnet_ops
We store our data here https://sourceforge.net/projects/newfmd/files/data/
You may be able to download it from the browser. But can't be downloaded with usual way (auto redirect). They promise to get it fixed soon. But not delivered yet till now.

**Comment by riderkick** [comment]
Mangatown is added back. You can check the update via Options > Website > Modules.
